### ISSUE TITLE
Document the workflow and considerations around "Sharing Clusters"

### ISSUE THREAD

**Issue by RichieEscarez** [GoogleCloudPlatform/kubernetes#10108]
Today we have "[sharing cluster access](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/sharing-clusters.md)" but need to build this concept and the related concepts better and in a single location. For example, if there are multiple clusters that multiple admins manage (for multiple teams), how do we help them set up and configure for this? [Is this even a valid scenario that we should consider?]

This requested document might mostly contain links to the existing information (and might tie in closely with security) but we should document and clarify:
 1. What the considerations are for setting up shared clusters.
 2. How admins setup and configure for "sharing clusters" (their services, resources?, etc.).

Related concepts that we should tie together:
"Security"
"Setting Resource Quotas"
"Namespaces"
"Sharing Cluster Access"
"Setting CPU and Memory Limits"

**Comment by thockin** [comment]
@jlowdermilk

**Comment by bgrant0607** [comment]
cc @erictune

**Comment by bgrant0607** [comment]
The "sharing clusters" doc is actually just about copying around kubeconfig files, which is really about accessing a cluster. Even a single user could need to do that if they created their cluster from one host and tried to access it from another. The topics suggested by this doc are about actual multi-tenancy.

**Comment by erictune** [comment]
docs/admin/README.md contains section "Multi-tenant support" which links to docs about namespaces and resource quota.

**Comment by erictune** [comment]
Checklist of original requests:
- [x] *What the considerations are for setting up shared clusters.* 
  - docs/admin/README.md#multi-tenant-support covers this
- [x] *How admins setup and configure for "sharing clusters" (their services, resources?, etc.).*
  -   - docs/admin/README.md#multi-tenant-support covers this
- [ ] "Security"
- [X] "Setting Resource Quotas"
  - PR #11487 improves this.
- [ ] "Namespaces"
- [X] "Sharing Cluster Access"
  - not going to include in same doc because this is a total hack right now. 
- [X] "Setting CPU and Memory Limits"
  - this is covered in the users' guide.  I will link to it from the Resource Quota

**Comment by erictune** [comment]
Calling this good enough for 1.0.
