### ISSUE TITLE
Flaky e2e test: Etcd failure should recover from SIGKILL (Failed 2 times in the last 30 runs. Stability: 93 %)

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#10144]
Master tracking issue: #9312 

Etcd failure should recover from SIGKILL
```
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/etcd_failure.go:67
Expected error:
    <*errors.StatusError | 0xc208d40600>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/pods/e2e-tests-etcd-failure-1l2hm?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]",
            Reason: "",
            Details: nil,
            Code: 500,
        },
    }
    501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/pods/e2e-tests-etcd-failure-1l2hm?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
not to have occurred

```

**Comment by quinton-hoole** [comment]
See also: #9484

**Comment by quinton-hoole** [comment]
@mikedanese Can you take a look into this?  Not super-duper urgent.

**Comment by quinton-hoole** [comment]
See #10146 for details.

**Comment by davidopp** [comment]
@quinton-hoole Should we close this issue and move #10146 to 1.0?

**Comment by davidopp** [comment]
Sorry, #10146 is already marked 1.0. Please close this issue if you agree.

**Comment by quinton-hoole** [comment]
To contradict what I said in this morning's meeting, these are actually two separate issues.
This one is for the SIGKILL test failing in isolation, about 7% of the time.
#10146 is for the SIGKILL test borking all subsequent tests when it fails.  We have debugged that one (#10146), and there is a PR in the works, but this one (#10144) is still at large, AFAIK.
@mikedanese can you confirm?

**Comment by mikedanese** [comment]
There are still a few issues being tracked down with the etcd sigkill test. The error referenced in this issue should be fixed but there is still the catastrophic failure issue in #10146 and the timeout issue.

**Comment by mikedanese** [comment]
There is a curious temporal relation between the catastrophic failures and the p0 issues attributed to killing etcd https://github.com/GoogleCloudPlatform/kubernetes/issues/10122#issuecomment-113662922

**Comment by davidopp** [comment]
So IIUC there are three problems, that are loosely related:
1) [code problem] The cbr0 stuff (#9822 and #10122)
2) [code problem] The fact that etcd before 2.0.12, and possibly also 2.0.12, does bad things on SIGKILL or other non-graceful shutdown (#10146)
3) [test problem, becomes a non-issue if/when (2) is fixed] The fact that because of (2) we can't run the "SIGKILL etcd" test right before other tests (is there an issue for that?)

I know @dchen1107 is working on (1). Is anyone working on (2)? Which of these three things is this issue about, or is this issue about something else? Are there other things I left out?

**Comment by mikedanese** [comment]
As for 2) Apparently issue is closed upstream. I have reenabled the SIGKILL test, as of an hour ago for observation. coreos/etcd#2877

**Comment by cjcullen** [comment]
coreos/etcd#2877 is closed, but I don't feel confident that this is entirely solved upstream (see https://github.com/coreos/etcd/issues/2276#issuecomment-114607008)

**Comment by quinton-hoole** [comment]
I think that we can close this one. We don't need the upstream etcd fixes.  We fixed the cbr stuff, and adjusted the test to only send one SIGKILL to etcd, not 30 in 30 seconds (which is what it was doing, and is quite unrealistic).  Since merging the aforementioned fixes, we have seen 20 successful runs of this test in a row.  Not 100% conclusive, but good enough for now.  I'll re-open if the test flakes.

**Comment by davidopp** [comment]
Agree with closing since you say the modified e2e is consistently green now. But we should perhaps lobby the etcd maintainers to change their position on the statement that CJ linked to above ("why do you want to kill etcd right after it restarted? We know there is a small chance it can lead etcd cannot restart. We have no plan to fix it.") In any event, we can follow up on the etcd issue instead of here.

**Comment by mikedanese** [comment]
Ya I agree with @davidopp. That should be fixed.

**Comment by dchen1107** [comment]
Also both issue listed by @davidopp in 1) [code problem] The cbr0 stuff (#9822 and #10122) are closed.
