### ISSUE TITLE
how to start the kube api server with https?

### ISSUE THREAD

**Issue by wangzhezhe** [GoogleCloudPlatform/kubernetes#10159]
Hi , I'm trying to connect the kube-apiserver by https, this is the info when I start the api server：
````
$ ./kube-apiserver --insecure_port=8080  --secure-port=8081 --etcd_servers=http://127.0.0.1:4001 --logtostderr=true --service-cluster-ip-range=192.168.3.0/24 --client-ca-file=/home/vcap/certs/ca.crt --tls-cert-file=/home/vcap/certs/server.crt --tls-private-key-file=/home/vcap/certs/server.key
````
when I use the same ca.cert file to connect the api server in another machine I got the following mistake:

````
$ curl --cacert ca.crt https://k8master:8081/api/v1beta3/namespaces/default/pods -v
* Hostname was NOT found in DNS cache
*   Trying 10.10.103.250...
* Connected to k8master (10.10.103.250) port 8081 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
* Server certificate: k8master
* Server certificate: k8master
> GET /api/v1beta3/namespaces/default/pods HTTP/1.1
> User-Agent: curl/7.37.1
> Host: k8master:8081
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Content-Type: text/plain; charset=utf-8
< Date: Sun, 21 Jun 2015 02:52:22 GMT
< Content-Length: 13
< 
Unauthorized
* Connection #0 to host k8master left intact
````
Could any one give me some suggestions? Than you!

**Comment by cjcullen** [comment]
The `--cacert` option tells `curl` to use the provided certificate authority to verify the server cert that the apiserver present.

The `HTTP/1.1 401 Unauthorized` you get is because the secure endpoint on the apiserver requires that the client present some form of authentication. That can be done through client-certificate, bearer token, or HTTP basic auth.You can read more about those three options in [authentication.md](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/authentication.md).

Personally, I think the easiest way is using a bearer token.
You can create a file `tokens.csv` containing a token for your client to use:
```
abcdTOKEN1234,wangzhezhe,wangzhezhe
```
The token can be anything. On gce, we [generate random tokens](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/configure-vm.sh#L329) for clients.

Start your apiserver with `--token_auth_file=tokens.csv`.

Then add `-H "Authorization: Bearer abcdTOKEN1234"` to your curl command, and the apiserver should correctly authenticate you as user `wangzhezhe`.

**Comment by wangzhezhe** [comment]
Thank you for your suggestions! there are thee questions:
1. how should I config the port of api server when I try to use the token to make an authentication? Actually I try to start the api server like this :
````
./kube-apiserver  --insecure-bind-address=10.10.103.250 --insecure-port=8080 --bind-address=10.10.103.250 --secure-port=8081 --etcd_servers=http://127.0.0.1:4001 --logtostderr=true --serce-cluster-ip-range=192.168.3.0/24  --token_auth_file=/home/vcap/certs/tokens.csv

````
than I connect the server :
````



````

**Comment by cjcullen** [comment]
You still need to specify `--cacert` with your curl command. Otherwise, curl will use your OS's default CA bundle (which the apiserver's cert will not trace back to).

Your full command should look like:
```
curl --cacert ca.crt -H "Authorization: Bearer abcdTOKEN1234" https://k8master:8081/api/v1beta3/namespaces/default/pods -v
```

**Comment by wangzhezhe** [comment]
Thanks for your advice!
It seems ok to add cacert and -H config in curl command at the same time .
This is my info to start the api-server
````
sudo ./kube-apiserver  --insecure-bind-address=10.10.10350 --insecure-port=8080 --bind-address=10.10.103.250 --secure-port=8081 --etcd_servers=http://127.0.0.1:4001 --logtostderr=true --service-cluster-ip-range=192.168.3.0/24  --token_auth_file=/home/vcap/certs/tokens.csv --client_ca_file=/home/vcap/certs/ca.crt --tls-private-key-file=/home/vcap/certs/server.key --tls-cert-file=/home/vcap/certs/server.crt
````
In my case, I userIf I want to use the cert created by system in /var/run/kubernetes ,  what ca.crt file should I use ?

Thank you !

**Comment by cjcullen** [comment]
Oops I didn't see part 3 of your question.

With the self-signed cert, the apiserver cert and the certificate authority are the same, so you would just set `--cacert /var/run/kubernetes/apiserver.crt` (or wherever you copy that cert to).

**Comment by wangzhezhe** [comment]
sorry , some spell mistakes in curl command , Its  Bearer but not Beare
curl --cacert ca.crt -H "Authorization:Bearer abcdTOKEN1234" https://k8master:8081/api/v1beta3/namespaces/default/pods -v

**Comment by fzu-huang** [comment]
@wangzhezhe   Can you teach me  how to create .crt and key?  what should '-subj' be ??

**Comment by wangzhezhe** [comment]
@fzu-huang maybe this will help you: http://localhost:4000/blog/2015/08/05/httpsandgolang/

**Comment by fzu-huang** [comment]
@wangzhezhe 谢谢！
so  what i need to do is  just edit a conf and load it when i create key and crt  by openssl~?
i'll try it !
