### ISSUE TITLE
Master reporting healthy even when etcd just isn't

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#10251]
The bigger issue with with #10122 is that we're not actually checking etcd health correctly, which means that when GKE health checks the master components, we totally missed the #10122 symptoms and called the master good and just assumed all the nodes were bad.

If we had noticed the master was bad, we could've made different choices, like shooting the master and data PD in the head.

cc @cjcullen @fabioy @alex-mohr

**Comment by alex-mohr** [comment]
I think @cjcullen had some ideas on how we could improve this?  Or perhaps it was @fabioy?

**Comment by cjcullen** [comment]
In getServerversToValidate() ([here](https://github.com/GoogleCloudPlatform/kubernetes/blob/d8e522514481c9a8952c6333527212a2addde238/pkg/master/master.go#L718)) we should be hitting `/health` instead of `/v2/keys/`.

In the non-functional clusters, `/health/` reports `{"health": "false"}` with an `HTTP/1.1 503 Service Unavailable`, but `/v2/keys/` continues to successfully serve the empty key list.

**Comment by cjcullen** [comment]
It looks like the /health endpoint was a new feature in 2.0.*, so trying to read the keys was historically our best guess at etcd cluster health.

**Comment by fabioy** [comment]
Yeah, that's a new endpoint and we should definitely switch to it. The
other ideas was to cause the health check to do a write and a subsequent
read from etcd.

On Tue, Jun 23, 2015 at 1:40 PM, CJ Cullen <notifications@github.com> wrote:

> It looks like the /health endpoint was a new feature in 2.0.*, so trying
> to read the keys was historically our best guess at etcd cluster health.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/10251#issuecomment-114635157>
> .
>



-- 
*-- Fabio Yeon*
