### ISSUE TITLE
Issues with GCE and service type LoadBalancer

### ISSUE THREAD

**Issue by juntagabor** [GoogleCloudPlatform/kubernetes#10290]
Now that publicIPs have become deprecatedPublicIPs, and is on its way out. I have found a couple of issues dealing with service type LoadBalancer.

1. It doesn't support UDP (if I recall correctly this is being addressed)
2. Doesn't support static IPs on GCE. I can't seem to find a way to create a LoadBalancer service on kubernetes, and then assign an existing static IP you already have on GCE to it. So if you delete the service and create it again, there is no way to go back to the old IP you had, even if you still own that IP (GCE) and is free to be used.
3. It creates a target pool per each service. So if I have 70 services and I scale the cluster, I have to manually go thru all 70 backends and update its members. It will be nice if LoadBalancer type had a way to pass which backend to use, if it doesn't exists create it, otherwise reuse it. At the end all backends point to the same set of minions, why create one per each service?

Use cases:
- DNS: this applies for 1 and 2
- Any service that requires an static IP, lets say a company web site: this applies for 2
- If you have a lot of services and decide to scale the cluster... have fun: applies for 3.

The way I used to deal with those use cases was to manually create the forwarding rules on GCE using only one backend and then create a service clusterIP with publicIP set to the GCE loadbalancer IP. This solves 1, 2 and 3.

Am I looking at this from the wrong angle and missing something? Is there anyways to deal with those issues without publicIPs / deprecatedPublicIPs ?

**Comment by mbforbes** [comment]
+cc @cjcullen / know who else to rope in?

**Comment by thockin** [comment]
UDP: Yes, it should not actually be a big change it just didn't get done.  #2849 

Static IP: This is actually two problems.  part 1 is "I want o keep an IP".  Until proper support is done you can just not delete your Service object.  part 2 is "I want to use a specific IP".  This is, in fact missing from the current API.  It's not a very big change, I think, but it's also not done.  I just don't think it can be squeezed in before 1.0, but it should be easy after 1.0.  I opened a new issues for this - #10323

TargetPools - those should be updated automatically.  If that is not the case, it's a bug.  The rationale is that a future rev of kube-proxy would be smarter about choosing local backends, and the LB would then not target all nodes, but just the nodes with backends.  Anyway, the service controller is supposed to be updating target pools, I think.  If it is not doing that, please please open a bug on that specifically.

@a-robinson 

The reason this API was changed is because the old way SO loose it was hard to do safely and it while it worked on GCE, it did not work on any other platforms (afaik).

I hope that explains, if not softening the blow.

Given that there are issues open for the individual points, I am going to close this (just for tidiness).  That doesn't mean you can't re-open it if you think this is insufficient or want to discuss it more deeply :)

**Comment by a-robinson** [comment]
Yes, the target pools are updated automatically by the service controller when nodes are added or removed from the cluster. If they're not being updated for you, it's most definitely a bug.
