### ISSUE TITLE
Vagrant and cluster_monitoring no longer work

### ISSUE THREAD

**Issue by eparis** [GoogleCloudPlatform/kubernetes#10406]
@derekwaynecarr So it looks to me like vagrant has influxdb as the default
```
vagrant/config-default.sh:ENABLE_CLUSTER_MONITORING="${KUBE_ENABLE_CLUSTER_MONITORING:-influxdb}"`
```
but only 1G per node:
```
$vm_minion_mem = (ENV['KUBERNETES_MINION_MEMORY'] || ENV['KUBERNETES_MEMORY'] || 1024).to_i
```

https://github.com/GoogleCloudPlatform/kubernetes/pull/10260 Set resource requirements of 2G and 2.5G for components.

So effectively that change broke vagrant, right?

**Comment by eparis** [comment]
@vishh @dchen1107

**Comment by dchen1107** [comment]
@vishh and I just talked about this. The resource limit we choose is based on our scalability test, which is indeed over-killed for small cluster. If we have auto-pilot features, we don't need to do this. Here are several proposals:

1) Set addon services with minimal default resource limit based on the default configuration: # of nodes, 30~50 pods per node. Then document how much each service requires based on cluster size and workload, and cluster admin decides how much to give at cluster creation time.

2) Update the script for addon service to calculate resource requirement for each service at cluster creation based on cluster size. 

cc/ @bgrant0607 
@roberthbailey on GKE side.

**Comment by roberthbailey** [comment]
@dchen1107 This sounds reasonable. Do you consider it a v1.0 blocker?

**Comment by bgrant0607** [comment]
@roberthbailey Yes.

**Comment by roberthbailey** [comment]
@dchen1107 - What happens when the user resizes their cluster? Say I initially create a cluster with 10 nodes to test drive kubernetes and we size heapster appropriately. Then I decide that I like it and everything is working, so I go into my MIG configuration and crank the size up from 10 --> 100. Now heapster is underprovisioned and cluster monitoring will be ineffective. 

If we are going to set a value less than the amount we need for the maximum cluster size that we support, we need a way to change it over time in response to the cluster size changing.

**Comment by dchen1107** [comment]
@roberthbailey Good question! This is why I updated #7046 and put it into v1.0 candidate for more discussion. This is also the initial reason we chose the peak usage of heapster and influxdb at the first place.

**Comment by dchen1107** [comment]
I believe reverting #10430 should fix this already.
