### ISSUE TITLE
TokenRateLimiter uses too much cpu above 10hz

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#10445]
https://github.com/golang/go/wiki/RateLimiting

High rate limits cause a huge amount of wasted CPU (8-10% above 60-100qps).  We should use a different implementation.

@ncdc @liggitt

**Comment by smarterclayton** [comment]
Consider https://github.com/youtube/vitess/blob/master/go/ratelimiter/ratelimiter.go or http://godoc.org/github.com/juju/ratelimit

**Comment by ncdc** [comment]
When OpenShift runs at idle in a Fedora 21 VM running in Parallels on my late-2012 27" iMac, it uses 25 to 35% CPU.

I swapped in juju/ratelimit to see how it compared at idle. I'm seeing it much lower - somewhere between 1 and 5 for the most part, with some bursts up to 10-15% at times.

I have not yet tested to see how effective it is at actually rate limiting, as well as if it's able to distribute the requests within a second, instead of having them all bunch at the beginning of the time period.

**Comment by liggitt** [comment]
I just tested it, and it smooths as well as the current throttler. The only difference seems to be whether the bucket is initialized to the burst rate or not.

**Comment by liggitt** [comment]
Actually, nevermind... juju/ratelimit initializes the bucket to capacity as well. Here's the code I used to test the initialization/smoothing behavior:
https://gist.github.com/liggitt/0bbf37f71ffb21ac169d

**Comment by liggitt** [comment]
In general, if our rate limiter has a `Stop` function, I think we're doing it wrong :)
