### ISSUE TITLE
elasticsearch-logging-v1 spec:  invalid value 'es-transport-port'

### ISSUE THREAD

**Issue by marekbiskup** [GoogleCloudPlatform/kubernetes#10537]
Error from kubectl when the addon controller is created:

```
The ReplicationController "elasticsearch-logging-v1" is invalid:spec.template.spec.containers[0].ports[1].name: spec.template.spec.containers[0].ports[1].name: invalid value 'es-transport-port': must be an IANA_SVC_NAME (at most 15 characters, matching regex [a-z0-9]([a-z0-9-]*[a-z0-9])*, it must contain at least one letter [a-z], and hypens cannot be adjacent to other hyphens): e.g. "http"
```

**Comment by marekbiskup** [comment]
I see that the validation was added recently by @thockin.
cc @satnam6502

**Comment by marekbiskup** [comment]
Please check also why e2e tests didn't find this problem (I suggest we have tests for all addons that we expect to be working).

**Comment by zmerlynn** [comment]
@satnam6502: Sending your way.

**Comment by zmerlynn** [comment]
There is actually an Elasticsearch logging e2e. I'm curious why it didn't find it - it may be on the perma-skiplist, which would be disappointing considering how much I made @satnam6502 bleed for it. :(

**Comment by satnam6502** [comment]
It is on the skip list which is why this change did not get caught and more importantly why cluster level logging with Elasticsearch is broken at head until #10453 merges. The test was put in falky and then skipped @quinton-hoole which is a shame because I think that although this is a pesky test it does exposes a variety of errors and concerns.

**Comment by zmerlynn** [comment]
There's a process issue there, then. We need addons to be tested at some
basic level regardless, even if it's just a health check that can't fail
and isn't flaky. Maybe there's a P1 bug that all addons have that test, at
least.

**Comment by quinton-hoole** [comment]
@satnam6502 @zmerlynn You'll notice that all e2e cluster builds are broken at the moment, because the  monitoring-heapster and kube-dns pods in the default namespace never report in Ready.  I assume that's the type of test that you're looking for?  Is elasticsearch-logging not running in the default namespace?  If so how was it not checked, or if it was checked, why did it report in as Ready?  I assume that the attempt to launch it failed outright, and it was thus never in the list of pods in the default namespace to start with?

Perhaps we should augment this test with an explicit check for named pods that we expect to be there?  But the problem is that elasticsearch-logging is optional, right? So it won't always be there?

INFO: 4 / 6 pods in namespace 'default' are running and ready (600 seconds elapsed)
INFO: POD                           NODE                 PHASE    CONDITIONS
INFO: kube-dns-v4-cce8o             e2e-gce-minion-595b  Running  [{Ready False}]
INFO: monitoring-heapster-v5-bgg0e  e2e-gce-minion-595b  Running  [{Ready False}]
INFO: 
F0630 07:28:49.352952   28697 e2e_test.go:140] Error waiting for all pods to be running and ready: Not all pods in namespace 'default' running and ready within 10m0s

**Comment by marekbiskup** [comment]
I need a fix for my other tests. I'll make a quick PR.

**Comment by marekbiskup** [comment]
#10609 renames the port. (it turned out that the port name wasn't used anyway)

@quinton-hoole , Correct me if I'm wrong: we don't need to do anything about tests because @satnam6502 's test does the job.

**Comment by satnam6502** [comment]
There is an existing PR which changes the port names #10453 which has been waiting for a merge for a while -- so you could cherrypick the commit in that -- my PR for the namespace change also has that change. I think that is preferable to making a new PR.

**Comment by zmerlynn** [comment]
@satnam6502: Sorry about that. My memory really has been goldfishy as on-call.

**Comment by satnam6502** [comment]
Thank you kindly, whoever you are.

**Comment by marekbiskup** [comment]
already fixed (I can't recall which PR)

**Comment by pencilcheck** [comment]
I'm getting the same error with the name 'backend-demo-test'

I just updated kubectl and it still gives me the same error
