### ISSUE TITLE
Update kube2sky to use v1 API

### ISSUE THREAD

**Issue by nikhiljindal** [GoogleCloudPlatform/kubernetes#10754]
I see that kube2sky is still issuing v1beta3 requests in e2e tests.
We need to update it to use v1 API.

We cant stop exposing v1beta3 in master, unless this is fixed (https://github.com/GoogleCloudPlatform/kubernetes/pull/10525)

Example request from e2e logs:
```
GET /api/v1beta3/endpoints: (458.105µs) 404 [[kube2sky/v0.20.0 (linux/amd64) kubernetes/unknown] 10.240.92.0:37178]
```

**Comment by nikhiljindal** [comment]
cc @thockin @ArtfulCoder @bgrant0607

**Comment by nikhiljindal** [comment]
Looking at the code, it seems like it is correctly configured to use v1: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/dns/kube2sky/kube2sky.go#L438
Not sure why is it emitting v1beta3 requests.

**Comment by thockin** [comment]
I don't know the logic here - could use an assist to figure it out - I
built 1.10 with the v1 changes, I am 99% sure.

**Comment by zmerlynn** [comment]
cc @jlowdermilk 

It's presumably getting it's kclient.Config from an sideloaded kubeconfig, isn't it, rather than the if block there? Is it possible the client code in the container was built pre-#9762?

**Comment by zmerlynn** [comment]
Or, shot in the dark, does #10556 play a role here? Not sure when those images were built, nor that familiar with the client code.

**Comment by jlowdermilk** [comment]
@zmerlynn, loaded or constructed kubeconfig shouldn't make a difference; that code isn't setting apiversion in overrides so it's getting the hardcoded default from pkg/latest. Is there a good way to determine what commit/pr # the kube2sky container was built from?

**Comment by jlowdermilk** [comment]
@nikhiljindal, @thockin Looking at https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/dns/kube2sky/kube2sky.go#L438 , that will only set apiversion explicitly if no kubecfg flag was provided. Since we are setting a kubeconfig flag for gce, that means it is [defaulting](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/helper.go#L493) to whatever was set in `pkg/latest` at the time the kube2sky container was built. To always set explicit apiversion, put
```
config.Version = "v1"
```
at the bottom before the call to `kclient.New(config)`

**Comment by nikhiljindal** [comment]
Fixed by https://github.com/GoogleCloudPlatform/kubernetes/pull/10771
