### ISSUE TITLE
Wrong node cpu/mem limit metrics

### ISSUE THREAD

**Issue by jszczepkowski** [GoogleCloudPlatform/kubernetes#11052]
Metrics "kubernetes.io/cpu/limit" and "kubernetes.io/mem/limt" have wrong (default) values for the whole node (container "/"). To reproduce, create a GCE cluster with "n1-standard-2" node with GCE and enter container "/" in the query. Metric "kubernetes.io/cpu/limit" on GCM will be 1 (despite our nodes have 2 cores) and metric "kubernetes.io/mem/limt" will be -1 (MaxUint64). These seem to be the default values set by cadvisor in https://github.com/google/cadvisor/blob/master/container/docker/handler.go#L150.

**Comment by jszczepkowski** [comment]
@piosz @vmarmol @rjnagal @vishh

**Comment by vmarmol** [comment]
The memory part was just fixed by google/cadvisor#804 but we'll need to update Kubernetes' Godep to get it. The CPU part is trickier, the kernel (and cAdvisor) export the interface in CPU shares which Heapster then assumes 1024 shares == 1 core (which is what we do in Kubernetes). We can't "fix" that in cAdvisor, we'll need Heapster to replace that value with the machine size. Filed: GoogleCloudPlatform/heapster#399

**Comment by rjnagal** [comment]
Closing this in favor of heapster issue, where we can make the actual fix.
