### ISSUE TITLE
Move user docs to docs/user-guide and create an up-to-date TOC

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#11093]
We've started to create a user guide in docs/user-guide. We should move related docs and concept-oriented examples to there, and create a TOC.

We probably need to merge, refactor, rename, etc. docs as well.

Files to move:
* docs/user-guide.md -> docs/user-guide/README.md, and updated
* Generated kubectl docs to docs/user-guide/kubectl/  @jlowdermilk 
* docs/accessing-the-cluster.md
* docs/annotations.md
* docs/application-troubleshooting.md
* docs/compute_resources.md
* docs/container-environment.md
* docs/containers.md
* docs/debugging-services.md
* docs/downward_api.md
* docs/identifiers.md
* docs/images.md
* docs/k8s-ui-*.png
* docs/kibana.png
* docs/kubeconfig-file.md
* docs/labels.md
* docs/logging.md
* docs/monitoring-architecture.png
* docs/monitoring.md
* docs/namespaces.md
* docs/overview.md
* docs/persistent-volumes.md
* docs/pod-states.md
* docs/pods.md
* docs/replication-controller.md
* docs/secrets.md
* docs/security_context.md
* docs/services.md
* docs/services*.png
* docs/sharing-clusters.md
* docs/ui.md
* docs/volumes.md
* docs/working_with_resources.md
* examples/downward-api
* examples/environment-guide
* examples/explorer
* examples/limitrange
* examples/liveness
* examples/logging-demo
* examples/node-selection
* examples/persistent-volumes
* examples/resourcequota
* examples/secrets
* examples/update-demo
* examples/walkthrough
* examples/multi-pod.yaml
* examples/pod.yaml
* examples/replication.yaml
* examples/simple-yaml.md
* examples/simple-nginx.md

Related: #9220, #9494 

cc @nikhiljindal @lavalamp

**Comment by RichieEscarez** [comment]
Hi @bgrant0607, 
Since all user docs are moving over to gh-pages, i dont see this file reorg necessary. Ive also already created the site navigation files for v1 based on the docs/*.md and examples/*.md file structure so this move will also have impact there. Once we move these files to kubernetes.io (#9494), the site navigation will serve as the TOC. Here is a screen cap from my local build: 
![k8s io](https://cloud.githubusercontent.com/assets/11762685/8654497/7a02d554-293f-11e5-9fdb-40d6883ee122.jpg)

**Comment by bgrant0607** [comment]
cc @mikedanese
