### ISSUE TITLE
kubectl describe node should include allocated resource

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#11238]
kubectl describe node includes, node resource capacity, and all pods allocated to that node already. It should also include resourceAllocation information.

**Comment by yujuhong** [comment]
@dchen1107, by "allocated resources" do you mean the "total resource requirements of all pods on the node"?

E.g., `describe node` currently shows:
```
Capacity:
 memory:	3800808Ki
 pods:		40
 cpu:		1
```

kubectl can look at the pods assigned to the nodes, and compute:
```
Allocated resources:
 memory:	100808Ki
 pods:		3
 cpu:		0.5
```

I assume kubectl'd have to exclude pods in terminated states (e.g., failed/succeeded) when summing the allocated resources since they no longer consume any cpu/memory. Scheduler also does the same thing.
