### ISSUE TITLE
Jenkins gce-flaky is running all tests if GCE_FLAKY_TESTS is empty list

### ISSUE THREAD

**Issue by wojtek-t** [GoogleCloudPlatform/kubernetes#11576]
cc @gmarek @davidopp @thockin 

See gce-flaky runs - e.g. 2270 or 2271

**Comment by wojtek-t** [comment]
The reason for it is that if GCE_FLAKY_TESTS is empty, then:
join_regex ${GCE_FLAKY_TESTS[@]:+${GCE_FLAKY_TESTS[@]}}
(see: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/jenkins/e2e.sh#L135 )
returns an empty string, which unfortunately matches all the tests.

**Comment by wojtek-t** [comment]
cc @ixdy 

On the other hand, we can consider it as "working as intended" - if GCE_FLAKY_TESTS is empty, the it doesn't make much sense to just start and stop the cluster without running any tests - so maybe in that case running everything is what we want?
If so - we need to definitely add a comment about it.

**Comment by ixdy** [comment]
I can't decide how to feel about this. It is surprising that gce-flaky runs all tests right now, since no tests are in the flaky set; I initially thought something was very wrong when I ran into this last week.

The most logical thing would be to not run gce-flaky at all when there are no flaky tests, but II don't know how to programmatically control whether the Jenkins project runs from our repo.

Simply building a cluster and tearing it down without running any tests doesn't make sense.

I guess we're left with running all tests, and adding a big warning or disclaimer that this is the expected behavior, even if confusing.

(I guess one last option is to specify some focused test which always runs on the flaky build; when there are no flaky tests, that's the only one which runs. Doesn't seem like that gives us much benefit for the resources used, though.)

**Comment by wojtek-t** [comment]
>
The most logical thing would be to not run gce-flaky at all when there are no flaky tests, but II don't know how to programmatically control whether the Jenkins project runs from our repo.

Yes - I also looked into it and haven't found anything useful.

>
Simply building a cluster and tearing it down without running any tests doesn't make sense.
I guess we're left with running all tests, and adding a big warning or disclaimer that this is the expected behavior, even if confusing.

I think I agree with that (although it's not very strong feeling).

**Comment by zmerlynn** [comment]
I actually have no problem with running the empty set. It might seem like a waste, but it's more consistent and means various people don't have to remember that oddity if they glance at this test run. It might seem like a waste, but *shrug*. I've actually been meaning to write just an up/down test anyways...

**Comment by thockin** [comment]
I think I agree with Zach.
