### ISSUE TITLE
Using Kubernetes with OVS

### ISSUE THREAD

**Issue by Pensu** [GoogleCloudPlatform/kubernetes#11877]
Hi all,

I want to use OVS with Kubernetes. I am deploying this stuff from scratch and I am following bottom up, i.e. I have created an etcd cluster and now, I want to come to networking part. Flannel is creating some issues for me, so I am thinking about going with OVS. Now, I am not able to find much documentation about OVS, I mean is it used along with flannel or is it a replacement for flannel? 

Can you please provide me with any pointers or guide me to some article or something where is it explained as to how to use OVS with kubernetes? TIA.

**Comment by yujuhong** [comment]
@Pensu, [this doc](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/admin/ovs-networking.md) explains how kubernetes uses OVS. Our vagrant scripts also sets up OVS for network. You can find the details in the scripts under [kubernetes/cluster/vagrant](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/cluster/vagrant).

**Comment by mikedanese** [comment]
If you want to dig through some code, checkout https://github.com/openshift/openshift-sdn which is using OVS.

**Comment by Pensu** [comment]
@yujuhong @mikedanese hi, thanks for your help guys. I looked at the doc and deployed kubernetes using vagrant. There is no flannel and I can see the gre tunneling. One thing I have to ask here, is etcd being used here? As I can see that etcd container is running on my master, but it's not present on the minion. As far as my understanding goes, etcd is used to create cluster and send information about minion to the master. But if there is no etcd on minion, how exactly is the cluster being formed? Or is that being taken care by OVS itself? Forgive me, if the questions sound too noob!

**Comment by bprashanth** [comment]
Without getting into the technical details, openswitch gives you the ability to operate a 'real' sdn by forwarding traffic through a control plane (so multi-tenancy, traffic shaping etc are easier). Flannel was built to be a simpler overlay network that assigns routable ips to containers on multiple hosts. A fairer comparison would be openswitch in "bridged" mode and flannel.

At the end of the day flannel and ovs use tunnels and encapsulation, so I'd suggest sticking with flannel if you don't care about openvswitch's "flow" mode properties. I believe a flannel plugin that manages tunnels through ovs is being worked on. 

Closing the issue, since others have given you some pointers.
