### ISSUE TITLE
e2e: SchedulerPredicates flaky last 4 runs on gce

### ISSUE THREAD

**Issue by alex-mohr** [GoogleCloudPlatform/kubernetes#12254]
The last 4 runs of Jenkins GCE tests have all failed with due to SchedulerPredicates test -- output is some variant of:
"""
SchedulerPredicates validates MaxPods limit number of pods that are allowed to run.

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/scheduler_predicates.go:221
Expected
    <int>: 200
to equal
    <int>: 300
"""

Appears to be insufficient time for a timeout.  #12251 to fix pending.

**Comment by alex-mohr** [comment]
Also worth understanding how a broken test made it in -- I think the SchedulerPredicates change went in today?  Are we not covering that in PR-based runs?

**Comment by ixdy** [comment]
It's explicitly excluded from the PR-based runs per https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/jenkins/e2e.sh#L108.

If we're OK with the submit queue taking longer, we could maybe create a separate Jenkins configuration which runs PRs without enabling Ginkgo's parallel mode, which would enable us to run more of the e2e tests.

**Comment by gmarek** [comment]
Yeah - it's unfortunate, but luckily it's not everyday we modify e2e tests that cannot be run in parallel. I think this problem is better than the opposite, which is running e2e test sequentially. Parallel runs usually ends in 1X minutes, sequential ones took over an hour last time I checked.

I'm sorry for this test - it was running successfully on my e2e cluster.
