### ISSUE TITLE
Need better docs for `kubecfg create minions`

### ISSUE THREAD

**Issue by isArbit** [GoogleCloudPlatform/kubernetes#1315]
kubecfg seems to support minion creation as I tried `kubecfg create` command:

    kubecfg.go:247] usage: kubecfg [OPTIONS] create <minions|pods|replicationControllers|services>

But when I tried `kubecfg create minions`, it shows:

    kubecfg.go:102] Need config file (-c)

But I cannot find any minion schema in documentation directory? Is it any ways I can create or add a new minion in existed Kubernetes cluster?

**Comment by GovindarajRangan** [comment]
I installed Kubernetes on three hosts (not using a Cloud Provider right now). Started "apiserver, controller-manager, kubelet and proxy" on master, "kublet and proxy" on two other servers. I checked the IP, env variables for KUBERNETES_MASTER, KUBE_ETCD_SERVERS etc. All config looks fine. But the Minion list isn't populated. I see an error saying there is no key defined at ETCD endpoint: /registry/registry/nodes/192.168.0.5/boundpods. No minions detected, can't create any pod! Please help...

**Comment by brendandburns** [comment]
Closing this as obsolete, since we have migrated to kubectl.

@GovindarajRangan my guess is that you need to set --hostname_override on your kubelets to their IP addresses.  Otherwise they will use the hostname.

If you continue to have problems, please find us on IRC at #google-containers, or open a new issue.

Thanks!
--brendan
