### ISSUE TITLE
Test all api versions

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#1473]
We need to make our tests parameterized for api version, e.g., via a command-line flag. Then we need to make hack/test-go.sh run our tests once for each version we support.

Ad-hoc testing of different versions is going to be error prone and repeat a bunch of logic unnecessarily.

Concrete steps:

a. Make an api/test library
b. It defines a command-line flag
c. It defines a Codec, etc (like the api/latest package) which is set based off of the command line flag
d. Tests everywhere are changed to import this library and use its Codec.
e. The testing script runs tests once for each version.

**Comment by davidopp** [comment]
Should we consider this required for 1.0? Sorry for the super-naive question, but how are we handling this today? Do we only test v1? Which tests actually depend on the API version?

**Comment by nikhiljindal** [comment]
Yes. We were testing only v1beta1.
I recently submitted a PR to test both versions (v1beta1 and 3) in our integration tests: https://github.com/GoogleCloudPlatform/kubernetes/pull/5587
I am now working on updating other tests as well.
Tracking that as part of: https://github.com/GoogleCloudPlatform/kubernetes/issues/5475

**Comment by ixdy** [comment]
As I commented in #5687, I'm a bit worried about testing all API versions in hack/test-go.sh by default. This will result in `make test`

**Comment by nikhiljindal** [comment]
Thanks for looking at that PR @ixdy.
Thats a valid concern.
For a short time, after we enable v1beta3 and before we deprecate v1beta1, we need to test both the API versions.
Looks like /hack/test-go takes about 2 minutes right now to run on travis. So we will be increasing its run time by 2 minutes by running it twice.
We can try it and see if travis behaves fine.
If not, we can pick a random version each time and run the tests for that (a bit like what our fuzzer tests do now). Maybe we can do that just on travis and run the tests for both the versions, when it is run locally?
We can even start with that first and see how that works instead.

What do you think?

**Comment by smarterclayton** [comment]
Testing all version in travis makes sense (but not by default).  If it's an ENV var switch it should be clear what caused the failure, and users can easily recreate.  My 2c

----- Original Message -----

**Comment by nikhiljindal** [comment]
@smarterclayton Yes there is an echo at the top of the script that prints the API version for which the tests were run.

I discussed this with @bgrant0607 and he agreed that we can run the tests just once on travis (picking a version at random) and testing both versions locally.
One idea he suggested was that we can choose different APIVersion for each go version, so that we end up testing both api versions in each travis run.

**Comment by nikhiljindal** [comment]
Fixed by https://github.com/GoogleCloudPlatform/kubernetes/pull/5687.
We will now test both the versions in test-go and test-integration when run locally.
On travis, we will test "v1beta1" with go 1.4 and "v1beta3" with go 1.3.
You can change the versions being tested using KUBE_TEST_API_VERSIONS env variable.
