### ISSUE TITLE
Idempotent creation

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#148]
Provide a mechanism to ensure idempotent creation of all resources and/or update kubernetes.raml if it is already possible.

**Comment by bgrant0607** [comment]
I think human-friendly names for pods generated by the replication controller are important for usability, and we might as well use a standard approach to name auto-generation, since I don't think that's hard. 

I propose a URL parameter, `&uniquify=true`, which will cause a unique suffix (uid? timestamp?) to be added to the provided name. The uid can be used if the name is empty. Pods created by config files on Kubelet would always uniqify. `--uniqify` would cause kubectl to add this URL parameter on create.

**Comment by thockin** [comment]
I'm not sure I am following.   We already generate names for pods under
replication controllers, but those names are UUIDs.  If we just change that
to be <pod_name>.<5_random_hexits> (or flip the order maybe), that retains
the need for unique names but is more human friendly.

When would your uniquify ever NOT be true, and what would it mean for N > 1?

We don't need uniquify on hosts because we generate namespaces for them
(though perhaps we should carve out a reserved space that is guaranteed not
to collide with users, rather than "probably won't collide").

**Comment by bgrant0607** [comment]
@thockin Yes, this is about human friendliness. UIDs don't make good names. I'd be fine with name_prefix-not_huge_number_of_characters. I understand the motivation for swapping the order when using dot as the separator, but find that problematic from a usability standpoint (e.g., imagine sorting by name).

This is also about consistency across API objects and across usage scenarios (e.g., other kinds of controllers, generated services or replication controllers).

Uniquify would generally not be true -- this doesn't just apply to pods created by replication controllers. Replication controller would always use it for the pods it created, however. If the user used this on the replication controller itself, the replication controller would then have a uniquified name.

**Comment by smarterclayton** [comment]
So after I think about this a bit, I don't like having this *only* be able to be specified as part of the query.  I think that a client should be required (or encouraged) to specify the desire of uniqueness as part of the resource POST body (server is not required to make the stored resource exactly match the incomin request).  This allows a config file on disk to specify uniqueness, which has concrete meaning to both the client (in applying logic to determine names) and server (POST resource X wants a unique name).  This does not prevent client uniquification or name mutation (which have to be done by the client, because the server does not see an atomic unit)

If we could represent this commonly across as all resources, and find an unambiguous way to describe it, would that satisfy the use case?

I have two proposals:

1. Allow the "name" attribute to contain a single * in leading, trailing, or internal positions.  On POST, a resource that supports uniqueness would generate / calculate an appropriately transformed value and attempt to save.  

2. Add a new attribute to metadata called "nameTemplate" which can specify an optional prefix or suffix behavior like 1 (it's a template for a name).  The server may or may not persist that value along with the generated value (is it useful to know that later?)

3.  Add an attribute to metadata called "generateName" which is a struct with optional Boolean field "prefix".  It would mutate the provided name (if name was non empty).

I prefer 2 for succinctness of representation, but I think 3 is more predictable.  I feel 3 is strictly better than query parameters.  Opinions?  Will go implement this if folks are on board.

Note on uniqueness impl: If the create results in an already exists error in the underlying store, the server should generate a new name up to X times, and if it is unable to proceed, return a response indicating a transient error for the client to retry (not 503, but similar).  Clients specifying "unique" should never receive a 409 from the server unless a secondary attribute is also required to be unique (and that should probably be a 422 with field value must be unique error).

**Comment by smarterclayton** [comment]
Note: Naming of attributes is arbitrary, just to convey distinct positions.

**Comment by thockin** [comment]
Option 1 is "cute" but not is a good way.

Option 3 is most obvious.  Do you intend for this new field to be part of ObjectMeta or part of individual REST objects?  Will it apply to ~every REST object?

Do we need it at all?  What if, like docker, we assumed absence of name means "generate random"?

**Comment by smarterclayton** [comment]
See the attached pull for an example of what 3 looks like.  Omitting the name isn't terrible - one advantage of 3 is a naive get > json > create cycle randomly generates a new name.  3 is extremely clear what you want and what you get, and also allows you to get nice prefixing.

**Comment by bgrant0607** [comment]
@smarterclayton I agree with the problems with URL params. I was trying to avoid adding fields that wouldn't make sense in some contexts, such as kubectl config files.

@thockin We already plug in uids for pods in the absence of names. It's pretty user-hostile. Hence the desire to support specifying a user-friendly prefix. 

I agree that inserting a '*' is too cute. Clients would have to parse names in order to watch out for that.

Additionally, I'm not so keen to support so much flexibility in name autogeneration. Is there a strong need, for instance, for inserting the uniquifier as a prefix or in the middle? In particular, inserting random characters as a prefix would destroy any useful sorting.

How about just a `namePrefix` metadata field? If that's set and the name is empty, then the name is autogenerated using the prefix and a unique suffix.

Whatever we do should be supported uniformly for all objects.

**Comment by smarterclayton** [comment]
----- Original Message -----
> @smarterclayton I agree with the problems with URL params. I was trying to
> avoid adding fields that wouldn't make sense in some contexts, such as
> kubectl config files.
> 

I think as a field can make sense in config files that are intended as "create-only".  Since the labels are consistent, I might have X copies of things running, and can run kubectl create -f and inject them into the environment to do things at periodic intervals.  The one benefit is that you can manipulate these without introducing additional REST semantics and versioning.

> @thockin We already plug in uids for pods in the absence of names. It's
> pretty user-hostile. Hence the desire to support specifying a user-friendly
> prefix.
> 
> I agree that inserting a '*' is too cute. Clients would have to parse names
> in order to watch out for that.
> 
> Additionally, I'm not so keen to support so much flexibility in name
> autogeneration. Is there a strong need, for instance, for inserting the
> uniquifier as a prefix or in the middle? In particular, inserting random
> characters as a prefix would destroy any useful sorting.

I'm fine witch that.

> 
> How about just a `namePrefix` metadata field? If that's set and the name is
> empty, then the name is autogenerated using the prefix and a unique suffix.

I would advocate for a verb in there to convey that it's a field that has meaning during an action (i.e. like "restartPolicy" or "pullPolicy" or "createExternalLoadBalancer").  We can make it a pointer to a string, but I guess it comes down to whether there is ever any other reasonable parameter.  Empty string vs absent is harder to represent in some client languages - that's the only possible reason to leave it a struct with an optional "Base" field. I *think* that for things like Swagger pointer to struct vs pointer to string will result in a clearer API doc

**Comment by bgrant0607** [comment]
appendUniqueSuffixToThisPrefixToCreateTheName? :-)

More practical possibilities (trying to avoid "uniquification"):
* uniqueName{Prefix,Base}
* nameGeneration{Prefix,Base}
* autoName{Prefix,Base}

I had assumed that an empty string would imply not present -- it wouldn't be possible to autogenerate a unique name with no prefix. That doesn't seem like a huge restriction to me, given that it could be a single character.

**Comment by smarterclayton** [comment]
What I had right now was

  generateName: {
    "base": "",
  } 

but could be

  generateName: {
    "from": "",
  }

I thought we made pretty convincing arguments before for optional behavior being pointers to structs, but am happy to bikeshed more on it since it will stick around for a long time.

----- Original Message -----

**Comment by smarterclayton** [comment]
"generateName": {
  "from": "required non empty string"
}

?  The extra curly brackets add a bit more stuff, but it avoids the longer name and makes it fit well with "name".

Or do you guys strongly prefer not having the nested struct?

**Comment by bgrant0607** [comment]
I personally feel that the nested struct is overkill in this case, and is more complex to deal with. We're moving away from that for restartPolicy.

I view this as field defaulting rather than as optional behavior -- it shouldn't affect ongoing behavior. If the client specifies the name, then non-empty prefix is either irrelevant or an error, depending on how we want to define it. If the name is empty and the prefix is non-empty, then the prefix is used to auto-generate the name.

**Comment by smarterclayton** [comment]
Ok.

"generateNameFrom" is my preferred field of the ones mentioned so far, I'll go with that unless there is another preferred choice.

**Comment by thockin** [comment]
I'm fine with that, even if the "from" is a bit cutesy. :)

**Comment by smarterclayton** [comment]
That's too much ruby on the brain:

i.want.you.to do |what| is.asked! and :not end

**Comment by bgrant0607** [comment]
I'm fine with it, also.

**Comment by bgrant0607** [comment]
I believe this to be done.

**Comment by bgrant0607** [comment]
For reference:

Name-based creation idempotence was done long ago, as described here: https://github.com/GoogleCloudPlatform/kubernetes/issues/148#issuecomment-58224130

Facilitating non-idempotent creation and providing user-friendly generated names (instead of just uids) was completed recently.
