### ISSUE TITLE
Real container ssh

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#1513]
Forking ssh off of #386.

To debug a containerized application, currently, a user can ssh to the host and then use nsenter/nsinit or docker exec to enter the container, or they could run their own sshd inside their containers or pods, which we'd like them to not need to do. For non-interactive commands they could use kubelet's RunInContainer API, but there will be cases where the user wants an interactive shell or debugging session. For that, we should facilitate ssh directly into a container.

I don't think we'd implement ssh support exactly the same way, but geard implements a neat trick in order to support ssh directly to a container. I looked into how it did this a few months ago.

geard will generate ssh keys for containers upon request, and put them into `/var/lib/containers/keys`.

In addition to the keys themselves, geard injects its namespace entering command:
`command=\"/usr/bin/switchns\"`

`switchns` finds the container with the same name as the "user" and starts bash in the container using the equivalent of docker exec.

`/etc/ssh/sshd_config` needs to be changed to add a geard-specific key lookup command:
```
AuthorizedKeysCommand /usr/sbin/gear-auth-keys-command
```

This enables you to do:
```
ssh ctr-mycontainer@myvm
```

This mechanism was intended for lookup of users and their keys in remote services, such as LDAP.

Relevant assumptions for our solution:
* It should look like standard ssh as much as possible, as per the proposal in #386 
* I assume we'll be supporting user namespaces at some point.
* IP per pod
* Potentially multiple containers within the pod

The problem with `ssh <user-within-namespace>@<IP-of-pod>` is that the pod could have multiple containers.

I haven't done enough investigation to make a proposal as yet, but I wanted to record this feature request.

/cc @smarterclayton @erictune

**Comment by smarterclayton** [comment]
Now that exec has landed and is looking pretty stable, some followups to look at:

### Variants on nsenter that are more aligned with the container

We've talked before about extending nsinit from docker to be a true "execute in running Docker container" process, like rockets' equivalent.

### Taking the proxies out of the loop (or at least, the kubelet proxy)

Instead of using nsenter to run the user process, use nsenter to start a process in the container with a predetermined port and secret that would listen for a subsequent connection.  The kubelet could then redirect the response back to the caller with the port and location, and the caller can connect directly to the process.  The stub process would then do the necessary exec to launch the child and clean up after itself.  Important part is that this would make the network I/O part of the container's cgroup, not the kubelets.

### Pattern for launching SSHD in a container via exec

Launch SSHD via exec, then terminate the exec connection and connect from the client directly to a port.  Might be a simple package you could install into your container.

### On demand port proxy

Be able to request using your credentials that a new, random port be exposed through the cluster so you can access a container from anywhere that can reach a master.  The port might only accept one connection or require a specific source IP

**Comment by thockin** [comment]
Should this bug be closed now?

**Comment by smarterclayton** [comment]
I think as a bug it's done.  The last comment from me is next steps and it's not a priority right now.

**Comment by bgrant0607** [comment]
We should keep this open until we capture that in a doc or another issue.

**Comment by nehayward** [comment]
What's the process to setup a container on kubernetes and then ssh to it? I have minikube running on my computer as well as kubernetes running on gce. But haven't been able to ssh to a deployed pod.

**Comment by thockin** [comment]
see `kubectl exec`

**Comment by nehayward** [comment]
@thockin thanks for the quick response. I've been able to do that, but I need to be able to ssh to it. As I'm trying to Perfkit on kubernetes.

**Comment by thockin** [comment]
I don't have any experience setting up "real" SSH in a container

**Comment by nehayward** [comment]
This is the closest thing I've found so far. https://docs.docker.com/engine/examples/running_ssh_service/

**Comment by thockin** [comment]
For the record, it's generally an anti-pattern to run real SSH in a
container.  That doesn't mean you can't, just that you might want to think
about finding a way forward :)

**Comment by nehayward** [comment]
@thockin I agree. That's just how https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/tree/d7de2e2aa82650190b4640f8d64657846608144b is setup right now.

**Comment by s1113950** [comment]
@nehayward if you'd like to `ssh` to your container, here's how we do it: 
https://gist.github.com/s1113950/79b29d6ae82184b15d538e3cfe6a5439

It's an `anti-pattern` to do it this way, but sometimes all you need is an environment where you can run your code against, and you'd like to have kubernetes manage that environment :)
SSH also allows for things like remote code syncing via Pycharm!

**Comment by sadlar** [comment]
k8s dashboard 实现了ssh，但是也没有在docker里开ssh，dashboard的源码看一下，是不是调用的kubelet某些我们不知道的接口？
