### ISSUE TITLE
Remove need for the apiserver to contact kubelet for current container state

### ISSUE THREAD

**Issue by jjhuff** [GoogleCloudPlatform/kubernetes#156]
While the kubelet certainly is the source of truth for what is running on a particular host, it might be nice to have it push that info to the apiserver on a regular basis (and on state changes) rather than force the apiserver to ask.

Reasons:
 - In some deployment scenarios, the apiserver might not have direct contact to individual kubelets. 
 - It'd give the apiserver (and it's clients) access to a reasonably current state of the world without needing to poll each kubelet. This would be handy for improved replication/placement/auto-scale algorithms.
 - The update could include other info like statistics for both the host and containers
 - Open the door for auto-registering hosts

The kubelet could publish this to etcd, but I think it'd be good to aim for fewer dependencies on etcd rather than more. Thoughts on that?

**Comment by smarterclayton** [comment]
David is going to open an issue on the security of the kubelet in general with a proposal to restrict the kubelet via TLS client certs.  We may also need to let the kubelet ask the master whether certain things are allowed which would be covered under his SubjectAccessReview proposal

**Comment by bgrant0607** [comment]
cc @erictune

**Comment by alex-mohr** [comment]
@roberthbailey @cjcullen Robby and CJ have also been looking into securing the kubelet <-> master communication with TLS certs.  We definitely need to harden that path, but I think that's a separate issue than this one?

**Comment by smarterclayton** [comment]
@deads2k

----- Original Message -----

**Comment by bgrant0607** [comment]
This proposal was to change to unidirectional communication from kubelet to apiserver. If we replicated apiserver #473, I think that could work reasonably well, and would be inline with the approach used by other components, such as controller-manager and scheduler.

**Comment by bgrant0607** [comment]
@yujuhong

**Comment by bgrant0607** [comment]
Related: #3168, #2435, #2303. All issues predicted by @jjhuff.

**Comment by erictune** [comment]
On #3168,  @jlowdermilk said 
*I think we still need a secure channel from apiserver to kubelet to do things like exec in a container and stream container logs.*

**Comment by thockin** [comment]
Did the thundering herd suddenly stop being a problem?

**Comment by erictune** [comment]
@thockin hold that thought...

**Comment by erictune** [comment]
We could still maintain unidirectional kubelet -> apiserver communication if we introduce a third server, a bastion for logs streaming and command execution and ssh sessions.

So, then the flow would be:
```
kubelet --> apiserver <-- user
   ^                       |
   |                       |
   +------ bastion <-------+    
```
where `A --> B` means A is a client of B.

This has a couple of nice properties:
  -  maintains unidirectional kubelet -> apiserver comms. 
    - helps with some things for Hosted kubernetes implementation.  In that case, either run bastion in same domain as kubelets which user already has access to, or don't have a bastion, and user talks directly to kubelets to do those operations.   @alex-mohr @cjcullen 
    - may result in easier to reason about system, better layering and composeability
  - @smarterclayton had said he wants to always use bastion for SSH on openshift, so it is not really adding a component.
  - ssh sessions and log streams should not be going through the apiserver anyways.  the problem of auditing ssh sessions for certain actions or auditing streamed logs for sensitive content, etc, are quite different from implementing an apiserver, and so deserve a separate binary.

**Comment by bgrant0607** [comment]
I like the proposal, @erictune.

@thockin Yes, I'm now convinced thundering herd is a manageable problem, because:
a) We could replicate apiserver, load balance, and maintain session affinity (kubelet->apiserver and perhaps apiserver->etcd), if necessary.
b) We could fuzz communication initiation times upon kubelet restarts.
c) Beyond a certain scale, we should shard into multiple clusters.

**Comment by erictune** [comment]
Regarding @smarterclayton 's comment above about kubelet needing to "ask the master whether certain things are allowed".  The alternative to having the kubelet check for permission is to have users first explicitly enable an action they intend to do, by changing a special field on the Pod spec.    That could have some nice properties.

Here is how it might work:
  - User creates pod.  By default, kubelet will not allow pod's containers cannot be ssh'ed to or their logs to be streamed.
  - Later, user wants to ssh to a container of that pod.
  - User updates the pod spec to set the `Spec.RuntimeAccess.AllowSSH` to true.
  - Kubelet sees the change in the pod because it is watching the pod.
  - Kubelet enables SSH to that pod's containers in its server.
  - Kubelet updates the pod's Status to include `Status.RuntimeAccess.SSHAllowed` to true and `Status.RuntimeAccessHistory.SSHAllowed` to true. 
  - The user's client program notices that the change has propagated and so sets up the SSH session, as described elsewhere, using a Bastion or not.
  - Afterwards, the `Status.RuntimeAccess.SSHAllowed` bit is set back to false.  The `Status.RuntimeAccessHistory.SSHAllowed` bit stays true to show that the Pod is tainted by having been ssh-accessed.

Some nice properties of this approach:
  - maintains unidirectional kubelet->apiserver communications
  - minimizes how much of the policy and security model of apiserver that the kubelet has to understand (better for composibility)
  - makes it visible to anyone watching the pod that the pod has changed state.  
  - makes it easy to permanently *taint* the pod by virtue of the user having SSHed to it (who knows what the user did to it).  One could imagine a replication controller that killed and started replacements for tainted pods.
  - makes it easier for e.g. a network finalizer to interven and setup some special network thing needs to happen to allow the SSH to happen.

**Comment by erictune** [comment]
What I haven't thought through in the last post is how to say "which user is authorized to SSH to this pod".

**Comment by M13Kd** [comment]
Let's merge repositories in UX DEVELOPMENT thanks. 


Sent from my MetroPCS 4G Android device

-------- Original message --------

**Comment by smarterclayton** [comment]
The direction I had been thinking was preferably with delegated trust (macaroons) or simply to let the kubelet call subjectaccessreview.  Both keep the primary part of the logic on the masters, even though the latter requires asking the master for something it's part of a clear APi call pattern.  Ssh as an admin would be managed by another pattern.

**Comment by smarterclayton** [comment]
Andys proposal for remote exec essentially lays out the pieces for the bastion as described by Eric.  Right now it goes through the apiserver proxy, but that code is loosely coupled with the rest of the apiserver and high volume traffic can be easily split.

Agree with the other points Eric makes below

**Comment by smarterclayton** [comment]
Also, the bastions need to authorize calls as well so in my head the bastion proxy and the kubelet can check auth exactly the same way (to start), and then in the future we could get more sophisticated - ie:

User contacts bastion with their token, bastion combines its authority to talk to kubelets (granted by its client cert, etc) to mint a macaroon that allows the user to access host x, pod y, and container z for 10 seconds (clock skew).  The bastion then connects to the kubelet with that macaron (and its client cert), and the kubelet can efficiently verify the chain of trust that allows the delegation.

Or if you want the bastions to be simple, you contact the master to get a macaroon that lets you talk to the xyz tuple, and both the bastion and kubelet check the tuple the same way.

**Comment by erictune** [comment]
Work items to close this issue:
  - [ ] https://github.com/GoogleCloudPlatform/kubernetes/issues/4561
  - [ ] https://github.com/GoogleCloudPlatform/kubernetes/issues/4562
  - [ ] https://github.com/GoogleCloudPlatform/kubernetes/issues/4564
  - [ ] https://github.com/GoogleCloudPlatform/kubernetes/issues/4565

**Comment by bgrant0607** [comment]
We're working on this.

**Comment by dchen1107** [comment]
Should we close this one?

**Comment by bgrant0607** [comment]
Yes
