### ISSUE TITLE
GC old dead containers and unused images

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#157]
As far as I can tell, we never call DELETE/RemoveContainer nor RemoveImage. 

We should keep containers around for some amount of time for inspection, copying files out, etc., but should eventually clean them up. 

We could treat images as a cache, evicting on LRU when we reach some predetermined space limit -- ideally before the disk just fills up.

**Comment by dchen1107** [comment]
I am reopening this issue since I believe #3097 doesn't address image gc issue. See #3264 for detail reasons. In a short version, current support of gc of image depending on docker's "dangling=true", which gives us proper unused images on a node. Instead it only returns a list of image layers without tag.

**Comment by bgrant0607** [comment]
@vmarmol are you working on this? If not, please summarize the status and unassign.

**Comment by vmarmol** [comment]
It was just assigned to me :) I plan on tackling it this coming week.

**Comment by bgrant0607** [comment]
User on IRC just reported OOD due to too many dead containers from different dead pods:
http://paste.kismatic.io/view/a13c5e16#t15QhxeWR8MVIHhEKle50JpFhJjA9op4

@brendandburns @dchen1107

**Comment by vmarmol** [comment]
Created #5457 and assigned to myself.
