### ISSUE TITLE
Support `--net=host` through kubelet

### ISSUE THREAD

**Issue by jbeda** [GoogleCloudPlatform/kubernetes#175]
Ideally we'd run the proxy in a container itself.  But to really make that work, we'd need it to be able to use the `--net=host` mode in Docker.

**Comment by thockin** [comment]
I am closing this - I think it is unlikely to be something we really want to do.  HostPorts are dangerous enough - this is heading in the wrong direction, and I think we can achieve the goals without this limitation.

**Comment by dchen1107** [comment]
I am re-opening the issue. To able to run master components in a pod (#5011), we need to have host networking support,  at least on master node. 

I marked this for v1.0 for now, and bumped the priority to P1. 

cc/ @vmarmol @ArtfulCoder @thockin

**Comment by vmarmol** [comment]
Assigning myself as @ArtfulCoder and I will be tackling this in the coming days.

We deemed it higher priority since it is necessary in order to run the master components and the kube-proxy in pods. That will allow us to have an upgrade story for 1.0.

**Comment by bgrant0607** [comment]
I understand why kube-proxy would need host networking, but why does the master need it?

**Comment by dchen1107** [comment]
@bgrant0607 I and @ArtfulCoder debugged his issue together this afternoon: Current approach we put all master components into one pod, including nginx. Network container is started with its own PodIP, but ssl cert is generated for host IP. All minions rejects the connection from apiserver, since the IP from cert doesn't match the IP of apiserver. Also PodIP is dynamic and will be changed when network container restarted, there is no easy way to regenerate ssl cert from new PodIP and securely distributed to all minions. 

But I do have one puzzle since kubectl get <resource> works this afternoon? Why? Maybe kubectl doesn't validate cert?

**Comment by bgrant0607** [comment]
Isn't every service running on Kubernetes going to have this problem?

Also, using host networking is not going to work for HA #473.

**Comment by bgrant0607** [comment]
I suppose services running on Kubernetes should use SSL certs with the service IP(s) (external and/or internal). However, that would still mean that the keys would need to be minted after dynamic IP address assignment. Maybe @erictune knows what the plan is for that (or knows who knows).

**Comment by thockin** [comment]
Right, after looking at this issue this afternoon, I think either we do
this or we rethink master components in pods for 1.0

**Comment by bgrant0607** [comment]
Do "this" being host networking? Given that it's needed for kube-proxy, I'm fine with that as a workaround for the master.

However, I'm also wondering what the solution will be for users.

**Comment by thockin** [comment]
I think the general solution will be to use an L7 SSL terminating balancer

**Comment by bgrant0607** [comment]
That makes sense.

**Comment by ArtfulCoder** [comment]
We may not need need to use host networking for the master pod if we can assign an ip to the docker container that we create for pause.

While docker does not have any command flags that let us specify the ip of the created docker container, we can take over creation of the networking namespace for the container and configure it ourselves.

Doing this allows us to assign an ip to the docker container. I tried out the following steps from the [docker networking page](https://docs.docker.com/articles/networking/#container-networking) and it seems to work.

At one shell, start a container and leave its shell idle and running

$ sudo docker run -i -t --rm --net=none ubuntu /bin/bash
root@63f36fc01b5f:/#

At another shell, learn the container process ID and create its namespace entry in /var/run/netns/
for the "ip netns" command we will be using below

$ sudo docker inspect -f '{{.State.Pid}}' 63f36fc01b5f
2778
$ pid=2778
$ sudo mkdir -p /var/run/netns
$ sudo ln -s /proc/$pid/ns/net /var/run/netns/$pid

Check the bridge's IP address and netmask

$ ip addr show docker0
21: docker0: ...
inet 172.17.42.1/16 scope global docker0
...

Create a pair of "peer" interfaces A and B, bind the A end to the bridge, and bring it up

$ sudo ip link add A type veth peer name B
$ sudo brctl addif docker0 A
$ sudo ip link set A up

Place B inside the container's network namespace, rename to eth0, and activate it with a free IP

$ sudo ip link set B netns $pid
$ sudo ip netns exec $pid ip link set dev B name eth0
$ sudo ip netns exec $pid ip link set eth0 address 12:34:56:78:9a:bc
$ sudo ip netns exec $pid ip link set eth0 up
$ sudo ip netns exec $pid ip addr add 172.17.42.99/16 dev eth0
$ sudo ip netns exec $pid ip route add default via 172.17.42.1

When we finally exit the ubuntu container, Docker cleans up the container, the network namespace is destroyed along with the virtual eth0 — whose destruction in turn destroys interface A out in the Docker host and automatically un-registers it from the docker0 bridge. So everything gets cleaned up without having to run any extra commands. 

Clean up dangling symlinks in /var/run/netns

rm /var/run/netns/$pid

**Comment by thockin** [comment]
This could work, but I think host networking is needed anyway.

**Comment by ArtfulCoder** [comment]
Why does kube-proxy need to run in net=host mode ? so that it can intercept the packets designated for service ips ? I haven't explored it completely, but I believe we could do that without net=host mode.

**Comment by thockin** [comment]
It needs to program iptables in the root netns

**Comment by ArtfulCoder** [comment]
One approach could be - 
Since Kubelet runs as root on host and manages all containers - the kubelet can configure the netns of all containers (except kube-proxy container) to direct traffic for service ips to the kube-proxy container.

This can be achieved since kubelet would take over creating netns for containers it does not rely on docker for creation of the network namespace.

**Comment by eparis** [comment]
@mrunalp @rajatchopra   I know mrunal and rajat have been doing "horrific hacks" sort of like those described in https://github.com/GoogleCloudPlatform/kubernetes/issues/175#issuecomment-84355019 in order to get their openshift-sdn OVS stuff to work around docker's inadequacy.  I believe they are trying to find a better solution to some of this through their network hooks and just want to make sure they see it happening again (slightly differently, obviously).

**Comment by thockin** [comment]
Abhi - that doesnt scale well.  Now kubelet has to install all the rules in
all the containers.  If you assume up to 30 pods per machine, that is 30
times more work.  Not impossible, but I dont think it is better.

**Comment by ArtfulCoder** [comment]
We can move the iptables-rules-for-service-ips logic in kubelet. The rules can divert traffic to the kube-proxy container.

The kubelet can set up these rules on host net space instead on each container.

That way, we still get away without --net=host.

Whatever logic needs to be done at a host level, should be kept in the kubelet that runs on the host direcrly.

**Comment by thockin** [comment]
We want kubelet in a container too.  That aside, setting up the iptables
rules requires you know the ephemeral port numbers allocated inside the
kube-proxy.

**Comment by ArtfulCoder** [comment]
We can have kube-proxy logic completely as part of kubelet (just as we have cadvisor in kubelet now)
kubelet can run as a container with --net=host, but not configured as a pod
That way we can still prevent --net=host for pods.

I am not sure if we can have kubelet as a pod, because (per my understanding) pod has to be instantiated by by a pre-running kubelet on the host.

**Comment by eparis** [comment]
Trying to think how to actually solve the master --net=host because of certificate problems, because I agre with you Tim, tons of things are going to have that problem.  This is exactly the problem satnam was facing months and months ago when he first looked at aggregated logging, we've seen it when trying to use kube to build ceph or gluster clusters (aka, you can't).

Only thing that comes to mind is 'nominal services' which expose the pod IP instead of a portal_net IP + kube-proxy in the middle and extension to the future networking 'stuff' that lets us specify the pod IP....   is that possible in the future?

Do we think requiring network plugins to let us specify an IP on a Pod is a legitimate requirement?  Seems like that turns into a number of problems...

**Comment by vmarmol** [comment]
After discussing with @ArtfulCoder and @thockin we decided to continue the route of adding support --net=host. We believe the complexity of the feature is low and is one that we will need to add regardless. The feature does not create any new significant problems we will need to handle. We will need it since even with the above alternatives, if we run Kubelet in a container (which is a goal), we'll need for it to run with --net=host.

We do plan for this to be a feature that is not enabled by default except for on-machine cluster services.

**Comment by dchen1107** [comment]
+1 on NOT having kube-proxy logic in kubelet. Kubelet could be down, update and crash, which shouldn't affect running services / containers. If all kube-proxy functionalities are included in Kubelet, we cannot achieve such goal. We want a simple proxy now, and eventually pushing down most of functionalities to kernel.

**Comment by brendandburns** [comment]
I don't think that running the kube-proxy in the kubelet is a blocker for v1.0, and all other uses don't required --host networking.  So I'm moving out of 1.0.

**Comment by dchen1107** [comment]
@brendandburns We need this for running master components in pod too, I explained the reason at: https://github.com/GoogleCloudPlatform/kubernetes/issues/175#issuecomment-84209309

**Comment by vmarmol** [comment]
This was fixed by #5886. Marking closed. A remaining TODO is for apiserver to use the property only if the capability exists. Will file an issue for that.
