### ISSUE TITLE
resolve label vs. selector confusion

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#2131]
Guest book example shows this service as an example:
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/guestbook#step-four-create-the-redis-slave-service

part of its json is this:
"labels": {
    "name": "redisslave"
  },
  "selector": {
    "name": "redisslave"
  }

Why both selector and label are needed - they have the same value, don't they have the same purpose too?

**Comment by brendandburns** [comment]
Closing this as the query param is now fixed in v1beta3.

**Comment by abonas** [comment]
> Closing this as the query param is now fixed in v1beta3.

@brendandburns can you elaborate what is exactly fixed - how does it behave now/new query param names for label and selector?

**Comment by nikhiljindal** [comment]
In v1beta3, the query param name has been changed from "labels" to "label-selector" and "fields" to "field-selector"
For ex: /api/v1beta1/pods?labels=name=xyz will change to /api/v1beta3/pods?label-selector=name=xyz

**Comment by abonas** [comment]
@nikhiljindal thank you. I'll update the client accordingly.
can you also elaborate/refer me to docs about the field-selector - what is this param represent?

**Comment by nikhiljindal** [comment]
Yes. We do not have any documentation around field-selectors.
Not sure if thats because we do not want external clients to use it @bgrant0607 ?

Similar to label-selectors, you can specify field-selectors as query params, primarily to LIST and WATCH.
Right now, only pods and events support them.
For ex: If you want a list of all unscheduled pods, you can access:
`/api/v1beta1/pods?field-selector=DesiredState.Host=` (https://github.com/GoogleCloudPlatform/kubernetes/issues/5207)
You can find the list of fields supported by pods and events here: 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta1/conversion.go#L1382
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/conversion.go#L27

**Comment by brendandburns** [comment]
@abonas, with my recent PR, the query params for v1beta3 are
'label-selector' and 'field-selector'

Brendan

**Comment by abonas** [comment]
@nikhiljindal thank you!

**Comment by bgrant0607** [comment]
Correct, @nikhiljindal. field-selector is an "internal" mechanism that isn't ready for broad usage, until #1362 is resolved.
