### ISSUE TITLE
Deprecate kubecfg

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#2144]
Do we have plans to keep both kubectl and kubecfg? If so, why? If not, what are we waiting for to get rid of kubecfg?

There's a lot of duplicated code between them. Also, it's annoying to have to fix two clients.

**Comment by bgrant0607** [comment]
All the necessary functionality has been added to kubectl. Now we can complete the removal of kubecfg.

**Comment by brendandburns** [comment]
#1928 is subsumed by this bug.

**Comment by wnegus** [comment]
I am trying to do a very important demo of Kubernetes using a tutorial on Google.com  - but the issue is the tutorial uses the deprecated kubecfg.sh, and the instructions on the tutorial have not been updated to reflect the new kubectl.sh commands.  Can someone please look at the below and advise the equivalent command line entries to do the same thing using kubectl.sh?   Need help on this urgently please. 

https://cloud.google.com/solutions/real-time/kubernetes-redis-bigquery

**Comment by lavalamp** [comment]
"list pods" -> "get pods"
" -f <file> create <type>" -> "create -f <file>" (type automatically deduced)
"resize foo 0" -> "stop foo"
"delete pods/foo" -> "delete pod foo"

(All from memory and unchecked, YMMV)

I filed a bug report internally to get this page updated.

**Comment by wnegus** [comment]
Awesome !  Thanks for the quick response :)
