### ISSUE TITLE
Field selectors need to be versioned and converted to internal representation

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#2518]
Field selectors on GET and WATCH should refer to versioned fields and get converted to the internal representation just like the REST objects, and we should have a general-purpose way of finding the values of the fields to be matched.

In particular, podToSelectableFields in pkg/registry/pod/rest.go needs to be fixed to not reference v1beta1 (introduced in #2503 to address problem introduced by the v1beta3 refactor in #2097).

/cc @markturansky @smarterclayton @lavalamp

**Comment by bgrant0607** [comment]
@smarterclayton Are you actively working on this (and/or #3084)? Since it's one of the last open v1beta3 issues, I'd like to get it in soon. @nikhiljindal could write the PR if you'd be willing to review. 

Also, do you have a solution in mind?

**Comment by smarterclayton** [comment]
I had thought about it, but not started working.

The larger option in my head was to upgrade scheme to define mappings between structure locations for conversion (which would be useful later for limiting the number of conversion functions we need), and then building out a total mapping.

    every version to internal, then reverse
      map[string]string{
        "id": "metadata.name",
        "currentState.field.original": "spec.field"
        "currentState.field.renamed":  "spec.field"
      }

I don't know what the fan out is, but i assume it's manageable.  The name conversion mappings (when objects are moved to arbitrary positions) might be tricky, especially since refactors need to verify that an internal field move is accurate (we can probably test this during reflection with fuzzing).  The more tactical option is of course to define a map of only the needed attributes (with test functions to verify it) for the short term.

@lavalamp may have thought through this as well.  

----- Original Message -----

**Comment by bgrant0607** [comment]
@smarterclayton Thanks. I'd prefer to start with something narrow and iterate, if possible. For example, start with just supporting conversion for the current set of selectable fields:

**Comment by smarterclayton** [comment]
Certainly reasonable - the gap we originally had was error messages and validation - field selectors are really important to a UI so we need some variant of that in Openshift before we GA.  But we can always build that underneath an abstraction later.
