### ISSUE TITLE
Define industry buzzwords

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#2752]
Someone mentioned that our docs presuppose lots of knowledge about Docker, containers, microservices, etc. We should define these terms, or at least point to definitions. Some possible links below.

Containers: http://www.pwc.com/us/en/technology-forecast/2014/cloud-computing/features/open-source-application-deployment-containers.jhtml
Cloud native: http://www.slideshare.net/adrianco/netflix-what-changed-gartner-catalyst
Microservices: http://martinfowler.com/articles/microservices.html
12-factor: http://12factor.net/

**Comment by davidopp** [comment]
I think the best way to do this would be to create a glossary page and then link to it as appropriate, rather than try to define these terms inline (there's no fixed order in which people will read our docs, so we'd  have to define everything every time we use it).

BTW does anyone know how to link into the middle of a doc in Markdown? For example if I create a glossary, how do I link to one entry in it?

**Comment by bgrant0607** [comment]
On links to anchors, short answer is use html anchors:
http://stackoverflow.com/questions/5319754/cross-reference-named-anchor-in-markdown

**Comment by bgrant0607** [comment]
Added to wiki:
https://github.com/GoogleCloudPlatform/kubernetes/wiki/Why-Kubernetes%3F
