### ISSUE TITLE
Babysit daemons on KNode

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#2884]
In many cases, we saw docker daemon crashes caused by various reasons: docker bugs, sys OOM, OOD, even a bad docker pull (docker/docker/issues/8422) etc. We need a way to keep daemons running: docker, kubelet, cadvisor, ... 

cadvisor has no problem since once kubelet start running, it will drive the node to the desire_state, which includes cadvisor. kubelet's crash is handled by our own crash_handler, and will restart automatically. But if there is manual kill to kubelet, it won't restart itself. Also sometimes, we might need to restart kubelet if it fail /healthz check. Docker daemon crashes a lot, and there is no crash handler provided. 

We should have a mechanism to babysit our daemons, there are many different approaches: using supervisor, cron, start docker by kubelet, or start kubelet as docker container, etc.

Starting kubelet as docker container enable us to get kubelet and other daemon's monitoring / logging for free. But once docker daemon crash, kubelet will be killed along with rest of docker containers. In this case, we pretty much lost all states on the node. 

Starting docker by kubelet might be a better since kubelet is going to support node API. Kubelet could health check docker, restart docker, and report docker unavailability back to upper layer. But in this case, we have to have script to create cgroups for kubelet at init time, and teach cadvisor to check the resource usage too. Not sure how much burden for cadvisor here. Also we have to config fluentd to collect kubelet's log. But I think it should be straightforward here. 

cc/ @satnam6502 @vmarmol @brendandburns @bgrant0607 @thockin

**Comment by saad-ali** [comment]
Most of the Kubernetes components are, or will be, run in containers managed by Kubernetes. However, for the time being, kubelet, docker, and a few other processes are run on the host machine.
We want these processes to automatically restart if they crash for any reason.

**Option 1:**
Schedule a periodic cron job that kicks off a script that checks to see if the processes we care about are running, and starts them if the are not.

**Option 2:**
Modify the Kubernetes setup scripts for each cloud provider to install a process supervision tool (unless it is included in the host image for that provider). Use the process supervision tool to launch processes (and automatically restart them if they fail).
There are tons of process supervision tools out there:
* [monit](http://mmonit.com/monit/)
  * Used by [Kubernetes today](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/cluster/saltbase/salt/monit) to monitor ```etcd``` and ```kube-apiserver```, and restart them if they go down.
  * Does not spawn a child process, instead polls process every x seconds.
* [daemontools](http://cr.yp.to/daemontools/supervise.html)
* [daemontools-encore](http://untroubled.org/daemontools-encore/supervise.8.html)
* [runit](http://smarden.org/runit/benefits.html)
* [s6](http://skarnet.org/software/s6/why.html)
* [supervisord](http://supervisord.org/introduction.html)
* [systemd](http://freedesktop.org/wiki/Software/systemd/)
  * Uses cgroups to manage child processes
  * New process manager for Debian/Redhat/CentOS/Fedora process (available with Debian 8.0)
* [upstart](http://upstart.ubuntu.com/)
  * Process manager for Ubuntu. Ubuntu will also transition to systemd
* [circus](https://github.com/circus-tent/circus)
* [inittab](http://unixhelp.ed.ac.uk/CGI/man-cgi?inittab+5)
* [perp](http://b0llix.net/perp/)
* [nosh](http://homepage.ntlworld.com/jonathan.deboynepollard/Softwares/nosh.html)
* [god](http://godrb.com/)
* [bluepill](https://github.com/bluepill-rb/bluepill)

I'm leaning towards either S6 or systemd. S6 appears very light weight. Systemdd will be PID 1 for most major distros in the near future, and managing forked processes with cgroups seems particularly robust.


Thoughts? Should we go with a simple script or should we use a process supervisor, if, process supervisor, which one?
With a script we don't have to worry about if the monitoring tool is available on whatever host image in whatever cloud provider. And a script can be upgraded without bringing down any of the processes it is monitoring.
On the other hand, because both a script polls to see if the processes are up there may be a longer delay between a process crashing and it being restarted. Also, writing a monitoring/restarting script from scratch means it will likely initially be buggy/unreliable (reinventing the wheel).
Also, with a process supervisor, it's worth asking who monitors the monitor?

**Comment by derekwaynecarr** [comment]
I think for vagrant cloud provider, which is just fedora boxes with systemd, I have a restart policy on etcd now.  I would prefer we do not mandate monit - I disabled it on vagrant based setup since it's redundant to systemd doing it for me.  I will take a pass tomorrow to ensure I have restart policy set on the other unit files.

**Comment by brendandburns** [comment]
we should validate that we're happy w/ the version of systemd that ships
with debian/wheezy-backports

**Comment by dchen1107** [comment]
cc/ @filbranden Filipe, you helped one of our summer interns last year to play with systemd for our internally system, do you have result published somewhere? Also we might have to change startup scripts for our containerVM image for GKE.

**Comment by thockin** [comment]
Is it really possible to adopt systemd "just a little" without retooling
the whole distro?

**Comment by vmarmol** [comment]
We should also ensure that we can do the sub-cgroup management we were thinking of doing with systemd (I *think* we can, but we need to make sure). The whole "cgroups under" discussion has been around systemd not managing the cgroups.

**Comment by vishh** [comment]
@vmarmol: By manipulating systemd 'services' and 'slices' won't we be able
to achieve our "cgroups under" goals?

**Comment by vmarmol** [comment]
In theory yes, in practice we've run into trouble since they didn't allow slices under slices or something along those lines. I don't know details :) but when we tried some months ago we ran into trouble. Just want to make sure those don't affect us if we go that route.

**Comment by dchen1107** [comment]
@thockin Yes, that is what I want to figure out with Filipe. @vmarmol and @vishh, I don't think we want systemd to manage the cgroups at least for now. Let's continue moving the discussion of "cgroups under" with docker / libcontainer.

On this very topic, I personally prefer have a simple loop.sh(s) which start docker daemons and kubelet. We are managing our internal system like this for years without much issues at all.

**Comment by vmarmol** [comment]
+1 to @dchen1107's suggestion, having to do the install/setup for systemd/S6 may be more trouble than we want today.

**Comment by filbranden** [comment]
@thockin I don't think adopting a distro that uses systemd would have any bad side effects, at least last time I checked the default setup for Vagrant uses Fedora with systemd and I don't think kubelet + docker has any trouble running there. Do you have an example of where systemd might create problems for kubelet or cAdvisor right now?

I discussed this today with @dchen1107, @saad-ali and @rlarocque2 and it seems that moving towards CoreOS and moving off of Debian, in particular debian-backports.

(Nothing wrong with Debian per se, but even if we stick with them they'll go to systemd anyways, the main problem with Debian is how long that's going to take as compared to switching to a systemd-based distribution now.)

**Comment by vmarmol** [comment]
@filbranden I think what @thockin meant is that if the distro doesn't use systemd, how hard is it to install and use it alongside whatever they use today. The concern is that it is a hard and error prone process to do that. I don't think there are any issues with using a distro that uses systemd.

**Comment by thockin** [comment]
Right - I don't have a real problem with systemd (or no more so than I ever
had). I just don't want some weird frankenlinux.

**Comment by derekwaynecarr** [comment]
@thockin - I debated what my own Linux distro would be called at lunch the other day.  I like frankenlinux :-)

**Comment by smarterclayton** [comment]
Just as a note, when we run Kube with systemd on RHEL systems we're going to have to deal with systemd managing cgroups.  Ideally, we'd take feedback and requirements from Kube to drive the focus on what gets implemented in systemd (or at least, where we spend effort).  Knowing the limitations there sooner rather than later is going to be important for us as well.

**Comment by filbranden** [comment]
@thockin @vmarmol Yes I understand. So my opinion is that right now debian-backports is already pretty close to frankenlinux (we like Debian but we want a kernel from a non-default repo and in some cases we are tweaking it to enable some basic cgroup stuff that's disabled by default.) Pulling systemd into our debian-backports will probably bring it all the way into frankenlinux :-)

There are plenty of nice distributions that are available right now on GCE that support systemd, so we might as well do the switch today.

If we stick with Debian, at some point we're going to do the switch to systemd anyways, so we might as well just do it now towards another distro.

As @smarterclayton said, they're already running Kube alongside systemd on RHEL and I don't believe they're running into issues with it.

**Comment by saad-ali** [comment]
My two cents: I don't think that process supervision has to accelerate the switch to systemd/CoreOS.

For the time being, we are using monit to monitor etcd. It's not perfect, but it gets the job done. I will go ahead and extend that to monitor kubelet and docker.

As various cloud providers start updating their images to something that has systemd as the primary init system (whenever that happens), we can remove monit and start taking advantage of systemd's service auto restart and watchdog features to monitor/restart processes if they crash/hang--pretty much what @derekwaynecarr is doing for vagrant.

So, no need to to create any frankenlinux or rush to a new distro/image.

**Comment by bgrant0607** [comment]
Can this be closed?

**Comment by dchen1107** [comment]
Yes. Other issues were filed separately already.

**Comment by philips** [comment]
@dchen1107 What were those other issues?

**Comment by philips** [comment]
@dchen1107 nevermind, I see the references above bgrant's comment.
