### ISSUE TITLE
e2e --tests does not apply to cmd/e2e/e2e.go tests

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#2927]

**Comment by ixdy** [comment]
The e2e tests are now using Ginkgo, which supports --focus to filter tests based on the `FullTestText`. There's some discussion in #3837 about the desire to tag tests rather than searching the text.

Additionally, cmd/e2e/e2e.go has a -t or --test arg which plumbs through to the Ginkgo test runner; I haven't tested whether it works, but we may want to simplify the ways of selecting tests.

**Comment by zmerlynn** [comment]
I think this bug is stale. Instructions for how to focus are in development.md, I'm not sure we need to do more work.

**Comment by ixdy** [comment]
It might still be worth cleaning up - do we want to have both the --test option as well as --focus, when they're basically doing the same thing?

**Comment by zmerlynn** [comment]
If you want to use this bug to get rid of -t, go for it :)

**Comment by satnam6502** [comment]
I use `-t` every day but happy to switch to focus.

**Comment by ixdy** [comment]
I'm probably getting rid of -t/--test. We should just switch to using --ginkgo.focus.

**Comment by zmerlynn** [comment]
+1
