### ISSUE TITLE
kubectl commands should support multiple resources

### ISSUE THREAD

**Issue by ouyanggh** [GoogleCloudPlatform/kubernetes#3050]
Currently, it could not delete multiple pods at once, need to delete them one by one, it's very inconvenient if I have tons of pods to delete.

Unlike docker, docker can multiple stop/rm containers/images at once.

    # kubectl delete pods cae4affd-8726-11e4-bf50-0023ae9d8532,b30089bd-8726-11e4-bf50-0023ae9d8532
    F1219 10:34:57.539428   29761 delete.go:60] pod "cae4affd-8726-11e4-bf50-0023ae9d8532,b30089bd-8726-11e4-bf50-0023ae9d8532" not found

    # kubectl delete pods cae4affd-8726-11e4-bf50-0023ae9d8532 b30089bd-8726-11e4-bf50-0023ae9d8532
    E1219 10:35:02.354295   29767 cmd.go:132] If passing in command line parameters, must be resource and name
    E1219 10:35:02.354350   29767 cmd.go:133] See 'kubectl delete -h' for help.

**Comment by kbeecher** [comment]
Would this be a suitable task for someone new to k8s development? If so, I'd be willing to take a look at this, if someone could provide a couple of hints where to start.

**Comment by kbeecher** [comment]
Further to my last message, I have a functional work in progress I would like to share, if anyone is interested?

**Comment by erictune** [comment]
PRs are welcome.  See https://github.com/GoogleCloudPlatform/kubernetes/blob/master/CONTRIBUTING.md

**Comment by brendandburns** [comment]
Yes, this is a reasonable place to start.  Since its in the client, you
won't get much orientation to the core server code, but it will be a good
place to orient to the client side API.

There us also prior art that you can model off of.  The kubectl create ...
command already supports multiple resources.

A good command to adapter would be the 'label' command.  You can find it in
pkg/kubectl/cmd/label.go

Many thanks in advance!
Brendan
