### ISSUE TITLE
Document that PUT doesn't support partial updates

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#3112]
sending the following json to update a service:
"{"apiVersion":"v1beta1","port":6380,"containerPort":6379}"
fails with 422 and message: "service "" is invalid: name: required value ''"

It's not clear from the message what is exactly the problem.
is the "name" field missing? isn't it called "id" at the moment?
if yes, another issue (#3085) points on the fact that including the id fails the request with another error.

**Comment by bgrant0607** [comment]
Update requires the full resource to be specified. GET the resource, modify the fields you want to change, and do a PUT.

**Comment by bgrant0607** [comment]
Using #3084 for the field name conversion problem.

**Comment by ghodss** [comment]
As mentioned, PUT should not accept partial updates - PATCH should, and the issue for that is #4578.

This is documented in [api-conventions.md](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api-conventions.md): "Otherwise, PUT expects the whole object to be specified." Where else does it need to be documented?

**Comment by bgrant0607** [comment]
http://kubernetes.io/third_party/swagger-ui/
