### ISSUE TITLE
Rewrite the remaining e2e bash tests in Go

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#3130]
Whilst doing so, reduce/remove the cases where the tests were incorrectly passing.

**Comment by timothysc** [comment]
We were looking @ http://onsi.github.io/ginkgo/ if folks are interested.  It would be easier if we could contribute some of our tests upstream, and would be useful to the community.

**Comment by smarterclayton** [comment]
In general I've been disappointed with the extra headaches that come with some of the test frameworks on top of Go.  We tried a few, and in the end tried to consciously limit our tests to what the core library provides.  That mostly applies to unit and integration tests - for e2e tests the bar is a bit lower because you're assuming higher reuse of the core infrastructure between tests, which goes against some of the core Go test frameworks.

**Comment by zmerlynn** [comment]
We may want to have a wider GVC on this after canvassing options. The e2e
tests in bash are certainly flexible in some ways, but there's a bunch of
us that don't necessarily love programming in bash, plus it does make
testing a lot of things really hard. It'd be nice if you could do both, in
the end. I'd like to come up with an option that works for both core and
vendors both.

**Comment by rrati** [comment]
Here's a basic proof-of-concept for using ginkgo:
https://github.com/rrati/kubernetes/tree/ginkgo/test/ginkgo

**Comment by filbranden** [comment]
@rrati Nice!

I'll take a look at it and play with it a little bit. @satnam6502 I think this will also interest you.

One question I have is how to parameterize it, right now I see you're hardcoding `http://localhost:8080` as the master URL, how can we make it so that we'll run against a master in the cloud?

Is there any support for logging? Will ginkgo provide logging primitives so that each test can log its messages and they'll get attached to that specific test?

What about generating reports that can be consumed by a continuous integration system like Jenkins? Does ginkgo help generate something like Jenkins TAP or JUnit XML?

Otherwise it certainly looks nice, looks like a real testing framework...

Will take a closer look, I'll let you know if I have further questions for you.

Cheers,
Filipe

**Comment by rrati** [comment]
I think we could parameterize the tests with ENV variables or whatever method is used for the current e2e go tests.  The porting from those files to ginkgo is pretty simple and straight forward.  It's almost a copy/paste of the test.  Since this was just a POC I didn't take the time to provide a way to change the master URL, but we'd definitely want to be able to run against a cloud, local kube instance, or even a local kube cluster.

I updated the tests to use the By keyword, which can be used to log messages.  In ginkgo terms it uses By to denote a step, which may or may not be what is desired.  You can also always use fmt.Println to print messages as the test runs.  Output from a test is hidden by default and only shows up if the test fails, but you can run with ginkgo -v and see all log messages as the tests run regardless of success/failure.  I'm not sure what you mean by "attached to that specific test".  The log/step messages look to print out after a test competes so even when running in parallel the logs for a test are always printed with information for that test.

You can write custom reporters for a test suite that could probably generate the reports desired.  There are also a number of options to ginkgo that are recommended for running in a CI environment.  The docs recommend "-r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress".

**Comment by zmerlynn** [comment]
I believe all of the individual tests have workitem bugs, and we've got Gingko in the tree running the shell tests. What are the last nails in the coffin here? There's no real work item bug around the removal/cleanup of `hack/e2e.go`, though I think @filbranden is working on it with extreme prejudice anyways.

**Comment by roberthbailey** [comment]
This has become the roll-up bug. And, as you mentioned, there are a couple of loose ends to track down even after we have go version of each of the e2e tests. 

Assigning this to you for now so that once the tests are migrated we verify that the appropriate clean up has been done.

**Comment by mbforbes** [comment]
Assigning this and sub-issues to cluster lifecycle team as @roberthbailey and @zmerlynn seem to be owning; feel free to undo if I'm being too pedantic about adding `team/` labels here.

**Comment by satnam6502** [comment]
+1 to what @smarterclayton says although I understand I should defer to the appropriate `team/`.

**Comment by zmerlynn** [comment]
![download](https://cloud.githubusercontent.com/assets/4942464/8990225/bdd7abce-36a5-11e5-8a53-244bcb1eb8c0.png)

**Comment by zmerlynn** [comment]
Killed when #4184 was closed.

**Comment by roberthbailey** [comment]
Yay!

**Comment by timothysc** [comment]
Yippie!

**Comment by satnam6502** [comment]
RIP
