### ISSUE TITLE
Create a soak test

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#3137]
Strawman proposal: launch a cluster and run a large number of tasks against it in a randomized (but reproducible) order and monitor for failures.

@brendandburns suggests that as part of the soak test we try to stress the garbage collection facilities with both a bunch of failed pods as well as continuously updating and pulling new versions of the same image.

**Comment by alex-mohr** [comment]
FWIW, there's enough low-hanging fruit that we can start with trivial load generators and see what breaks after N hours.  We don't need a fully-automated jenkisinified monitored v1.

**Comment by alex-mohr** [comment]
@saad-ali are you actively working on this?

**Comment by saad-ali** [comment]
I am not. Removed my self as assignee. Feel free to re-assign.

I believe @lavalamp and @satnam6502 were working on a a load generator (see [`test/e2e/density.go`](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/density.go)), not exactly a soak test, but these efforts could be combined.

**Comment by satnam6502** [comment]
I can't recall where I left off the conversation -- but I could check in the simple test I wrote which created a N serve_hostname pods using a replication controller and made sure it could read the hostname from each one and it also reported the distribution. Perhaps too simple for a soak? Services, replication controller, pods, networking etc. would have to work for the test to pass so perhaps it's OK as a start if we put the test in a loop that is run every M seconds/minutes?

**Comment by davidopp** [comment]
@satnam6502 it would be great if you could check that in. I'd like to take a look at all of the benchmarking code, and seeing yours along with the others would be helpful. Please label the PR with the misc/perf-1.0 label. Thanks!

**Comment by satnam6502** [comment]
OK: I will.

**Comment by jayunit100** [comment]
am currently working some  on a `soak.go` implementation as well in the e2e/'s which is more comprehensive (using k8petstore).  it should be a good compliment to satnams isolated soak.  ill open a pr within a few days for that as well

**Comment by jayunit100** [comment]
as per conversation in irc w/ dr satnam, we will both be working on soaks, and organically commit them, maybe both. his might take longer to implement anyway.

**Comment by gmarek** [comment]
@jayunit100 - can you take an ownership of this Issue and close it when you feel that we have enough soak tests?

**Comment by gmarek** [comment]
Sorry - I just noticed that @jayunit100 is not an owner. Assigning to @satnam6502

**Comment by dchen1107** [comment]
I talked to @saad-ali last week and he is interested on helping with this.

**Comment by roberthbailey** [comment]
This probably has some overlap with #3139.

**Comment by quinton-hoole** [comment]
Hi Saad

Thanks for volunteering :-) to get a soak test up and running in Jenkins.

As discussed, the high level approach for phase one, code-named "Get A Basic Soak Test Running ASAP" is:

- Configure a new Jenkins Project to build a new test cluster (as per "go run e2e.go --up").  This should run approximately weekly (configurable).
- Configure a new Jenkins Project to run one iteration of our e2e tests against the cluster built in 1 above (and output the results).  Make this run as often as possible (every 20 min) for about a week.
- After e.g. a week, tear down the cluster and go to 1.

The details of how to configure an new Jenkins Project are below.  @jgrafton is the best local person to consult if you need assistance with Jenkins.

I would hope that the above is achievable within about a day (correct me if I'm wrong jgrafton).

After we have the basic setup working (early next week), we can refine it further.  A few necessary refinements that I anticipate are e.g.:

- What happens when the test cluster gets into a borked state?  e.g. if this happens on day 1 of the week, we don't want to wait until day 7 before a new test cluster is automatically built.  Provide an easy way to manually kick Jenkins to build a fresh test cluster (i.e. "goto 1" above) if anyone notices that tests are repeatedly failing.
- Automatically do the above (e.g. if 'n' test runs in a row fail, abort and rebuild the cluster).
- ... other... ? 
Q

On Thu, Apr 9, 2015 at 11:13 AM, Jeff Grafton <jgrafton@google.com> wrote:
Yes, I am very sorry - I meant to reply yesterday afternoon but got distracted. :(

A general overview of the flow is documented here: https://github.com/GoogleCloudPlatform/kubernetes/tree/master/hack/jenkins

Though it's not explicitly mentioned there, the kubernetes-build job runs hack/jenkins/build.sh, and the kubernetes-e2e-* jobs run hack/jenkins/e2e.sh.
There's one additional job not describe there - kubernetes-e2e-gke-test - which runs a prerelease testing version of kubernetes.

Each of the e2e jobs controls the tests and environment by setting environment variables before running e2e.sh.
For example, the commands run for each job:

kubernetes-e2e-gce
export KUBERNETES_PROVIDER=gce
export E2E_CLUSTER_NAME=jenkins-gce-e2e
export E2E_NETWORK=e2e
export E2E_ZONE=us-central1-f
export E2E_OPT=""
export PROJECT="kubernetes-jenkins"
curl -Ss "https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/hack/jenkins/e2e.sh" | bash -

kubernetes-e2e-gke
export KUBERNETES_PROVIDER=gke
export E2E_CLUSTER_NAME=jenkins-gke-e2e
export E2E_NETWORK=e2e-gke
export E2E_ZONE=us-central1-f
export E2E_OPT="--check_version_skew=false"
curl -Ss "https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/hack/jenkins/e2e.sh" | bash -

kubernetes-e2e-gke-ci
# export CLOUDSDK_API_ENDPOINT_OVERRIDES_CONTAINER="https://www-googleapis-staging.sandbox.google.com/container/v1beta1_testing/"
export CLOUDSDK_ENDPOINTS_CONTAINER="https://www-googleapis-staging.sandbox.google.com/container/v1beta1_testing/"
export KUBERNETES_PROVIDER=gke
export E2E_CLUSTER_NAME=jenkins-gke-e2e-ci
export E2E_NETWORK=e2e-gke-ci
export E2E_ZONE=us-central1-f
export E2E_OPT=""
export E2E_SET_CLUSTER_API_VERSION="yes"
curl -Ss "https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/hack/jenkins/e2e.sh" | bash -

kubernetes-e2e-gke-test
export CLOUDSDK_ENDPOINTS_CONTAINER="https://www-googleapis-staging.sandbox.google.com/container/v1beta1_testing/"
export KUBERNETES_PROVIDER=gke
export E2E_USE_LATEST_RELEASE_VERSION=yes
export E2E_CLUSTER_NAME=jenkins-gke-e2e-test
export E2E_NETWORK=e2e-gke-test
export E2E_ZONE=us-central1-f
export E2E_OPT="--check_version_skew=false"
curl -Ss "https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/hack/jenkins/e2e.sh" | bash -

As you can (maybe) see by comparing the configurations, each job uses its own cluster and network inside the kubernetes-jenkins project so that they don't conflict with each other.

Thus, to set up another job for density/scalability tests, you'd probably first need to update hack/jenkins/e2e.sh to allow you to change the cluster setup (e.g. the node count) and select which tests are run. (Maybe E2E_OPT is sufficient here? I haven't looked in too much detail in what you need to do.)
Then after that is done, we'd need to create new networks and Jenkins jobs, set it all up, and hope that everything works.

ACLs-wise, you should already be able to set up things in the kubernetes-jenkins GCP project (just don't delete anything!), but to configure Jenkins you'll need to create an account there and I or Zach will need to set the right bits on your account.

Would you want to target just the gce provider, or would you be interested in one or more of the gke providers as well? I'm probably OK duplicating everything for this, but I don't really want this to become a common trend, as it'll probably quickly become unmaintainable.

**Comment by jayunit100** [comment]
Also #7639 is now pending, which runs a modest soak as well as functional test of the k8pEtstore app

**Comment by quinton-hoole** [comment]
We now have a test in our Google-internal continuous integration environment which does the following:

1. Build a test k8s cluster
2. Continuously run our standard e2e battery of tests against the same test cluster for 1 week (configurable), reporting full results ever ~20 minutes.
3. After 1 week, goto 1.

Closing this 1.0 issue \o/
