### ISSUE TITLE
High-level guidance about what types of updates to use in what scenario

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#3153]
There's a lack of documentation and examples of use cases - when the entities should be updated, and which fields are updatable. 
For example, can a port of a service be updated? replicas number of a rep.controller be reduced? containers section of a pod changed to have another containers than the original?

**Comment by smarterclayton** [comment]
it would be ideal if this was called out in the api doc generated by swagger - I believe that was proposed here https://github.com/GoogleCloudPlatform/kubernetes/pull/2282 but not yet implemented

**Comment by abonas** [comment]
@smarterclayton , generating means it's supposed to be documented somewhere, right? So any docs/explanation here regarding update concept will be beneficial.

**Comment by bgrant0607** [comment]
Proposal to tag readonly fields: #2970.

Yes, we should also document which fields cannot be updated -- most can. I'd also use tags that could be converted to some kind of properties exposed via swagger for that.

**Comment by bgrant0607** [comment]
Let's use #1728 for which fields can be updated and which ones can't.

#3112 is for documenting PUT semantics.

#3086 is for documenting use of resourceVersion in PUT and /watch.

This issue should be for providing high-level guidance about what flavor of update to use in what situation. Also, since most users will use kubectl, we should start with docs in terms of kubectl. When to use kubectl update, --patch, rollingupdate, resize, label, delete/create, etc.

**Comment by bgrant0607** [comment]
There is some guidance here:
https://github.com/GoogleCloudPlatform/kubernetes/issues/1702#issuecomment-117839206

**Comment by bgrant0607** [comment]
Fixed by #11071
