### ISSUE TITLE
Verify that master failure doesn't kill any running containers

### ISSUE THREAD

**Issue by davidopp** [GoogleCloudPlatform/kubernetes#3163]

**Comment by a-robinson** [comment]
Verified manually, and I'll work on adding a unit test soon. Mentioning in a comment since apparently I can't self-assign issues yet.

**Comment by davidopp** [comment]
FWIW I was not able to assign this to you either. Your username doesn't come up in the auto-complete list (probably the same thing you saw). Not sure the reason...

**Comment by a-robinson** [comment]
The kubelet has two dependencies on the master:
1. Sending events to the apiserver - this is already handled and tested, although the policy isn't great. The event recording code (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/record/event.go#L44) retries with sleeping between attempts if the master is unreachable. This is already unit tested (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/record/event_test.go#L164). However, the "policy" is to just try 3 times, sleeping one second between attempts. This needs to be improved to handle realistic master downtime if we don't want to lose events.
2. Watching etcd - This was actually recently fixed by Brendan (#2994) such that no pods will be deleted without receiving the current state from all config sources being used by the kubelet, even if the kubelet is restarting and doesn't know about the pods from etcd yet. He added a test to verify this behavior (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet_test.go#L519).
3. Polling an HTTP endpoint (which could be the master). This is tested in the same way as watching etcd.

The kube-proxy depends on the apiserver OR etcd on the master, depending on the configuration, to retrieve and watch for updates to the list of services/endpoints.
1. If the master goes down while watching, the proxy will just continue retrying the watch while not changing anything, which is great.
2. If the master is down when the proxy needs to retrieve the list of services/endpoints, it will continue retrying until it doesn't fail in both implementations. The apiserver version has tests covering this (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/proxy/config/api_test.go#L112). On the other hand, the etcd version doesn't have any tests, but that's because its code isn't structured to be very amenable to tests. Since it won't be around for much longer before we stop letting minion components talk directly to etcd, I don't think it's worth putting the effort into refactoring it to make it testable.

Thus the only real action item is to improve handling of events while the master's unavailable if we consider events important enough to be worth taking up a bit more kubelet memory. @lavalamp, would you say that events are worth putting a little more effort into saving during master downtime?

**Comment by lavalamp** [comment]
> 3. Polling an HTTP endpoint (which could be the master). 

The only use of the HTTP endpoint polling at the moment AFAIK is in the container VM environment, where there is no master, and the HTTP endpoint is the GCE metadata server.

> The kube-proxy depends on the apiserver OR etcd on the master, depending on the configuration, to retrieve and watch for updates to the list of services/endpoints.

The later is deprecated, the former doesn't work everywhere yet.

> Thus the only real action item is to improve handling of events while the master's unavailable if we consider events important enough to be worth taking up a bit more kubelet memory. @lavalamp, would you say that events are worth putting a little more effort into saving during master downtime?

I think the relevant case is here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/record/event.go#L72, and in that case it's a good idea to perhaps allow more than 3 tries, and wait more than 1 second between each try. Note that this code will be used by any component sending events, not just kubelet. There was a bug earlier where a bad event would block the entire queue because the server was rejecting it--must not reintroduce that.

Bulk event creation would be an interesting feature to add in the future.

**Comment by a-robinson** [comment]
All the cases that I'm aware of are now covered by tests. Closing the issue, but please reopen if I've missed anything.
