### ISSUE TITLE
Secure node -> master communication

### ISSUE THREAD

**Issue by davidopp** [GoogleCloudPlatform/kubernetes#3168]
In some hosting environments/configurations, the network traffic between node and master may traverse the public Internet. As a result, we'd like to secure the communication between the node components (e.g. kubelet and proxy) and master. To avoid the complexity of securing the kubelet API, we'd like to secure the node -> master communication, but not the reverse. This simplification has a downside; it means all communication between kubelet and master would have to be initiated by the kubelet. For example, we'd have to change health checks to be initiated by the kubelet, which in turn raises a question of how to do flow control (master apply backpressure when it becomes overloaded).

**Comment by alex-mohr** [comment]
I'd like to leave this open as specifically tracking secure master <-> kubelet communication and farm out other independent parts to separate issues (fuzz testing, (D)DoS prevention, and the wide variety of issues in #2483).

**Comment by bgrant0607** [comment]
#156 is a proposal to make apiserver and controllers not contact kubelet. I am now in favor of that proposal.

**Comment by jlowdermilk** [comment]
I think we still need a secure channel from apiserver to kubelet to do things like exec in a container and stream container logs.

**Comment by bgrant0607** [comment]
Proxy/bastion cases. Fair enough.

**Comment by erictune** [comment]
Let's continue discussion of "exec in container and stream container logs" on #156

**Comment by roberthbailey** [comment]
@liggitt @a-robinson 

Here is my plan to get us to "Static Clustering" as defined in [clustering.md](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/clustering.md):

1. Configure the kubelet to use HTTPS
  * Generate a self signed certificate on the kubelet, bind to the port using TLS.
  * The master will connect over HTTPS without verifying the certificate.
2. Modify the kubelet to register itself with the master
  * For GCE/GKE, the master location is currently passed as the name of the master VM which is resolved into the internal IP of the master. For non-salt based platforms this is currently TBD until I investigate further.
  * The kubelet will pass its public key and location to the master, which will be stored persistently in etcd. The master can either use the current means to accept the kubelet into the cluster or implement the "insecure-always-approve" policy (as it will not yet be able to verify the certificate provided by the kubelet).
  * The master will now connect over HTTPS and verify that the certificate for the kubelet has the correct public key. Note that the kubelet will still not verify the master. 
3. Distribute certs to the master/nodes during cluster creation
  * For GCE/GKE this can be through the GCE metadata server or using gcloud ssh. For other providers this can be via ssh or another side channel.
  * For GCE we will use a single “cluster” certificate for all of the nodes instead of generating a separate certificate for each node to support managed instance groups. 
  * Instead of generating self signed certificates, the certificates on the master and nodes will now be signed by the same certificate authority. 
  * When the kubelet registers with the master, the master can verify that the provided certificate to register as well as the client certificate in the TLS handshake are signed by a known CA (the same one that signed the master certificate). The kubelet can verify that the server certificate provided by the master was signed by a known CA. 
  * When the master connects to the kubelet over HTTPS the kubelet can verify that the client certificate provided by the master is signed by a known CA (the same one that signed the kubelet certificate) and the master can verify that the server certificate provided by the kubelet was signed by a known CA.

**Comment by smarterclayton** [comment]
@liggitt I *think* this is the best place to describe the things we were talking about w.r.t. securing the kubelet.

**Comment by liggitt** [comment]
`NewMainKubelet()`/`Kubelet` already take a `client.Client` used to call the master API. That already provides a way to give the kubelet the master CA, and credentials to use against the API (cert, token, etc).

I'd like to start by plumbing the TLS, cert, and key options from the `Kubelet` options down to the server start. First stab at that is here: https://github.com/GoogleCloudPlatform/kubernetes/pull/5104

Note that there are still places that assume http and 10250 (like `minion.ResourceLocation`) that need to know the particular scheme and port for a given node. I think that means the node API object should probably contain that info in addition to the hostname.

**Comment by liggitt** [comment]
Before doing `the kubelet will pass its public key and location to the master`, could we update the Node API object to keep track of the location (scheme, host, port)? That seems like a much smaller change that would prereq what is described in #2, but would enable manually registering nodes using https or alternate ports (and would also let us fix `minion.ResourceLocation`)

**Comment by roberthbailey** [comment]
@liggit I'm finally getting some time to work on this issue and it seems like you've gotten a bit of a start for me. Thanks!

The list items above were a bit hand-wavy and weren't meant to represent consecutive PRs but rather the general plan forward, knowing that it will need to be tweaked as I dig into the details for each step. For your specific question, when the node registers with the master, we can certainly store a bit of extra information about how to contact the node, including port (I hadn't considered storing the scheme, since I'd just assumed everything would need to move to https but we can discuss that when we get there).

**Comment by roberthbailey** [comment]
An update with the current status of this work item (on GCE):

During cluster creation, a CA is created and then 3 pairs of keys/certificates are generated: server, client (kubectl), and node (kubelet). The server's key and certificate are passed to the server via the GCE metadata server, pulled down by salt, and used for the apiserver's HTTPS endpoint. The client key and certificate are kept locally and added to the kubeconfig file so that kubectl can use them to authenticate to the apiserver. The node key and certificate are added to the metadata for the managed instance group template that is used to create nodes in the cluster. It is pulled down onto each node by salt and then used by the kubelet to authenticate to the apiserver. The kubelet also exports an HTTPS interface on port 10250, but I believe that it isn't yet using the certificate from the metadata server but is instead generating a self signed certificate locally when it starts running.

Current state of connections:
 - kubelet -> master: secure. The kubelet verifies the certificate presented by the master and presents a client certificate for authentication.
 - kube-proxy -> master: secure. The kube-proxy verifies the certificate presented by the master and presents a bearer token (also pulled from the metadata server) for authentication.
 - master -> kubelet: insecure. The master does not check the certificate presented by the kubelet and the kubelet does not authenticate the master when it connects. 

The only remaining connections from the master to the kubelet (once the /validate endpoint is removed, see https://github.com/GoogleCloudPlatform/kubernetes/pull/8224) is for the proxy functionality in the master. We use this proxy heavily in our e2e testing as well as in many of our examples. So while it's a noble goal to remove all master -> kubelet communication, I don't see it happening for v1.0 and we instead need to finish securing this communication pathway.

**Comment by davidopp** [comment]
Awesome work!

**Comment by alex-mohr** [comment]
Update: @cjcullen is actively driving this -- CJ, can you please mention this issue for the relevant PRs so we can track them as they land?  (And thanks also to @brendandburns for helping out!)

**Comment by timothysc** [comment]
cc @rrati

**Comment by cjcullen** [comment]
SSH proxy code is in. The only remaining question is whether to leave 10250 open to the public internet (in which case we'd still need to secure it) or close it off and only listen inside the cluster.
@a-robinson @vishh

**Comment by roberthbailey** [comment]
We've decided not to leave 10250 open to the internet, so I'm bumping this to the v1.0-post milestone (since we still want to add better security to the kubelet's http endpoint, just not for 1.0).

**Comment by wingedkiwi** [comment]
I'm trying to follow the status of this issue. Is the master -> kubelet connection still insecure?

**Comment by roberthbailey** [comment]
The master -> kubelet connection is not secure enough to be run across the internet. The master currently only connects to the kubelet for proxying user requests that need to be forwarded to the kubelet (e.g. hitting the /api/v1/proxy/ endpoint or using kubectl exec / kubectl logs). In most cases, this is done over a local secure network. For GKE, we use ssh tunnels to securely put packets onto the cluster's network without exposing the kubelet's web server to the internet. 

Remaining work: The kubelet needs to serve its https endpoint with a certificate that is signed by the cluster CA. Right now it uses a self signed cert for its web server, even though it uses a client certificate signed by the CA as credentials to authenticate to the master. The master needs to have a client certificate signed by the cluster CA to present to the kubelet when connecting. 

We are also looking at moving the proxying functionality out of the master, which would entirely remove the need for the master to connect to the kubelet, making the work to secure the kubelet unnecessary. I'm not sure whether that will land first or if it's still worth trying to secure the master -> kubelet communications.

**Comment by smarterclayton** [comment]
The proxying function still has to go somewhere, so I would assume that has
to be secured?  :)  Is there an issue for the move out?

On Fri, Jul 24, 2015 at 12:26 PM, Robert Bailey <notifications@github.com>
wrote:

> The master -> kubelet connection is not secure enough to be run across the
> internet. The master currently only connects to the kubelet for proxying
> user requests that need to be forwarded to the kubelet (e.g. hitting the
> /api/v1/proxy/ endpoint or using kubectl exec / kubectl logs). In most
> cases, this is done over a local secure network. For GKE, we use ssh
> tunnels to securely put packets onto the cluster's network without exposing
> the kubelet's web server to the internet.
>
> Remaining work: The kubelet needs to serve its https endpoint with a
> certificate that is signed by the cluster CA. Right now it uses a self
> signed cert for its web server, even though it uses a client certificate
> signed by the CA as credentials to authenticate to the master. The master
> needs to have a client certificate signed by the cluster CA to present to
> the kubelet when connecting.
>
> We are also looking at moving the proxying functionality out of the
> master, which would entirely remove the need for the master to connect to
> the kubelet, making the work to secure the kubelet unnecessary. I'm not
> sure whether that will land first or if it's still worth trying to secure
> the master -> kubelet communications.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/3168#issuecomment-124572671>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by roberthbailey** [comment]
There's been quite a bit of discussion internally (not necessarily conclusive one way or another), but I don't know if there's an issue open.... looking.

**Comment by roberthbailey** [comment]
Looks like there are (at least) two: https://github.com/GoogleCloudPlatform/kubernetes/issues/10209 and https://github.com/GoogleCloudPlatform/kubernetes/issues/3481.

**Comment by roberthbailey** [comment]
I've created https://github.com/GoogleCloudPlatform/kubernetes/issues/11816 to discuss securing the master -> node communication, so I'm going to close this issue in favor of that one.
