### ISSUE TITLE
Pod is scheduled but stuck in pending state

### ISSUE THREAD

**Issue by bluemeric** [GoogleCloudPlatform/kubernetes#3187]
If the minion hostname is not the same as its IP address, then when a pod is deployed, the pod gets scheduled but the deployment is stuck in "pending" state. As a temporary resolution, in the /etc/kubernetes/controller-manager file on the master, the kubelet_addresses configuration should contain the 'hostname -f' value instead of the IP address. ie.,

KUBELET_ADDRESSES=“—machines=minion-hostname-f“

Similarly, in the /etc/kubernetes/kubelet file on the minion, the kubelet_hostname configuration should contain the IP address of the minion. ie.,

KUBELET_HOSTNAME=“—hostname_override=minion-public-ip"

**Comment by lavalamp** [comment]
Yeah, you can call the minion whatever you want, but kubelet and apiserver have to agree on what that is.

Actually I think you will expose some bugs if you use a name that doesn't actually resolve, if so please file issues, those are bugs we should fix.

Yes, #3185 is an example of this problem.

I'm not sure what it is that this issue is requesting that we fix, so I'll close for now; if I misunderstand, please reopen with a concrete action item.

Thanks!
