### ISSUE TITLE
Endpoints is wierd

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#3215]
The fact that Endpoints is a type of standing query is sort of neat.  
But, the fact that it is an object whose name is implicitly linked to the same-named object of another type (service) is less neat.  Why isn't Endpoints part of ServiceStatus?  
Probably this has been discussed before.

We have the same pattern with pods/boundPods. BoundPods is a standing query about pods bound to a single host, and endpoints is a standing query about ips matching a single service's selector.  

I'd like to head towards eliminating the BoundPods object as a thing you can read.   It would be nice if there was a similar, if perhaps long-term, goal for services.

**Comment by thockin** [comment]
I made a very similar observation regarding Endpoints, so I agree it is a
bit funky.

**Comment by thockin** [comment]
What is the desired outcome of this issue?  Do we want to re-open the discussion of generalized standing queries?  Propose moving endpoints to ServiceStatus?

**Comment by erictune** [comment]
Propose endpoints goes into ServiceStatus and `kubectl endpoints` is changed to extract endpoints from ServiceStatus.

**Comment by thockin** [comment]
I think I would be OK with that refactoring.

**Comment by lavalamp** [comment]
Yeah that's a pretty logical place for it to go.

**Comment by bgrant0607** [comment]
I am strongly opposed to both generalized standing queries and making it part of service status.

The lack of adequate addressing, naming, and discovery mechanisms continue to be among the most serious impediments to the adoption of containers. A number of solutions have been developed, but require code changes to use, and no standard protocol/API has yet emerged, in part because the most of solutions are tied to a particular storage and/or distribution implementation, a particular programming language, or a particular protocol (e.g., HTTP), or are opinionated or inadequate in some other way (e.g., dictating application naming structure or lacking adequate namespacing). We should not repeat the mistakes of these other systems and develop a solution that is tightly coupled to Kubernetes APIs.

We need a simple, unopinionated endpoint API for cloud-native dynamic group membership lookup and watching. Ideally, this API would not be specific to Kubernetes. We need a de facto standard that can become the equivalent of DNS for dynamic cloud-native applications. What we have isn't quite what we need but it's much closer than the proposed alternatives.

**Comment by thockin** [comment]
Why does our first-order API have to be this thing you want to see?
Wouldn't we be better served to make clean layers - our API that does what
it needs to do cleanly, and then another layer on top of that to sync k8s
-> your naming API of choice.

**Comment by bgrant0607** [comment]
Why not? Why add another API with only one consumer (the service proxy) and then translate to the more widely used API? That seems like unnecessary complexity.

Also, what about endpoints is unclean? A narrow, special-purpose API is much more clean than the alternatives, and facilitates polymorphic endpoint generation, such as manual endpoint set management, endpoints for master-elected services, etc. Endpoint consumers (distributed cloud-native applications, enlightened clients, monitoring agents, load balancers, etc.) should be oblivious to the means by which the endpoints are generated.

Yes, it should be possible to translate the endpoints API to etcd, consul, serf, eureka, smartstack, etc., but we should support a viable general protocol out of the box. We should do this for the primary distributed computing middleware APIs, such as master election, sharding, task queues, and runtime configuration. That's what is going to enable a vibrant ecosystem of portable cloud-native applications.

**Comment by thockin** [comment]
> what about endpoints is unclean?

It's inconsistent with the rest of the system.  That said, if we get to generic plugins, as we discussed yesterday, then endpoints is an obvious candidate for being removed from the core completely (in fact I used it as such in my registry plugins sketch PR and it was easy).

**Comment by bgrant0607** [comment]
In what way is it inconsistent? It's not going to be the only example of secondary view/control APIs.

**Comment by thockin** [comment]
The primary objects have spec and status blocks - this "feels" like status
for Services.  But as per my previous message, I'd be happy to see
endpoints become more separated or more integrated - right now it's weirdly
in-between.

**Comment by erictune** [comment]
After talking to Brian, I no longer think this is a problem.  We don't actually have to store Endpoints in the registry.  It doesn't have to behave like other REST objects.  It is just a convenience URL for getting just the information you need.
