### ISSUE TITLE
Command for reporting cluster information

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#3290]
Perhaps we can use a command to report cluster information? For example, during cluster creation, the output announces the URL of the master, the Grafana dashboard for monitoring and (when my PR gets merged) a URL for the Elasticsearch that is storing the logs and another URL for the Kibana viewer for these logs. It would be good to have some kind of "kube info" command, or flag to kubectl, which gives basic cluster information.

**Comment by saad-ali** [comment]
**Formal Proposal:**
Add a command (```kubectl clusterinfo```) that will:
 1. Print the master host IP or URL
   * ```kubectl``` loads configuration information including master host location from either a config file, command line parameter, or environment variable.
   * The new command would echo this information.
   * For example: ```Kubernetes master is running at https://104.154.45.3```
 2. Print the Grafana dashboard URL, if Grafana is running
  * The command would execute ```get pods -l name=influxGrafana```, parse the host IP from the result, and return it
  * For example,

    ```
POD                                    IP                  CONTAINER(S)            IMAGE(S)                            HOST                                                         LABELS                                   STATUS
9099f0da-a72d-11e4-bfd9-42010af0a495   10.244.2.3          influxdb                kubernetes/heapster_influxdb:v0.3   kubernetes-minion-2.c.saad-dev-vms.internal/104.154.33.132   name=influxGrafana                       Running
                                                                   grafana                 kubernetes/heapster_grafana:v0.3
    ```
would cause ```Grafana dashboard is running at http://104.154.33.132``` to be output
 3. Print the Elasticsearch URL, if running
   * Similar to 2, we could execute ```get pods``` and find the host IP for the ```elasticsearch-logging``` container, append port ```8080``` to it and return it.
    * For example, ```Elasticsearch is running at http://146.148.59.62:9200```
 4. Print the Kibana URL, if running
   * Similar to 2, we could execute ```get pods``` and find the host IP for the ```kibana-logging``` container, append port ```5601``` to it and return it.
    * For example, ```Kibana is running at http://104.154.33.132:5601```

**Problem:**
Using the node host IPs is not ideal, because pods are ephemeral and maybe killed and recreated on other nodes.

Kubernetes gets around this by creating a "service" for Grafana, Elasticsearch, and Kibana which gives them all a consistent (stable) IP. This IP however is internal to the cluster, and not externally accessible, so we can't use it directly.

The process of exposing this internal IP externally is unique per cloud provider, and normally involves creating a firewall rule. But because this process for creating (and later accessing) an external IP for a Kubernetes service is unique, ```kubectl``` can't rely on it.

Therefore, unless there is a cloud-provider-agnostic way to fetch the external IP for a Kubernetes service, to create this new command ```kubectl``` would have to return the ephemeral IPs.

**Comment by derekwaynecarr** [comment]
I think we will want to support different information so we need to allow some flexibility.  @smarterclayton

**Comment by bgrant0607** [comment]
It would be nice if information about cluster/addons were not hardcoded into kubectl. We could put a label on all cluster-level services (not pods) and then just query those.

We do need to solve the external IP problem.

**Comment by piosz** [comment]
It's blocked by #341. See discussion in #4417.
