### ISSUE TITLE
Pods should receive environment variables only from services in the same namespace

### ISSUE THREAD

**Issue by pmorie** [GoogleCloudPlatform/kubernetes#3293]
Currently in master, pods receive variables from services in other namespaces:

            "TEST_SERVICE_SERVICE_HOST=10.247.107.180",
            "TEST_SERVICE_SERVICE_PORT=5434",
            "TEST_SERVICE_PORT=tcp://10.247.107.180:5434",
            "TEST_SERVICE_PORT_5434_TCP=tcp://10.247.107.180:5434",
            "TEST_SERVICE_PORT_5434_TCP_PROTO=tcp",
            "TEST_SERVICE_PORT_5434_TCP_PORT=5434",
            "TEST_SERVICE_PORT_5434_TCP_ADDR=10.247.107.180",
            "TESTSERVICE_SERVICE_HOST=10.247.121.223",
            "TESTSERVICE_SERVICE_PORT=5434",
            "TESTSERVICE_PORT=tcp://10.247.121.223:5434",
            "TESTSERVICE_PORT_5434_TCP=tcp://10.247.121.223:5434",
            "TESTSERVICE_PORT_5434_TCP_PROTO=tcp",
            "TESTSERVICE_PORT_5434_TCP_PORT=5434",
            "TESTSERVICE_PORT_5434_TCP_ADDR=10.247.121.223",
            "TESTSERVICE_SERVICE_HOST=10.247.38.194",
            "TESTSERVICE_SERVICE_PORT=5434",
            "TESTSERVICE_PORT=tcp://10.247.38.194:5434",
            "TESTSERVICE_PORT_5434_TCP=tcp://10.247.38.194:5434",
            "TESTSERVICE_PORT_5434_TCP_PROTO=tcp",
            "TESTSERVICE_PORT_5434_TCP_PORT=5434",
            "TESTSERVICE_PORT_5434_TCP_ADDR=10.247.38.194",

The correct behavior should be to receive variables only from services in the same namespace as a pod.

**Comment by pmorie** [comment]
@smarterclayton @derekwaynecarr @lavalamp agree this is a bug?

**Comment by smarterclayton** [comment]
It's certainly not intentionally chosen to be that way.

**Comment by derekwaynecarr** [comment]
It's a bug.

**Comment by pmorie** [comment]
Looks like the `registrytest.ServiceRegistry` type doesn't handle namespaces correctly, which is necessary to fix this.

**Comment by lavalamp** [comment]
It's a bug.

However, "from same namespace" is not completely correct either. The rule should be "that it has permission to see". That's true by default for services in the same namespace. It should also be true by default for things like the "kubernetes" namespace that has the master service in it...

**Comment by smarterclayton** [comment]
We probably want to spend some time on predeclaration, service permission, and how special global services are exposed

**Comment by derekwaynecarr** [comment]
Prefer a near term fix that respects the namespace boundary and we need follow on design for handling communication back to the master which I think is a special case.  I don't necessarily agree that permission to see is right either.

**Comment by pmorie** [comment]
@lavalamp per our discussion i'll special-case the "default" namespace for now.

**Comment by pmorie** [comment]
@derekwaynecarr @smarterclayton okay with the above?

**Comment by derekwaynecarr** [comment]
So what is the effect of two same named services in the default namespace and other namespace?  It will clash right?  It needs a giant TODO if we do that solution.

**Comment by pmorie** [comment]
That's a good question @derekwaynecarr.  Currently collisions result in the same keys being present in the env, I imagine but haven't confirmed that the latest value in the env array overrides all the other overloaded ones.

**Comment by smarterclayton** [comment]
If someone defined a Kube service in their namespace it must take priority

**Comment by thockin** [comment]
Yeah, it's a bug.  I think it correctly needs to take all services from "default" and then overlay all services in the pod's own namespace.

**Comment by erictune** [comment]
@thockin why do you think a pod in namespace "foo" should take services in namespace "default"?  I think that there is nothing special about the "default" namespace other than it is the one you get if you don't specify one.

@lavalamp For the automagic "kubernetes" and "kubernetes-ro" services, I think we should use magic to automatically create the service entries in every namespace, rather than exposing a second special namespace to each namespace.      Doing that would mesh nicely with issue #2159 (Namespace as own Kind).

**Comment by derekwaynecarr** [comment]
@erictune +1 to your proposal.

----- Original Message -----

**Comment by pmorie** [comment]
@erictune I think that makes sense; for now, should we fix this by making only services in namespace X visible to pods in that namespace, or should the fix for this issue handle the magic for the special `kubernetes{,-ro}` services?

**Comment by thockin** [comment]
I'm fine with either approach - I thought it would be more work and edge
cases to make magical cross-namespace services.

Satnam and I were just discussing whether things like DNS, logging,
monitoring, etc should be in "default" namespace or in a "kubernetes"
namespace.  And if so, should all of "kubernetes" be magical (maybe marked
as such by a policy).

**Comment by thockin** [comment]
I think it is important that kubernetes and kubernetes-ro be visible to all
pods

**Comment by smarterclayton** [comment]
I think that's yucky - that means that master startup has to "magically" create an etcd resource in every visible namespace, which is racy.  I don't see how you can get around magic inheritance of services and perform.

----- Original Message -----

**Comment by pmorie** [comment]
@thockin it's definitely more work and edge-cases to make magic cross-namespace services

@erictune How do you about the following:

1.  For now, pods in namespace X will see services in namespace X and namespace default
2.  The PR for #2159 can remove the special casing for the default namespace and add the magic to create the special services in each new namespace

**Comment by pmorie** [comment]
@smarterclayton could you not create a resource for each magic service for each new namespace that is created?

**Comment by thockin** [comment]
We could make a single namespace that we declare to be transcendent, and
then apply the previously described overlay logic in real-time in the
registry?

**Comment by derekwaynecarr** [comment]
The transcendent or 'global' namespace is something that comes up many times on our side too.  It has its fans and detractors.  The current proposal for 'default' to always be included is in my view equivalent to making 'default' transcendent - this does make the name kind of appropriate, since the values in the 'default' namespace are inherently then the default.

----- Original Message -----

**Comment by pmorie** [comment]
@derekwaynecarr @thockin generally i agree with derek's comment, with the exception that I think @thockin's proposal to handle this in the service registry is probably better than my WIP code (which applies this notion solely to the `BoundPodFactory`)

**Comment by smarterclayton** [comment]
Creating one kubernetes service per namespace won't fly, because then whenever the master IP changes we have to update 1 set of endpoints *per* namespace.  We'll need to do overlay of some form - having the administrator get to choose that would be nice.

----- Original Message -----

**Comment by pmorie** [comment]
@smarterclayton noted

**Comment by pmorie** [comment]
Thoughts, @derekwaynecarr @lavalamp ?

**Comment by pmorie** [comment]
My example above has convinced me that is this probably the wrong way to go, do not like mixing namespaces in the output of List call.

**Comment by derekwaynecarr** [comment]
I like the idea of making the 'default' namespace the transcendent namespace.  It warrants a larger discussion on what transcendence means on a resource-specific basis.  Transcendence should NOT mean if I say LIST all services in namespace X, that the result set includes services in Namespace X and Namespace default.  Any special transcendence logic should happen at the point closest to the desired behavior.  I think the fix to overlay services from the local namespace with the 'default' namespace at the point of env var injection is the right fix for this for where I think the transcendent discussion would end-up.

----- Original Message -----

**Comment by erictune** [comment]
@lavalamp @erictune and @bgrant0607 had a quick office conversation. 

@bgrant0607 pointed out the following:
 - internally, we have something like namespaces, and every team of 3-10 people tends to have their own "namespace".  
 - we have a thing that is sort of like services, and automatically makes DNS entries that are roughly like `$SERVICENAME.$NAMESPACE.$CLUSTERID.blah`
 - when one team exposes its service to other teams (which happens all the time), they typically don't use the automatic DNS entries.  They use a layer of indirection, like a PTR or CNAME record, and a ~global manually generated name, which points to the automatically generated name.  This allows the team to hide their internal naming, and to move across clusters without dependent services needing to update their names.   Also, because things in the same cluster share fate, they may need another layer of load balancing above what the cluster can provide (of the `createExternalLoadBalancer` sort) to insulate clients from cluster failures.
 - however, frontends and backends belonging to the same teams, and thus in the same namespace, may use the automatically generated DNS entries to refer to each other.  This is less work to setup, and the reasons given in the previous bullet don't apply.

I said that my model of a namespace was that it was, to a first order, indistinguishable from having your own private cluster, in the same way that a pod is, to a first order, indistinguishable from having your own private machine.

Based on these observations, I proposed that: 
 - we recommend a best practice of using DNS (or env vars when needed) to reach services in the same namespace.  
 - we make all services in the same namespace visible to all other pods in the same namespace.  We won't plan to have a way to hide them in the same namespace, though we will help provide sub-namespace authorization using service accounts and policies and other mechanisms, not yet fully specified.
 - we won't add new features to help people access services in different namespaces.  If they want to do this they can:
  - use the setup their own CNAME or PTR records when they want to export a service from a namespace.
  - use something like `createExternalLoadBalancer`, and use application level access controls and/or cloud-provider-specific network config to limit access.
  - use the automatically generated DNS names with the namespace prefix.

**Comment by erictune** [comment]
@smarterclayton for the special case of the kubernetes service, we don't actually have to create a resource.  We just need to put the env var into each Pods environment (or, if DNS is setup, put an env var with the DNS name and port of the master into each Pods environment, and setup the kube-proxy.

**Comment by derekwaynecarr** [comment]
re: use the automatically generated DNS names with the namespace prefix.

that works fine for this issue, and if you are running with skydns.

if there is a separate need for 'transcendence', then we can discuss it in a separate issue?

----- Original Message -----

**Comment by pmorie** [comment]
@derekwaynecarr Agree, exposing services into other namespaces in any way (either via a namespace which has transcended the namespace-condition and evolved into pure energy, or a more granular mechanism) is probably best to discuss in a separate issue.

**Comment by erictune** [comment]
Revisions to above proposal:
 - there is a kubernetes and kubernetes-ro service in namespace kubernetes.
 - there is no transcendence magic in the apiserver.
 - if DNS is setup, pods can use `kubernetes.kuberntes.kubernetes` to reach the master, etc.
 - kubelet will magically put the host and port of the kubernetes and kubernetes-ro services into the env of every pod.  This is for backwards compatibility.  We won't use this mechanism as a general transcendence mechanism.  For any new services that should be in every namespace, you should use DNS.

**Comment by pmorie** [comment]
@erictune in your revised proposal, how should collisions for `kubernetes-{,ro}` be handled?

**Comment by smarterclayton** [comment]
If you say Kubernetes 3 times in front of a darkened mirror an angry Greek sailor shows up and hits you over the head with a ships wheel....

----- Original Message -----

**Comment by pmorie** [comment]
@smarterclayton you hear people say that but almost no one has ever died that way

**Comment by thockin** [comment]
I was waiting for someone to make the beetlejuice joke.

A revision on etune's statement is that the namespace into which the
master's virtual service(s) are put should probably be configurable.  At
the moment it is "default".  It could be changable by a flag, or we could
decide ~now that "kubernetes" is a better namespace (a breaking change, we
could bridge it and deprecate gently.  or not)

What I like is that there's very little (no) magic.  The master services
remain as real Service objects, which makes syncing to naming services easy.

**Comment by smarterclayton** [comment]
With predeclaration we have a better cross namespace story as well - I would prefer no magic on transcendence but instead declarative dependency.

----- Original Message -----

**Comment by pmorie** [comment]
@erictune @thockin @smarterclayton regarding implementing the injection in the kubelet instead of the `BoundPodFactory` in the api server, the environment entries won't show up in the BoundPod environment.  Does that matter?

**Comment by thockin** [comment]
I think that is a net win.  It's too huge.

**Comment by brendandburns** [comment]
Please note that moving the kubernetes and kubernetes-ro services around is
a breaking change.   There is already software out there using those
endpoints.  I don't think we can move away from kubernetes and
kubernetes-ro in the default namespace (or at least not without some
warning to folks)

--brendan

**Comment by brendandburns** [comment]
ah, just saw Eric's last point which makes my comment redundant.
 nevermind, nothing to see here, keep walking, keep walking...

**Comment by pmorie** [comment]
@erictune I have a need for the kubelet to be wired with the kube client for this change and I saw your earlier PR laying the groundwork.  I'll take it a little further and will rebase onto your next changes if they go in first.

**Comment by lavalamp** [comment]
We should make some e2e tests that actually exercise non-default namespaces. I think those code paths are undertested.

**Comment by erictune** [comment]
It would be quite easy to extend TestPodHasServiceEnvVars in cmd/e2e/e2e.go to have multiple namespaces.    And it would be resilient to changes in where we are doing the vars (master vs kubelet.)

**Comment by erictune** [comment]
@pmorie suggest testing your change with that e2e test.

**Comment by pmorie** [comment]
Good advice @erictune; i am planning on it but have been leaving tests to
get some buy-in on implementation
