### ISSUE TITLE
"list pods" accidental semantic change

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#3502]
A change was made to have the nodes object return nodes even if they're unhealthy. This changes how pod cache is going to report pods that are on unhealthy nodes. (they used to be reported as "failed", now I'm not sure what they'll be reported as)

pkg/master/pod_cache.go's currentNodes should be changed to healthyNodes, and its nodeExists functions should check if the node is healthy in addition to whether it exists--it should basically always exist now.

**Comment by dchen1107** [comment]
Now the status of pod on unhealthy node is Unknown. I think Unknown is better than Failed in this case.

**Comment by ddysher** [comment]
Previously, a pod scheduled on an unhealthy node has Failed state because we specifically set it:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/master/pod_cache.go#L141

Right now, when pod cache tries to connect to unhealthy node for pod info, it gets connection error; which we then set pod status to Unknown:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/master/pod_cache.go#L150

Agree with @dchen1107 that Unknown is bettern than Failed, but @lavalamp is correct about the semantic change.  The current Unknown status is just an coincidence, it's not designed so.

I'll take a look.
