### ISSUE TITLE
End to end tests incorrectly establish Kubernetes root

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#3523]
Our end to end tests do not properly detect the root of the Kubernetes install to use because they try to get the name of the binary and this is going to be a problem when the tests are run with `go run e2e.go` as we describe in our [documentation](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/development.md) which issues commands from the `hack` directory -- but the binary will be somewhere in `/tmp/...`

```
$ cd hack/
$ go run e2e.go --build
2015/01/15 09:51:58 Running: build-release
2015/01/15 09:51:58 Error running build-release: exit status 1
2015/01/15 09:51:58 Error building. Aborting.
exit status 1
```

By a happy coincidence of errors that cancel each other out running `go run hack/e2e.go` does work.

This should get fixed as part of the overhaul of the end to end tests e.g. PR #3447.

**Comment by zmerlynn** [comment]
See also #2990. This bug is the cause of that.

**Comment by zmerlynn** [comment]
Well. Partially. There may be more to #2990. The KUBE_ROOT gets awfully messy in that scenario.

**Comment by gmarek** [comment]
The problem here is that filepath.Clean(filepath.Join(path.Base(os.Args[0]), "..")) is not a thing we need. It returns more or less current directory, not the thing we need which is an analogue of ${BASH_SOURCE}. AFAICT current implementation is equivalent of getting current work directory. I don't know how this code behaves on Windows though.

**Comment by satnam6502** [comment]
Since this is no longer deemed to a high priority issue let's close it and live with it.
