### ISSUE TITLE
Preserve TAP output while transitioning shell tests to go tests

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#3567]
I have a proposal for a bridge between the Go tests and the shell tests that makes it easy on Jenkins:

1. Add an `--except` to `hack/e2e.go` so that things can be excluded from wildcard pickups, so that Jenkins can call `hack/e2e.go --except=goe2e.sh`
2. Change `hack/jenkins/e2e.tap` to call cmd/e2e/e2e.go directly, putting TAP output in a separate file in a similar fashion to the `e2e.$BLAH.tap` in there today. (call it go-e2e.$BLAH.tap, maybe?)
3. Possibly improve the TAP output in `cmd/e2e/e2e.go` to add the `duration_ms` fields. This is something I added in `hack/e2e.go` to get timings printed by Jenkins. It would also be nice if log messages were printed in the YAMLish style, so the "Extended TAP Results" page could pick it up (so you don't have to go to "Console Output" to see the test result failure output).
4. Reconfigure Jenkins to pickup both tap files (trivial)

Then it's easy to drain one pool and add to the other. It also fixes an annoyance I've had for a while, which is that anytime `goe2e.sh` fails-via-timeout, it destroys other tests. This way, it's run last.

Context https://github.com/GoogleCloudPlatform/kubernetes/pull/3550#issuecomment-70204266

cc @satnam6502 @filbranden

**Comment by filbranden** [comment]
+1 to adding TAP output support to `cmd/e2e/e2e.go` I can try to tackle that myself.

Instead of adding `--except` to `hack/e2e.go` I'd prefer to just get rid of `goe2e.sh` and instead have `hack/e2e.go` call the `cmd/e2e` explicitly passing it a `--tap` argument. The idea is that `hack/e2e.go` will shrink and eventually be completely replaced by `cmd/e2e`.

We still need `hack/e2e.go` to drive `cmd/e2e` since `hack/e2e.go` is currently what's doing kube-up/kube-down, so we need `cmd/e2e` to run *before* kube-down happens...

I wouldn't mind assigning this one to myself... But don't expect something today, more likely Wed/Thu of next week...

Cheers,
Filipe

**Comment by zmerlynn** [comment]
The purpose of adding `--except` is that today, if you were to remove `goe2e.sh`, people would accidentally not run the `cmd/e2e` tests. The purpose of adding `--except` to `hack/e2e.go` is that today, people run e2es by running `hack/e2e.go`, which picks up the go e2e tests by picking up the shell script. If you just remove the shell script, people will stop running the go tests accidentally. That's *bad*. I'm proposing a path that surgically lets Jenkins run them separately, but doesn't change yet how people would normally run them.

**Comment by zmerlynn** [comment]
Oh, I just re-read your comment. No. Unless you want to implement the YAML-ish subtest gorp (https://wiki.jenkins-ci.org/display/JENKINS/TAP+Plugin, see Subtests), trying to deal with the TAP output from `cmd/e2e` directly in `hack/e2e` is a way that leads to madness, I think.

**Comment by roberthbailey** [comment]
Closing now that we've switched from TAP output to junit output for Jenkins.
