### ISSUE TITLE
Kubernetes architecture in AWS VPC

### ISSUE THREAD

**Issue by rgolg** [GoogleCloudPlatform/kubernetes#3604]
Hello Kubernetes community,

Happy to have found my way here. I'm very interested in making Kubernetes work in an AWS VPC and have looked at the changes @silasdavis has made to the original CloudFormation template for setting up Kubernetes in AWS running on CoreOS (https://github.com/GoogleCloudPlatform/kubernetes/pull/2649) (Thanks @silasdavis!). However, I'm struggling with choosing the best architectural approach.

Let me preface all this by saying that I feel that I am bringing in baggage from my experience with designing and running immutable infrastructures using AMI instances and other AWS resources in AWS VPCs. Maybe the controls provided within a Kubernetes cluster, along with the controls on the nodes, pods, and containers make the need for VPCs and network partitioning obsolete. So *please* let me know if I should be looking at this differently and there's a better Kubernetes/Container-native approach. 

Also, if someday AWS decides to support Kubernetes directly with their Elastic Container Service (when it is real...still waiting to get my preview access!) all of this will quickly become obsolete. Frankly, the easiest thing would be if AWS allowed the option for creating a Kubernetes master when deploying a subnet, similar to how an ECS agent can be included in an AMI (based on what I've seen and read about ECS).

Probably stating the obvious here but my most important objective for this infrastructure architecture is balancing security, performance, scalability, and flexibility.

The options I'm considering are:

* One cluster per subnet in a VPC, with one master autoscaled with min/max/desired number of instances of one, and a set of minions in the same subnet behind an autoscaling group that can possibly be scaled by external monitors triggering CloudWatch alarms for scale up and scale down events. With this setup, at least theoretically, the proxies for the same pods spread across different subnets in different availability zones can be registered to ELBs allowing for load-balancing applications/services in pods across availability zones.
 * Pros:
    * Load-balancing applications/services in pods across multiple availability zones.
    * The Kubernetes master communicates with the minions in the same subnet avoiding any networking complexities between the replication controller on the master and the nodes and Kubelets on each pod.
 * Cons:
    * Seems like an overkill to run a separate master on each subnet.
* One cluster per security zone: 
  
  *Definition:
      * public subnets route to internet through the VPC's internet gateway. Resources in public subnets can be accessed publicly if assigned EIPs.
      * private subnets route to internet through NAT instances in the public subnets. Resources in private subnets cannot be accessed publicly.
      * management subnets are private subnets that can communicate with resources in both public and private subnets. Resources in management subnets cannot be accessed publicly.
      * All resources in public/private/management subnets can communicate with each other. More granular security constraints can be applied with network ACLs and security groups around resources in each of the subnets.
      * public/private/management subnets are deployed in pairs, with one subnet of each pair in one availability zone and the other of the pair in another availability zone.*
  1. Deploy a Kubernetes cluster for the public subnets, with the Kubernetes master deployed to the management subnet and its minions on the public subnets.
  2. Deploy a Kubernetes cluster for the private subnets, with the Kubernetes master deployed to the management subnet and its minions on the private subnets.

 * Pros:
   * Load-balancing applications/services in pods across multiple availability zones.
 * Cons:
   * Kubernetes master nodes running in the management subnets may have issues communicating with the minions in the private and public subnets. I'm not sure if there will be any issues here but I have read in a couple of places that its better to keep all nodes of the Kubernetes cluster on the same network. Not sure if that means keeping them on the same subnet as well.

I'm curious to find out how others are thinking about deploying Kubernetes in AWS and would love to contribute anything I can and work within the community to make it happen.

Thanks,
Reza

**Comment by erictune** [comment]
I think you should have one cluster for each availability zone that you want to be in.  Each cluster has its own apiserver (a.k.a. master).   This is not overkill in my view, for a couple of reasons:
  - operational cost (your time) will likely exceed cost for the extra VMs.  Having completely independent clusters will be simpler operationally than shared-master but partitioned-minions.
  - the load and memory requirements on the masters will be less with master-per-zone, so you could probably get by with a smaller VM for the master if you are really cost-sensitive.
  - amazon's availability is only one component of your total availability.  There is also a possibility of faults in the kubernetes software such as apiserver, unavailability due to faults while rolling out new versions of kubernetes, general operator mistakes, etc.  Having multiple highly independent clusters, including separate apiservers, means that you can fail over to another cluster if one of these other types of faults happens.

**Comment by erictune** [comment]
I don't know enough about amazon's networking to say what cluster-per-availability-zone implies for subnets.

**Comment by erictune** [comment]
I think the second big bullet is saying that you might want to have two clusters in an availability zone: one which runs pods that don't need to talk to the internet and another cluster which does.  Yes, that is a reasonable approach for now.  Eventually, I think we hope to have a way to have different classes of minions in the same cluster, so that you could have an apiserver in the management subnet, some minions on the private subnet, and other minions on the public subnet.  But that is some ways off.

**Comment by brendandburns** [comment]
Actually, if you were willing to label your minion nodes appropriately, I
think that we could handle scheduling across one class of machines that can
see the external internet, and one class of machines that can't.

However, I would say that more broadly, it's actually better if _none_ of
the worker nodes can actually see the external internet, and the only
access that occurs is mediated through a load balancer.  In this model, you
would set up an ELB for ever service that you wanted to connect to the
external internet.

Any other access (e.g. debugging ssh, etc) would need to go through a
bastion server (typically the master/apiserver node, which _does_ need to
be on the external internet for client access)

I second Eric's suggestion that you put one cluster in each availability
zone.

Hope that helps, let us know if we're not being clear, or if there are
details of the AWS set up that we are not aware of.

Best
--brendan

**Comment by rgolg** [comment]
Thanks for your response Eric and Brendan. 

Eric: 
Your last comment is along the same lines of what I was thinking. In our architecture the only things that are allowed to reside in the public subnets are reverse proxies (gateways). There sole purpose is to route inbound calls to the services in the private cluster.

Brendan: 
The minions/containers in the private cluster will "see" the internet through NATs in the public cluster, meaning they can make outbound calls to things like public third-party APIs. However, there is no direct path to them from the internet for inbound calls. The only way inbound to the services in the private cluster will be  through the reverse proxies in the public cluster. On your first point, I am not a big fan of doing things by convention. We prefer using native deployment capabilities such as CloudFormation instead of relying on Kubernetes to launch minions. If you do it that was then you have to maintain Kubernetes deployment model for every cloud provider. 

Both:
It seems like we definitely need a public and a private cluster. In our current state, we always deploy things to a minimum of 2 availability zones for HA. That means at a minimum, we'll need 4 clusters. 2 public clusters, each in a different availability zone, and 2 private clusters also each in a different availability zone (same availability zones as the public clusters).

Now lets rethink this without carrying the AWS baggage. Do we still need to think in terms of private subnets and public subnets to partition the network in a VPC for the purpose of security? It seems like we are replacing the subnets use for security partitioning with public and private clusters taking over that role. Maybe it would make more sense to have one big subnet per availability zone? A flatter network? Similar to Google Cloud Platform's networking architecture. The public clusters route to internet both ingress and egress through the VPCs AWS managed internet gateway. Our service containers deployed to the private cluster will have outbound access to internet through NAT containers in the public cluster.

The whole thing can also be architected without VPCs, if one choses to do so. What needs to be provided are public and private clusters with correct routing as described above.

What do you think?

The next thing to think about is how to auto-scale. Should we be thinking about a cluster as the unit of scale for the entire system?  I'm guessing there has to be a threshold for the max number of minions within a cluster managed by the master. Is there a predefined max number of minions per cluster? 

Ideally, we'd like auto-scaling (both vertical and horizontal scaling) to work at all levels, including containers, minions, and the clusters themselves. There's the concept of the replication controller in Kubernetes. Should there also be an auto-scaling controller?

We need health metrics at the cluster level so that once a certain threshold of resource availability is reached, auto-scaling kicks in to launch more clusters (private or public). Auto-scaling in AWS is slow but since we are talking about auto-scaling clusters it fits the gradual increase in scale which auto-scaling was really meant for. I think the clusters must be big enough to handle some level of traffic bursts.  

There's a lot here but I'd really appreciate your input.

Thanks again,
Reza

**Comment by erictune** [comment]
My intuition is that a flatter network would be better.   If you want to be more precise, then we probably need to define what security goals you have, and compare how those would be met with subnets versus kubernetes-level and application-level security.  

Regarding auto-scaling:  The way I'd thought about it, you'd fix the number of clusters you need initially based on availability, latency and serviceability goals, and then scale up the node count and pod count as needed to handle load.  You would not automatically add a cluster.

**Comment by erictune** [comment]
We intend for kubernetes to be able to scale up to large numbers of nodes, so you should not have to add clusters due to node count, unless you are a really really big user.

**Comment by rgolg** [comment]
I agree with the flat network.

I have to disagree with that scaling approach. If we are going to pre-provision a fixed number of cluster with the right size ahead of time, then we are over-provisioning initially to allow for future load. Sounds a lot like what we used to do in the data center. This would definitely defeat the purpose. What does a fixed number of clusters really mean in terms of AWS resources? Let's say we want to have 4 clusters. Does this mean we only provision the masters and the minions get auto-scaled by the master? I'm open to other points of view but it would be pretty hard to convince many folks on a pre-provisioned model for auto-scaling. Keeping an AWS EC2 instance up just sitting there waiting for load seems like a waste, not to mention the cost. 

There are other things we need to understand before going down this route. How big can a single cluster get? How many minions can a master handle given the master's size? Is there a hard limit?

I'm also curious to understand why you think clusters shouldn't auto-scale? Is there something fundamentally wrong with that?

**Comment by rgolg** [comment]
I'm still thinking about this about pre-provisioning the clusters vs auto-scaling the clusters. Maybe its not such a big deal starting with a fixed number of clusters. Come to think of it when we create a subnet in AWS we are really pre-provisioning a limited address space. The difference being with the subnet I know exactly how many IP addresses I'm "reserving." Also, at least in AWS there is no charge for a subnet within a VPC. There will be a charge for keeping the masters up. If there was a clear way to know how many nodes a cluster could handle then setting up a predefined number of clusters wouldn't be as much of a concern.

My current thought is the masters, however,  should at least be behind an auto-scaling group of min/max/desired=1. That way if the master fails, auto-scaling will replace it. What would that do to the state of the master? In order for the master to continue its work after its replaced, how do we approach state persistence?

**Comment by erictune** [comment]
Just to clarify, I was saying that the number of clusters would be fixed
but the number of nodes in each cluster would be automatically scaled.

Our roadmap (
https://github.com/GoogleCloudPlatform/kubernetes/blob/24e59de06e4da61f5dafd4cd84c9340a2c0d112f/docs/roadmap.md)
calls for 100 node clusters at v1.0 and 1000 node clusters in the middle of
this year.

An example of how one might think about number of clusters is like this:
 - I decide I want to have at least one cluster in each of US, AP, and EU,
to provide low latency to most of my global user base.  This means spending
at least $X more than with only one cluster, but I decide I'm willing to
pay that price for giving my users lower latency.
 - I decide that in the event of AWS unavailability, I will have my load
balancers fail over traffic from one region to the other two, and just eat
the latency hit in that case.
 - I decide that I want to be able to tolerate both a cluster software
failure and an independent AWS failure, and still have two clusters up.
So, I add a fourth cluster in a different availability zone.  This will
cost me $Y more but I decide it is worthwhile for the added exepected
availability.
- I determine that I need 10 nodes at current peak traffic in each cluster.

- I decide that I want to be able to tolerate 5x that traffic due to growth
in the next year, DDOS, slashdot-effect, etc.  Since kubernetes supports
>50 node clusters (or will at v1), then I conclude that I don't need extra
clusters due to a maximum cluster size effect.

**Comment by erictune** [comment]
The master writes its state to etcd which persists its state to disk.  As long as your VM has reliable storage attached to it (not sure what AWS calls this, it is called PD on GCE), then you can re-create the VM with that same PD and it should keep running.

**Comment by rgolg** [comment]
Thanks for the detailed explanation Eric. Having a deterministic way of knowing how many nodes a single cluster can handle is one of the things I was trying to find out. I hate to make the comparison but that would give us the same level of information when designing systems that a size of a subnet would. The scenarios you've outlined make sense. Considering the instance size of each node in a cluster, 100 nodes per cluster can be a relatively small number if one decides to scale out the nodes horizontally vs having a less number of larger size nodes sitting around underutilized most of the time. It would be nice to auto-scale the clusters themselves beyond scaling the nodes in a cluster, if possible. 

Keep in mind the way I'm thinking about this is combining Kubernetes with the cloud provider's existing high-availability, fault-tolerance, and auto-scaling capabilities, where available, to scale not only the minion nodes in a cluster but the clusters themselves as well. A better way perhaps would be providing a Kubernetes plugin mechanism for providing the same HA, FT, AS functionality, along with things like dynamic DNS services like AWS Route53, independent of the cloud provider. That way the interested parties would simply implement the plugin for their cloud providers. The plugin implementation can be used by other interested parties using the same cloud provider. I am oversimplifying things here but its something to consider, if it hasn't been. Excuse my ignorance, but from what I understand, Kubernetes currently doesn't have a way of auto-scaling the nodes in the cluster either, correct? I have read that there's work to make the nodes scale using GCEs autoscaler. A plugin model would allow the same in AWS. When you spin up a cluster, I think it should just include the master and the absolute minimum number of worker nodes. The worker nodes should scale up and down based on internal monitoring triggers and perhaps external synthetic monitors triggering scale up or scale down events for the clusters themselves. 

I read the roadmap and saw plans for pluggable mechanisms for persistent storage and authentication. IMHO it would be nice if the same pluggable approach is taken for providing HA, FT, and AS for Kubernetes' own components (master, minions), beyond the pods and containers that Kubernetes manages on each node in the cluster.

The AWS equivalent persistent storage device you mentioned is called an Elastic Block Store (EBS) volume. In the case of an auto-scaled instance, normally the instances are stateless. The instances can be set to attach to a brand new volume, an existing volume, or they can also start up using a volume created from an EBS snapshot. To reuse the same volume, a little extra coding is needed to have a volume attach to the new replaced instance on deployment. We currently do this on some of our systems so I don't see a problem.

Thanks,
Reza

**Comment by erictune** [comment]
Auto-cluster creation does sound like an interesting problem to solve, but we probably need to prioritize auto-pod-scaling, auto-node-scaling, and many-node-support ahead of that.  If you'd like to help, we'd love to have someone report back on how many nodes can be supported by a single cluster on AWS before things start to break.  Most of the Kubernetes devs use other clouds, so that would be quite helpful.

**Comment by rgolg** [comment]
Agreed. First things first. :-) But the pluggable model is still important to keep in mind in case of auto-node-scaling which is in your current list of higher-priority items.

I'm absolutely willing to help with this. I can spin up a cluster on AWS for this test using the CloudFormation example. Is there a specific test you'd like to perform? Would just a spin up of a cluster with some really simple hello world service be enough to start with? Are there any similar tests in GCE documented anywhere that I can use to model the test in AWS?

**Comment by erictune** [comment]
@satnam6502 you did some scalability testing.  I think it is useful to do this on multiple cloud providers, @rgolg is willing to try on AWS.  Is there anything you can point him at in terms of load generation or advice?

**Comment by satnam6502** [comment]
Yes, I did some scalability work up to the end of last year and I hope to pick it up again next week. Basic issues:
* Generating > 255 IP addresses. I used a bash function to allow the generation of 1,000 IP addresses. This was written by @jbeda and I have not checked it in because I am not sure if this is really how we want to do it -- it is in a Gist which I can't find anymore.
* I had to do a lot of work to make cluster bring up and tear down more robust otherwise -- at least for GCE -- there was no change of successfully creating a large cluster. This process now seems pretty solid for GCE but I imagine similar things would need to be done for other providers. For example, any GCE operation can fail for unknown reasons -- so I added a lot of re-try logic.
* We still need to work on basic Kubernetes things for scalability e.g. detecting / listing large numbers of minions and listing large numbers of pods with appropriate caching. This is the work I hope to turn to next week.
* At this early stage the workloads I have been using have just been lots of pause containers created independently (rather than with a replication controller). Next week I hope to use the kubernetes/serve_hostname:1.0 image with a replication controller and hostPort to ensure even balancing across all nodes. I would then instantiate several of these (with different host ports). The objective is to have 1,000 nodes working with 10,000 containers.

**Comment by satnam6502** [comment]
Also, I would be delighted to co-ordinate on scalability testing and it would be great if we could share as much of the code as possible across providers!

**Comment by jbeda** [comment]
The gist with the bash IP generation: https://gist.github.com/jbeda/16191ad2cec4835de40b.  It is kind of slow and hack-o-rama but it works.

**Comment by satnam6502** [comment]
I've been using this reliably to instantiate 1,000 node clusters.
Do you think I should check it in as part of the gce kube-up process?
It's annoying having to copy and paste it into a local version each time...

Satnam

**Comment by rgolg** [comment]
Great timing @satnam6502! Please let me know when you are ready to pick this up. I have been able to bring up a cluster in classic EC2 (non-vpc). I will use the changed version of the CFN template in a VPC in pull request https://github.com/GoogleCloudPlatform/kubernetes/pull/2649 in a single subnet to spin up the initial cluster and will add worker nodes to the cluster until it breaks. I have to be careful with the cost of spinning up 1000 nodes in AWS but I can start small and then do one test with a 1000 t1.micro nodes to keep the cost down, if we can get the cluster that big. 

The worker nodes are going to be pretty tiny. What I was also interested in was what you actually deployed to your cluster to test it after you had all the nodes spun up? Would it work for testing a cluster with a large number of very small worker nodes?

Thanks!

**Comment by satnam6502** [comment]
I deployed the kubernetes/pause container because it is very small so we should be able to easily install many of them on each node. Currently the only test is "are they all in the running state?". The next step I propose is to use the kubernetes/serve_hostname container (usually based on scratch with a single statically linked binary although currently this is temporarily not the case) and I think we should be able to run 10 of these on each node with no sweat. Then an HTTP GET to this service (which returns it hostname) would let us know if the pod is working correctly. Once we can get this very basic setup working we can move onto more realistic workloads. But I think we have our hands full to get even the simple cases working acceptably.

I've got a Go program (not check in yet) that generates and deploys and tests and then deletes all the pods. Next week I will aim to get this checked in and then we should be able to use it for all providers.

**Comment by satnam6502** [comment]
Also, I had planned to do some testing on Amazon myself at some point. If running 1,000 nodes is going to be too expensive for you then once you have a setup that I can easily replicate then I offer to run the larger scale tests for you.

**Comment by rgolg** [comment]
That sounds great! I'll work on a script for adding nodes to an existing cluster running in AWS this week. I've forked the project so I'll probably put any new scripts I create into the aws folder in the documentation section of my fork so that you can create the VPC with a single subnet using cloudformation, then use a simple aws_worker_node_deployer.sh bash script which I'll create to spin up any number of nodes. Can you share any scripts you used for spinning up the 1000 node cluster on GCE? Do you happen to have it checked in somewhere?

**Comment by satnam6502** [comment]
For GCE, I just modify cluster/gce/config-default.sh to change the number
of instances and I also modify it using Joe's script for generating lots of
IP addresses. Then I just do a regular cluster/kube-up.sh (after having
made many modifications to cluster/gce/util.sh for robustness -- that's
where most of the retry logic is).

Satnam

**Comment by rgolg** [comment]
Got it. Thanks. I'll take a look.

**Comment by thockin** [comment]
Is this issue still open?

**Comment by rgolg** [comment]
You can close it.

Thanks

**Comment by dolftax** [comment]
@rgolg Quoting your comment above "To reuse the same volume, a little extra coding is needed to have a volume attach to the new replaced instance on deployment."

Could you be a bit more specific on this? Just steps would add more clarity :)
