### ISSUE TITLE
Remove /operations

### ISSUE THREAD

**Issue by nikhiljindal** [GoogleCloudPlatform/kubernetes#3644]
As per @smarterclayton's comment https://github.com/GoogleCloudPlatform/kubernetes/pull/3548#issuecomment-70715714, "Operations should be removed altogether."

@smarterclayton: Can you please clarify why is it not required anymore?
It seems to be used for listing the ongoing actions on the server.

**Comment by erictune** [comment]
@nikhiljindal feel free to assign to yourself if you plan to work on this.

**Comment by smarterclayton** [comment]
We reached agreement at the last Kube face to face that the original design (that operations could be long running on the apiserver, so we need to track them) would be better accomplished by a) controller loops and status on the objects, and b) breaking actions up to never be long running.  In that world, we do not need operations because no operation can be slow.  @brendandburns / @lavalamp just for sanity unless I'm misrepresenting the discussion we had.

----- Original Message -----

**Comment by bgrant0607** [comment]
We do need to satisfy the use cases described in #1899. However, we did agree that operations as currently implemented are not useful (they don't wait for the conditions deployment tools and/or users care about), not reliable (they aren't persisted),  and not friendly to replication or sharding (since they are server-local). I'm also not sure they are currently compatible with namespaces. So, I'm happy for them to be removed.

**Comment by bgrant0607** [comment]
Removing operations would also address one of the inconsistencies in the API (#2740).

**Comment by smarterclayton** [comment]
Also not secure (leak information if you can guess operation id).

**Comment by bgrant0607** [comment]
Please remove this from the client library:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/restclient.go#L134

**Comment by bgrant0607** [comment]
And here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/request_test.go#L802

That must not be exercised?

**Comment by nikhiljindal** [comment]
Thanks for pointing it out.
Sent https://github.com/GoogleCloudPlatform/kubernetes/pull/3921 for that.

**Comment by bgrant0607** [comment]
This is basically done.

**Comment by bgrant0607** [comment]
Actually, the objects (type Operations, OperationsList) still exist in the API. We should remove them.

**Comment by nikhiljindal** [comment]
Sent https://github.com/GoogleCloudPlatform/kubernetes/pull/4150 to delete those API objects.
