### ISSUE TITLE
Swagger method parameters duplicating Minion type in body

### ISSUE THREAD

**Issue by iantw89** [GoogleCloudPlatform/kubernetes#3755]
The v1beta{1/2}.Minion field appears to be duplicated in the method parameter section where ever it appears.

**Comment by iantw89** [comment]
Repro:
Use the steps outlined here to stand up a cluster on GCE: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/gce.md

View the swagger docs at https://{kubernetes master}/swaggerapi/api/v1beta2

**Comment by nikhiljindal** [comment]
Thanks Ian for reporting!

The issue seems to be due to this line: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/apiserver.go#L132
Reads(versionedObject) is added twice and hence minion in beta1 and beta2 and Pod in beta3 is repeated twice in POST body params.
Will send a PR to fix.
