### ISSUE TITLE
Swagger base path displays internal IP

### ISSUE THREAD

**Issue by iantw89** [GoogleCloudPlatform/kubernetes#3758]
The 'basePath' field is exposing the internal IP of the instance running the master. I.e. I get a 10.x.x.x. IP. The IP should be the external one, if possible. Otherwise clients outside the network of the master will be unable to form requests.

**Comment by iantw89** [comment]
Repro:
Use the steps outlined here to stand up a cluster on GCE: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/gce.md

View the swagger docs at https://{kubernetes master}/swaggerapi/api/v1beta1

**Comment by piosz** [comment]
@nikhiljindal are you working on it?

**Comment by nikhiljindal** [comment]
No. Feel free to take it up.

**Comment by piosz** [comment]
So I'll take a look. Thanks!

**Comment by nikhiljindal** [comment]
We are using master.publicIP to generate the swagger basePath (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/master/master.go#L524).
master.PublicIP is set from config.publicAddress, which it seems is the internal IP address.

@a-robinson : Any idea how can the master get its public IP when it is running in GCE?

**Comment by a-robinson** [comment]
Due to the way GCE networking works, the OS actually has no knowledge of whether it has an external IP or what it is. The way to get it is to query the metadata server, as described [here](http://stackoverflow.com/questions/23362887/can-you-get-ext-ip-address-from-within-a-google-compute-vm-instance).

It'd be pretty awkward to do this from within the apiserver itself (currently the default public IP is filled in [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/dfc19185f5de9325bb2c3cbfc2ffc3ea8f9490f0/pkg/master/master.go#L206) if none is provided), so it should be added to the startup script and passed as a flag.

**Comment by a-robinson** [comment]
It looks like sticking it in [PublicAddressOverride](https://github.com/GoogleCloudPlatform/kubernetes/blob/7703b50078848fcc8d33d5eeb0c9a2d65a5f846d/cmd/kube-apiserver/app/server.go#L118) would do the trick.

**Comment by a-robinson** [comment]
Except that it may break the cluster-local read-only and read-write services, so you'd have to test such a change carefully.
