### ISSUE TITLE
Fix provisioning when using portal created vnets (azure)

### ISSUE THREAD

**Issue by withinboredom** [GoogleCloudPlatform/kubernetes#3782]
I have a patch that fixes vm provisioning in MS Azure, I'd like to submit the patch to you if possible.

**Comment by thockin** [comment]
Please do.  The usual process is to create a github pull request, but we
could also take patches, if you prefer.

**Comment by withinboredom** [comment]
Pull request created

**Comment by thockin** [comment]
Sorry, I was reading email on my cell, and did not realize this WAS a pull request :)

**Comment by thockin** [comment]
Sigh, long week.  This is not the Pull request I am looking for :)

**Comment by withinboredom** [comment]
What pull request are you looking for? ;) I got all weekend to play with
azure and kubernetes ...

Robert Landers
Software Engineer
Charleston SC, USA

**Comment by thockin** [comment]
Sorry, I meant that I clicked through and thought "oh this IS a pull request".  But then it wasn't.  I am not a smart man on Friday evenings.

I'm going to go ahead and close this, since you have a PR in flight, and this issue, while perhaps colorful with regards to my mental state, is not helpful to the technical discussion. :)
