### ISSUE TITLE
A server assigned Service.PortalIP should be stored in status, not spec

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#3908]
The user did not choose the portalIP, so we should not pretend they did.

We should fix this in v1beta3 for #1519

**Comment by alex-mohr** [comment]
@bgrant0607 fyi re: API.

**Comment by bgrant0607** [comment]
The user _can_ choose it, however. So, effectively, it's like setting a custom default value, currently.

We should decide what to do as part of #2585.

**Comment by smarterclayton** [comment]
I meant, it should be stored in two places.  The user sets portalIP, stored as part of spec and *always* returned in status.  Set by the system, never stored in spec, and set in status.

That means you can export a service by name to another namespace and reuse it, because the user's lack of caring about the portalIP is preserved.

**Comment by bgrant0607** [comment]
Ok, I'll buy that.

**Comment by smarterclayton** [comment]
In theory service portal ip assignment can be modeled as a finalizer if people can wait for status, which means you can do single writer allocation and the APIServer can scale again.

**Comment by bgrant0607** [comment]
I will point out, however, that that fact that fields will be set by defaulting, rollout tools, imperative commands, auto-scalers, etc. are going to require that we annotate which fields the user really cares about in order to do a merge from a declarative config file with the current desired state in the system. This really isn't different.

**Comment by bgrant0607** [comment]
HostIP is another example.

**Comment by bgrant0607** [comment]
And the scheduler could be considered a "finalizer". That's just another entity that sets fields, among many.

**Comment by smarterclayton** [comment]
One way to look at "spec" means "set by user" and "status" means "things the system things are important for the user".  For our user facing objects, if spec *implicitly* means "preserve my input", then it simplifies how tools reason about those options.  How different imperative tools work with status is a lower priority item, and a process that sets "status" working with others.  Our conflict with that pattern is really Pods, which doesn't have "status" right now for finalizers to set things into, but is likely to be a massive target for finalizers.  The more complex this system gets of course, the more it resembles your layered proposal for defaults.

GET -> POST really feels like a user focused action (copy my intent across broad contexts).  With Pod Templates, we don't need as strongly to support GET -> POST on Pods (users that want to template pods should use... pod templates).  Does that mean that GET -> POST is more important for higher level objects (services / RCs / pod templates)?  If so, Pods are really the only object that spec clarification becomes important for (today). I'm just trying to adjust my mental model about design constraints so that I'm not advocating the wrong thing.

----- Original Message -----

**Comment by bgrant0607** [comment]
Spec isn't just things set by the user. It's the desired state. In an extensible system, there's no clear definition of "the system". Is an auto-scaler part of "the system"? Is kubectl part of "the system"? Is Openshift?

Expecting to be able to POST then GET back exactly what was posted, and no more, is a misguided expectation, IMO.

We can make GET -> POST work the same way as config merge, by using annotations to record fields of interest. It's less first-class than my layered API proposal, but, on the plus side, it can easily generalize to N layers.

**Comment by bgrant0607** [comment]
To be a little more clear, hopefully: 

System components, add-ons, extensions, etc. need a clear view of the desired state.

The user wants to be able to distinguish what they care about vs. fields set by everything else, not just the apiserver, in order to clone objects within a namespace, or copy/move them across namespaces or clusters, or produce clean configuration files they can then use going forward.

So, really, it's user vs. everything else, as I wrote in my original "shadow spec" proposal.

Status should be another thing entirely -- observed state.

**Comment by bgrant0607** [comment]
Also, status must be 100% reconstructable by observation.

This is just a case of smart defaulting / initialization.

Spec is the right place.
