### ISSUE TITLE
kubectl describe nodes <id> should have more information

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#4075]
'kubectl get nodes' returns a list of nodes with name, label and status. But 'kubectl describe' only returns node name. This is useless, it should have the same information as kubectl get as minimal. Here is the full list of the information I want for a kubectl describe

1) name, label and status
2) node level resource aspects: capacity, usage #2903
3) events related to node
4) # of Pods, or event Pods information on that node

**Comment by dchen1107** [comment]
cc/ @ddysher @bgrant0607

**Comment by ddysher** [comment]
Yeah, we definitely need to do this, except some of the information may not be available immediately.  e.g. we don't seem to publish event related to node.

**Comment by dchen1107** [comment]
We do have kubelet birth events from kubelet. NodeController should publish events related to node too.

**Comment by bgrant0607** [comment]
cc @rsokolowski

**Comment by ddysher** [comment]
@dchen1107 The kubelet birth cry is reported as a reference to its host, which should be included in the event list from kubectl describe node host.  But i don't see it, is this a known issue?

**Comment by dchen1107** [comment]
Yes, it is known issue since all events have 2day TTL. It is possible all events are deleted after 2 days. I am filing an issue to take care of this.

**Comment by ddysher** [comment]
PR #4396 and #4697

@dchen1107 I can't see the event even if the cluster is just created.  It maybe that BirthCry doesn't construct the correct reference.

**Comment by gmarek** [comment]
I don't think it's still an issue. By running 'kubectl describe' I get an info about: Type, Status, LastProbeTime, LastTransitionTime, Reason and Message (wrongly populated though), IP address, Capacity, ExternalID and list of names of running(bound?) pods.

The problem currently present is that there's some problem with data formatting:
```
Conditions:
  Type		Status	LastProbeTime				LastTransitionTime			Reason					Message
  Ready 	Full 	Mon, 23 Mar 2015 14:01:22 +0100 	Mon, 01 Jan 0001 00:00:00 +0000 	kubelet is posting ready status 	
```
I believe that "Type" should be renamed to "Condition" or "State", eventually "Kind" to reflect the JSON type of this entry. Current state is especially confusing because in 'get nodes' we have STATUS, which corresponds to 'Type', not 'Status'.

The biggest followup question is if we want to serve things present in NodeStatus only, or do we want to allow some joins to output more relevant data (e.g. statuses of pods bound to the minion, events), which can be useful while debugging a cluster.

I think that we can allow client side joins in kubectl, as it shouldn't be called too frequently. If we're using 'describe' in some scripts we can add a flag --full-description (or something) which will enable printing out data from joins, and normally output only basic data.

@dchen1107: Do you have any comments?

**Comment by ddysher** [comment]
Condition.Kind has changed to Condition.Type in v1beta3, and Condition.Status=Full/None may be changed to True/False.

STATUS from `kubectl get` is a joint status from Condition.Type and Condition.Status.  Agreed it's a bit confusing, any suggestion?

As we list names of pods on the nodes, we already have the data necessary to do a 'join', but I think it more like spam, esp when you have a lot pods.

**Comment by dchen1107** [comment]
I think eventually we want some joined data, such as usage at node level retrieving from different source. But I think "kubectl describe nodes id" returns a list of pods bounded to that node is good enough since the user can easily retrieve pod's information from "kubectl describe pods pod_name".

**Comment by gmarek** [comment]
@ddysher I'm generally fond of simple state machines as NodePhase, and IIUC Condition is something strange. The way I understand it is that there are 3 'dimensions' of Condition (reachability, readiness, schedulability), each of them can be set to True/False separately. Do we really want to have Schedulable, non-ready nodes? 

I don't exactly follow the reason for split between Phase and Condition (I read #2315), so I can't really tell how it should be. Generally I guess ```get node``` should report lifecycle Phase/Stage, as it is the interesting thing. My interpretation is that Condition is basically a set of health check results, so names like 'Ready' etc. are confusing (especially when connected to names of Phases).

For describe I think we should reword Conditions to what the are (the way I understand it). Which is various health checks. I'd change it from 'Conditions' to 'Health Checks', Type can stay, Status should be 'OK' or 'Bad' (or whatever), and the rest can stay as it is. Plus we should report the Phase.

@dchen1107 I agree for now. My experience from debugging clusters suggests that having statuses of bound pods in this place can be helpful, but that's far from being a priority in any foreseeable future.

**Comment by bgrant0607** [comment]
cc @davidopp 

Phase is monotonic -- provisioning lifecycle.

Condition is the most recently observed status.

For all practical purposes, we can't distinguish reachable vs. ready at the moment, so one of those two could be eliminated for simplicity until we can.

They're not all "health checks".

None of the conditions are aggregations of information -- they are orthogonal. In particular, "Schedulable" just reflects whether the unschedulable bit is set in the spec or not.

**Comment by ddysher** [comment]
We don't have a good support for node lifecycle now, so Phase is hidden from user.  Eventually, we'll report it, which will make things more clear.  Also, I'll take some time to remove reachable to simplify things a little bit; afaict, it's not v1.0

The 'schedulable, non-ready nodes' means admin (or other authorized entity) marks the node schedulable, but the node itself is not ready.  On the other hand, 'non-schedulable, ready nodes' means the node is ready, but admin marks it unschedulable, so nothing will be scheduled on that node.  As @bgrant0607 methoned, they are observed status, not just health check.

**Comment by davidopp** [comment]
I agree the Phase vs. Condition thing is a bit confusing. They're not completely orthogonal, in that not every element of the cross-product is possible. We have some ideas for simplification of NodeReady, for example, not using ConditionUnknown to explicitly mark an unreachable node. OTOH that may make things worse, since then it will be less obvious when a machine is temporarily unreachable. I think a state/substate model (possibly allowing backward transitions) might have been simpler, but hopefully tweaking what we have now will be good enough.

**Comment by gmarek** [comment]
I think we all agree that current state is confusing, as we use similar words in different contexts. The way I understand current "Condition" is that it reflects various parts of Nodes health. I don't see a strong reason for non-ready schedulable nodes (the opposite is for drains, this is clear). For this reason I think we can say that non-schedulable nodes are not 'healthy' per se, hence my 'health check' suggestion.

The problem with 'observed status' argument is that it's hard for me to give concrete semantics to 'observed status' term (or rather I can too many different ones, i.e. it can mean pretty much anything). Maybe if I see more examples of what kind of 'observed statuses' we'll have, I'll understand why "Condition" is a appropriate name. The ones that are currently there are, in my opinion, health metrics (for some reasonable definition of health).

The thing I'm afraid of is that we'll get locked in with confusing terminology, with no way to change it (it'll certainly be true after 1.0). On higher level I agree with David, that state model, even allowing backward transitions, might be simpler, but I'm afraid it's too late for that.

**Comment by bgrant0607** [comment]
@gmarek @davidopp Would it help to have a discussion about this?

**Comment by bgrant0607** [comment]
The following pattern is being applied to all our API objects, currently most complete in Node and Pod.

Lots of early discussion about "states" (or lack thereof) was in #1365. Note that no field is called "state". That's deliberate, as is the lack of a complex state-machine model.

The Phase is a monotonically progressing lifecycle phase. The intent is to keep the set of phases very small, such as Pending, Running/Active, Terminated (or Success/Failure, which was a compromise). Pending is the provisioning/instantiation period, everything up to the resource being fully realized. Terminated means that the node has been permanently deleted from the cloud provider or machine database -- it's gone, not just rebooting.

Reason is intended to provide a single-word categorization of the cause for the current phase or condition. Message is a longer description and may include specific details about the cause for that specific object/occurrence. Where these fields appear in an Status subobject, such as PodStatus or NodeStatus, they elaborate causes of the current Phase. Where they appear in a Condition, they elaborate causes of the current Condition Status.

As mentioned before, Conditions are most recently observed status, in different dimensions. Ready implies that the Kubelet (and, ideally, its dependencies, such as Docker) is fully operational and responsive. Reachable would imply that the node (not necessarily the Kubelet) can be contacted, such as via ping. Schedulable implies that scheduling is administratively permitted for the node -- it is not lamed or being shutdown. Runnable would imply that container execution is administratively permitted for the node -- it's not drained. We've also discussed adding conditions such as (root) Disk Full, and other hardware/system problems.

In order to implement more sophisticated pod and data durability policies (e.g., forgiveness #1574), the node controller will need to distinguish between these different conditions. It's easy to imagine the scheduler needing to do so, also.

It does make sense, however, to combine the information in kubectl output. kubectl get should be the most concise. kubectl describe typically provides more details, including joins. kubectl can/should also provide less terse, denormalized English descriptions of the status.

**Comment by ddysher** [comment]
The issue is fixed.  Please open a new issue if current pattern is still confusing.
