### ISSUE TITLE
Node should sync back to master with allocated Pods through file source

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#4090]
Every node on GCE by default has cAdvisor, fluentd-es running as pod. We are going to put etcd server into a pod soon, and other master components into pods later. Those pods are pre-provisioned, and not through apiserver, and scheduler, I called them "static" pods. 

Today, kubelet does generate events related to those static pods, and push them to etcd. But there is no way to query those pods config from clients, and static pods in crashloop cannot be detected easily  because apiserver doesn't aware of them. 

Also those pods do consume resources, and without awareness of static pods on a node, scheduler might overcommit a node easily. 

We should have a mechanism defined for kubelet to sync back to master with those static Pods. 

cc/ @bgrant0607 @thockin @brendandburns

**Comment by thockin** [comment]
+1

**Comment by bgrant0607** [comment]
Note that this goes beyond #490. What I want to do is fully represent pods submitted to kubelet so that they can then be managed via apiserver, such as via a daemon/per-node controller or replication controller (for self-hosting master components).

**Comment by vishh** [comment]
+1

**Comment by yujuhong** [comment]
I have some questions and hope someone can shed some light.

 * What's the goal of this issue? Do we simply want the master to be aware of the existence of such pods (read-only pods as mentioned in #1523) or do we want the scheduler/controller to manage the static pods (should they be killable by user requests)?

 * Why are we migrating the master components (#490) into pods? Is it just because we want to monitor the resource usage or do we want the pods to be managed somehow. The latter might not make sense because the component itself could be critical to the managing process.

 * What components should be run as pods? Is it possible to *not* rely on the static pods from manifest files? For example, can we create a cadvisor pod through the apiserver? We may need to introduce a new concept of *pinned* pods in this case to make sure scheduler doesn't assign it to other nodes, but it may be doable. For the master components, things are trickier if you want *all* components to be run as pods...

**Comment by davidopp** [comment]
Those are good questions.

1) From Brian's comment, it sounds like the long-term goal is to make these pods indistinguishable from pods created through API server. However, you might want to implement this feature in two steps, first as read-only pods (which would be sufficient for having the scheduler take them into account when scheduling), and then as the second step convert them to full regular pods.

2) I think the main reason to migrate the master components into pods is for resource control (so they can have resource limits and it is easier to monitor their resource usage).  We have also discussed that it would make master upgrade easier, since all the state would be in containers so it is easy to start the new version and get rid of the old version. I think that as long as one "working" version of each master component is up, it is possible to bring up new components without running into the problem you described (the component is critical to the managing process). For example, imagine upgrading the scheduler: you could start the new scheduler pod (even using the old scheduler to schedule it) and then once it is up and has taken over scheduling, kill the old scheduler pod.

3) I think the goal is to eventually run everything inside a pod. I don't think this means all of these pods will be scheduled by the master, though -- they can be started up through a manifest file, as you mentioned. BTW we have discussed something like the *pinned pods* you mentioned -- see #1518.

**Comment by thockin** [comment]
Also see #2491 wherein I started to make a per-node pod controller and
realized how awful it was to implement.  surrounding code has evolved a lot
since then

On Tue, Feb 17, 2015 at 4:21 PM, David Oppenheimer <notifications@github.com

**Comment by yujuhong** [comment]
@davidopp, thanks for pointing out #1518!

1. These file-based pods are inherently different from the regular pods. I doubt that it is possible to make them truly indistinguishable. For example, user cannot delete the pod, as kubelet will immediately create a replacement. Users also cannot change the pod configuration in ways other than changing the manifest file on the node. If the end goal is to transform the static pods into fully manageable pods, we need to approach this different. E.g., we could implement the pinned pods (or the alternatives proposed in #1518) to replace the manifest files.

2. I was thinking more of a failure scenario, where a component fails and restart of such a component/pod is expected to be automatically done by the master. Upgrade is definitely a different use case, and an easier one(?).

3. Since we #1518 is far from being fixed, this might be nothing other than a thought experiment. If we have the ability to create pinned pods, we can write them into etcd during bootstrapping. This way, etcd could continue to be the contact point of pod entries.

**Comment by thockin** [comment]
I think that if we get to read-only pods from files, we'll be doing well.
I am less convinced that we need fully-managed pods from files, especially
in the short term.

**Comment by dchen1107** [comment]
Agreed with @thockin. For 1.0 release, we just need:

1) master knows read-only pods on node
2) scheduler takes those pods' resource usage, cpu and memory only so far into account 
2) user can query read-only pods' status, events and logs.

**Comment by davidopp** [comment]
Scheduler using pod usage for scheduling was bumped from 1.0, so #2 from @dchen1107 list is not a blocker for 1.0.

**Comment by bgrant0607** [comment]
See also #19, #246 (esp. https://github.com/GoogleCloudPlatform/kubernetes/issues/246#issuecomment-64533959), #473, #1573, #1627, #2303, and #2884.

Running in our components in pods would solve many problems, which we'll otherwise need to implement other, less portable, more brittle solutions to, and doesn't require much that we don't need to do for other reasons. Full self-hosting is the eventual goal. 

The main use case for converting pods from files to entities that are manageable through the apiserver is kubelet management. Other daemons could use the per-node controller.

For bootstrapping master components, it would be sufficient to submit the pods to the kubelet's API server and have those pods adopted by the cluster apiserver. That solution goes hand in hand with running multiple instances of master components for availability and/or scalability.

**Comment by yujuhong** [comment]
Here is an preliminary proposal after poking around the relevant modules.

**Goal**: Expose static pods and their associated events through `kubectl`
**Non-goal**: Make scheduler aware of the resource consumed by static pods so that it can make more intelligent scheduling decisions. This is scoped for future work.

Kubelet watches 4 sources for pods: http, apiserver, file, and etcd. It receives the regular pods via the apiserver source, while the *static* pods through the file source. The master/apiserver/etcd is not aware of the static pods running on the nodes. 

To reuse the existing mechanism for retrieving pod information/statuses through API server, Kubelet should create a mirrored pod entry via the apiserver for each and every one of the static pods on the node. Scheduler should completely ignore such mirrored pods.

When Kubelet is asked to get the status of the pod, it needs to map the mirrored pod to the corresponding static pod. Note that this is required because Kubelet distinguishes pods from different sources using its own internal namespacing. A pod is identified by its full name, which is `name.namespace.source`. E.g. the mirrored pod may be named `foo.namespace.api`, but the actual static pod can be named `foo.namespace.file`. Since `foo.namespace.api` is a placeholder pod without actual statuses, it needs to be mapped to `foo.namespace.file`. A naive solution is to fall back to retrieving `*.file` pod if the `*.api` pod does not exist.

In short, 
- Kubelet monitors the static pods and translate a mirrored pod into the corresponding static pod when asked to return the pod status. It is also responsible for creating/deleting mirrored pod entries during `SyncPods()`.
- Apiserver/etcd on the master is only aware of the mirrored pods.
- Scheduler does not know static pods and consciously ignores mirrored pods.

Other issues and options:
 1. Scheduler needs to be able to distinguish between the mirrored (static) pods and the regular pods.
    - a. Add a new field in the PodSpec to indicate that the pod is read-only.
    - b. Alternatively, pass this information through labels/namespaces.
    - I am inclined to go with (a) because (b) could cause conflicts with user-created objects.
 2. Scheduler is in charge of setting the *Host* field in the PodStatus for a given pod. Without setting the Host field, pod cache will always assume the status of the pod is pending (since there is no Kubelet to consult). 
   - a. When creating the pod via apiserver, Kubelet should set the Host field in the PodStatus. This is currently *not* doable because users are not allowed to create/update PodStatus through pod creation/update. We need to relax this restriction.
   - b. Alternatively, once #4561 is fixed (i.e., Kubelet POSTs pod status directly), this would be a non-issue.
 3. The namespace of a static pod is currently generated as `file-hash-node_hostname`. This seems unnecessarily complicated now that we can view the pods through `kubectl get pods`.
  - Change the namespace to `node_hostname` . All the static pods on one node will then share the same namespace. Users can filter the pods by the namespace easily.

p.s. There is no corresponding BoundPod entry for a mirrored pod.

Suggestions are welcome!

**Comment by thockin** [comment]
Plan sounds good overall.  I'm not sure I understand the shadowing - but I
guess I don't really know how the API server "asks kubelet" for info..

I agree 1a.

Regarding point 3: The problem with using hostname as namespace is that
it's entirely possibly for users to collide with that.  We do not have any
"reserved" namespace that we can use.  What we do now is a hack to make it
less likely to collide.  Maybe we need to do something like declare that
namespaces that start with "k8s-" are reserved for use by cluster
components.

But even more, we can't let all static pods on a machine share a namespace
because we don't do name-collision checking on static pods.  If two pods
both declare their name to be "frank" - what do we POST to apiserver?
Kablam!

**Comment by yujuhong** [comment]
We had an offline discussion and agreed on *some* things.

 - Instead of using a unique/reserved namespace for each node, we settled on using a single namespace for k8s system pods. We will tentatively use the "default" namespace for now (which may change later), and encourage users to create their own namespace to avoid name collision.
 - http and file sources should generate a unique pod name for each pod to avoid collision. For example, `cadvisor-file-hash-hostname` or `cadvisor-http-hash-hostname`.

What's still up in the air is how to prevent scheduler from scheduling the read-only pods. Here are some options that we discussed.
 1. Wait until #4561 is fixed, so that Kubelet can post pod status directly.
 2. Add a "to-be-deprecated" read-only field in PodSpec.
 3. Use labels to identify the read-only pods.
 4. Use annotations.

/cc all the people who joined the discussion today. @thockin, @derekwaynecarr, and @bgrant0607.

**Comment by davidopp** [comment]
Sorry for falling behind on this issue. Thanks for your nice write-up of the issue earlier in the thread, Yu-Ju. Your proposal earlier sounds reasonable, as does your most recent entry here. With respect to how to prevent the scheduler from scheduling pods, annotations sounds like it might be the best solution until #4561 is completed. It's less hassle than adding a new field to PodSpec and then removing it, and it seems better than labels in the sense that there is less chance that users might start relying on it.

If we do it as an annotation we might not want/need to get rid of it even once we finish #4561, as it would provide useful debugging information.

**Comment by dchen1107** [comment]
I don't like both 3 and 4 at all. Annotation should be used only as pass-through metadata , and shouldn't used by scheduler at all. Label is even more arbitrary, bigger no.

**Comment by davidopp** [comment]
@dchen1107 Can you explain what you mean "Annotation should be used only as pass-through metadata"? Do you mean, an annotation should only ever be consumed by the same component that produced it? I guess that is a reasonable guideline, but perhaps we could argue around it just in this case by saying long-term this information (pod source) will just be debugging information, so consumption by scheduler is only temporary?

**Comment by dchen1107** [comment]
I am based on the comment of Annotation in our api: 
```
Annotations are unstructured key value data stored with a resource that may be set by
external tooling. They are not queryable and should be preserved when modifying
objects.
```

But you are right if it is just a temporary solution. Once we have #4561 done, we could retire this.

**Comment by bgrant0607** [comment]
We don't need a new field to make the scheduler ignore the pods, and we definitely shouldn't use an annotation. Just pre-populate the Host field in the PodSpec.

Name: Let's pick one namespace for the whole cluster, and could append the hostname to a prefix provided in the file.

**Comment by bgrant0607** [comment]
I also don't think we should worry about collisions between http and file. File can be checked first. http would then just lose. Besides, once we have per-node controller, we should consider getting rid of file input.

**Comment by bgrant0607** [comment]
Also don't worry about BoundPods. We're in the process of nuking them.

**Comment by bgrant0607** [comment]
Scheduler watches for pods with no host set:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L146

**Comment by yujuhong** [comment]
We had a offline discussion and there are a few related issues.
- #4561 for posting pod status from kubelet.
- #3453 for Kubelet cannot accept DNS subdomain compatible names/namespaces. This has to be fixed if we want to use hostname as part of the pod name. We should also revisit using "source" as part of the container name.
- The general issue of nuking BoundPods.
 
Although we can work around some of these issues, we will have to patch them again in the near future. The consensus is to wait until the related issues are resolved and implement a cleaner solution.

p.s. the code that @bgrant0607 pointed out was misleading
`cache.NewListWatchFromClient(factory.Client, "pods", api.NamespaceAll, labels.Set{"DesiredState.Host": ""}.AsSelector())`
There is another level of mapping which translates `DesiredState.Host` to `Pod.Status.Host`
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/pod/rest.go#l122

**Comment by erictune** [comment]
This issue is a good candidate for summarizing, closing, and filing finer-grained work items.

**Comment by erictune** [comment]
I don't buy that we should get rid of file based pods.  If you only have http, then people have to run a local http server in order to have non-network-dependent pods created at startup.  That seems annoying.

**Comment by erictune** [comment]
why would the scheduler need another field to detect readonly pods?  If the kubelet fills in the Host field, then the scheduler would know it does not need to schedule the pod.

**Comment by bgrant0607** [comment]
I was thinking we'd allow pods to be posted directly to kubelet via a local socket.

I agree that no additional field is necessary.

**Comment by yujuhong** [comment]
@erictune, if the kubelet fills in the `Host` filed in the pod status, it'd be sufficient. Currently, we don't allow pod creation through the apiserver to set the pod status. It was also discussed in the previous comments https://github.com/GoogleCloudPlatform/kubernetes/issues/4090#issuecomment-76448384

**Comment by bgrant0607** [comment]
Please populate Spec.Host. See #5256.

**Comment by yujuhong** [comment]
@bgrant0607, that's what I have been doing, and my code works with the current implementation. Scheduler would go ahead and update the BoundPod by inserting the mirrored pod kubelet created. On the other hand, kubelet would de-duplicate the pods from different sources.

**Comment by yujuhong** [comment]
A brief summary:

#5401 creates a mirror pod via the apiserver for each static pod, where the mirror pod has the same name and namespace as the static pod.
  + It allows users to view the status of the static pods by querying the apiserver
  + Scheduler is aware of the resources consumed by the static pods.
 
However, because events are associated with the static pods (which has a different UID than the mirror pod), `kubectl describe <mirror_pod>` does not aggregate the relevant events. This is what we decided to tolerate for now, and we may eventually fix it.
