### ISSUE TITLE
Rewrite pd.sh end-to-end in Go

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#4183]
Part of umbrella issue #3130. cc @satnam6502 @filbranden 

And @brendanburns.

Also, good luck to whoever attempts this one.

**Comment by cjcullen** [comment]
pd.sh only really tested that a pod w/ a PD could be attached (because detach was flaky/broken and slowing everyone else down).

Rewritten version has two parts:
1. Schedule Pod w/ PD on minion 0. Delete it. Schedule the same thing on minion 1. Make sure they both come up.
2. Schedule Pod w/ readonly PD on minion 0. Schedule same thing readonly on minion 1. Make sure they both come up.

**Comment by ixdy** [comment]
hack/e2e-suite/pd.sh still exists. Should it be removed?
