### ISSUE TITLE
Support adding/removing containers from a pod

### ISSUE THREAD

**Issue by marvell** [GoogleCloudPlatform/kubernetes#4212]
```
$ kubectl -shttp://kube-master:8080 update -f back.pod.yml
F0206 18:59:12.062877   16519 update.go:111] Pod "exactfarming-back" is invalid: spec.containers: invalid value '[{Name:app Image:some_host:5000/marvell/exactfarming__back:0.1.1 Command:<nil> WorkingDir: Ports:[{Name:http HostPort:8002 ContainerPort:9292 Protocol:TCP HostIP:}] Env:[{Name:RAILS_ENV Value:production_dev} {Name:FRONT_HOST Value:http://some_host:8001} {Name:BACK_HOST Value:http://some_host:8002} {Name:SATELLITE_API_HOST Value:http://some_host:8084/}] Resources:{Limits:map[]} VolumeMounts:<nil> LivenessProbe:<nil> Lifecycle:<nil> TerminationMessagePath: Privileged:false ImagePullPolicy:IfNotPresent Capabilities:{Add:<nil> Drop:<nil>}} {Name:mongo Image:mongo Command:<nil> WorkingDir: Ports:<nil> Env:<nil> Resources:{Limits:map[]} VolumeMounts:<nil> LivenessProbe:<nil> Lifecycle:<nil> TerminationMessagePath: Privileged:false ImagePullPolicy:IfNotPresent Capabilities:{Add:<nil> Drop:<nil>}} {Name:redis Image:redis Command:<nil> WorkingDir: Ports:<nil> Env:<nil> Resources:{Limits:map[]} VolumeMounts:<nil> LivenessProbe:<nil> Lifecycle:<nil> TerminationMessagePath: Privileged:false ImagePullPolicy:IfNotPresent Capabilities:{Add:<nil> Drop:<nil>}} {Name:nginx Image:some_host:5000/marvell/exactfarming__back__nginx:0.1.0 Command:<nil> WorkingDir: Ports:<nil> Env:<nil> Resources:{Limits:map[]} VolumeMounts:<nil> LivenessProbe:<nil> Lifecycle:<nil> TerminationMessagePath: Privileged:false ImagePullPolicy:IfNotPresent Capabilities:{Add:<nil> Drop:<nil>}}]': may not add or remove containers
```

kubernetes v0.10.0

**Comment by dchen1107** [comment]
Like output of " may not add or remove containers" indicates currently our validation doesn't allow change container number in an existing pod.

**Comment by bgrant0607** [comment]
Changed the title. We plan to support this eventually, but do not support it at the moment.

**Comment by bgrant0607** [comment]
BTW, I would normally recommend that you just create a new pod, but I see it contains your DB. So, you'd need durable local storage #598 that outlived the pod in order to do that.

You might consider splitting this into multiple pods.

**Comment by sergmelikyan** [comment]
Hi @bgrant0607,

This issue is blocking integration of Kubernetes with OpenStack based on Murano, It would be very helpful if this issue will be re-prioritized. Any chance to fix this issue in upcoming release?

Murano creates Pod and after that containers are added to the Pod, but with this issue, only first container is spawned, following calls are failed. This is low priority when you are manually spawning Pods, but it is very inconvenient for automation tools, like Murano.

We have [recorded demo](https://vimeo.com/120445504) of integration from recent Kubernetes Meetup in SF, in case you are interested in how this integration looks like.

References:
* [Kubernetes Application for Murano (source-code)] (https://github.com/stackforge/murano-apps/tree/master/kubernetes)
* [Murano](https://wiki.openstack.org/wiki/Murano)

**Comment by bgrant0607** [comment]
Discussed w/ @craiglpeters. 

I suggest deleting and re-creating the pod as a workaround. See the [update demo](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/update-demo) for our current recommended practice for rolling out updates to replicated pods.

We do eventually intend to support in-place updates, but it adds significant complexity, not just in Kubelet, but upward through the scheduler and apiserver as well, since in-place updates are usually desired by high-availability applications that want to minimize disruption.

What it sounds like you want in this case is to defer scheduling until all containers have been added, using the "initializer" approach discussed in #3585. That's also likely to be better supported in the future, but not likely before 1.0.

If you simply want to make it mechanically possible to update a scheduled pod in order to add/remove containers, we could accept PRs to do that, but it may not achieve the effect you desire.
