### ISSUE TITLE
clarification needed on event object

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#4328]
example here:
https://github.com/abonas/kubeclient/blob/master/test/json/event_list_b3.json

this event says "kind": "BoundPod", but from the message is regarding docker id, and it's not
clear which exact entity (pod? container?) does the event refer to.
why the "kind" property reflect the same entities as  in the regular REST api?

**Comment by roberthbailey** [comment]
This event looks like it was from creating the nginx container in your pod named php because the "fieldPath" identifies a specific container from the pod spec ("spec.containers{nginx}"). 

From https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L1071:

	// Optional. If referring to a piece of an object instead of an entire object, this string
	// should contain information to identify the sub-object. For example, if the object
	// reference is to a container within a pod, this would take on a value like:
	// "spec.containers{name}" (where "name" refers to the name of the container that triggered
	// the event) or if no container name is specified "spec.containers[2]" (container with
	// index 2 in this pod). This syntax is chosen only to have some well-defined way of
	// referencing a part of an object.
	// TODO: this design is not final and this field is subject to change in the future.

Possibly unrelated, but FYI @erictune is in the midst of removing BoundPods.

**Comment by roberthbailey** [comment]
@abonas did that answer your question? I'm going to assume yes and close this issue but if not please feel free to reopen.
