### ISSUE TITLE
Question about ResourceQuota objects

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#4388]
Question from Frank on google-containers@googlegroups.com:

Hi all,

Consider the file below, I feel confused about the 'resourcequotas' filed in resource-quota.json file.

{
  "id": "quota",
  "kind": "ResourceQuota",
  "apiVersion": "v1beta1",
  "spec": {
    "hard": {
      "memory": "1073741824",
      "cpu": "20",
      "pods": "10",
      "services": "5",
      "replicationcontrollers":"20",
      "resourcequotas":"1",
    },
  }
}

I think the use case of resourcequotas is here, 

list, err := q.client.ResourceQuotas(a.GetNamespace()).List(labels.Everything())
	
for i := range list.Items {
  quota := list.Items[i]

If resourcequotas > 1, then there will be multiple ResourceQuotas objects. Then how should we edit the resource-quota.json file? Just modify resourcequotas to n(n > 1)?

In fact, I am not very clear about the usage of 'resourcequotas' field in resource-quota.json file. It indicates the number of ResourceQuota objects? However, how can the one who write the resource-quota.json file know how many ResourceQuota objects exist in the specified namespace? I am not sure whether it's necessary for the existence of 'resourcequotas' field.

--
Regards,
Frank

**Comment by derekwaynecarr** [comment]
For some background on this, see the design document here:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/admission_control_resource_quota.md

I will pull the pertinent piece here for review:

>>To optimize system performance, it is encouraged that all resource quotas are tracked on the same ResourceQuota document. As a result, its encouraged to actually impose a cap on the total number of individual quotas that are tracked in the Namespace to 1 by explicitly capping it in ResourceQuota document.

A ```ResourceQuota``` is intended to support the ability to cap the total amount of compute resources (cpu/memory) that is consumed by pods in a ```Namespace```.  In addition, it is also intended to cap the total number of any given kinds of objects that can exist in that ```Namespace``` in order to restrict usage in a scenario where you may want to limit the number of items that can exist in a **dev** namespace so it does not compete with **prod** namespace.  In practice, this means if a Kind of object can be in a ```Namespace```, it's fair game for a ```ResourceQuota``` to apply a restriction on the ```num(Kind)```.  Naturally, this includes the number of ```ResourceQuota``` objects that can exist in a Namespace.

Every create/update operation in a ```Namespace``` is evaluated against each ```ResourceQuota``` when the pertinent admission controller is enabled.  In order to maintain system performance, it's recommended that you cap the number of active quota documents.  A simple mechanism to do that is to make the first quota you add to a ```Namespace``` prevent anymore ```ResourceQuota``` objects from being added.

**Comment by m1093782566** [comment]
Hi Derek,

Thanks for your explanation, I have got my answers. However, why `kubectl describe quota` doesn't show the `Used` and `Hard` information of `resourcequota` like `pods` below?
```
$ kubectl namespace myspace
$ kubectl create -f examples/resourcequota/resource-quota.json
$ kubectl get quota
NAME
myquota
$ kubectl describe quota myquota
Name: myquota
Resource  Used  Hard
--------  ----  ----
cpu 100m  20
memory  0 1.5Gb
pods  1 10
replicationControllers  1 10
services  2 3
[lack of resourcequota information?]
```

--
Frank

**Comment by derekwaynecarr** [comment]
Which provider are you using?

**Comment by m1093782566** [comment]
kubernetes version 0.9

In fact, you can see kubectl does not provide info about 'resourcequota' [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/admission_control_resource_quota.md#kubectl)

**Comment by brendandburns** [comment]
Hello,
Sorry for the delay in responding.  Those objects are not present in kubernetetes version 0.9
