### ISSUE TITLE
Bringing down the cluster doesn't delete forwarding rules and load balancer for default services

### ISSUE THREAD

**Issue by fgrzadkowski** [GoogleCloudPlatform/kubernetes#4411]
Bringing down the cluster doesn't delete forwarding rules and load balancer for default services running on GCE.

**Comment by roberthbailey** [comment]
We've informally talked about adding some sort of cluster shutdown hooks to the master and having the teardown code notify the master that is going to be destroyed.

**Comment by jszczepkowski** [comment]
There are two separate problem here: 
(1) update for service does not update external load balancer (not implemented yet, marked as TODO),
(2) when cluster is shut down by kube-down.sh external load balancer are not removed.

To solve (2), I suggest just to delete all cluster's services in kube-down.sh, before shutting down master and minions. I'm not sure if services should be removed by a special tear-down code is master, because  we may want to shut down master and restart it on a different server without changed state of cluster. Such operation should not affect resources.

**Comment by jszczepkowski** [comment]
Problem (1) is solved by #4484. We still need to solve (2): removing of external load balancers during shut down.

**Comment by roberthbailey** [comment]
@jszczepkowski It looks like the first half of this was solved by #4484 and the other half has it's own issue (#4630). Can we close this one out?
