### ISSUE TITLE
Merging .kubeconfig from multiple locations causes frustration and anger

### ISSUE THREAD

**Issue by jlowdermilk** [GoogleCloudPlatform/kubernetes#4428]
The fact that kubectl merges config from multiple .kubeconfig locations was neat in theory, but in practice it's surprising, confusing, and occasionally infuriating. See #4426, #4397. If it causes this much pain for k8s devs, it's likely unusable by average kubernetes users.

Proposal: get rid of kubectl loading from a local .kubeconfig, `--kubeconfig` flag, and `$KUBECONFIG` env var . If a user needs to overrwrite behavior, they can use the `--cluster|context|user` flags. Having N ways to load config is just too confusing.

cc @deads2k, @satnam6502, @erictune

**Comment by satnam6502** [comment]
I'd love to know what the profile of an "average Kubernetes user" is.

**Comment by deads2k** [comment]
#4397 was a straight up bug.  That was confusing because it didn't work right.

#4426 isn't quite as clear to me.  Is it just the fact that viewing a config shows a merged set of items whose provenance isn't made clear and so to figure out where any individual piece of configuration is coming from requires checking each of the four potential locations?  (By the way, that sounded a lot more reasonable before I actually wrote it down.)

If I were going to change it, I would eliminate merging, but keep the `--kubeconfig` flag as option to completely replace the default `.kubeconfig` file and probably want to respect an environment variable as a complete replacement as well.  Specifying a completely different file is a very helpful construct, but being able to mix and match pieces from disparate locations is of questionable value.

I think @ghodss had the original proposal, so he probably has some thoughts.

**Comment by jlowdermilk** [comment]
The problem with #4426 was that a previous command created a local .kubeconfig that did nothing but set current-context. The merge rules resulted in a behavior where you set an entry, and than view config and see that entry is not set (because the merging happens silently).

I think the merging is really what causes confusion, because it's a mystery where a particular config entry is saved and where it is loaded from. Specifying an entirely different kubeconfig is more reasonable.

**Comment by deads2k** [comment]
I'll start working on this.

**Comment by smarterclayton** [comment]
Should retitle this issue "Kube developer hulk smash inherited config".  Agree we should preserve explicit config on filename and env, and unless Sam remembers something, ditch multiple files.  Who else at the last f2f was involved in the discussion?

**Comment by liggitt** [comment]
@derekwaynecarr and Sam talked through this, I think

**Comment by ghodss** [comment]
Yeesh. My apologies for causing so much consternation.

However... I do not think we should eliminate merging altogether. Merging kubeconfigs is important and powerful for the same reason that bash runs /etc/bashrc before ~/.bashrc, why git merges $(prefix)/etc/gitconfig with ~/.gitconfig and then $(repo)/.git/config, and why yum reads /etc/yum.conf and then merges in any additional configs in /etc/yum.repos.d: it's hugely advantageous to have the ability to add configs merely by adding or modifying global files on the filesystem. For example, if I want to use a config management system (puppet/ansible/salt/etc.) to make sure that everyone on my team has access to the dev cluster just by using --context=dev, it's really hard to do that if kubectl only takes one .kubeconfig file at any given time. I could ask them to do --kubeconfig=/etc/dev-cluster/.kubeconfig, but they would have to do --context=dev as well, which is a lot to keep track of if I'm trying to provide many different clusters from many different sources. This is why we were originally thinking of actually crawling all files in ~/.kube/ recursively to find all configs that could be merged.

Regarding the issues: nearly all of kubeconfig merging should be purely additive, which appears to be the case, and these instances should not cause and do not appear to be causing issues. The real issue seems to be from current-context being set and overridden by tooling and scripts in confusing and unpredictable ways. Tooling should never set current-context (or set anything that affects current-context). It should drop a purely additive config into somewhere that is searched (e.g. ~/kube/gce.kubeconfig) and use that context through the --context= command line flag. It should then make that --context= flag available to the user to use, or to make sticky as a personal preference.

If we are less clever with how current-context is set and detected, I think we will see far fewer (if any) issues with merging. In the mean time, any time we print current-context, we should print how we arrived at it (i.e. the last known location that merged it in). Further, it may make sense to restrict where current-context can be set (e.g. only the master .kubeconfig file, and only overridable through the command line or env var). This kind of care really only needs to be done with non-additive config variables, the only one of which is current-context I believe. But eliminating merging of additive configs entirely would be a big loss to managing kubectl.

@deads2k @jlowdermilk and others: Are there any issues you know of that would still be frustrating if all we did was clean up how current-context is detected and set?

**Comment by jlowdermilk** [comment]
@ghodss, I can appreciate the arguments for keeping merged kubeconfig, but I disagree that merging is essential functionality. I've been thinking about this, and IMHO, kubeconfig shouldn't try to emulate gitconfig or bashrc, because the latter are both more about saving and merging local preferences, whereas kubeconfig is really just a way to package client credentials for talking to remote services. #4517 forwards the model of kubeconfig as a contained config, and it may turn out to be more useful to consider kubeconfig as having a narrower purpose. That is, kubeconfig just encapsulates the information that a client needs to identify and talk to a set of clusters. It currently supports additional preferences, but afaik, there isn't an actual use case for that. We don't have to consider narrowing kubeconfig's scope here, but I think it's worth focusing on what is the problem we are trying to solve with kubeconfig. I think (and please correct me if I'm wrong) that problem is basically

1. how do clients store and load config to talk to multiple clusters?, and
2. how do clients keep track of which cluster they're talking to?

If that is the problem, let's pick a simple solution. Standalone kubeconfig with a client that can switch between them (but only uses one at a a time) is a simple solution.

> it's hugely advantageous to have the ability to add configs merely by adding or modifying global files on the filesystem.

I agree, and standalone kubeconfig files can provide this; make a kubeconfig accessible to users and have them run kubectl with --kubeconfig=/path/to/config or set the $KUBECONFIG env.

> For example, if I want to use a config management system (puppet/ansible/salt/etc.) to make sure that everyone on my team has access to the dev cluster just by using --context=dev, it's really hard to do that if kubectl only takes one .kubeconfig file at any given time.

They actually wouldn't need to set --context=dev, because the kubeconfig file itself specifies the current-context. They would only need to set context themselves if they are using a single kubeconfig file to define to multiple clusters/contexts. And in the multiple context case, setting --kubeconfig or $KUBECONFIG to specify a config to load, and --context to specify a context to use from said config is only 2 things to remember. 

We could treat current-context as a special kubeconfig value and restrict the ways it can be set and detected, but I don't think that makes the usage less confusing; if anything it just adds to the learning cost. (Side note: as it's now implemented, you can't specify current-context in a kubeconfig unless that context is defined in the same kubeconfig. Merging contexts from multiple sources and having current-context be defined in one special location doesn't work, though it could be made to. ) If you can only ever use one kubeconfig file at a time, you don't have to think about load order or source hierarchy or additive vs overwriting config; you just put the cluster info you want to use/share in a kubeconfig and point clients at it.

Anyway that's my opinion. @brendandburns and @bgrant0607 should probably chime in.

**Comment by satnam6502** [comment]
My brain is far too small for this. I am going to alias every kube* command to `rm -rf .kubeconfig; command; rm -rf .kubeconfig` which is probably the only way I can remain sane. I don't want the identity of a cluster to be defined by overrides over dot files which to me seems like madness (but note my small brain comment, perhaps you guys have brains the size of Jupiter so it is fine for you). I want the identity of a cluster to be defined by some YAML file I can point to and provide as an argument to any kube* command.

**Comment by erictune** [comment]
I tend to agree with @ghodss.

Like a .git directory, a .kubeconfig is about both preferences and credentials.  (it has a preferences section)

I think there were a few rough edges here that contributed to the frustration, and those edges are pretty easily fixed without throwing away the power of merging.
  - IIUC, the intent was for the current-context of the local .kubeconfig to trump higher ones, but there was a bug.  great, we should fix that.
  - when you use the in-command help, it doesn't hint at merging.  by contrast, `git help config` mentions the ` --system, --global, --local and --file` options
  - any powerful tool is going to be a bit frustrating at first. that doesn't mean we should not make kubectl powerful.

**Comment by ghodss** [comment]
>  I've been thinking about this, and IMHO, kubeconfig shouldn't try to emulate gitconfig or bashrc, because the latter are both more about saving and merging local preferences, whereas kubeconfig is really just a way to package client credentials for talking to remote services.

current-context is in fact a preference and therefore is exactly the kind of thing that should follow inheritance rules. And in yum, the extra files inject new repos into the config, which is what I would like to accomplish by crawling for files.

However, your point is well taken that we may have conflated two purposes in trying to use kubeconfig as both a preferences store and a credentials store. How's this as a proposal (disclaimer: exact locations are up for debate):

Preferences (current-context, colors, etc.) are stored in /etc/kubectl with ~/.kubectl overwriting. You can override this file but that's rare - more often you would just override specific parameters with things like --context=.

Contexts (cluster, credentials, etc.) are defined in &lt;name&gt;.kubeconfig files. They can only define contexts - they can't set any preferences, including current-context. By default these are searched for in /etc/kube/\*.kubeconfig and ~/.kube/\*.kubeconfig, but you can specify additional directories to search in preferences/config. If you're not kubectl but want to use a cluster config (e.g. kubelet), the same search rules apply, but you just choose your context through the --context= command line param. You can also point to additional kubeconfig files to load with the repeatable param --kubeconfig=.

Splitting the two concepts should significantly clear up the confusion while retaining the power of merging.

**Comment by smarterclayton** [comment]
I'm on the Eric / Sam side of the fence here, in that done right (and clearly) will allow me to have common prefs across all clusters, but separate config for the right use cases.

I think an important use case is going to be tying a git repo to a particular KUBECONFIG - that might not require multiple files, but it will require the user to think about Git (and the Git repo they are in) as a "layer" that affects config.

**Comment by smarterclayton** [comment]
I don't know... This didn't sound less complex :)

**Comment by bgrant0607** [comment]
Sorry, I've largely been ignoring this. Catching up.

What are the main problems we're trying to solve?

* Make it easy to create multiple clusters
* Make it easy to interact with multiple clusters
* Make it easy for admins to provide access to shared clusters
* Make it easy for users to assume multiple roles
* Make it easy to set UX preferences for the CLI (colors, whatever) 
* Make tests not cause side effects in the local environment in the cases of ordinary test success/failure
* Make it easy to predict and figure out what the tool is going to do for any given command
* Get rid of kubectl.sh

It's not clear to me that multiple sets of preferences are important/desirable, other than in the case of merging (like .bashrc).

My preference would be to nuke KUBERNETES_PROVIDER entirely, both for kubectl and for cluster turn up/down. kube-up.sh and kube-down.sh could explicitly take whatever parameters are necessary: provider, cluster name, etc. Cluster up/down commands are unlikely to be invoked often relative to the frequency of kubectl commands, except in tests. 

The config contains multiple orthogonal parts:
* cluster info: credentials, addresses, etc.
* user info: credentials, etc.
* UX preferences: colors, whatever
* context: cluster, user, namespace

The cluster and user info seems pretty orthogonal. Commands to create, edit, and delete this info make sense. I don't think "merging" makes sense, other than just aggregating the info from multiple places. Creation of configs probably should only be possible in the first directory/file in the path. A default path seems reasonable, but should be overridable in a consistent manner, such as KUBECONFIG_PATH env var and --kubeconfig-path= flag. Tests could override the path to store their configs in a place that doesn't interfere with users' environments.

.bashrc-style fine-grain merging from multiple sources makes sense for UX preferences. Same path behavior seems fine, unless someone has a reason why the path needs to be different.

I'm not convinced that context makes sense at all as persistent state. Like the kubeconfig path, I'd make the context settable via env vars and flags, such as KUBE_CLUSTER, --cluster, KUBE_USER, --user, KUBE_NAMESPACE, --namespace.

**Comment by bgrant0607** [comment]
One more thought: It would be reasonable to create a context bundle, that tied a cluster, uesr, namespace, whatever together. However, the selection of the context bundle should be done via env vars and/or flags.

My typical multi-cluster use case involves opening 2 terminals on the same host logged in as the same user sharing the same repo clone, each dealing with a separate cluster. If a command in one terminal changed the behavior in the other, that would be a problem.

**Comment by smarterclayton** [comment]
Fair - I wouldn't want to take away that flexibility at all.

**Comment by ghodss** [comment]
From what I can tell, my proposal above supports @bgrant0607's assertions. To rephrase:

* \*.kubeconfig files can specify clusters, users, and contexts (a context is a tuple of cluster, user, and (optionally) a default namespace). They can be aggregated together from many locations and don't overwrite each other (unless there is a name conflict, which can be warned about). 
* /etc/kubectl and ~/.kubectl are just ways to persistently set command line parameters, like --context=, --cluster=, --user=, --ns=, --colors, or even --api-version=, --match-server-version=, etc. They are totally decoupled from \*.kubeconfig files. Env vars are another way to persistently set command line parameters.

We also eliminate KUBERNETES_PROVIDER and cluster/kubectl.sh and instead define everything in the above terms.

**Comment by bgrant0607** [comment]
That sounds reasonable to me.

**Comment by jlowdermilk** [comment]
+1 to make .kubeconfig a context bundle and decouple current settings.

**Comment by deads2k** [comment]
> /etc/kubectl and ~/.kubectl are just ways to persistently set command line parameters, like --context=, --cluster=, --user=, --ns=, --colors, or even --api-version=, --match-server-version=, etc. They are totally decoupled from *.kubeconfig files. Env vars are just another way to persistently set command line parameters.

I have a few questions about this file:
 1. Are various .kubectl files merged together or loaded in a highest level wins order?  
 1. Should .kubectl files be built in a generic way that maps them exactly to command line parameters or is it a defined subset?  
 1. Should environment variables be one off overrides or should there be some pattern for describing them?

**Comment by ghodss** [comment]
> I have a few questions about this file:
> 
> Are various .kubectl files merged together or loaded in a highest level wins order?

Merged. It should work similarly to gitconfig or bashrc - you start with /etc/kubectl and merge ~/.kubectl on top. We could also add the ability to provide a custom kubectl through command line param or env var but it should not be a common use case, and certainly tooling should not use that strategy (tooling should just use command line parameters).

> Should .kubectl files be built in a generic way that maps them exactly to command line parameters or is it a defined subset?
> Should environment variables be one off overrides or should there be some pattern for describing them?

We should start with a generic way for both and see how far that gets us. For example, for .kubectl the rule could be to take off the -- from the long param name, and the env var should be KUBECTL_LONG_PARAM_NAME. This should work pretty consistently because of the nature of command line parameters: they have to be fit into a string. But if we run into issues where the generic pattern doesn't make sense, we can make the decision whether to abort doing things generically or to just have a few exceptions.

**Comment by bgrant0607** [comment]
I agree that we should try a generic approach. In my experience, ad hoc mappings create usability and maintainability problems.

**Comment by bgrant0607** [comment]
Do we have any plans to add api version to saved settings? All uses of `-o template` require an API version and relying on a built-in default is dangerous, as we found when we changed it from v1beta1 to v1beta3.
cc @nikhiljindal

**Comment by smarterclayton** [comment]
We would want there to be a way for a client user to do an auto detection dance against the server to populate the value.  I assume it's part of cluster, but there might be a lower subdivision below that so you can talk to two server APIs at different points in their lifecycle (Kube api at v2beta1, Openshift api at v1, resources api at v1beta2?)

**Comment by bgrant0607** [comment]
Autodetection from the server doesn't help if the version doesn't match the version the user expected when writing a template expression.

An alternative would be to allow/require the version to be specified in template uses, as with apiVersion in objects.

**Comment by smarterclayton** [comment]
I meant auto detection the first time they used the cli - that would be before they ever use the cli to output something.

**Comment by jlowdermilk** [comment]
I think we can close this out. #6680 made the kubeconfig loading chain *much* simpler. Default loading behavior sources a single file without merging. Merging is still supported by loading multiple kubeconfig locations specified via envvar.

There was a proposal to separate current-context from kubeconfig, but the current setup actually works quite well, and requiring more than one file would complicate self-contained use cases (e.g. service account kubeconfig for kubelet/kube proxy, kubeconfig secret).

Any objections to closing this?

**Comment by satnam6502** [comment]
Fine by me.

**Comment by smarterclayton** [comment]
SGTM

**Comment by liggitt** [comment]
But then what can I blame for my frustration and anger?

**Comment by smarterclayton** [comment]
Definitely the width of kubectl get pods

**Comment by liggitt** [comment]
Excellent. Feel free to close
