### ISSUE TITLE
hack/test-integration.sh is flaky

### ISSUE THREAD

**Issue by jlowdermilk** [GoogleCloudPlatform/kubernetes#4500]
A significant number of builds fail with the error

```
F0217 20:14:13.799188   16880 integration.go:299] FAILED: pods never started running timed out waiting for the condition
```
If you look at [shippable history](https://app.shippable.com/projects/54c71b655ab6cc135289dd2d), this is the leading cause of flakes (build passes on 1.4, fails on 1.3 or vice versa).

**Comment by dchen1107** [comment]
I am going to look into this one.

**Comment by yujuhong** [comment]
I kept getting emails about shippable failures...

Below is the snippet of the log that includes @dchen1107's new log messages:
```
I0219 01:00:35.995225   17113 integration.go:242] Check whether pod nginx-controller-133ol.test exists on node ""
I0219 01:00:35.995299   17113 integration.go:244] Pod nginx-controller-133ol.test is not bound to a host yet
F0219 01:00:35.995316   17113 integration.go:301] FAILED: pods never started running timed out waiting for the condition
```
The host field of the pod was not assigned and the check failed after 30 seconds of polling. This means either the scheduler *didn't* schedule the pod or it *couldn't* schedule the pods due to, say, conflicts.

The pod in question was from `api/examples/controller.json`
```
  {
    "id": "nginx-controller",
    "apiVersion": "v1beta1",
    "kind": "ReplicationController",
    "desiredState": {
      "replicas": 2,
      "replicaSelector": {"name": "nginx"},
      "podTemplate": {
        "desiredState": {
           "manifest": {
             "version": "v1beta1",
             "id": "nginx-controller",
             "containers": [{
               "name": "nginx",
               "image": "dockerfile/nginx",
               "ports": [{"containerPort": 80, "hostPort": 8080}]
             }]
           }
         },
         "labels": {"name": "nginx"}
        }},
    "labels": {"name": "nginx"}
  }
```
I have a wild guess. Since usually only *one* runtime fails (1.3 or 1.4), could it have been port conflicts (hostPort: 8080) that failed the tests?

**Comment by roberthbailey** [comment]
Is this still a problem? Or can we close this issue now?

**Comment by yujuhong** [comment]
Some bugs were discovered and fixed, but in general, timeouts are still a problem in integration tests.

We can close this one though because there are other issue (#6651) tracking problems like this. #6651 is currently blocked on a reflector benchmark to stress test the watch performance.
