### ISSUE TITLE
Rename `.kube/.kubeconfig` to `.kube/kubeconfig` or `.kube/config`

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#4615]
By analogy to `.git/config`.

I expect a config directory to be hidden, but not the files inside it.

@dead2k what do you think?

**Comment by lavalamp** [comment]
+1

**Comment by yujuhong** [comment]
cc @deads2k

**Comment by thockin** [comment]
+1

**Comment by deads2k** [comment]
.kube/config sounds fine to me.  How would you like to handle the transition?  If we keep merging, should we attempt to merge files using the old names as well as the new?

**Comment by erictune** [comment]
if both .kube/.kubeconfig and .kube/config are present, it is a fatal error.
if .kube/.kubeconfig is present, then move it to .kube/config and notify
the user if practical

**Comment by fabianofranz** [comment]
Just to clarify, is that a proposal for renaming the config files support in *both* home and current directories, or just the one in home?

```
~/.kube/.kubeconfig   ->    ~/.kube/config 
./.kubeconfig         ->    ./.kube/config
``` 
+1 for both

**Comment by smarterclayton** [comment]
Why not `.config/kubernetes`?  Of course, only half the programs in Linux follow that convention...

**Comment by erictune** [comment]
I don't care what it is called.  I just want:
  - a directory to hold various kubernetes files.
  - nothing hidden when I `ls` in that dir
  - bonus points to migrate the old way to the new way
  - bonus points to follow the example of a familar tool such as git, vim, etc.

**Comment by ghodss** [comment]
Considering https://github.com/GoogleCloudPlatform/kubernetes/issues/4428#issuecomment-75426081, can we name our kubeconfig files? It should just be a unique high-level name for the clusters/users/contexts that live in that kubeconfig file. So use ~/.kubeconfig as the directory, and all files inside are parsed and aggregated as kubeconfig files. Those files could just take the convention of name.type, so cluster-name.yaml. A valid kubeconfig dir could look like:

* ~/.kubeconfig/gce.yaml
* ~/.kubeconfig/local.json

We don't care about the file name or type, we just try to parse each file into the kubeconfig format and aggregate everything inside. There are no ordering concerns because kubeconfig files should not have preferences (https://github.com/GoogleCloudPlatform/kubernetes/issues/4428#issuecomment-75124344).
