### ISSUE TITLE
skydns depends on quay.io/coreos/etcd:latest

### ISSUE THREAD

**Issue by alex-mohr** [GoogleCloudPlatform/kubernetes#4743]
The DNS addon has a dependency on a container image "quay.io/coreos/etcd:latest".  That's currently v0.4.6, but will presumably shift to v2.x at some point.

To prevent an incident when that happens, we should launch etcd from a known-good version that's known-compatible with skydns -- not :latest.

**Comment by rsokolowski** [comment]
The easiest thing is to replace latest with v0.4.6, however this version has issues like https://github.com/coreos/etcdctl/issues/109
I've checked with v2.0.0 and DNS works however I've encountered https://github.com/coreos/etcd/issues/2253. 
Since API-server's etcd is being converted to v2.0.3 ( #4442) I'm going to use the same version and just fix the command line to make etcd accessible from outside (etcdctl).

**Comment by dchen1107** [comment]
coreos folks patched etcd 2.0, and built v2.0.3 for us: https://quay.io/repository/coreos/etcd?tag=v2.0.3

**Comment by brendandburns** [comment]
Closing this as we are now locked to 2.0.3
