### ISSUE TITLE
“kubectl update service --patch” is broken in hack/test-cmd.sh

### ISSUE THREAD

**Issue by lhuard1A** [GoogleCloudPlatform/kubernetes#4771]
`hack/test-cmd.sh` contains a list of `kubectl` commands to test.
Those commands are run in a loop of API version.

Among those commands, there is the following one:
```
kubectl update service service-${version}-test --patch="{\"selector\":{\"version\":\"${version}\"},\"apiVersion\":\"${version}\"}"
```
This command is supposed to update the version selector of the service.

The `kubectl get services` command that is just after shows:
```
NAME                   LABELS                                    SELECTOR            IP                  PORT
[…]
service--test          <none>                                    version=old         10.0.0.96           80
service-v1beta1-test   <none>                                    version=v1beta1     10.0.0.254          80
service-v1beta2-test   <none>                                    version=v1beta2     10.0.0.147          80
service-v1beta3-test   <none>                                    version=old         10.0.0.58           80

```

The `version=old` on the first and last lines indicate that the update failed.

**Comment by mikedanese** [comment]
I can look at this.

**Comment by mikedanese** [comment]
For the case where ${version}="" the patch is `'{"selector":{"version":""},"apiVersion":""}'` which is invalid as there is no apiversion.

For the case where ${version}="v1beta3" the patch is `'{"selector":{"version":"v1beta3"},"apiVersion":"v1beta3"}'` which is a valid patch but `.selector` has been moved to `.spec.selector`, so it doesn't actually change the service object.

Test is fixed with attached PR.

The error for the first is easily caught by validating a patch has an api version. The second is less easy as json.Unmarshal() doesn't error when there are fields in the json that are not present in the struct.

The test is fixed by treating the patch json how we treat the service json: keep the apiVersion invariant over the loops so we don't have to worry about changes in the api schema.
