### ISSUE TITLE
Add e2e test for etcd failures handling

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#4783]
We ran into a lot of issues when etcd crashes. We need tests to ensure all components / daemons are doing the right things etcd is down, and recover later.

**Comment by zmerlynn** [comment]
Note that, like the existing `services.sh` test, this is a case of a system level that probably can't be parallelized very easily. (Though rolling over etcd while running other tests is a perfectly fine chaos-monkey style test, but it's not very controlled.)

cc @ixdy

**Comment by alex-mohr** [comment]
As context, this came up at the conference last week.  In particular, if etcd crashes or goes unavailable, then recovers, it was reported that some cluster components do not recover gracefully.

**Comment by quinton-hoole** [comment]
We're still looking for a volunteer for this. Any takers?
cc: @marekbiskup who might be interested.

**Comment by quinton-hoole** [comment]
@marekbiskup has accepted

**Comment by marekbiskup** [comment]
I discussed the test scenario with @lavalamp. We came up with the following:

1. set up a few pods, so that the system has something to do.
1. wait a bit, so that they are initialized
3. set up 100 watches on the API server (to simulate a large system)
  * if possible, use NewEndpointController (from endpoints_controller.go - which is supposed to be used by all controllers) to simulate real clients. This EndpointController will automatically restart watches. It's interesting to see what happens at the API server when all watches are restarted at the very same time.
4. kill etcd (ssh onto the machine)
5. wait bit (?)
6. create new pods (maybe don't wait, just retry on error)
7. wait to see that they are scheduled (we check here only that the scheduler still works).
  * It makes no sense to test everything after etcd is restarted because we would end up repeating all tests. We will just use the fact that tests are run in random order so we hope next tests will find components that didn't recover properly after etcd crashes (or rather after their watches having been terminated).
8. finish the test

**Comment by quinton-hoole** [comment]
May I suggest a perhaps simpler first step, which does most of the above with minimal effort...

- Clone an existing e2e test (guestbook and rc are good candidates)
- Tweak it slightly such that:
  -- At the point where success would usually be declared, instead of declaring success, ssh into the etcd machine and render etcd temporarily uncontactable (more on how to do that below).
  -- Now kill all of the Pods in the application (with appropriate retries).  We now rely on the replication controller to recover and reconstitute the test application. 
-- check that the test eventually fulfills success criteria again.

I think that the above will be super-simple to get working.

Once that is working, you can do the same thing for a much larger scale test (e.g. one of the scalability e2e tests.

**Comment by quinton-hoole** [comment]
Oh, and regarding how to make etcd uncontactable for a while, two suggestions:

1. ssh into the node (use the new ssh utility in test/e2e/utils) and schedule a simple cron job to insert an iptables DROP rule to block all incoming traffic to etcd, sleep for a while (I think it will have to be >5 minutes to trigger stuff), and then remove the iptables rule to allow traffic to flow again.

alternatively:

2. ssh into the node and schedule a cron job to repeatedly kill the etcd process for ~5 minutes, and then stop killing it, allowing monit to restart it automatically.

**Comment by lavalamp** [comment]
@marekbiskup I think your step 1/2 is not really necessary-- there are pods running in the cluster by default.

@quinton-hoole black holeing traffic to etcd seems like a good thing to try too, but I think we should also test killing/restarting it.

**Comment by quinton-hoole** [comment]
@lavalamp, agreed.  Change "alternatively" to "in addition" above :-)

**Comment by marekbiskup** [comment]
Ok, how about the guestbook test, with just killing etcd *before* creating all the objects (maybe several times during 5 minutes). 

Then I'll add more complicated scenarios.

I suggest being careful about modifying the environment (like iptables or cron). If the test crashes in the middle, all following tests will fail.

Do we have a cleanup/healthcheck executed procedure before each test? I could insert resetting iptables (or cron) there. (If not, shall we create it?)

**Comment by quinton-hoole** [comment]
Yes, just killing etcd before the test will also work.

Regarding modifying, yes, that's why I suggested cron (on the etcd machine), so that the cleanup will happen even if the test code itself fails.  I think that's good enough.

**Comment by timothysc** [comment]
fwiw we regularly do this, but have chosen not to make it an e2e due to sec-keys and our etcd cluster resides on a different loc from our master.  We could use etcd-discovery service to make it more dynamic, but we would still have the issue of keys.

**Comment by mikedanese** [comment]
Is anyone currently working on this?

**Comment by davidopp** [comment]
I emailed @jszczepkowski earlier today to see if he'd be interested in working on it, but since he'll be out Thu-Fri it would probably be better for you to do it, if you're interested.

**Comment by jszczepkowski** [comment]
@mikedanese please take it as I'm OOO next two days.

**Comment by mikedanese** [comment]
Just submitted PR #9236 to resolve this. I would appreciate review.

**Comment by mikedanese** [comment]
Current e2e tests has two failure cases: network partition and SIGKILL. The network partition runs consistently but the SIGKILL is flaky. I'm investigating further.
