### ISSUE TITLE
Take advantage of Docker ulimit support once it's merged

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#4911]
https://github.com/docker/docker/pull/9437

**Comment by rjnagal** [comment]
We talked about this in summit w/ @thockin and decided to just put a high limit of all containers to start with. I can go ahead and do that if you agree.

**Comment by bgrant0607** [comment]
Could you be more specific? :-)

**Comment by rjnagal** [comment]
specifically: setting number of procs and fds to a high value, so no container fails by hitting inherited docker daemon limit. Longer term, I proposed exposing {low, high, default} to users rather than actual numbers. Not sure if everyone agreed. In the current setup, users are hitting the low limits from docker daemon and not the global resource exhaustion issues.

**Comment by bgrant0607** [comment]
Short-term plan SGTM.

Longer-term approach has predictability problems in the case that low/default/high vary platform-to-platform or release-to-release. I'm happy to defer that discussion to later, though.

**Comment by bgrant0607** [comment]
Dupe of #3595
