### ISSUE TITLE
Proposal: use constant number of GCE TargetPools per cluster

### ISSUE THREAD

**Issue by tkulczynski** [GoogleCloudPlatform/kubernetes#5241]
Currently, there's a Target Pool created per service, but they only potentially differ in affinity type and there's few options available for it. Instead there could be a Target Pool per affinity type created at cluster creation and the right one chosen and reused for each of the services.

I believe this is both easier and more efficient (currently there's O(cluster size) redundant work being done for each service). It would simplify changing the node set dramatically: with the current solution, somebody should update all the existing target pools whenever a new node appears - with the per-cluster Target Pools there are only constant number of them and updating them can be delegated to the Managed Instance Group that controls nodes.

**Comment by roberthbailey** [comment]
@tkulczynski Can you explain the affinity type (it isn't immediately obvious to me why 1 target pool pointed at all nodes wouldn't be suficient)?

Also, what happens if we want to create 2 Managed Instance Groups (with different node types) as part of the cluster? Can we still delegate updating to the Managed instance Groups or do we need a coordinator inside of k8s?

**Comment by tkulczynski** [comment]
That was my intuition too, but there's GCECloud.makeTargetPool method that creates a pool per service and one of the arguments is AffinityType that comes from ServiceSpec.AffinityType. And it's not just an implementation issue: it comes from the fact that target pool holds both the information about where to send the traffic and what affinity to use. While the former is common for all the services, the latter might be one of the three options.

MIG will not take full control over the target pool, it will just add an instance there whenever it creates one and delete it whenever it shuts it down. You can have other instances in the target pool, and so you can also have multiple MIGs that add to the same target pool.

**Comment by alex-mohr** [comment]
FWIW, there was some discussion at the kubernetes conference where it might make sense to keep a targetpool-per-service.

In particular, we might be able to remove the 2 layers of loadbalancing targetpool->kubeproxy->pod if we had a TargetPoolController that watched each service and dynamically programmed it with only the VMs hosting that service's pods.

Note that GCE.HealthChecks can also be associated with GCE.TargetPools, so per-service-Pools would seem necessary for the ones with a service-specific health check?

**Comment by tkulczynski** [comment]
If you do want to attach service-specific HC then I totally agree we should stay with per-service TargetPools. 
Even with that, I still think it's currently easier to let the MIG update TargetPools (all of them, that probably introduces some limit on the number of them in the cluster, but it's hundreds so I don't think an issue for now) instead of manually updating all of them on each node creation/deletion. That's true for TargetPools containing all the nodes. If we'll create ones that have a subset of nodes in the future, I guess we should update them on our own (my guess would be it is endpoints_controller's responsibility).

**Comment by jszczepkowski** [comment]
@alex-mohr @roberthbailey 
I want to start implementing solution described by @tkulczynski in the previous comment (automatic updating target polls for services by MIG). We need it for cluster resize. Are you OK with it?

**Comment by roberthbailey** [comment]
If we only want to allow re-sizing of the cluster by adding nodes to a MIG then that would make sense. What happens down the road when we want to allow you to add a second MIG to your resource pool? Which one updates the TargetPools? Both of them? What happens when we want to support bring-your-own-node? Some of them won't be part of a MIG, but we still want them to be part of the TargetPool.

It seems like making the master (which knows the full set of nodes in the cluster, whether they come from a MIG or not) is in the best position to keep the TargetPool up to date.

**Comment by zmerlynn** [comment]
I'm actually with Robby here. I'm happy to use MIG for all it gets us:
scaling of a template, possibly health checks, etc, but at the end of the
day, the k8s master is the shepherd.

**Comment by alex-mohr** [comment]
* I think it's fine to *allow* nodes to be provisioned via MIGs, but not to *require* that all nodes be part of a MIG (users able to bring their own nodes is important)
  * And especially not to require there to be just 1 MIG (we need heterogenous machine types soon too)
* As we add more options to services (e.g. different affinities, different health checks, different other parameters), the number of ServiceGroups grows exponentially.
  * And given that new releases or values (health checks?) can result in the creation of new ServiceGroups, we'd need something that can create those groups dynamically, not just have a fixed set at cluster creation time?
* Meta: It's often easier to have a flat mapping rather than hierarchies, e.g. if I want to change property X on service A, that's easy if it's A.setX(newValue).  Harder if I have to find which of the classes is identical to current class other than differing in the changed X.
* Given the above, efficiency benefits seem short-lived and outweighed by costs.

It seems something like a TargetPoolController (that could also exist in a GCEController) that reconciles the currently observed node set for a pool with the desired node set for a pool would be simpler and tie in better with direction than adding a grouping mechanism?

**Comment by tkulczynski** [comment]
Thanks for your opinions everyone!
I do not fully agree with all the points you've made, but all in all I'm pretty sure now that we shouldn't go for constant number of Target Pools. I'm also somewhat convinced we shouldn't use MIG for adjusting Target Pools (or at least it only makes sense for short term, so might not worth be doing at all).
Let me just clarify that I've not wanted to introduce a *requirement* for a single MIG in a Cluster, and this proposal does not influence that. Things do get complicated in other setups though, especially if you have multiple MIGs *and* some other instances brought by the user. The fact that we want to support instances outside of MIGs as they come and go (effectively: support non-MIG resizes of the cluster) means we'll have that TargetPoolController anyway, in which case it's clearly better to use it for all the instances.
BTW, I think we're marking a line here between k8s master and MIG: would you follow that thinking and agree in general that the master should treat Instances coming from MIG just as all others and simply not care about the "managed" part of GCE? The user, MIG or some other higher-level infrastructure system is then responsible for tending node VMs, which the master uses to form the cluster.

**Comment by alex-mohr** [comment]
Re: simply not care about the "managed" part of GCE, I'm not sure that entirely follows, depending on what you mean by it.  For example, it might be expedient to say that if a user brings their own node, they're responsible for managing its health and repairing it if it's not working, but for nodes that are spun up by the master or its MIG, perhaps we can point the IG's health check at the kubelet's /healthz port, and that means the k8s master doesn't need health checking logic?

Summary of my take (with caveat that I could easily be missing things):
* Should we multiplex N services onto < N TargetPools or use 1 target pool per service?  We should do N:N.
* Do we need to support M different machine types shortly after beta?  Yes, which I think means M MIGs.
* Observation: master components need to respond to new node creation by e.g. giving them a CIDR block, allocating an Advanced Route, and such.
* Can we use MIG health checks to make nodes auto-healing?  Sure. 
* If MIGs can update node lists for target pools while satisfying those requirements above, can we do that instead of having the k8s master do it?  Sure.  My understanding is that it wouldn't, re: multiple MIG pools -- let me know if I have that wrong?

But I also don't want perfect to be the enemy of the good.  I don't understand the details here amazingly well -- and there could be gotchas in having k8s master update target pool contents over time.  From far away, though, it seems we need a TargetPoolReconciler that creates them when they don't exist but should, deletes them when they do exist but shouldn't, and updates them when they need to change.

**Comment by roberthbailey** [comment]
Yes, the master should treat any instances that try to join the cluster in a uniform way, whether or not they are part of a MIG. The user may want a MIG to autoscale one tier of their service based on load (e.g. front end serving) but manually scale another tier (e.g. databases that require more manual replication configuration). 

Also see #6087 and #3168.

**Comment by jszczepkowski** [comment]
You comments indicates that my initial idea, to automatically update target pools by MIG is not correct.

Therefore, I'm implementing updating target pools for external services from NodeController, whenever set of cloud nodes is changed. This is more general solution.

**Comment by thockin** [comment]
I came to this discussion from having the same thought - less pools.  Then I talked myself out of it for the same reasons.

Can we close this?

**Comment by jszczepkowski** [comment]
Updating target pools on change of nodes in cluster is done. Closing this.
