### ISSUE TITLE
Event failed to update

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#5327]
Seen in integration test output:

```
E0311 14:09:25.955280   99741 event.go:127] Unable to write event '&api.Event{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"127.0.0.1.13ca8dd23271fd55", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", CreationTimestamp:util.Time{Time:time.Time{sec:0, nsec:0x0, loc:(*time.Location)(nil)}}, Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Minion", Namespace:"default", Name:"127.0.0.1", UID:"127.0.0.1", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"starting", Message:"Starting kubelet.", Source:api.EventSource{Component:"kubelet", Host:"127.0.0.1"}, FirstTimestamp:util.Time{Time:time.Time{sec:63561704965, nsec:0x38560b55, loc:(*time.Location)(0x12138e0)}}, LastTimestamp:util.Time{Time:time.Time{sec:63561704965, nsec:0x38560b55, loc:(*time.Location)(0x12138e0)}}, Count:1}': 'events "127.0.0.1.13ca8dd23271fd55" already exists' (will not retry!)
```

**Comment by erictune** [comment]
@saad-ali

**Comment by erictune** [comment]
We talked about this and thought it was suspicious.

**Comment by saad-ali** [comment]
There is a race condition in ```pkg/client/record/event.go```. If the same event is created in rapid succession it is possible that ```ResourceVersion``` used to update one of the events becomes out-of-date.

**Comment by saad-ali** [comment]
The integration test error  is not caused by the race condition I mentioned above (I'll create a separate issue to track that).

This error, `events ... already exists`, indicates that an event with the same key already exists in etcd.

It happens because etcd is called two times to create the same exact event. This happens because the integration test [creates two kubelet instances](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/integration/integration.go#L223) (on two different ports), however the setup process creates two different event listeners that listen to the [same event channel](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/record/event.go#L167). Thus, when an event is generated by either instance of kubelet, it is passed through the shared channel, and is [consumed by both instances of kubelet](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/record/event.go#L149), both of which [issue calls to the API server to create the same exact event](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/record/event.go#L73) in rapid succession (which ever call arrives first, succeeds, and the subsequent call fails with this error).

Proposed fix:
* Create a new `watch.NewBroadcaster` on each [`StartRecording(...)`](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/record/event.go#L53) call.
* Have [`SetupEventSending(...)`](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/util.go#L39) return the `watch`
* Modify event recorder `recorderImpl` to store the `watch`.
* Then when `recorder.Eventf(...)` is called it only triggers it's own watcher.
* Will also need to fix tests relying on `record.GetEvents(...)`.
