### ISSUE TITLE
Documentation adding user

### ISSUE THREAD

**Issue by erikthorselius** [GoogleCloudPlatform/kubernetes#5489]
Hi, I can't find any documentation how I add more admin users so my team members can deploy pods.

**Comment by a-robinson** [comment]
@erictune @jlowdermilk  Is there a functioning concept of different user types yet or is the answer here just passing around kubeconfig files?

**Comment by brendandburns** [comment]
For now, the answer is to pass around kubeconfig files.  There are better
answers coming sometime, but afaik, not yet.

--brendan

**Comment by jlowdermilk** [comment]
Yep. AFAIK, the apiserver doesn't yet support multiple user credentials, so if you want to grant others access to a cluster, they'll need to share credentials (stored in kubeconfig file).

**Comment by a-robinson** [comment]
Ok, and we do have a doc on [kubeconfig files](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/kubeconfig-file.md), but unless I'm mistaken, it appears to be more targeted at developers rather than users and doesn't talk about how to find the file to copy it between machines, or where to put it when you do so.

And how is a new user supposed to find that documentation if they don't know that the file is called kubeconfig?

**Comment by jlowdermilk** [comment]
I'm happy to add a short doc describing how to share/copy kubeconfig files for cluster access. Does `docs/sharing-clusters.md` sound sufficiently discoverable?

**Comment by erikthorselius** [comment]
Thanks for all the answers. A doc in `docs/sharing-cluster.md` is fine for me.
