### ISSUE TITLE
kubectl(release 0.11.0) create pods always failed with 255 return code

### ISSUE THREAD

**Issue by HackToday** [GoogleCloudPlatform/kubernetes#5590]
I used kubenetes examples, redis-master as  below:
id: redis-master
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    id: redis-master
    containers:
      - name: master
        image: kubernetes/redis:v1
        cpu: 1000
        ports:
          - name: api
            containerPort: 6379
        volumeMounts:
          - name: data
            mountPath: /redis-master-data
        env:
          - key: MASTER
            value: "true"
      - name: sentinel
        image: kubernetes/redis:v1
        ports:
          - name: api
            containerPort: 26379
        env:
          - key: SENTINEL
            value: "true"
    volumes:
      - name: data
        source:
          emptyDir: {}
labels:
  name: redis
  role: master
  redis-sentinel: "true"

But I always found it failed with 

F0318 10:19:37.871436    4576 create.go:81] 

I checked echo $?
it is 255.

**Comment by HackToday** [comment]
I used 0.7.0 release, the kubectl can work.

**Comment by brendandburns** [comment]
What does kubectl version report?

**Comment by HackToday** [comment]
Hi @brendandburns , since my env is I have one kubernetes cluster setup before. In another machine, I installed the latest 0.11.0 to use its cli: kubectl to call remote kubernetes cluster. Info as below:

[fedora@kqcontainer ~]$ kubectl version  -s http://192.168.1.231:8080
Client Version: version.Info{Major:"0", Minor:"11+", GitVersion:"v0.11.0-dirty", GitCommit:"18ddff0eb6bc069b41832ce47d19b5b89cfb26e3", GitTreeState:"dirty"}
Server Version: version.Info{Major:"0", Minor:"6+", GitVersion:"v0.6.0-4-g993ef88eec9012-dirty", GitCommit:"993ef88eec9012b221f79abe8f2932ee97997d28", GitTreeState:"dirty"}

**Comment by brendandburns** [comment]
That's a super old server version (0.6.0)

What instructions are you using for set up?

I'd recommend upgrading your server binaries...

Brendan

**Comment by HackToday** [comment]
Hi @brendandburns  
1) I am not sure why we not support that case ?


2) if I have a know cluster, how to upgrade smoothly without break anything?

**Comment by HackToday** [comment]
if upgrade is inevitable, what would I do for such upgrade ? Do you have guide for such case ?

**Comment by brendandburns** [comment]
Kai,
In theory it should work.  However there have been lots of changes between
0.6 and head that are probably why its not working.  It would be useful to
see the error that the server is sending back to understand what isn't
working properly.

Upgrade isn't really very well supported right now.  Its one of the
requirements for our 1.0 release, but upgrading from 0.6 to a more recrent
release is going to be tough.  I'd definitely practice it on a scratch
cluster first, if you wanted to go that route.

However, you're probably better off just turning up a new cluster and
migrating your workload, rather than trying to upgrade your cluster, its
bound to be far easier.

Sorry about the trouble.  These types of scenarios are sort of the
definition of an alpha/beta release.  We're addressing them as part of the
push to 1.0.

Please let us know if we can help further.

Best
Brendan

**Comment by HackToday** [comment]
hi @brendandburns  thanks for your info.

I am interesting with 2 things,

1) how to check server errors ? what's the log location?

2) If you talked about migrate workload, I am not sure what's the proper way to do that ? I am not familiar with that.  Any link or guide would be helpful.

**Comment by brendandburns** [comment]
Closing this as obsolete...
