### ISSUE TITLE
Create e2e test that will test external load balancer

### ISSUE THREAD

**Issue by piosz** [GoogleCloudPlatform/kubernetes#5604]
Follow up from #5268

**Comment by roberthbailey** [comment]
Bumping this up to P1 given that 0.12.2 wasn't able to create a service with an external load balancer and we didn't notice before cutting the release.

**Comment by zmerlynn** [comment]
@roberthbailey: No, to be clearer, 0.12.2 wasn't able to create a service with ELB on *GKE*. That was on our side entirely.

**Comment by zmerlynn** [comment]
But it doesn't invalidate the need for this.

**Comment by piosz** [comment]
The guestbook.sh example is using ELB.

**Comment by a-robinson** [comment]
@piosz are you actively working on this? If not, I'd be up for doing it today.

**Comment by piosz** [comment]
Maybe not actively but I know what to, however I won't be able to finish it today, so if you think you can do it today please move forward.

**Comment by roberthbailey** [comment]
@zmerlynn We run the e2e tests on GKE, so if we had a test for creating an ELB we would have known that the 0.12.2 release wouldn't work on GKE. I don't see how your point applies. The e2e tests are in place so that we don't have to test each feature manually to verify that it is working, and we only found out that this feature was broken on GKE after we pushed 0.12.2, hence the need for an e2e test.

**Comment by mbforbes** [comment]
> But it doesn't invalidate the need for this.

@roberthbailey I think @zmerlynn and you are in fact in agreement

**Comment by jayunit100** [comment]
right now, k8petstore tests the external load balancer by curling down the amount of transactions ingested from the REST API.  im playing with porting it as a e2e test now.    The code in the shell script is a little raw, but you can see that it specifies a PUBLIC_IP and then curls down from it at the end (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/k8petstore/k8petstore.sh).

**Comment by roberthbailey** [comment]
@jayunit100 that sounds great. What I'd really like to see here though (and what @piosz is going to do early next week) is a very simple test that isolates creating a service with an ELB to verify that creating a load balancer works in isolation from a complex test of other parts of the system. This will give us a really clear signal when the test starts to fail instead of needing to debug lots of moving parts when we see a test failure.
