### ISSUE TITLE
Check protocol of port defined in service and pod

### ISSUE THREAD

**Issue by hurf** [GoogleCloudPlatform/kubernetes#5895]
I created a service with following template

	id: webserver
	kind: Service
	apiVersion: v1beta1
	protocol: UDP
	port: 8888
	containerPort: testport

But in the in pod behind the service the port is defined using TCP protocol 

 	ports:
      - name: testport
        protocol: TCP
        containerPort: 80

I think it should throw an exception rather than allow the service to be created. Though currently the proxy support only TCP protocol.

**Comment by thockin** [comment]
The proxy supports both TCP and UDP (it runs DNS, which is UDP).

Making the service not match the pods is an error, but very hard to catch
statically because the pods that back a service can change dynamically.  We
do not intend to do protocol conversion.

This basically leaves the option of logging when a pod's named port doesn't
match a Service, which probably slips through today.

We'll need to decide if it is allowed to have the same name on two ports of
different protocols.  I'm in that code right now, so I will think about
this issue.

**Comment by hurf** [comment]
Can we just compare the protocol section of the two ports and if not match then throw an exception?

I saw in pkg/service/endpoints_controller.go line 211 it verified the name, can we just add an comparison of protocol?

**Comment by thockin** [comment]
Yeah, but I am pretty much rewriting all of this code to support multiple
ports.  If it is easy I will just add it in.  If not, this bug will serve
as a reminder :)
