### ISSUE TITLE
Unnecessary killing of the pod infra container.

### ISSUE THREAD

**Issue by yifan-gu** [GoogleCloudPlatform/kubernetes#5896]
Currently, we evaluate whether the `pod infra container` should be killed by computing each container's hash and compare them with the running container's hash. If any of them has changed, then we mark the `pod infra container` to be killed.

Instead, how about just comparing the expecting pod infra container's hash with the running one's? If nothing has changed, then we don't need to bother with the `pod infra container`. If the hash does have changed, then we restart it before in ahead. 

By doing this, I think we can simplify the kubelet's syncPod loop a lot. And also this can make it easier to migrate to new container runtimer interface (e.g. We can let `RunContainerInPod` to test and compare the hash).

Hope to hear from your opinions:) Or questions? Thank you!

@dchen1107 @vmarmol

**Comment by vmarmol** [comment]
We should only need to restart the pod infra container with network-related changes since those would need for it to restart. Today we don't have the logic in place to only recognize these changes so we're conservative by default and restart on *any* change. We can certainly improve this.

Marking as P2 since I think we can live with the current behavior. @dchen1107 let me know if you disagree :)

**Comment by yifan-gu** [comment]
@vmarmol Agree! So I think by comparing the hash of the `pod infra container` is enough to recognize the network-related changes. I'm willing to start work on this if you don't have objections :)

**Comment by vmarmol** [comment]
@yifan-gu it's a bit harder than that sadly because the network information is spread across the containers. The pod infra container does not have an api.Container object for itself.  I think the approach we need to take is to identify a class of fields in api.Container that are relevant to the pod infra container and then see if any of those changed.

From looking at api.Container, it looks like Ports is the only field that affects it. Doesn't sound so bad after all :) If you're still interested, we'd be happy to have you tackle it and I can assign you the issue.

**Comment by dchen1107** [comment]
We have one pod infra container per Pod, which does porting mapping for all user containers. One could do is having a sorted list of ports coming in PodSpec, and comparing it the existing port mapping list to decide if we need to kill pod infra container.

It is P2 indeed.

**Comment by yifan-gu** [comment]
@vmarmol Yes. But I think since we have the `*api.Pod` as input for syncPod, so we can create the expected `api.Container` for the pod infra container, then we are able to compare the hash, or compare the port mappings as @dchen1107 suggested.

I am happy to tackle with this :)

**Comment by vmarmol** [comment]
SGTM @yifan-gu

**Comment by yifan-gu** [comment]
Fixed by #6608
