### ISSUE TITLE
Error when trying to create service with createExternalLoadBalancer field

### ISSUE THREAD

**Issue by roman-shuhov** [GoogleCloudPlatform/kubernetes#5920]
This issue only appears in google cloud. When i try to add guestbook service from the example https://cloud.google.com/container-engine/docs/guestbook

```
{
  "apiVersion": "v1beta1",
  "kind": "Service",
  "id": "guestbook",
  "port": 3000,
  "containerPort": "http-server",
  "selector": { "name": "guestbook" },
  "createExternalLoadBalancer": true
}
```

I got error 

```
reate.go:83] googleapi: Error 400: Invalid value for field 'resource.name': '-guestbook'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)
```

if i remove this field, command executes without errors

**Comment by roman-shuhov** [comment]
is it possible to fix in any way? Any workarounds?

**Comment by quinton-hoole** [comment]
What version of kubernetes are you running?

**Comment by roman-shuhov** [comment]
v0.12.2

**Comment by roberthbailey** [comment]
Unfortunately that is a known issue with 0.12.2 on GKE that we found
shortly after making it available. We've since pulled that release from GKE
but clusters that are still running it won't be able to create external
load balancers.

Your best bet is to create a new cluster (the default is now 0.13.2) which
has this bug fixed.

Sorry for the trouble.

Robby

**Comment by piosz** [comment]
Won't be fixed (unfortunately).

**Comment by roman-shuhov** [comment]
just fyi, looks like it's not possible to choose kubernetes version for the container cluster and by default it installs 0.12.2 version. i also created question http://serverfault.com/questions/678498/create-google-container-cluster-with-custom-kubernetes-version

**Comment by zmerlynn** [comment]
You can choose the cluster version on the command line with
--cluster-api-version:

https://cloud.google.com/sdk/gcloud/reference/preview/container/clusters/create

We have a downlevel version available (usually). Also, 0.13.2 is default as
of yesterday afternoon, and because of this issue, 0.11.0 remains our
downlevel version.

**Comment by roman-shuhov** [comment]
great, thanks!
