### ISSUE TITLE
Master upgrades

### ISSUE THREAD

**Issue by mbforbes** [GoogleCloudPlatform/kubernetes#6075]
This is the worklist item for a minimum viable master upgrade mechanism for 1.0. Other issues will improve upon the feature spec'd here.

### Minimum requirements:
- provider: **G*E**
- in-place: **no** (can request new node / disk)
- language: **bash**

### Plan:
- mechanism: **out-of-band** (not on master)
- provider: **GCE, then GKE**

### Outline:
0. Stop master VM
0. Blow away boot PD but preserve data PD
0. Create a new boot PD from latest image
0. Update metadata startup script
0. Attach boot PD to master VM
0. Start master VM

[May want to re-order to minimize downtime for VM?]

### Extensions:
- _Here we'll add issues that, while not required to meet the minimum 1.0 bar, would be great to have._

@zmerlynn please edit this as the requirements / plan / outline change

### Related work
- #2524 Full cluster upgrade discussion
- #3174 Looked at requirements for master upgrades (GCE)
- #4175 Put master data on a PD and reserved the master's IP (GCE)
- #4855 Full cluster upgrade discussion for 1.0; clarifies versioning
- #5472 Proposal for `kubedeploy`
- #6079 Node upgrades roll-up

**Comment by mbforbes** [comment]
+cc @dchen1107 @davidopp @lavalamp @erictune @zmerlynn @alex-mohr

**Comment by alex-mohr** [comment]
Thanks Max.  Re: outline, may want to re-order actual implementation to minimize downtime?  E.g. create new boot PD first in case it fails or takes a long time.  Then stop VM, swap PD refs, update metadata, restart VM, and only then delete old PD?

And this might be too much complication, but it may also be worth having a rollback plan, e.g. if master doesn't come up or respond, stop it and switch back to the known-good old PD?

**Comment by zmerlynn** [comment]
We'll call those "refinements" :)

**Comment by JeanMertz** [comment]
wrt cluster-upgrades. It would be nice if Kubernetes supports clustering of the master nodes. We currently have three "manager" nodes running on CoreOS with their primary focus being running a HA Etcd cluster. Besides those three, we also have a scalable number of "worker" nodes.

Since Etcd (preferably) requires a cluster of three nodes anyway, and Kubernetes uses Etcd, it would be nice to be able to use the other Etcd nodes as Kubernetes master nodes as well.

This way, upgrading becomes a lot easier, with zero-downtime as well. You simply swap out each master node one-by-one, and data gets replicated across the masters as soon as a new master joins the cluster.

Currently, we have Kubernetes master running on all three manager nodes (because it simplifies our setup where all manager nodes are 100% equal, and all worker nodes as well), but the workers only connect to the first one, due to the current single-master limitation.

**Comment by davidopp** [comment]
We are planning to do master clustering soon after 1.0. There are several steps to this -- running multiple etcd replicas, running controller manager and scheduler in warm standby configuration, and running multiple API server replicas. I agree that this will make master upgrade somewhat more complicated.

Some relevant issues and docs are  #6559, #8295, and
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/proposals/high-availability.md

Longer-term we are planning to make the master components be self-hosting so we can use regular Kubernetes rolling upgrade mechanisms to upgrade the master components.

**Comment by pires** [comment]
@davidopp awesome! /cc @josephjacks

**Comment by davidopp** [comment]
@zmerlynn @roberthbailey is there any additional work for this for 1.0 (other than #8151, which is almost done)? If not, I'll close this.

**Comment by alex-mohr** [comment]
I think https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/upgrade.sh meets this one for GCE and thus is post-v1 or closable?

It'd be nice if someone'd do an equivalent for AWS, for example.  @justinsb might be interested, but probably busy with other things?  Someone else?

**Comment by zmerlynn** [comment]
I think we're done here for GCE, yeah - except for testing.

**Comment by alex-mohr** [comment]
@zmerlynn does #8081 capture the testing we want?  if so, please close, else please file a bug that captures?

**Comment by zmerlynn** [comment]
Closing, since #8081 encompasses testing.
