### ISSUE TITLE
Need reconciliation loop for node schedulable

### ISSUE THREAD

**Issue by ddysher** [GoogleCloudPlatform/kubernetes#6077]
Node controller stops posting node status, which means it also stops posting node schedulable bits.  What this implies is that when user mark a node unscheduable, it will never work, scheduler will still schedule pods on it, because node status is not updated by node controller anymore.

We need to merge status from node controller and kubelet.  node controller still syncs node, only if its observed status changed.

This is somehow similar to #6072

**Comment by ddysher** [comment]
@davidopp @bgrant0607 @gmarek

**Comment by davidopp** [comment]
Shouldn't the scheduler be using the Unschedulable bit in NodeSpec to decide whether a node is eligible for scheduling, rather than using NodeSchedulable condition?

(BTW @bgrant0607 had suggested in another thread that "NodeSchedulable should really be an ACK that Kubelet saw the spec bit" which I interpret to mean Kubelet should be posting NodeSchedulable, which would fix this problem. But I still think the scheduler should be looking at the spec, not the status, for unschedulable.)

**Comment by ddysher** [comment]
We can also post the condition from kubelet BTW

**Comment by ddysher** [comment]
Right, I the fix should be kubelet posting schedulable condition.  We've also discussed somewhere that node controller can merge the conditions.

Having scheduler looks at just status makes more sense to me. It provides a uniform view of node status to action on.

**Comment by davidopp** [comment]
I think the scheduler should use the Schedulable value in NodeSpec, not the one in NodeStatus. Why do we care whether the node thinks it can be scheduled on?

**Comment by bgrant0607** [comment]
The reasons for NodeSchedulable were:
1. To represent an ACK from Kubelet, since it's the last line of defense.
2. To enable clients to just look at NodeStatus and not look at NodeSpec when determining properties they need to reason about, such as schedulability.

I'm fine with eliminating the NodeSchedulable condition in NodeStatus, at least for now.
