### ISSUE TITLE
CoreOS_Standalone: Redis-slave can't resolve redis-master:6379 in guestbook example

### ISSUE THREAD

**Issue by gosharplite** [GoogleCloudPlatform/kubernetes#6158]
I was in step three of the guestbook example. Redis-slave containers are running fine, except they can't connect to redis-master.

Controller, pod, service and docker containers are all in place. The trouble is from the output of ``docker logs <CONTAINER ID>``.
```
core@standalone ~ $ kubectl get rc
CONTROLLER          CONTAINER(S)        IMAGE(S)                    SELECTOR            REPLICAS
redis-master        master              dockerfile/redis            name=redis-master   1
redis-slave         slave               kubernetes/redis-slave:v2   name=redis-slave    2
```
```
core@standalone ~ $ kubectl get po
POD                  IP                  CONTAINER(S)        IMAGE(S)                    HOST                  LABELS              STATUS              CREATED
redis-master-gziey   10.244.6.3          master              dockerfile/redis            127.0.0.1/127.0.0.1   name=redis-master   Running             30 minutes
redis-slave-0133o    10.244.6.5          slave               kubernetes/redis-slave:v2   127.0.0.1/127.0.0.1   name=redis-slave    Running             21 minutes
redis-slave-oh43e    10.244.6.4          slave               kubernetes/redis-slave:v2   127.0.0.1/127.0.0.1   name=redis-slave    Running             21 minutes
```
```
core@standalone ~ $ kubectl get se
NAME                LABELS                                    SELECTOR            IP                  PORT
kubernetes          component=apiserver,provider=kubernetes   <none>              10.100.0.2          443
kubernetes-ro       component=apiserver,provider=kubernetes   <none>              10.100.0.1          80
redis-master        name=redis-master                         name=redis-master   10.100.102.114      6379
```
```
core@standalone ~ $ docker ps
CONTAINER ID        IMAGE                       COMMAND                CREATED             STATUS              PORTS               NAMES
2fb15939e1d5        kubernetes/redis-slave:v2   "/bin/sh -c /run.sh"   19 minutes ago      Up 19 minutes                           k8s_slave.440cfb35_redis-slave-0133o_default_ee95b721-d6e0-11e4-9bbb-fa163e5031a3_40b1a38c     
05a8570f43c1        kubernetes/redis-slave:v2   "/bin/sh -c /run.sh"   19 minutes ago      Up 19 minutes                           k8s_slave.440cfb35_redis-slave-oh43e_default_ee957029-d6e0-11e4-9bbb-fa163e5031a3_bcd95eaf     
1d3fbb6156b3        kubernetes/pause:go         "/pause"               23 minutes ago      Up 23 minutes                           k8s_POD.1b73ed2a_redis-slave-0133o_default_ee95b721-d6e0-11e4-9bbb-fa163e5031a3_8bd46732       
15b031834e3f        kubernetes/pause:go         "/pause"               23 minutes ago      Up 23 minutes                           k8s_POD.1b73ed2a_redis-slave-oh43e_default_ee957029-d6e0-11e4-9bbb-fa163e5031a3_22c28294       
8e1ed51d76c9        dockerfile/redis:latest     "redis-server /etc/r   28 minutes ago      Up 28 minutes                           k8s_master.9008f85c_redis-master-gziey_default_a8f24fd4-d6df-11e4-9bbb-fa163e5031a3_a81c7686   
9dd327a2faa4        kubernetes/pause:go         "/pause"               32 minutes ago      Up 32 minutes                           k8s_POD.1b73ed2a_redis-master-gziey_default_a8f24fd4-d6df-11e4-9bbb-fa163e5031a3_ee0cf31b      
```
```
core@standalone ~ $ docker logs 2fb15939e1d5
[11] 30 Mar 13:55:46.747 * Connecting to MASTER redis-master:6379
[11] 30 Mar 13:55:46.861 # Unable to connect to MASTER: No such file or directory
```
I have read below issues, still can't figure out what's wrong.
#1233 Guestbook Example: redis-slave containers can't resolve redis-master service hostname
#1279 No DNS in vagrant cross minions, need explicit IP as host
#5747 ubuntu_cluster: Can't dermine redis-master's ip in guestbook example

CoreOS: 633.1.0
kubernetes: v0.13.2
OpenStack: Juno

**Comment by gosharplite** [comment]
@AntonioMeireles Appreciate if you can provide some hint and direction on this issue #6158.

**Comment by gosharplite** [comment]
There are two possible solutions.
One way is to modify redis-slave docker image to use environment variable for redis-master service. 
```
core@standalone ~ $ docker inspect 05a8570f43c1 | grep REDIS_MASTER_
            "REDIS_MASTER_SERVICE_HOST=10.100.102.114",
            "REDIS_MASTER_SERVICE_PORT=6379",
            "REDIS_MASTER_PORT_6379_TCP=tcp://10.100.102.114:6379",
            "REDIS_MASTER_PORT_6379_TCP_PROTO=tcp",
            "REDIS_MASTER_PORT_6379_TCP_PORT=6379",
            "REDIS_MASTER_PORT_6379_TCP_ADDR=10.100.102.114",
            "REDIS_MASTER_PORT=tcp://10.100.102.114:6379",
```
The other way is to use k8s cluster add-on "DNS server". It will resolve redis-master to virtual service ip.

**Comment by pebo** [comment]
I get the same problem when following the coreos aws (cloudformation) setup (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/aws/cloudformation-template.json)

CoreOS: 681.0.0
kubernetes: v0.17

Does the getting started / guestbook docs mention setting up DNS?

**Comment by gosharplite** [comment]
Not sure about aws, since I use openstack. Below links might help you on setting up DNS in kubernetes.
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/dns/README.md
https://github.com/pires/kubernetes-vagrant-coreos-cluster/tree/master/dns
https://groups.google.com/forum/#!topic/google-containers/XAejyzqcwRg

**Comment by kcao3** [comment]
I have the same problem as @gosharplite and @pebo did. If I am not mistaken, the root cause of this
problem is that the two Redis-slave containers are running but not able to connect to the Redis-master
because they cannot find IP address for the Redis-master host: redis-master. Given 7ac2b07bea5a
and 23aed8bb7882 are the IDs of my two redis-slave containers, their logs show the exact 
error as @gosharplite reported:

docker logs 7ac2b07bea5a
....
[10] 19 May 15:57:20.913 # Unable to connect to MASTER: No such file or directory
[10] 19 May 15:57:21.915 * Connecting to MASTER redis-master:6379
[10] 19 May 15:57:21.916 # Unable to connect to MASTER: No such file or directory
[10] 19 May 15:57:22.926 * Connecting to MASTER redis-master:6379

docker logs 23aed8bb7882
....
[10] 19 May 15:57:23.930 # Unable to connect to MASTER: No such file or directory
[10] 19 May 15:57:24.933 * Connecting to MASTER redis-master:6379
[10] 19 May 15:57:24.933 # Unable to connect to MASTER: No such file or directory
[10] 19 May 15:57:25.936 * Connecting to MASTER redis-master:6379

So, before following option #2 suggested by @gosharplite: setting up DNS server to be used by the Kubernetes cluster, I have done some quick "hacking" to test if indeed resolving the Redis-master host from the two Redis slaves would fix the problem. To do so, I "went inside" these two redis-slave containers by running this command: docker exec -i -t <redis-slave_container_id> bash. Once inside these containers, I modify the /etc/hosts files to add a new entry. The following shows the content of the /etc/hosts file of one of my redis-slave container. Note that 10.244.48.2 is the IP address of my redis-master container.
...
10.244.48.2     redis-master
...
Once I updated the two /etc/hosts files, it seems to me that the two redis-slave containers were able
to connect to the redis-master. The following are the logs of the three containers:

redis-master container  bcbc99bc2bf1:
docker logs  bcbc99bc2bf1
....
1:M 19 May 14:18:42.319 * The server is now ready to accept connections on port 6379
1:M 19 May 15:49:21.723 * Slave 10.244.14.2:6379 asks for synchronization
1:M 19 May 15:49:21.723 * Full resync requested by slave 10.244.14.2:6379
1:M 19 May 15:49:21.723 * Starting BGSAVE for SYNC with target: disk
1:M 19 May 15:49:21.724 * Background saving started by pid 159
159:C 19 May 15:49:21.728 * DB saved on disk
159:C 19 May 15:49:21.728 * RDB: 6 MB of memory used by copy-on-write
1:M 19 May 15:49:21.821 * Background saving terminated with success
1:M 19 May 15:49:21.821 * Synchronization with slave 10.244.14.2:6379 succeeded
1:M 19 May 15:57:25.915 * Slave 10.244.14.3:6379 asks for synchronization
1:M 19 May 15:57:25.915 * Full resync requested by slave 10.244.14.3:6379
1:M 19 May 15:57:25.915 * Starting BGSAVE for SYNC with target: disk
1:M 19 May 15:57:25.915 * Background saving started by pid 170
170:C 19 May 15:57:25.919 * DB saved on disk
170:C 19 May 15:57:25.919 * RDB: 6 MB of memory used by copy-on-write
1:M 19 May 15:57:25.954 * Background saving terminated with success
1:M 19 May 15:57:25.954 * Synchronization with slave 10.244.14.3:6379 succeeded

redis-slave container 7ac2b07bea5a:
docker logs 7ac2b07bea5a
....
[8] 19 May 15:49:21.749 * Connecting to MASTER redis-master:6379
[8] 19 May 15:49:21.750 * MASTER <-> SLAVE sync started
[8] 19 May 15:49:21.751 * Non blocking connect for SYNC fired the event.
[8] 19 May 15:49:21.752 * Master replied to PING, replication can continue...
[8] 19 May 15:49:21.752 * Partial resynchronization not possible (no cached master)
[8] 19 May 15:49:21.752 * Full resync from master: fa30f1e61ca8099b4c9f96cc2ab9ae454f4b8e2f:1
[8] 19 May 15:49:21.850 * MASTER <-> SLAVE sync: receiving 18 bytes from master
[8] 19 May 15:49:21.850 * MASTER <-> SLAVE sync: Flushing old data
[8] 19 May 15:49:21.850 * MASTER <-> SLAVE sync: Loading DB in memory
[8] 19 May 15:49:21.850 * MASTER <-> SLAVE sync: Finished with success

redis-slave container 23aed8bb7882:
docker logs 23aed8bb7882
....
[10] 19 May 15:57:25.936 * Connecting to MASTER redis-master:6379
[10] 19 May 15:57:25.936 * MASTER <-> SLAVE sync started
[10] 19 May 15:57:25.937 * Non blocking connect for SYNC fired the event.
[10] 19 May 15:57:25.938 * Master replied to PING, replication can continue...
[10] 19 May 15:57:25.938 * Partial resynchronization not possible (no cached master)
[10] 19 May 15:57:25.939 * Full resync from master: fa30f1e61ca8099b4c9f96cc2ab9ae454f4b8e2f:673
[10] 19 May 15:57:25.978 * MASTER <-> SLAVE sync: receiving 18 bytes from master
[10] 19 May 15:57:25.978 * MASTER <-> SLAVE sync: Flushing old data
[10] 19 May 15:57:25.978 * MASTER <-> SLAVE sync: Loading DB in memory
[10] 19 May 15:57:25.978 * MASTER <-> SLAVE sync: Finished with success

Things have looked very good so far. From these containers' logs, I believe the two Redis-slave 
are connecting to the Redis-master. However, from the Kubernetes master, I still receive errors 
when running this curl command: curl "http://172.31.40.136:80/index.php?cmd=set&key=messages&value=hello"
Note 172.31.40.136 is the public IP address of one of my kubelets. Below is the exact error I received:

core@ip-172-31-46-158 ~/kubernetes/examples/guestbook $ curl "http://172.31.40.136:80/index.php?cmd=set&key=messages&value=hello"
<br />
<b>Fatal error</b>:  Uncaught exception 'Predis\Connection\ConnectionException' with message 'php_network_getaddresses: 
getaddrinfo failed: Name or service not known [tcp://redis-master:6379]' in /vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php:141
Stack trace:
#0 /vendor/predis/predis/lib/Predis/Connection/StreamConnection.php(96): Predis\Connection\AbstractConnection-&gt;onConnectionError('php_network_get...', 0)
#1 /vendor/predis/predis/lib/Predis/Connection/StreamConnection.php(70): Predis\Connection\StreamConnection-&gt;tcpStreamInitializer(Object(Predis\Connection\ConnectionParameters))
#2 /vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php(96): Predis\Connection\StreamConnection-&gt;createResource()
#3 /vendor/predis/predis/lib/Predis/Connection/StreamConnection.php(144): Predis\Connection\AbstractConnection-&gt;connect()
#4 /vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php(181): Predis\Connection\StreamConnection-&gt;connect()
#5 /vendor/predis/predis/lib/Predis/Connection/StreamConnecti in <b>/vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php</b> on line <b>141</b><br />

I did try to restart the "front-end" rc but still see the same issue. I am not quite sure how to resolve it at this point.
Does anyone have any ideas how to resolve this problem? Many thanks in advance for your help.

**Comment by kcao3** [comment]
After updating all the /etc/hosts in all of the frontend containers to include both the IP address - host 
mapping entries for both the redis-master and redis-slave, I finally was able to get this example to work
temporarily. However, this is just a hack. As the pods get deleted, all of my changes will be gone.

**Comment by gosharplite** [comment]
Add below options when starting kubelet might help. Since kubelet will tell new pod where to find DNS.
```
--cluster_dns=<DNS service ip>
--cluster_domain=<default local domain>
```
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/cluster/addons/dns#how-do-i-configure-it

**Comment by kcao3** [comment]
So, the options above allow the kubelet to tell new Pod where to find the DNS. I am using skyDNS and at this point I have both the DNS rc and service running. At this point from a Docker container within a running Pod, I can see the DNS server. However, for some reason, the DNS server is still not able to resolve IP addresses for the following hosts: redis-slave, redis-master. So from the skyDNS server, does anyone know how to add the redis-slave and redis-master host-IP address mapping entries so that the IP addresses of these hosts can be resolved and available for a running Pod  to use.

**Comment by gosharplite** [comment]
kube-dns pod has three containers, etcd, kube2sky and skydns. kube2sky watches the kubernetes system for new services. When a new service is created, kube2sky adds new service ip into skydns.
You might want to destroy then create your services again in order for kube2sky to work with skydns.

**Comment by kcao3** [comment]
When I inspect my running kube-dns pod, I believe it has the following three containers as mentioned above:
1. container etcd with ID: 1406c76e3b99 from image: gcr.io/google_containers/etcd:2.0.9
2. container kube2sky with ID: aa57260e8c3c from image:  gcr.io/google_containers/kube2sky:1.5
3. container skydns with ID:  9e18e683afbd  from image: gcr.io/google_containers/skydns:2015-03-11-001. One thing I notice is that once this container is created, it only lives for a short period of time  (about 20+ seconds) before it gets destroyed. Once it is destroyed, another container is created and the sequence is repeated over again.

First, the etcd container's logs indicate no errors:
core@ip-172-31-40-170 ~ $ docker logs 1406c76e3b99
2015/05/20 03:00:07 etcd: no data-dir provided, using default data-dir ./default.etcd
2015/05/20 03:00:07 etcd: listening for peers on http://localhost:2380
2015/05/20 03:00:07 etcd: listening for peers on http://localhost:7001
2015/05/20 03:00:07 etcd: listening for client requests on http://127.0.0.1:2379
2015/05/20 03:00:07 etcd: listening for client requests on http://127.0.0.1:4001
2015/05/20 03:00:07 etcdserver: datadir is valid for the 2.0.1 format
2015/05/20 03:00:07 etcdserver: name = default
2015/05/20 03:00:07 etcdserver: data dir = default.etcd
2015/05/20 03:00:07 etcdserver: member dir = default.etcd/member
2015/05/20 03:00:07 etcdserver: heartbeat = 100ms
2015/05/20 03:00:07 etcdserver: election = 1000ms
2015/05/20 03:00:07 etcdserver: snapshot count = 10000
2015/05/20 03:00:07 etcdserver: advertise client URLs = http://127.0.0.1:2379,http://127.0.0.1:4001
2015/05/20 03:00:07 etcdserver: initial advertise peer URLs = http://localhost:2380,http://localhost:7001
2015/05/20 03:00:07 etcdserver: initial cluster = default=http://localhost:2380,default=http://localhost:7001
2015/05/20 03:00:07 etcdserver: start member 6a5871dbdd12c17c in cluster f68652439e3f8f2a
2015/05/20 03:00:07 raft: 6a5871dbdd12c17c became follower at term 0
2015/05/20 03:00:07 raft: newRaft 6a5871dbdd12c17c [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2015/05/20 03:00:07 raft: 6a5871dbdd12c17c became follower at term 1
2015/05/20 03:00:07 etcdserver: added local member 6a5871dbdd12c17c [http://localhost:2380 http://localhost:7001] to cluster f68652439e3f8f2a
2015/05/20 03:00:08 raft: 6a5871dbdd12c17c is starting a new election at term 1
2015/05/20 03:00:08 raft: 6a5871dbdd12c17c became candidate at term 2
2015/05/20 03:00:08 raft: 6a5871dbdd12c17c received vote from 6a5871dbdd12c17c at term 2
2015/05/20 03:00:08 raft: 6a5871dbdd12c17c became leader at term 2
2015/05/20 03:00:08 raft.node: 6a5871dbdd12c17c elected leader 6a5871dbdd12c17c at term 2
2015/05/20 03:00:08 etcdserver: published {Name:default ClientURLs:[http://127.0.0.1:2379 http://127.0.0.1:4001]} to cluster f68652439e3f8f2a

Second, the kube2sky container's logs show no errors:
core@ip-172-31-40-170 ~ $ docker logs aa57260e8c3c
I0520 03:00:07.778290       1 kube2sky.go:148] Etcd server found: http://127.0.0.1:4001
I0520 03:00:09.779534       1 kube2sky.go:202] Using http://172.31.46.158:8080 for kubernetes master
I0520 03:00:09.779550       1 kube2sky.go:203] Using kubernetes API v1beta3

Third, the skydns container's logs show the following errors:
core@ip-172-31-40-170 ~ $ docker logs 9e18e683afbd
2015/05/20 03:35:11 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns/config) [2801]
2015/05/20 03:35:11 skydns: ready for queries on kubernetes.local. for tcp://0.0.0.0:53 [rcache 0]
2015/05/20 03:35:11 skydns: ready for queries on kubernetes.local. for udp://0.0.0.0:53 [rcache 0]
2015/05/20 03:35:12 skydns: can not forward, name too short (less than 2 labels): `redis-master.'
2015/05/20 03:35:12 skydns: can not forward, name too short (less than 2 labels): `redis-master.'

Does anyone know what causes this error and how to resolve it?

**Comment by kcao3** [comment]
FYI. I have encountered the same problem as described by @biswars: https://github.com/GoogleCloudPlatform/kubernetes/issues/8042.
After disabling the check/livenessProbe section from the dns-controller.yaml file, the skydns container is running fine and not killed anymore. For the skydns error:  can not forward, name too short (less than 2 labels): `redis-master.', according to @thockin, skydns expects to a domain to have 2 tokens. I suspect the domain, redis-master only has one token and that why it is not accepted by skydns. I could be wrong though. Does anyone have any idea how to resolve it?  Also just curious, does anyone ever have the guestbook example working?

**Comment by kcao3** [comment]
It turns out for this example, the correct domains for the redis-master and redis-slave are redis-master.default.kubernetes.local and redis-slave.default.kubernetes.local. See the -domain Flags section from this link for more detail: https://github.com/GoogleCloudPlatform/kubernetes/tree/master/cluster/addons/dns/kube2sky.

**Comment by gosharplite** [comment]
In case of missing kubernetes secret ```token-system-dns```, below links might help.
https://groups.google.com/forum/#!topic/google-containers/_aYdo_ITitA

**Comment by vekexasia** [comment]
where is the redis-slave image source?
