### ISSUE TITLE
The resourceVersion defined as int make Python client code fail.

### ISSUE THREAD

**Issue by madhuri-rai07** [GoogleCloudPlatform/kubernetes#6457]
The resourceVersion is defined as int in swagger-spec which make Python client code to fail with TypeError('int' object is not iterable)

**Comment by nikhiljindal** [comment]
I will recommend filing a bug with swagger-codegen on this.
I dont see anything that we can do abut this in kubernetes.

**Comment by bgrant0607** [comment]
resourceVersion is defined as string in v1beta3.

**Comment by madhuri-rai07** [comment]
So I think  we need ot change this in v1beta1 also. RIght?

**Comment by bgrant0607** [comment]
No, we can't change it in v1beta1 in order to preserve backward compatibility, though v1beta1 is also approaching its end of life. 

More about our approach to API versioning can be found here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api.md

Sorry, I didn't mean to derail discussion of the problem that was reported. 

resourceVersion in what object(s)?

The most recent version of our swagger output has:
```
     "resourceVersion": {
      "$ref": "uint64",
     },
```

which is definitely not right. This looks like a bug in the swagger-generation library we're using:
https://github.com/emicklei/go-restful/blob/master/swagger/model_builder.go#L250

Is that what it looks like in whatever version you're targeting? We've been making quite a few changes recently.

But I don't understand what the error you reported means.

**Comment by bgrant0607** [comment]
Maybe because `$ref` is specified rather than `type`, the generated python is either trying to iterate over the value or over the type definition as if it were a map/list.

cc @brendandburns, since he said he might take a look at swagger-codegen.

**Comment by nikhiljindal** [comment]
I see:

```
"resourceVersion": {
      "type": "string",
      "description": "string that identifies the internal version of this object that can be used by clients to determine when objects have changed; populated by the system, read-only; value must be treated as opaque by clients and passed unmodified back to the server: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api-conventions.md#concurrency-control-and-consistency"
     },
```
in ```https://github.com/GoogleCloudPlatform/kubernetes/blob/master/api/swagger-spec/v1beta3.json```

**Comment by bgrant0607** [comment]
Yes, uint64 is v1beta1.

**Comment by madhuri-rai07** [comment]
Yes, bgrant is right. But I think this issue is fixed in master now.
