### ISSUE TITLE
In CoreOS getting started guide cloud-config file, the multihost node etcdctl will default to localhost

### ISSUE THREAD

**Issue by bussyjd** [GoogleCloudPlatform/kubernetes#6555]
In node.yaml:22

    ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"10.244.0.0/16", "Backend": {"Type": "vxlan"}}'

will default to localhost etcd, which is running only on the master.

The solution I found is to point etcdctl to the master:

    ExecStartPre=/usr/bin/etcdctl -C <master-private-ip> set /coreos.com/network/config '{"Network":"10.244.0.0/16", "Backend": {"Type": "vxlan"}}'

**Comment by pires** [comment]
@bussyjd care to open a PR? Or @doniphon?

**Comment by hobti01** [comment]
The configuration is already set in master.yaml:
```
    - name: flanneld.service
      command: start
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Unit]
            Requires=etcd.service
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"10.244.0.0/16", "Backend": {"Type": "vxlan"}}'
```
Is there a need to set it again from the node, particularly when etcd is running on the master?

**Comment by pires** [comment]
@hobti01 it's intended for etcd clustering. @antoniomeireles can explain why he did it.

**Comment by hobti01** [comment]
Yes, I see the use case for when etcd is running as a single server or cluster and not on the master, but not as much with node.yaml:21, which requires the master to be running etcd:
```
[Service]
ExecStartPre=/bin/bash -c "until curl http://<master-private-ip>:4001/v2/machines; do sleep 2; done"
ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"10.244.0.0/16", "Backend": {"Type": "vxlan"}}'
```

Is the race between the node starting flannel and the gap between the master starting etcd and running the ExecStartPre for flannel the reason for this?  Would a viable alternative be to have the node.yaml:21 wait for the network/config to exist in etcd?

Or perhaps my concern of "last node wins the network configuration for the cluster" is unfounded?

**Comment by bussyjd** [comment]
@pires In the meantime I made a PR. Fell free to discard if not necessary anymore.
https://github.com/GoogleCloudPlatform/kubernetes/pull/6611

**Comment by bussyjd** [comment]
@hobti01 @pires This issue is still causing confusion in the guide.

**Comment by pires** [comment]
@antoniomeireles is the guy to blame here since I was in favor of a single `etcd` daemon in master and not in minions as well - because of possible race-conditions, etc. I've been calling on him for some time (even in this issue) but he's been busy, it seems. We should probably revert this behavior or get it working, so @antoniomeireles, what's the verdict?

**Comment by AntonioMeireles** [comment]
(sorry latency) 

two approaches. since etcd os masked in the minions/nodes we can either assume that there 's no chance of a node starting before the master is up with flanel setup. in that case the etcdctl invokation is crap and would be scrapped. right now we test in the nodes that etcd is up in te master *but* just that, not if flanneld is already setup (which should happen shortly after but ... nodes' could get faster), so i'd go for merging https://github.com/GoogleCloudPlatform/kubernetes/pull/6611 *but* extending it also to aws/cloud-configs/node.yaml also as it has the exact same issue.

**Comment by pires** [comment]
Yeah, I'd go with #6611 as well for all `node.yaml` that we have around. Thanks for pointing that out.

**Comment by bussyjd** [comment]
@pires @AntonioMeireles 
Extented to aws/cloud-configs/node.yaml https://github.com/GoogleCloudPlatform/kubernetes/pull/6890

**Comment by brendandburns** [comment]
Closing this in favor of #6611 and #6890
