### ISSUE TITLE
Kubelet loops endlessly looking at run once pods

### ISSUE THREAD

**Issue by jwforres** [GoogleCloudPlatform/kubernetes#6641]
See this issue https://github.com/openshift/origin/issues/1656

This also causes the API to continually spam open websockets watching /pods.

**Comment by jwforres** [comment]
@smarterclayton

**Comment by lavalamp** [comment]
To Dawn to triage.

**Comment by yujuhong** [comment]
IIUC, this is a performance optimization, rather than a bug? kubelet watches all pods with Spec.Host set to its node, and does periodical sync in addition to watch updates. It watches those pods, so that it knows that they are still alive (not deleted) and can respond to requests to check pod/container status and logs, etc. Potentially, it could also restart containers if the restart policy is updated to always.

**Comment by smarterclayton** [comment]
I'm not sure that we should ever allow a pod to transition it's restart policy.  The reason I bring this is up is that I do *not* see this behavior before the kubelet is restarted.  It looks like on restart the kubelet is handling completed run once pods differently.

**Comment by yujuhong** [comment]
Did your run once pods succeed or fail? I found a code that'd [ignore failed pods](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1389) even thought it wasn't intentional. In all cases, kubelet still watches all pods assigned to it though.

Agreed that transitioning restart policy may not be good, but we do allow it in the apiserver. We should explicitly disallow it if that's what we wanted.

**Comment by smarterclayton** [comment]
I don't see where pods can change restart policy.  So at least we know they can't today.

These were successful run once pods.

**Comment by yujuhong** [comment]
@smarterclayton, you were right. We cannot update the restart policy. The update validation prevents it. We should the json description to match that.

For successful run once pods, kubelet continues looping on them in my local setup, with or without restart. This seems to be the normal behavior.

**Comment by yujuhong** [comment]
Somewhat related to this issue: #7301 filtered out terminated pods in SyncPods so that kubelet doesn't try to sync them, which involves examining dead containers. Kubelet would still watching all pods (including the terminated ones) though.

**Comment by derekwaynecarr** [comment]
I think this issue can be closed now.

I did the following:

```shell
apiVersion: v1beta3
kind: Pod
metadata:
  name: valid-pod
spec:
  activeDeadlineSeconds: 30
  containers:
  - capabilities: {}
    image: nginx
    name: nginx
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
```

Waited for the pod to be killed by the kubelet after it ran to completion.

Verified the kubelet killed the container on the minion.

Verified that once the Kubelet changed the status of a pod to terminated that its resource version was stable for the next 10 minutes.  Meaning that Kubelet was properly filtering out terminated status pods, and not constantly updating the status, which previously caused the resource version to appear to chain, which caused spams to our watch clients.

Closing since all is good here now.
