### ISSUE TITLE
Deleting containers holds up the update bus on kubelet

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#6764]
This might just be WAI. We currently have something like (people who know better please correct):

```
apiserver
   |
reflector
   |
|(1) api  --(listen)>|                                 
|(1) file --(listen)>|(merge)->(compress) ->[update BUS (50)] ->syncLoop
|(1) http --(listen)>|                                  
```
Where (x) is a channel of capacity x

1. We can only get watch events as fast as we can compress in MergeState (which takes the lock on the pod storage and iterates through all its pods https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/config/config.go#L337)

    But still, that's mostly been *ok* in the little profiling I've done.    

2. It's fairly easy to fill up that update bus with a few tries of:
```
cluster/kubectl.sh create rc --replicas=30
<wait for pods to start running>
cluster/kubectl.sh stop rc
cluster/kubectl.sh create rc --replicas=30
```

Bump replicas to 100 on a 3 core system  and it'll happen sooner :)

The stop and second create will fill the bus with 50 podupdates while SyncPods is still destroying containers from the delete. This causes merge to stall for the 51st update, which causes the reflector to stall. So essentially everything is held up on delete, which feels kind of backwards, because I usually don't care about deleted pods anymore?

**Comment by yujuhong** [comment]
There is a slight optimization to batch the [recent updates in 5 ms] (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1618). Perhaps we can make it wait longer to batch more aggressively.

I think the kubelet's performance may have regressed since it switched to watching pods. Every pod status update kubelet sends would trigger an update from apiserver. We could potentially filter such updates when merging, or we could switch to using a more distributed per-pod merge/sync model. The latter is a bigger change and may not be needed for the 1.0. I will do some digging to see if this is truly needed.

**Comment by bprashanth** [comment]
The pod status shouldn't really be changing though unless you have crashy container right?

**Comment by yujuhong** [comment]
Yes, but if you do `create` and then `stop rc`, kubelet would still get the pod status update (to Running) in between those calls. These could fill up the channel as well, no?

**Comment by bprashanth** [comment]
Yes it would get the one set of pod status' that it just sent, those are usually snappy to process

**Comment by bprashanth** [comment]
Oh, those aren't sent to syncLoop if memory serves right, because the spec matches what you already have (def verify this)

**Comment by yujuhong** [comment]
I ran some tests on my local setup while setting GOMAXPROCS=1 for kubelet.

When replica count is 100, `stop rc` followed by `create` would fill up the channel, at which time kubelet could take up to a minute to finish the sync (mostly deleting the containers). This is because deleting containers are done in serial in [SyncPods](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1436) by one thread. I then spawned off go routines to (naively) kill containers for each pod. It reduced the sync time to <20 seconds. This could be lower if we let the go routines running int he background.

Can the performance be improved? Yes. However, given our v1.0 performance goal, I don't think the current performance is not tolerable. 
Besides deleting, I think eventually we should tackle the problem that any pod worker (a go routine listening on a channel) may be slow (e.g. due to image pulling), and potentially dragging down the performance of other pods.

**Comment by vmarmol** [comment]
+1 on this probably being okay for v1.0.

On the pod worker front, we should definitely fix any issues that cause one pod worker to affect other pod workers. I don't believe we have any of those issues today though. The thread per pod worker model is intended to separate the effects of a slow job and if your job is "difficult" to start you're only hurting yourself.

I think the problem you're observing is that we don't actually perform all operations in pod workers. The deletes (of non-desired pods) are done globally as you mentioned. We can probably improve this by having the pod workers handle their deletion as well and potentially having some "unknown pod" pod workers for the rest. We'd be extending the lifetime of pod workers to more closely match the pod objects they track.

There are other global operations we do in SyncPods outside of pod workers (stale cleanups for almost everything), we'll probably need to move those too eventually as we start feeling their pain.

**Comment by bprashanth** [comment]
SGTM, do with this what you will :)

**Comment by yujuhong** [comment]
I think I've mistaken how pod worker worked. Each pod worker has a update channel of capacity one, but kubelet would not send any update if the pod worker is busy. Basically it would ignore/discard any incoming updates (with an extra buffer of one). That's why the syncing process would not be slowed down by a slow pod worker.

For v1.0, if we want to improve the bottleneck of deleting unwanted pods, I'd vote for simple parallelization of cleanup or a dedicated cleanup thread (as opposed to restructure pod worker for this purpose)

**Comment by vmarmol** [comment]
Simple parallelization SGTM

**Comment by yujuhong** [comment]
#6804 proposed to let user specify the grace period before SIGKILL the containers (i.e., essentially `docker stop -t <timeout> <container_id`). This may necessitate pushing the container killing to the per-pod go-routines since user can specify an arbitrary long timeout and `docker stop` would block until the operation is completed. Simple parallelization would still help, of course, but the longest timeout would dominate the sync time.

On the other hand, I wrote a simple micro-benchmark to test the effectiveness of paralleling killing the containers. The benchmark creates 100 containers, and then launches N workers to do `docker inspect` and `docker stop`; this mimics the docker operations in kubelet for killing a container. Take the results with a grain of salt since I ran it only on my desktop. With 1 worker, it took ~17s to kill the containers, while 5 workers took ~8s. Going beyond 5 workers didn't help. In short, parallelizing does help. In reality, the benefits might be more obvious because the containers could take longer to clean up (the default grace period is 10s), while in my benchmark the containers were doing nothing.

**Comment by yujuhong** [comment]
Closing this issue because #7048 parallelized the container killing in SyncPods. 

Pushing container killing to pod workers would be easier and more meaningful after termination notice (#6804) is defined.

**Comment by vmarmol** [comment]
@yujuhong why would pushing to pod workers with the termination notice? If anything it seems like the other way around, termination would be easier if killing was done by pod workers.

**Comment by yujuhong** [comment]
I might have overstated by saying it'd be *easier*. What I really wanted to say was that "termination notice" and "killing by pod workers" should be designed together.  Termination notice definitely needs killing by pod workers so that it'd not unreasonably degrade kubelet's performance.

On the other hand, it also *seemed* like that termination notice would work better with the per-pod workers. Current pod-worker architecture relies on sending pod (specs) to per-pod workers. The lack of pod (specs) for the *deleted* pods makes killing by pod workers harder, or at least demands a big overhaul of existing structure. With the termination notice, I imagine the pod killing would work this way:
     1. User sends a pod delete request to the apiserver.
     2. Apiserver updates the pod to indicate that it should be terminated (note that the pod still exists)
     3. Kubelet receives such a pod update and send it to the pod worker. Pod worker handles the killing which should be finished by the time the apiserver actually deletes the pod.
(There are of course other corner cases that we need to handle. This model just seems more compliant to how per-pod workers work today)

`B` assumes that we will use termination notice (or graceful termination) by default, which *might* be easier to implement. If kubelet needs to support both ways of killing (hard & graceful), then we'd probably want to wait until termination notice is mostly defined anyway. Either way, it doesn't seem worthy of making this change until we know the requirements.
