### ISSUE TITLE
Document how the Kubernetes scheduler works

### ISSUE THREAD

**Issue by kmerker** [GoogleCloudPlatform/kubernetes#6781]
Write up a short summary of how the Kubernetes scheduler works for those curious about it.

**Comment by davidopp** [comment]
As part of this, also document how the Kubernetes-Mesos integration works.

**Comment by HaiyangDING** [comment]
If no one is working on this, I would like to write a brief document explaining how the scheduler works.

I think the following points should be well explained in the document:
 
1. When a pod is created with `kubectl create -f pod.yaml` command, it is queued
2. The scheduler is a separated process, the first pod in the queue is taken by the scheduler
3. The scheduler then filters the nodes in the cluster with predefined predicate functions. Each of the predicate functions is then briefly introduced.
4. After filtering with predicates, the candidate nodes are then scored with predefined priority functions. Each of the priority function is then briefly introduced.
5. The output of each priority function is scaled within 0-10 and 10 stands for "most preferred" and 0 for "least preferred". A weight is given to each priority function and the final score of a node is the sum of the `score * weight` of each priority function.
6. The scheduler picks the node with highest final score, if there are more than one nodes with equal highest score, a random node among those with highest score is picked.
7. A user can restart it with CLI command and specify custom schedule policies.

I think the above is enough for a started to know about the scheduler.

Any suggestions? May I start working on this? I think it would be finished within a day or two if started right now.

**Comment by erictune** [comment]
I don't think we should document the scheduler in that much detail because it may encourage people to rely on features that we later want to change.

I haven't see any question about how the scheduler works on IRC/email/issues.  From that I conclude that ti Just Works :tm: and so the less said the better.

**Comment by erictune** [comment]
@HaiyangDING 
don't want to discourage you at all.
happy to have help on documentation.
There are 60 unassigned documentation issues: 
https://github.com/GoogleCloudPlatform/kubernetes/issues?q=is%3Aopen+is%3Aissue+label%3Akind%2Fdocumentation+no%3Aassignee

**Comment by HaiyangDING** [comment]
@erictune 
Hi, not at all:) The reason I want to write this is that many of my colleagues are curious about the mechanism behind the scheduling of k8s. They are trying to justify to what extend they should modify the scheduler if they adopt k8s in the near future (the scheduling mechanism is considered to be very import in their product). Due to this, I think writing a brief document is a good idea.

However, if the scheduler is going to be changed in future, I agree that "the less said the better" and I will be watching the issues/PRs relating to scheduler so that I can always be aware of how the scheduler works however it changes.

I am going to see those unassigned docs to see if I could make some contribution there. When it comes to a point that a document of scheduler is required, I would always be happy to contribute one (I have written one already for my colleagues and I will keep updating it).

Regards

**Comment by davidopp** [comment]
@HaiyangDING  I think something with a bit less detail would be fine. Let me write an outline and then maybe we can iterate on it.

**Comment by HaiyangDING** [comment]
@davidopp ,

That sounds like a great idea to me! I am really looking forward to see the outline.

Regards
