### ISSUE TITLE
kube2sky not working with etcd versions bigger than 2.0.7

### ISSUE THREAD

**Issue by AntonioMeireles** [GoogleCloudPlatform/kubernetes#6852]
works perfectly up to 2.0.7. with 2.0.9 all i get is ...
```
Failed to connect to etcd server: http://172.17.8.101:2379, error: unknown server: etcd 2.0.9
```
(same with 2.0.8 other than the version string)

[sorry had no time to debug this further]. tested on k8s 0.15.0 over CoreOS. 

cc @pires

**Comment by pires** [comment]
Can't we just re-use the `etcd` used by `apiserver`? Having one `etcd` just for `kube2sky` seems redundant and, as we can see now, error-prone.

**Comment by AntonioMeireles** [comment]
@pires - humm. i don't think both issues related. i.e. a private etc-2.0.{8,9} for {kube2sky,skydns} has exact same issue. [anyway and in case i was blind last night i'll double check again later today)

**Comment by pires** [comment]
@AntonioMeireles given you **must**  have a working `etcd` for Kubernetes to work, if `kube2sky` reuses it, then this issue would never happen, since it would have been identified sooner.

**Comment by AntonioMeireles** [comment]
no. etcd 2.0.{8,9} **generally** works. afaict it's just kube2sky that for some reason is having trouble talking to it (it's specific to kube2sky so far)

**Comment by pires** [comment]
Ah OK. Still, I don't see why one should use a different `etcd` for that.

**Comment by AntonioMeireles** [comment]
afaict would happen with any etc > 2.0.7. anyway will make sure of that later :-) regardless of topology.

**Comment by erictune** [comment]
@thockin for DNS

**Comment by erictune** [comment]
Marking this P3 because if you use the kube2sky pod that is provided with kubernetes releases, it will pull 2.0.3.

The intent with kube2sky (and with the apiserver) was that their use of etcd is an internal implementation detail -- they might change at some later time to use another storage backend).  

So, if you are having apiserver and/or kube2sky talk to the same etcds as fleet uses, then you are doing differently than is intended.

**Comment by thockin** [comment]
@pires etcd for the apiserver is an implementation detail.  etcd for kube2sky is an implementation detail.  Just because they both happen to use the same piece of infrastructure in their implementation does not mean they should be coupled.

**Comment by thockin** [comment]
@AntonioMeireles you launched your own kube2sky pod for this, I guess?  Can you explain "afaict would happen with any etc > 2.0.7"? Did something change in etcd?

**Comment by pires** [comment]
@erictune @thockin thanks for clarifying. So, nothing stops me from reusing the same `etcd`.

**Comment by thockin** [comment]
Nothing stops you as long as that etcd is exposed enough for you to use.

**Comment by AntonioMeireles** [comment]
- @thockin (sorry lag). whatever way you setup etcd (either external or in-pod) with versions higher than 2.0.7 current kube2sky breaks as described above. this is fully reproducible afaict by me. 

- @erictune understood. OTOH, & fwiw  i think that for the sake of consistency it would be pertinent perhaps that independently of the way etcd is used across k8s (shared instances, isolated/independent ones, whatever) the version used be ideally the same and as up to date as reasonable (as in the specific etc case late 2.0.x revisions fix/solve a few key things, etc ...)

**Comment by thockin** [comment]
@vishh not highest prio, but may make other DNS work easier.

**Comment by roberthbailey** [comment]
@cjcullen and I have been looking into this while debugging why kube2sky seems to hang at startup. 

The error is from [etcd_helper.GetEtcdVersion](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/tools/etcd_helper.go#L494) where it tries to parse the json response from etcd with the release version & internal version. Unfortunately, etcd no longer sends a json response and now only reports the release version (see https://github.com/coreos/etcd/commit/60efd4d96ec1ff342ef438b724c52615226c72ab). 

We don't see this in our apiserver because the only uses of `etcd_helper.GetEtcdVersion` in our code base are in `etcd_helper_test.go` and `kube2sky.go`.

**Comment by thockin** [comment]
So was this not reproducible? Working as intended?  Fixed? I don't get it.

**Comment by roberthbailey** [comment]
Did you see my update above? We were checking the version of etcd by hitting it's /version URL and the output format changed. This call wasn't used outside of the kube2sky program so it didn't affect the apiserver but prevented kube2sky working with a newer etcd. It was fixed as part of #7675.

**Comment by cjcullen** [comment]
Sorry. I should have left a comment here before closing.

**Comment by thockin** [comment]
Got it, reading on a phone and missed some.

**Comment by roberthbailey** [comment]
Also note that after @cjcullen's change the DNS pod is now running the same version of etcd as the master (2.0.9).
