### ISSUE TITLE
kubectl update --patch doesn't work as advertised

### ISSUE THREAD

**Issue by kargakis** [GoogleCloudPlatform/kubernetes#6855]
https://github.com/openshift/origin/issues/1642

We just wrap update in OpenShift so I guess this issue belongs here.

**Comment by erictune** [comment]
User did the openshift equivalent of `kubectl update node $NODENAME --patch=`cat patch.json`
and got this unhelpful error:
`F0408 12:23:02.342063    3568 update.go:52] Error: Must provide resource and name command line params`

**Comment by caesarxuchao** [comment]
Maybe this is a related problem. I tried to update a pod: 
```
$ kubectl create -f examples/limitrange/valid-pod
$ kubectl update pods valid-pod --patch='{ "apiVersion": "v1beta3", "spec": { "containers": [{ "resources": { "limits": { "cpu": 0.5 }}}]}}'
```
And the result I got was:
```
Error from server: Pod "valid-pod" is invalid: [spec.containers[0].name: required value, spec.containers[0].image: required value, spec: invalid value '{Volumes:[{Name:default-token-0xcta VolumeSource:{HostPath:<nil> EmptyDir:<nil> GCEPersistentDisk:<nil> AWSElasticBlockStore:<nil> GitRepo:<nil> Secret:<*>(0xc2109667f0){SecretName:default-token-0xcta} NFS:<nil> ISCSI:<nil> Glusterfs:<nil> PersistentVolumeClaimVolumeSource:<nil>}}] Containers:[{Name: Image: Command:<nil> Args:<nil> WorkingDir: Ports:<nil> Env:<nil> Resources:{Limits:map[cpu:500m] Requests:<nil>} VolumeMounts:<nil> LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:IfNotPresent SecurityContext:<*>(0xc20b298cc0){Capabilities:<*>(0xc20e5646f0){Add:<nil> Drop:<nil>} Privileged:<*>(0xc21096679c)false SELinuxOptions:<nil> RunAsUser:<nil>}}] RestartPolicy:Always TerminationGracePeriodSeconds:<nil> DNSPolicy:ClusterFirst NodeSelector:<nil> ServiceAccount:default Host:kubernetes-minion-91q0 HostNetwork:false}': may not update fields other than container.image]
```

**Comment by nikhiljindal** [comment]
@caesarxuchao Your command fails because we try to replace the existing containers with the one you are providing. And there are required fields like name and image missing from your container spec, which is the error you are getting.

What you really want is to merge your container spec with the existing one (so that it takes the name and image from the existing container spec). That is what strategic merge patch does as described here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api-conventions.md#strategic-merge-patch.
Unfortunately, you cant perform a strategic merge patch via kubectl.

**Comment by caesarxuchao** [comment]
@nikhiljindal , thanks. Then we should remove the `--patch` option in `kubectl update`. What do you think @bgrant0607 ?
