### ISSUE TITLE
Use IntOrString for numeric types (like 'replicas') to make them parametrizable

### ISSUE THREAD

**Issue by mfojtik** [GoogleCloudPlatform/kubernetes#7043]
I propose to use the `IntOrString` type in all numeric fields in `api/types.go` and drop the `int` type. 
The reason is, using this type allows you to parametrize the numeric fields in JSON:

```
{
  "replicas": "${NUM_OF_REPLICAS}"
}
```

Secondary, you don't need to guard whether the field is type `string` or `int` in the JSON and using quotes for numeric values won't break the serialization.

https://github.com/GoogleCloudPlatform/kubernetes/issues/2264#issuecomment-85244661
https://github.com/openshift/origin/pull/827#discussion_r28615837

**Comment by mfojtik** [comment]
@smarterclayton FYI.

**Comment by erictune** [comment]
@bgrant0607

**Comment by smarterclayton** [comment]
Hrm - I don't think we should do this.  Numbers are numbers - I think the parameterization is a problem with the Openshift template mechanism.  Dropping everything to strings breaks other things.

We may want to *not* use internal objects (or deserialization) in our templating so you can store objects that don't match their schema.  Then we can add something to parameters which says "this should be a number".

**Comment by bgrant0607** [comment]
I agree w/ @smarterclayton -- we should not do this. It's effectively a request to use strings for all elements in the API -- not only to replace ints, but all non-string types. 

In order to convert from versioned to internal types, defaulting and conversion will be applied. Parameterization would confuse those transformations.

The parameterized templates need to be stored in a more generic form.

**Comment by thockin** [comment]
Agreeing with Clayton - parameterization should be happening before the API
server gets involved, I think.
