### ISSUE TITLE
getServersToValidate should not include nodes

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#7092]
getServersToValidate should not include nodes:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/master/master.go#L552

Other than as a proxy, we're trying to make the master not contact the nodes. Besides, this is what the node API is for. /componentstatuses should be reserved for cluster-level (master) components.

For more details, see discussion from #6597.

cc @fabioy

**Comment by davidopp** [comment]
@faiboy are you working on this? If so, please assign to yourself.

**Comment by fabioy** [comment]
Commenting here, since the other thread has mixed in code-review comments.

@bgrant0607 - I don't disagree necessarily on this, but here's the thing: it's nice to have a single end point to get all the status of all the things the master knows about. I was hoping to keep "componentstatus" as that place. I think it's ok for it to retrieve the node status from its internal state, but not having to do multiple API calls to get the data is good.

@davidopp - Sorry, no, I wasn't working on this at this moment.

**Comment by bgrant0607** [comment]
We've been steadily eliminating master-to-node communication. I fully expect that we'll break the current implementation in the not-too-distant future. The right solution isn't to fix this, but to eliminate it. The node API already needs to implement this for ongoing operation. It shouldn't be implemented twice, especially two totally different ways.

Also, when one has lots of nodes, they'd drown out the master components, making problems harder to debug.

And, a UI would want to display master and node health separately, so it would be useful to have them separated. Parsing the names isn't the best way to do that. I also find it confusing to assign the nodes component names that are different from the actual node names.

**Comment by fabioy** [comment]
I don't disagree with that. I think eliminating the master->node check is fine (and needed -- you're right that it won't scale).

What I do want, though, is to be able to make a single call and get all of the health status that the master knows. It'd simplify the monitoring a lot (and the master already knows it). Presumably, for node health, it could be as simple as "last status" and "timestamp" (the later to determine if the status is still good or stale). 

If "components" is not a good name for this, we can change it. But having to make multiple calls to reconstruct the overall cluster state seems crudy.

**Comment by davidopp** [comment]
A new endpoint that's just limited to master components SGTM. Then we can argue about how /validate should work separately.

**Comment by roberthbailey** [comment]
Please don't change /validate until we have a chance to migrate GKE to use a new validation endpoint. I think it would be OK (even if it's more work on our end) to hit two endpoints instead of on as long as we can validate the master components and validate the nodes to ensure the cluster is properly functioning.

**Comment by davidopp** [comment]
This is related to #6047

**Comment by fabioy** [comment]
This should have been fixed with #7735. Closing.
