### ISSUE TITLE
Error scheduling acloguv1m test2-j6rkr-dqex6: failed to find fit for pod: {{ } {test2-j6rkr-dqex6 test2-j6rkr- acloguv1m 

### ISSUE THREAD

**Issue by huangqg** [GoogleCloudPlatform/kubernetes#7291]
Hi,
I meet some performance issue with k8s scheduler, here is the cluster env:
- Node1: memory cost 90%
- Node2: memory cost 91%
- Node3: memory cost 30%

When creating a new pod, the k8s scheduler will judge which node to bind the pod, to my surprise, the scheduler will bind the pod to Node1 or to Node2, why not bind to node3 directly? what the mechanism of k8s scheduler handle the binding? and how to optimize the performance?

I checked the k8s architecture:
```The scheduler binds unscheduled pods to nodes via the /binding API. The scheduler is pluggable, and we expect to support multiple cluster schedulers and even user-provided schedulers in the future.```

can I bind the pods to nodes myself using /binding API? and can you pls give me some reference of how to support multiple cluster schedulers? and user-provided schedulers.

Thanks very much!

**Comment by huangqg** [comment]
Error scheduling acloguv1m test2-j6rkr-dqex6: failed to find fit for pod: {{ } {test2-j6rkr-dqex6 test2-j6rkr- acloguv1m ：

E0424 22:04:24.465514    1194 factory.go:272] Error scheduling acloguv1m test2-j6rkr-dqex6: failed to find fit for pod: {{ } {test2-j6rkr-dqex6 test2-j6rkr- acloguv1m /api/v1beta3/namespaces/acloguv1m/pods/test2-j6rkr-dqex6 97047a70-ea7a-11e4-89a0-00163e0057bf 2071340 2015-04-24 20:08:16 +0800 CST <nil> map[name:test2-j6rkr] map[]} {[{test2-j6rkr {0xc2089c25d0 <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil>}}] [{test2-j6rkr 10.171.81.240:8080/tenxcloud/ubuntu [] []  [{ 0 22 TCP }] [{ROOT_PASS 00000.}] {map[cpu:{0.500 DecimalSI} memory:{536870912.000 BinarySI}] map[]} [{test2-j6rkr false /data}] <nil> <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] Always ClusterFirst map[]  false} {Pending []    []}}Node 10.172.7.153: PodFitsResourcesNode 10.163.18.77: PodFitsResourcesNode 10.172.6.191: PodFitsResources; retrying

**Comment by huangqg** [comment]
Hi @davidopp , any idea?

**Comment by davidopp** [comment]
Hi. For your first question, you can take a look at defaultPriorities() in
plugin/pkg/scheduler/algorithmprovider/defaults/defaults.go
which lists the default priority policies (the ones that decide which machine to schedule a pod onto when multiple machines meet the requirements). The default policies are LeastRequestedPriority, BalancedResourceAllocation, and ServiceSpreadingPriority. The scheduler combines the outputs of these three policies to choose a best machine. These policies are implemented in
pkg/scheduler/priorities.go

(Still on your first question.) For your simple scenario, ServiceSpreadingPriority is not relevant. LeastRequestedPriority picks the node that is most empty *according to the resource requests* -- that is, the node with smallest (Sum(requested cpu) / Capacity + Sum(requested memory) / Capacity) where the Sums are over all the pods currently running on the node. BalancedResourceAllocation favors nodes where the (new pod's requested CPU + Sum(requested cpu))/Capacity and (new pod's requested memory + Sum(requested memory))/Capacity are close, i.e. after placing the new pod you want the fraction of the node's memory that is free to be about equal to the fraction of the node's CPU that is free. 

(Still on your first question.) So, there are two possible reasons I can think of why the scheduler didn't pick Node 3 in your example. The most likely is that the "memory cost" values you gave are based on the resource *usage* of the pods on the machine, not the resource *request* of the pods on the machine. We have an open issue (#274) to have the scheduler take usage into account, but it doesn't currently. So to know which machine it will pick, you need to look at the resource *requests* of the already-running pods. Now, if the "memory cost" values you gave are indeed based on the resource requests of the pods, then probably the issue is that the the order of the machines' "fullness" on the memory axis does not match the order of the machines' "fullness" on the CPU axis. (The priority functions we use take both CPU and memory into account, so you have to look at both.)

Now to your second question. We don't have any examples of user-provided schedulers yet, but the API definitely allows it (you found the relevant information; the API endpoint is called /binding.) If you want to write your own scheduler, you'll probably want to start with the one we have and then modify it; check out plugin/cmd/kube-scheduler/app/server.go. But it's unlikely that you really need to write your own scheduler. You can easily add your own scheduling policies. You can just add them to pkg/scheduler/priorities.go (or if you are interested in predicates rather than priorities, pkg/scheduler/predicates.go) and then define your own algorithm provider or use a config file (see the 
--algorithm_provider and --policy_config_file command-line arguments in plugin/cmd/kube-scheduler/app/server.go)

For your third question (the error message), it appears that none of the machines have enough free resources for the pod you are trying to schedule (hence the PodFitsResources reason).

I hope this helps.

**Comment by davidopp** [comment]
Ping? Did this help?

**Comment by huangqg** [comment]
it helps, thanks much for your reply.
