### ISSUE TITLE
Rep. Controller encodes created-by annotation incorrectly

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#7322]
pkg/controller/replication_controller.go uses ```json.Marshal(createdByRef)``` at one point to record a reference to a pod's creator in an annotation. This is incorrect because it's serializing an unversioned object.

Additionally, the rule should probably be "objects in annotations should be serializied in the same version as the parent object", but it's hard to see how we can enforce that without a very expensive trek through the annotations in every encode/decode call.

**Comment by bgrant0607** [comment]
Many annotations contain unstructured data, so this is less of a problem for them.

We could create a custom schema to use for such annotations, since this is an "API" to an external system/tool, rather than to Kubernetes components. Making it unstructured isn't really better, though we could use "kind/name" syntax here, which is at least fairly minimal. The only way it would break would be in the case of a kind change, such as minions to nodes. Or, if we had a reasonable way to look up objects by UID, we could switch to a UID, which would sidestep version, namespace, kind, etc.

cc @simon3z

**Comment by simon3z** [comment]
@lavalamp @bgrant0607 I thought that `apiVersion` in `kubernetes.io/created-by` was enough for versioning:

    - apiVersion: v1beta3
      kind: Pod
      metadata:
        annotations:
          kubernetes.io/created-by: '{"kind":"ReplicationController","namespace":"default","name":"nginx-controller","uid":"b47063a8-e8e3-11e4-8646-525400c903c1","apiVersion":"v1beta3","resourceVersion":"40136"}'

**Comment by lavalamp** [comment]
@simon3z confusingly, that apiVersion is the version of the thing that the ObjectReference refers to, not of the ObjectReference itself...

**Comment by simon3z** [comment]
@lavalamp argh! Really? I think it should be fixed... an ObjectReference should carry the api version of its format, not the version of the object it's pointing to (which might change over the time). Or maybe it should have both... but definitely not only the one of the pointed object.

**Comment by simon3z** [comment]
@bgrant0607 since the `created-by` annotation is generated internally by kubernetes and consumed externally it seems really asymmetric with the rest. Basically as you update the format of ObjectReference we'll start having pods with different annotation formats (old and new api version) and the old format will never be updated. Do you have a solution for this? Who's responsible of updating annotations? I understand that external application that are attaching additional info should be in charge of that, but this one is added internally.

**Comment by lavalamp** [comment]
@simon3z It's not a bug, object references need to specify the version of the thing they reference. We haven't previously marshaled just an object reference by itself; it really needs an ObjectMeta field before you should marshal it separately, and one should always use api.Encode/Decode and never json.Marshal to serialize our objects.

**Comment by simon3z** [comment]
@lavalamp any suggestion on what's the preferred solution here? Should we add an ObjectMeta or should we come up with a different format as mentioned by @bgrant0607 here https://github.com/GoogleCloudPlatform/kubernetes/issues/7322#issuecomment-96108736

I would lean toward using an ObjectReference (with ObjectMeta) but it may be too heavyweight for this use case. On the other hand if we need to change the format in the future, we may need versioning anyway (which is what ObjectMeta is providing anyway).

**Comment by bgrant0607** [comment]
Unfortunately, I don't have time to deal with this prior to 1.0. We can either leave this annotation as is, or back it out.

**Comment by lavalamp** [comment]
@simon3z Add a wrapper object, something like this:

```
type SerializedReference struct {
  ObjectMeta
  ObjectReference ObjectReference
}
```

I think it's not the end of the world to leave it like it is for a while. No one depends on this yet.
