### ISSUE TITLE
Pod vanishes when Spec.Host is prefilled with NotReady node

### ISSUE THREAD

**Issue by ghodss** [GoogleCloudPlatform/kubernetes#7340]
If I create a pod with a pod.Spec.Host prefilled to a hostname that's listed as NotReady in `kubectl get nodes`, the pod is created successfully but then disappears completely. (Also, no events are logged relating to that pod.) It seems that the pod should remain in the database, but in some kind of unrunnable state, for two reasons: you probably want that pod to run whenever the host is in a Ready state, and the current behavior makes troubleshooting more difficult.

**Comment by davidopp** [comment]
Sam, this is working as intended. Instead of pre-filling pod.Spec.Host (which users really shouldn't be setting anyway), you should add a label to the node (for example, hostname=foobar) using "kubectl label nodes" and then add to the pod a pod.Spec.NodeSelector to select that label value (e.g. hostname==foobar). If you do this, the scheduler will hold the pod until the node you want it to schedule on is healthy. What you are doing currently gets interpreted by the NodeController as a pod that had been running on that node but then the node went bad so the pod needs to get evicted.

Of course, if you want the pod to always restart, you should run it under a ReplicationController (still need the label).

I'm not sure what your use case is but if you are wanting to run a replica of some pod to run on *every* machine, that is the purview of the "per-node controller" (#1518), which doesn't exist yet.
