### ISSUE TITLE
ENV variables inside pods don't update afer the service restart

### ISSUE THREAD

**Issue by roman-shuhov** [GoogleCloudPlatform/kubernetes#7378]
I have a redis service

    redis-managed   name=redis-managed  name=redis-managed   10.100.62.203    6379

and inside of every pod i see the list of environment variables for it:

    env  | grep MANAGED

    REDIS_MANAGED_PORT_6379_TCP=tcp://10.100.62.203:6379
    REDIS_MANAGED_SERVICE_PORT=6379
    REDIS_MANAGED_SERVICE_HOST=10.100.62.203
    REDIS_MANAGED_PORT=tcp://10.100.62.203:6379
    REDIS_MANAGED_PORT_6379_TCP_PORT=6379
    REDIS_MANAGED_PORT_6379_TCP_PROTO=tcp
    REDIS_MANAGED_PORT_6379_TCP_ADDR=10.100.62.203

If i stop the service and start it again, it's IP address changes

    redis-managed   name=redis-managed name=redis-managed   10.100.72.226    6379

but environment variables inside pods don't update accordingly

    env | grep MANAGED

    REDIS_MANAGED_PORT_6379_TCP=tcp://10.100.62.203:6379
    REDIS_MANAGED_SERVICE_PORT=6379
    REDIS_MANAGED_SERVICE_HOST=10.100.62.203
    REDIS_MANAGED_PORT=tcp://10.100.62.203:6379
    REDIS_MANAGED_PORT_6379_TCP_PORT=6379
    REDIS_MANAGED_PORT_6379_TCP_PROTO=tcp
    REDIS_MANAGED_PORT_6379_TCP_ADDR=10.100.62.203

**Comment by thockin** [comment]
This is partly why environment variables are a bad idea, and it's why we have DNS support.  You can not update env variables without killing and restarting your pods.

Two bits of advice: First, don't bring a service down once you have a pod using it.  Second, use DNS instead of env vars.

I'm going to close this - it's "working" as expected, even if it is not ideal.  If you think there's more we can do here, please re-open and we can discuss.
