### ISSUE TITLE
Insert a layer in DNS hierarchy, tune search path

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#7472]
Instead of svc.ns.kubernetes.local, which leaves no room for non-service name stuff, let's insert literal "services" - svc.ns.services.kubernetes.local.  Adjust the search path to  ns.services.kubernetes.local, services.kubernetes.local, kubernetes.local

Not so important on its own, but hard to fix once we go to 1.0, and easy.

**Comment by ArtfulCoder** [comment]
I checked with Vishnu and he is Ok with me poaching this issue.

**Comment by vishh** [comment]
I was planning on refactoring the existing dns code to use new controller
framework. Can you hold on to your changes until then?

**Comment by ArtfulCoder** [comment]
We have one open question: 
1. Do we care about backward compatibility ?
If users are using relative dns names and don't specify a suffix like  ".kubernetes.local", there is no problem with getting to be backwards compatibility. We can change the suffix to ".services.kubernetes.local"
But if users specify the full path, we could do the following, for each service, we create two dns entries.

Assume namespace = "nsFoo", serviceName = "svBar"
The entries would look like:  

Version | DNS Name | Dir structure
--------- | -------------- | --------------
Backward Compatibility | svBar.nsFoo.kubernetes.local | /local/kubernetes/nsFoo/svBar 
New Format |  svBar.nsFoo.services.kubernetes.local | /local/kubernetes/services/nsFoo/svBar


But, Consider the case where the user is already specifying a namespace = "services" and a service like svBar 
His entries would be looking like:

Version | DNS Name | Dir structure
--------- | -------------- | --------------
Backward Compatibility | svBar.services.kubernetes.local | /local/kubernetes/services/svBar 
New Format |  svBar.services.services.kubernetes.local | /local/kubernetes/services/services/svBar

Is the "new format" entry possible ?

**Comment by ArtfulCoder** [comment]
To allow for entries 2,3 simultaneously, we could convert nsFoo into a folder and then have a file called nsFoo_. That way, in folder nsFoo, we could have svBar file to support entry no. 2, and a nsFoo_ file to support entry no 3. 

When a query is made for svBar.nsFoo.services (entry 2), it will be answered correctly.

But, when a query is made for nsFoo.services, it would end up returning 2 answers, one for entry 2 and another for entry 3. This is obviously incorrect, since it does not match user intent.

We probably should make a call that we will potentially break relative paths.

**Comment by thockin** [comment]
It comes down to what are we willing to break and how much are we willing
to shoulder right now to not break things.

A) Compatible:

1. Roll out kubelets which set dns-search to [ $ns.kube.local,
$ns.svc.kube.local, svc.kube.local, kube.local ]
2, Bounce all pods
3. Roll out DNS server that changes from $svc.$ns.kube.local to
$svc.$ns.svc.kube.local
4. Roll out kubelets which set dns-search to [ $ns.svc.kube.local,
svc.kube.local, kube.local ]
5. Bounce all pods

The gotcha is that we don't have a way to pass flags to kubelets from any
sort of admin console, so we only have time going for us.  In other words,
sit on each phase for a month and hope nobody gets hurt.

B) Somewhat incompatible:

1. Announce that an upcoming change to DNS will break running pods
2. Change kubelet to set dns-search to [ $ns.kube.local,
$ns.svc.kube.local, svc.kube.local, kube.local ]
3. Change DNS code from from $svc.$ns.kube.local to
$svc.$ns.svc.kube.local, but don't roll it out
4. Wait 6 months or for some edge (1.0?)
5. Change kubelet to set dns-search to [ $ns.svc.kube.local,
svc.kube.local, kube.local ] and hope nobody gets hurt.

In this case, we leverage the fact that we don't kube-push DNS.  Clusters
that are running will still work until (5).  New clusters will keep working.

C) Deploy 2 DNS pods?


In general: we need a statement about whether we expect people with pre-1.0
clusters to be able to upgrade to 1.0, or whether 1.0 is a
teardown-and-setup release?  @bgrant0607

We should probably fix the "bug" that we don't kube-push DNS

We should probably fix kubelet to bound pods that have the wrong DNS
settings

**Comment by ArtfulCoder** [comment]
One option could be the following:
1. We create new kube2sky, apiserver  versions that both use a service-definitions compatibility package.

2. The service-definitions compatibility checker reads the service definitions and checks for compatibility issues.

 3.   On startup, the new kube2sky checks for service name compatibility issues. 
      If there are compatibility issues, then:  it continues to work in the old-style mode.
                                                          else: it supports old and new style mode.
4.    On startup, the new apiserver does the same service name compatibility check.
     If there are compatibility issues, then: it does nothing and continues with startup normally.
     If there are no compatibility issues, then going forward: it actively denies new service creation requests that can introduce compatibililty issues.

5. We can have a flag that says, work in old style mode only (deprecated). At some point, we simply stop supporting the flag as well as the old style mode.

6. We add a kube-push log message that points out that compatibility issues were found  (if found) and that old-style is deprecated.

**Comment by thockin** [comment]
It's possible, but I am not keen on getting the apiserver involved in this
to the tune of a flag that users have to configure.

What of we just keep it constrained to DNS.  Operate in both modes (new and
old) but don't generate old-style names for any Service with a namespace of
"svc".  Log an event or something.  We could even have a tool that runs
before the push that says "stop, you have a namespace called 'svc'" - this
is going to cause a problem".

It will affect ~nobody.  We can then take out the legacy mode in a few
months.

**Comment by ArtfulCoder** [comment]
@thockin 
The flag is optional if we want to give ultimate control to the user. It is not pivotal to the proposed approach.

If we don't want to involve ApiServer then, your simplification is required, and it would work: 

(re-iterating what you said, below)

* Rather than go binary on compatibility, have a dialed approach and do both modes only for services which don't have 'svc' in the namespace. 

* Have the kube-push call out services with namespace 'svc'. kube-push and kube2sky can share this logic of detecting such service names. kube2sky wont create such services with svc as their namespace.

* Users who run kube-push get an opportunity to update their pod configs, before they proceed. 

* Pod restarts are manually done by the user. i.e. Users can manually update their pod configs, if required, to change their namespace from "svc" to something else, and restart only those pods.

* We support relative and fully qualified dns names. 

* User potentially shares some of the burden since kube-push alerts them to make changes, if required.

I think this is a good middle path :+1:

**Comment by ArtfulCoder** [comment]
We might also want to disallow more namespace names for future use e.g. "endpoints" etc..

**Comment by ArtfulCoder** [comment]
Tasks would be:
1. APIServer can immediately prevent new services with "svc" namespace from being created.
2. Kubelet can add a new search subdomain with svc.
3. We can enable kube-push to push kube2sky changes.
4. we can update kube2sky to support new style and old style.

Tasks 1,2,3 can be done in parallel immediately without breaking anyone.

**Comment by vishh** [comment]
This plan SGTM. One thing to keep in mind is that not everyone out there uses 'kube_push'. We can either switch to 'dns' being a required component or document our future releases to include DNS specific compatibility issues. 
For services with namespace 'service' should be done from the api-server or kube2sky, because, kube_push is not the primary deployment mechanism.

**Comment by thockin** [comment]
Closing this.  kube2sky now generates both names and #8569 covers the kubelet change.
