### ISSUE TITLE
"kubectl get nodes" output is confusing

### ISSUE THREAD

**Issue by davidopp** [GoogleCloudPlatform/kubernetes#7494]
Not sure how this will show up in Github, but when you do "kubectl get nodes" the columns are aligned such that it looks like "Schedulable" is a label (which it isn't), and the status is "<none> Ready" which is also confusing.

NAME                                                  LABELS        STATUS
kubernetes-minion-kraw.c.striped-torus-760.internal   Schedulable   <none>    Ready

**Comment by davidopp** [comment]
Yeah, that totally didn't show up right in Github.  Here is better:

```
NAME                                                  LABELS        STATUS
kubernetes-minion-kraw.c.striped-torus-760.internal   Schedulable   <none>    Ready
```

**Comment by davidopp** [comment]
My guess is that what happened is that the last two columns accidentally got flipped (should read
```
<none> Schedulable Ready
```
rather than
```
Schedulable <none> Ready
```

**Comment by mwielgus** [comment]
Are you sure that this is still a problem?

On some older build the bug was real:
NAME            LABELS        STATUS
172.28.242.98   Schedulable   <none>    Ready

But now the output is more like:
NAME            LABELS    STATUS
172.28.242.98   <none>    Ready

I suspect that this was fixed in https://github.com/GoogleCloudPlatform/kubernetes/commit/a2ac72c4e76241221017bca33b6b5f22cf4da514

**Comment by brendandburns** [comment]
+1, I agree w/ @mwielgus inspection of the code seems to validate that it is fixed.

I'm closing this.  @davidopp please re-open (and add repro. instructions) if it's still a problem.
