### ISSUE TITLE
[RFE] pod status of "pending" not very useful

### ISSUE THREAD

**Issue by thoraxe** [GoogleCloudPlatform/kubernetes#7784]
"Pending" can have lots of different meanings. One, for example, is that the underlying host is doing a docker pull of the image. But "osc get pods" doesn't tell you that.

Is it possible to add "more" status to the Pending line? For example: Pending:Pulling

I'm not sure what other pending states there are.

**Comment by mbforbes** [comment]
This might be a bit tricky because pods' phases become complex when they contain more than one container. For example, what would the phase of a pod be when one of its containers is pulling, and one is running? I think you'd want to introspect the container states themselves. With that said, the containers don't have a "pulling" state, only a "waiting" one as well.

Just for reference, here are [the pod phases](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/types.go#L723) and [container states](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/types.go#L695).

My top-of-the-head intuition is that when containers are waiting, they're either pending being pulled, or are actually being pulled. Is there a use case for which you'd want to know this distinction?

I'll pass this along to the node team for consideration, as having more introspection can be nice.

**Comment by thoraxe** [comment]
Is this information provided via "describe" or in the "-o YAML/JSON" output?

I could live with "pending" in the "get pod" output if there was some way to get more information about the containers in the pods.

**Comment by thockin** [comment]
kubectl describe pod has a LOT more info

**Comment by yujuhong** [comment]
`kubectl get pods` returns more than the pod phase. It shows the status, created time, and the termination message (or the last termination message) or reason of failure for *each container*. They were added in #7116.

As Tim suggested, `kubectl describe pod <pod_name>` gives you more information, plus events associated with the pod.
`kubectl get pod -o json <pod_name>` gets you the complete container states.

**Comment by dchen1107** [comment]
kubernetes/docs/pod-states.md describes a life of Pod, and lately we expose container state, previous terminated reason and other information through kubectl get pods. Also you can retrieve events related containers in a pod through kubectl describe too. Are those information enough for you to understand your workload?

**Comment by dchen1107** [comment]
I am closing the issue for now. @thoraxe If you feel that we didn't answer your question or we don't expose enough information for your wordload, please reopen it. Thanks!

**Comment by lavalamp** [comment]
Pending means "not running yet". Look at the events (e.g. `kubectl describe pod`) for more detail.
