### ISSUE TITLE
TestSyncPodsCreatesNetAndContainerPullsImage has non-deterministic order of docker` calls

### ISSUE THREAD

**Issue by yujuhong** [GoogleCloudPlatform/kubernetes#7788]
https://app.shippable.com/builds/5549046d42da970c000f2958
```
--- FAIL: TestSyncPodsCreatesNetAndContainerPullsImage (0.17s)
	kubelet_test.go:127: expected []string{"list", "list", "list", "list", "inspect_image", "create", "start", "inspect_container", "create", "start", "list", "inspect_container", "inspect_container"}, got []string{"list", "list", "list", "inspect_image", "list", "create", "start", "inspect_container", "create", "start", "list", "inspect_container", "inspect_container"}
```
The `list` and `inspect` are reversed in the actual calls.

**Comment by yifan-gu** [comment]
Seems that the first `list` comes from `GetPods()` in here: 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1113

The second one comes from `GetPods()` in here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/pod_workers.go#L93

The third one comes from here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1146

So the reason is the third one is racing with all operations with `syncPod()`. The solution is to replace `SyncPods` with `syncPod` in the tests.

**Comment by yifan-gu** [comment]
I found the better solution is to create a fake pod worker to sync in serial. Working on this.

**Comment by yujuhong** [comment]
@yifan-gu, thanks for taking on this!
