### ISSUE TITLE
kubectl output laughably wide

### ISSUE THREAD

**Issue by mbforbes** [GoogleCloudPlatform/kubernetes#7843]
Can we make it narrower (non-columnar) by default, and have the current ultra-wide output accessible via a command-line flag?

A user (@lgfausak) reported this in the Google Group, and I've struggled with this myself countless times. It's simply unusable. You can output in `json` or `yaml`, but that's equally bad for trying to get information, and asking users to learn Go's templating system before they can run a `get pods` isn't fair.

Here's the example output provided:

![output_too_wide](https://cloud.githubusercontent.com/assets/1170062/7497824/bb2a9f1a-f3d1-11e4-8c7d-b69ef4b880e6.png)

Apologies if this is available in a flag that I don't know about or is being discussed elsewhere. I'm putting as a v1.0 candidate because I really think it's a huge UX barrier.

+cc @jlowdermilk @bgrant0607, and please add relevant parties I'm missing

**Comment by quinton-hoole** [comment]
Agreed we need to do something better with this.  The current default record-per-row output is very handy for feeding to grep, awk, cut and friends, but it's pretty useless for looking at.

I would support spending some time on figuring out a better default output for v1.0, although I don't have any obvious suggestions for improvement, other than truncating field values or omitting some fields completely (be default), neither of which are very tasty.

**Comment by bgrant0607** [comment]
How wide is it (number of chars)?

**Comment by thockin** [comment]
In the very beginning of the kubectl UX discussions, I sort of argued for a
handful of alternate -o formats for this reason.

Propose:

-o table : what we have today

-o long : one line per existing table column, Key: value, blank lines
between records

-o kv : one line per record, no header, each existing table column output
as key="value" where format is strictly escaped (for downstream processing)


I originally wanted output format and data selection to be orthogonal
(select data with one set of flags, format with another), but that was
agreed to be a bit too complicated.

**Comment by derekwaynecarr** [comment]
Is it possible we could let the user specify the columns to render in a table, and then filter out tables whose header did not match?  I agree the output is out of control now with long pod names and long image names.

**Comment by derekwaynecarr** [comment]
For example, when we register column headers

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/resource_printer.go#L265

we can optionally map a column header to a shortname, and then let user's specify an explicit set of columns instead of the default set on any table listing command.

for example,

kubectl get pods --columns=pish

would render

pod, ip, status, host columns only.

If not specified, we would just render the default set.

**Comment by quinton-hoole** [comment]
Note that there is tons of prior art to draw on here.  Take a look at the man pages for 'ps', 'ls' and many other standard *NIX utilities.  There's probably a posix standard for this :-). I'm not terribly hung up adding the ability to add or cull columns (it would be nice, but not  super-critical) as it's easy enough to pipe through 'cut', 'awk' or similar to do that for you.

What bothers me more is that a noob user, who just does 'kubectl get pods' for the first time gets back an incomprehensible wall of text rather than a nice neat, friendly table that makes sense.

The best solution I can think of right now is:

- Detect whether we're outputting to a visual terminal (as opposed to a pipe or file), and if so, the width of the terminal.
- If we're outputting to a terminal, limit the set of columns included in the output to a set small enough to fit at least somewhat sensibly in 80 columns, possibly with some data abbreviation.
- For each column, enforce a maximum display width, influenced by the terminal width, and abbreviate the data in that column to fit within that width.  Abbreviation my either be via plain truncation, or probably better by replacing the middle section of the data with e.g. '...' as often the beginning (e.g. namespace) and end (e.g. UID) are the most important parts.
- If we're not outputting to a visual terminal, then keep the current behavior.

Something like that.

**Comment by smarterclayton** [comment]
> On May 7, 2015, at 11:53 AM, Quinton Hoole <notifications@github.com> wrote:
> 
> Note that there is tons of prior art to draw on here. Take a look at the man pages for 'ps', 'ls' and many other standard *NIX utilities. There's probably a posix standard for this :-). I'm not terribly hung up adding the ability to add or cull columns (it would be nice, but not super-critical) as it's easy enough to pipe through 'cut', 'awk' or similar to do that for you.
> 
> What bothers me more is that a noob user, who just does 'kubectl get pods' for the first time gets back an incomprehensible wall of text rather than a nice neat, friendly table that makes sense.
> 
The flip side argument is to make the default output work for most users in ~100 columns and make the full display visible in more.

**Comment by mbforbes** [comment]
+cc @goltermann

**Comment by quinton-hoole** [comment]
@smarterclayton Yes, that's not the flip side, I don't think.  It's what I was trying to propose :-)

Making the default output not wrap in ~100 columns is slightly challenging.  Even if the default output only included the absolutely crucial fields/columns, those can pretty easily exceed 100 chars right now.

More to come shortly...

**Comment by smarterclayton** [comment]
I mean, don't try to do clever detection of width (which we've tried in the past and was complex enough that in the short term just displaying less felt better).  Sorry for not clarifying, realized it was a vague statement.

Display less, require user input to get more.  Don't do terminal width detection (yet).  We know we want to do '-q' so the opposing '-a' or '-v' isn't crazy.

----- Original Message -----

**Comment by quinton-hoole** [comment]
To make the discussion more concrete, below are the fields currently included in the default output for get pods, with common field lengths:

NAME - 50
IP - 15
CONTAINER(S) - 24
IMAGE(S) - 80
HOST - 48
LABELS - 64
STATUS - 8
CREATED - 8 
MESSAGE - ?

GRAND TOTAL:  314 CHARS

And we want to squash that into ~100 chars.

**Comment by quinton-hoole** [comment]
@smarterclayton yes, agreed, start simple.

**Comment by quinton-hoole** [comment]
So here's a concrete suggestion on what to omit to get from ~320 to ~100 chars.

NAME: Abbreviate from ~50 to 16 chars
IP: as is 15 chars
CONTAINERS - abbreviate to 24 chars
IMAGES - omit
HOST - omit
LABELS - abbreviate to 24 chars
STATUS - as is 8 chars
CREATED - as is 8 chars
MESSAGE - omit

=========== 
GRAND TOTAL 80 chars

**Comment by smarterclayton** [comment]
We added message so you could get an at a glance about recent failures - would we roll that into status?  A pod that is restarting frequently is probably more important than labels or created.

----- Original Message -----

**Comment by quinton-hoole** [comment]
Sounds reasonable.  The above was intended as a strawman, for people  to argue about :-)

**Comment by smarterclayton** [comment]
You're good at this :)

----- Original Message -----

**Comment by bgrant0607** [comment]
Our internal dashboard has 28 columns. Even then, the message, if non-empty, is put on a separate line, that spans the columns.

We could potentially push more verbosity to describe.

We have a critical need to surface more container status information. Top dev use cases:
* sort by recency/frequency of failures
* get failure reason, message, etc.
* get URL to access the application status page (via proxy for us) or logs
* get image version (updated yet or not, correlating failures with version, etc.)

I could dig up the UI doc from the Dec. Kubercon. Most of it is relevant to the CLI UX, as well.

**Comment by bgrant0607** [comment]
I'd like an option to generate CSV for easy spreadsheet import, or a space for easy scripting. As with other unix tools, we should provide a flag to specify the separator.

**Comment by bgrant0607** [comment]
I'd omit IP and container names.

I'd omit host and instead translate that to an "unscheduled" status qualifier.

For labels, I'd like a flag to specify which label keys should be made into columns. Other labels should be elided. I imagine users setting default preferences for this. I think we should default the default with a curated set of recommended labels, which we should also support as first-class flags on our operations, in addition to the generic --labels.

**Comment by bgrant0607** [comment]
cc @caesarxuchao

**Comment by caesarxuchao** [comment]
Hi @smarterclayton , could you elaborate on the issues with the width detection? Dynamic width sounds decent to me.

**Comment by smarterclayton** [comment]
Mostly around windows, as well as ensuring automatic tools on a wide variety of platforms aren't impacted (detecting a tty, which we have code for, plus getting terminal width in a sane way).

If we can prioritize our columns anyway, it makes dynamic width useful without being required (you still want your most important columns in the first 100chars).  We can also exec a pager if necessary for large lists, which is probably strictly more useful for most folks.

**Comment by quinton-hoole** [comment]
Somehow my email response to this got lost, so here it is again:

========

For what it's worth I agree with @smarterclayton, and we should perhaps start simple with e.g. just two options

--short  which fits in ~100 characters, and is the default
--long which outputs "everything" (a.k.a. what we do today)

Q

**Comment by caesarxuchao** [comment]
Thanks for the inputs. I think it is a consensus that we need two output modes: the human readable mode and the full mode (a.k.a. what we do today). The human readable shall be the default.

One open question: for the human readable mode, shall we use multiline output or use truncation (e.g., use '...' replace middle secion as @quinton-hoole suggested)?

**Comment by jlowdermilk** [comment]
My vote for truncation. Keeping 1 line per output is still useful.

**Comment by bgrant0607** [comment]
We have at least 4 output commands:
* get list of resources
* get single resource
* describe list of resources
* describe single resource

We also have multiple output modes: template, json, yaml, etc.

Use cases:
* read by human
  * useful to bound total width to viewable area: if fixed default, a flag to override it would be useful; it's lame to not have automatic width discovery, though
  * want fixed-width columns -- will need to truncate field contents, so may want to expand them if necessary if enough space
  * should prioritize display of columns that are likely to contain info the user doesn't already know; may want to add more columns if enough space
  * multi-row per object (within reason) is ok and preferrable to truncation and/or losing critical information
* paste/import into spreadsheet
  * single row per object
  * want column headers
  * all fields ok, selected fields nice to have
  * need to be able to specify field separator or CSV format
* pipe into script that will use one or more values from columns
  * single row per object
  * want to be able to see column headers to figure out what's what, then turn them off (or could use tail -1, but...)
  * all fields ok, selected fields nice to have
  * need to be able to specify field separator
* pipe into json/yaml processing tool (e.g., jq) that will extract one or more values from fields
  * multi-row json/yaml output
* pipe into xargs
  * single row per object
  * "-q" to dump names only, or selected fields, w/ template or specified field separator
* expand on single command line
  * single row per object
  * "-q" to dump names only, or selected field

Eventually we'd like to be able to fetch just the fields requested (#1459).

Describe is expected to be more verbose than get by default, in addition to fetching related resources (e.g., events).

**Comment by bgrant0607** [comment]
Another use case:
* produce config file
  * json/yaml output
  * want to strip out readonly fields, such as status, metadata.uid, etc.

**Comment by quinton-hoole** [comment]
For the most part, I'm totally +1 to what Brian says, except as noted below:

On Tue, May 12, 2015 at 10:55 AM, Brian Grant <notifications@github.com>
wrote:

> We have at least 4 output commands:
>
>    - get list of resources
>    - get single resource
>    - describe list of resources
>    - describe single resource
>
> We also have multiple output modes: template, json, yaml, etc.
>
> Use cases:
>
>    - read by human
>       - useful to bound total width to viewable area: if fixed default, a
>       flag to override it would be useful; it's lame to not have automatic width
>       discovery, though
>       - want fixed-width columns -- will need to truncate field contents,
>       so may want to expand them if necessary if enough space
>       - should prioritize display of columns that are likely to contain
>       info the user doesn't already know; may want to add more columns if enough
>       space
>       - multi-row per object (within reason) is ok and preferrable to
>       truncation and/or losing critical information
>
> ^^^ For get list of resources, I still strongly prefer single row per
object, because it works so much better with the fantastic family of *nix
command line tools which are designed that way (grep, sort, uniq, awk,
cut....).  For bonus points it should be possible to pipe lists of resource
identifiers to kubectl so that things like "kubectl get pod | grep PENDING
| awk '{print $2}' | kubectl delete pod -" to delete all pending pods
become super-easy.

**Comment by bgrant0607** [comment]
Piping into command-line tools is a different use case than read by human.

**Comment by bgrant0607** [comment]
Good point about multi-row: we'd want to ensure we had sufficient sorting and filtering capabilities since it wouldn't be friendly to post-processing.

One option: make describe multi-row (see #7968) and keep get single-row.

I was also thinking of controlling this via auto-detection and flag, much like `ls`.

**Comment by quinton-hoole** [comment]
I like the idea of get being single-row, describe multi-row.

**Comment by caesarxuchao** [comment]
Why do we need to make describe multi-row? It's a list not a table, so the wrapping perfomred by the terminal doesn't hurt the readability, does it? e.g.,
```
# kubectl describe se elasticsearch-logging
W0512 15:01:17.329433   24711 request.go:291] field selector: v1beta3 - events - involvedObject.uid - 237cfa9b-f819-11e4-9ae7-42010af01964: need to check if this is versioned correctly.
W0512 15:01:17.329503   24711 request.go:291] field selector: v1beta3 - events - involvedObject.name - elasticsearch-logging: need to check if this is versioned correctly.
W0512 15:01:17.329513   24711 request.go:291] field selector: v1beta3 - events - involvedObject.namespace - default: need to check if this is versioned correctly.
W0512 15:01:17.329522   24711 request.go:291] field selector: v1beta3 - events - involvedObject.kind - Service: need to check if this is versioned correctly.
Name:                   elasticsearch-logging
Labels:                 kubernetes.io/cluster-service=true,name=elasticsearch-logging
Selector:               name=elasticsearch-logging
IP:                     10.0.219.106
Port:                   <unnamed>       9200/TCP
Endpoints:              <unnamed>       10.244.1.4:9200
Session Affinity:       None
No events.
```

**Comment by caesarxuchao** [comment]
I don't think "describe list of resources" is there right now. Are we going to support it in v1.0?

**Comment by bgrant0607** [comment]
We should support describe of multiple objects: #7467

**Comment by bgrant0607** [comment]
Describe is already multi-row.

**Comment by smarterclayton** [comment]
As discussed in #8685,

```
$ kubectl get pods 
POD                        IP             CONTAINER(S)   IMAGE(S)                               HOST                  LABELS         STATUS    CREATED      MESSAGE
nettest-controller-3a11u   172.17.0.103                                                         127.0.0.1/127.0.0.1   name=nettest   Running   47 seconds   
                                          webserver      gcr.io/google_containers/nettest:1.4                                        Running   22 seconds   
nettest-controller-5453i   172.17.0.110                                                         127.0.0.1/127.0.0.1   name=nettest   Running   47 seconds   
                                          webserver      gcr.io/google_containers/nettest:1.4                                        Running   20 seconds   
```

The infra pod takes up a whole row providing only one unique bit of info, which is the infra pod start time.  The majority of users do not need any info from the infra pod, therefore all of this is better collapsed into the first container, which for most pods (1 container pods) would drastically reduce the vertical space of this display.

**Comment by andronat** [comment]
JFYI, I am currently working on a flexible way to define which columns to be printed. What I am thinking of is that the user can define the name of the columns he want to see.

**Comment by thockin** [comment]
Before you go too far with it, can you share a rough design spec?

**Comment by andronat** [comment]
@thockin Yes of course. I thinking something like this: 8d2de53f1cb6a12a77850204d6d678958a57f3b3

A struct that is going to take care of all the formatting we need for the output. It can also be extended with other fields to satisfy other formatting requirements (e.g. long attribute per line output). It also supports a distinction between all possible printable columns and some default columns that we can preset.

I am thinking that can be integrated on the current code like this: 72acb3002b170dd8bc4d7e5b868c63d49bcd6603

Some show cases here: c19bcf4e168c3c9cb4548c8455fbe3bcd34f10d7

This is just a concept, it is not currently working (yet). What do you think?

**Comment by thockin** [comment]
How does it get exposed to users?  That matters most.

**Comment by andronat** [comment]
@thockin I didn't finish this part yet , but I am going to use some flags like this comment: https://github.com/GoogleCloudPlatform/kubernetes/issues/7843#issuecomment-104821801

Any suggestions are welcomed

**Comment by thockin** [comment]
I think we're pretty open to design, but I want to see it written in
English before being written in Go :)

**Comment by andronat** [comment]
I'll compile a list asap then

**Comment by andronat** [comment]
**Problem**: Output from `HumanReadablePrinter` is some times too long and inflexible

**Target**: 
* Create flexible way on managing the number and format of columns
 * The user can define which columns to be printed and in which order exclusively
   * `-o IP,POD,IMAGE` will print only those 3 columns in this order
 * Support default columns on printing
   * ATM `get pods` is printing 9 columns, we can agree on 5 which are going to be the defaults and the others can be printed only on request
 * The user can use the above idea to request column in a "differential" way 
   * `-o -IP,-IMAGE,+LABELS`. Those flags are interpreted like this: "From the 5 default columns, don't show the IP and the IMAGE but add LABELS"
 * The user can also refer to all passible columns with abbreviations (only first letter when there is no confusion). 
    * This `-o -IP,-IMAGE,+LABELS` is the same as this `-o -IP,-im,+L`
* Width of lines
  * The user can define a global maximum width per column
    * `--max-width=10` If the output is longer than 10 characters, we substitute the middle with `...` until we meet the max width (we can preset a default on that for the user's eyes only)
  * The above can be even generalized to per column max-width 
      * `-o IP:10,POD:30,IMAGE:50`
* Add the option of single or multi line printing
  * `--multi-row` to print in multi-row format with combination to the previous features
* A flag `--long` for maximum verbosity
  * Can be also used together with `--multi-row`


**How**:
   1. Columns are stored in a `[]string`. We could wrap them in a struct that also keeps a second `[]string` or even a `[]int` to define which are going to be the default printed columns.
   2. Create a control struct 
      1. Parses the user's flags and understand if it is in declarative or differential mode
      2. Expand abbreviations
      3. Filter the columns
      4. Enforce column width
      5. Create a printable format (per-line or multi-line)
   
**Interesting "side-effects"**:
  1. All printing functions can follow the same argument signature and in any case that we want to add more controlling in the future, this can be done through this controlling struct
     * Was: `printPod(pod *api.Pod, w io.Writer)`. Then we needed namespaces so: `printPod(pod *api.Pod, w io.Writer, withNamespace bool)`. We might need something else in the future, like `printPod(pod *api.Pod, w io.Writer, withNamespace bool, longPrint bool)`.
     * We can just have `printPod(pod *api.Pod, fc *FormatController, w io.Writer)` and every time we need to add something we just modify the struct
  2. This filtering can be generalized later on to print on whatever and not only to CLI. (e.g. JSON, YAML)
  3. `print*` functions are no longer responsible for manipulating the format. They only take care on feeding the appropriate data to the controlling struct. Formatting will be taken care of from the controlling struct and will be consistent between all types of data.

This is more or less what I am thinking of.

**Comment by thockin** [comment]
I'm not officially a reviewer of this area, so consider my input as
just another user of the system

On Sun, May 24, 2015 at 5:58 PM, Anastasis Andronidis
<notifications@github.com> wrote:
>
> Problem: Output from HumanReadablePrinter is some times too long and inflexible
>
> Target:
>
> Create flexible way on managing the number and format of columns
>
> The user can define which columns to be printed and in which order exclusively
>
> -o IP,POD,IMAGE will print only those 3 columns in this order

I would say `-o columns -c IP,POD,IMAGE` - the first part being fixed
is more consistent with -o yaml, -o template, etc.  I could see
changing -o template -t tmpl-string to -o template:tmpl-string, and
this to -o column:IP,POD

This overlaps a lot with template.

What are the valid values for this new output format?  How do I know
what columns are available?

> Support default columns on printing
>
> ATM get pods is printing 9 columns, we can agree on 5 which are going to be the defaults and the others can be printed only on request
>
> The user can use the above idea to request column in a "differential" way
>
> -o -IP,-IMAGE,+LABELS. Those flags are interpreted like this: "From the 5 default columns, don't show the IP and the IMAGE but add LABELS"
>
> The user can also refer to all passible columns with abbreviations (only first letter when there is no confusion).
>
> This -o -IP,-IMAGE,+LABELS is the same as this -o -IP,-im,+L

feature creep.  de-prioritize this until basics work

> Width of lines
>
> The user can define a global maximum width per column
>
> --max-width=10 If the output is longer than 10 characters, we substitute the middle with ... until we meet the max width (we can preset a default on that for the user's eyes only)
>
> The above can be even generalized to per column max-width
>
> -o IP:10,POD:30,IMAGE:50

feature creep.  de-prioritize this

> Add the option of single or multi line printing
>
> --multi-row to print in multi-row format with combination to the previous features

feature creep.  de-prioritize this

**Comment by andronat** [comment]
`-o columns -c IP,POD,IMAGE` makes sense to me, I will start with that and later on I can change it to `-o column:IP,POD`. My only concern on the second is how do we print the help notes, they might become a lot and hard to read.

As for the what are the valid values for this new output format, I am going to describe on the help string how can be used and also I will add a parameter `-c ALL` that will print all available columns.

**Comment by andronat** [comment]
A Demo [here](https://www.dropbox.com/sh/x9b1iz62c28l7p2/AACchHQW8qV37FNWevU8mMtka?dl=0)

**Comment by bgrant0607** [comment]
Default get pod output is implemented here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/resource_printer.go#L397

Current formats are default (implicit), json, yaml, template, and templatefile:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/resource_printer.go#L48

FWIW, we've discussed introducing a new template language (#4348).

I suggest we explicitly name the default `get` format "column".

By "multi-row", we didn't mean one line per field -- that might as well be json or yaml. We meant that content would spill over onto multiple rows.

I think we agreed that `get` would have single-row (column) output and multi-row output would be reserved for `describe` (and raw json/yaml).

I agree with @thockin's feature-creep concerns - we don't need so many ways of doing the same thing right now.

I'm also concerned about the use of ad hoc column names for selection.

Since the completeness and number of columns is likely to be variable, we should provide guidance that anyone scripting should not depend on the column output -- they should use json, yaml, or templates instead. I'd like a way to specify the field separator / delimiter, but that could be achieved with templates, if in a somewhat less convenient manner. 

Back to the original topic of this issue: We need to truncate the width of fields and reduce the number of fields displayed in `get` output. 

What are the most critical fields? See #8270 for use-case descriptions. For now, overall status -- are things running as expected, debugging, and rollout status are the most important use cases. Detailed debugging info should come from `describe`, not `get`. What `get` should provide is clues about which pods need to be `describe`d.

Obviously, we need to display pod names.

I assume creation timestamp is there to disambiguate the pods. I claim that it's not critical and should be omitted from default output.

Message could be very useful for debugging, but is potentially verbose and long, and mostly is unused at this point. It should just be displayed in describe output.

Pod IP isn't critical for default output, either. It's mostly not usable for anything from the kubectl client. The user will use the apiserver proxy if they need to contact the pod. It could be a substitute for scheduled / not scheduled, which would make it redundant with other info.

I don't think host is important, but is also a proxy for scheduled / not scheduled.

People find phase confusing (#7856), so we should not show it by default.

If we want both a single row and a fixed, bounded number of columns, we can't show container-specific information in long form. We need to roll it up to the pod level (e.g., a count of running containers), or condense it, such as using one character per container (e.g., `NNY`).

We're not showing pod readiness conditions yet.

[Container status](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L745) also contains ready, restart count, state waiting(reason) / running (start time) / terminated (exit code, reason, message, time), and last terminated state w/ the same info.

The solution to summarizing/condensing the above status info is to aggregate it into a couple columns. I suggest one column with the number of ready containers of the total number of containers in the format `M / N`, where "ready" is determined by container is running and is either ready, if a readiness probe is specified, or doesn't have a readiness probe. The other column should be a one-word CamelCase reason, which may be Unscheduled, if no host is assigned, or one of the non-empty Reasons from some container in state waiting (whichever we decide is most relevant), or Success if the pod terminated with success, or one of the non-empty Reasons from some container in state terminated, or ExitCodeN/SignalN if no reason is specified. Since crashlooping containers that are always restarted may never be observed in a terminated state, the shortest amount of time since last container start in the pod and/or sum of container restarts would also be useful.

Labels are of variable length and potentially long. The current output format stinks, anyway. Specifying label values to use as columns (with their keys as the column headers) would be tedious and less pretty to express using templates, so that should be a first-class feature. I believe we should support a few recommended labels directly in kubectl (see https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/cli-roadmap.md). We could display one or more of those by default as columns (e.g., "app", "deployment" -- NOT "name", which we shouldn't be using). "app" is probably often inferable from the object's name. Displaying a deployment label by default would reduce the importance of displaying the image(s) for rollout status.

```
NAME                  READY  REASON        RESTARTS  LAST_START          DEPLOYMENT
frontend-xy789    1 / 2        PullingImage   0                  32s                            v5
backend-al35h     0 / 1       Unscheduled   0                  Never                        sha0q239043589u34243523
```

I wrote the time since last start using a unit abbreviation and without spaces rather than something like "32 seconds ago" in order to reduce space and facilitate cutting by columns.

**Comment by ghodss** [comment]
@bgrant0607 I *really* like this format. I will try to write it as a spec below, along with my minimal modifications/suggestions.

@andronat let's keep iterating on the below as the spec for implementing this issue. Let's also restrict the scope of this issue exclusively to implementing the below as the default output of kubectl get pods. I would argue that this format is good enough that we don't even need --long for now, especially with the current issues the current output format already has, e.g. it's already multi-row (to list the containers) which breaks a lot of scripting you would want to do.

* NAME
 * Never abbreviated because, as Brian put it, get's primary purpose should be to provide clues about which pods need to be described. Really hard to describe a pod that you see in get if you don't have the full name. Also if we abbreviate it, it breaks all scripting where you would try to pipe the name based on some grep.
* READY
 * The number of ready containers of the total number of containers in the format `M / N`, where "ready" is determined by the container running and, if the container has a readiness probe, that the probe has ready status.
* REASON
 * One-word CamelCase reason:
  * If no host is assigned, Unscheduled
  * If the pod terminated with success, Success
  * If M < N,
   * and all containers terminated with success, Success
   * and >0 containers are in waiting state, pick one of the non-empty Reasons (TBD which is most relevant)
   * if no reason on any container, ExitCodeN/SignalN (need to flesh this out more)
  * If M = N, Reason should be blank
* RESTARTS
 * RestartCount of all containers summed together.
* AGE
 * Time pod was created. I would add this because (a) I think it's important when you're trying to find out which pod was just created or if you're in a created/vacated pod loop and (b) I think we can do the column in max 4 characters:
  * 1s, 59s, 1m, 59m, 1h, 23h, 1d, 364d, 1y, etc.

Omitted:
* LAST START
 * This is the only one I disagree with Brian on - I think READY + RESTARTS is sufficient to see that a container is crash looping. describe can tell you details like last start.
* IP
 * Agree w Brian above.
* IMAGES
 * Container name is enough. Use describe for more detail.
* HOST
 * Agreed that this is primarily useful as a proxy to "Scheduled". Also host is often important for pinning use cases (where a pod must be created on a specific host), but in this case we should encourage the usage of labels and a default column with that label as outlined by Brian above.
* LABELS
 * Specific-labels-as-columns is better - we're never going to be able to have a sane view of any meaningful number of labels in the default get pods output.
* MESSAGE
 * get should indicate something is wrong - describe should give message, events, etc.

Labels as columns should be a separate issue and a separate PR. So should --long, adding and removing columns, CSV, yaml, json, etc.

**Comment by ghodss** [comment]
One implication of this change is it takes us really far away from an original design goal of kubectl get, which was to map closely to API fields. But I think that's a necessary evil to come up with anything reasonable to display concisely, and additionally we can solve that with good documentation in kubectl help get.

**Comment by bgrant0607** [comment]
SGTM, with 1 nit:
"If M = N, Reason should be blank" -- we shouldn't leave the field blank, because it would change the number of columns. I still think templates should be used as the input to scripts, but...  I'd make the reason Running in this case.

I really think we need something like the DEPLOYMENT column, since we're going to omit container-specific info, such as image names, but I'm fine for that to be a separate PR from the above, which would be a huge improvement.

I'm not worried about moving away from the API fields, that's what -o json is for, except that we really should be targeting the latest stable API version: #3955.

**Comment by bgrant0607** [comment]
As for not truncating names: How would the width of the name column be determined? Would names exceeding the width just overflow? I personally think truncation is acceptable, in order to achieve a pretty table. Use templates for scripting.

**Comment by fabianofranz** [comment]
In my understanding, a big part of the issue is the fact that the content inside a cell doesn't break lines gracefully. If there's too much content for the column width but it wraps correctly, that's *a lot* of improvement. Example:

```
+---------------------+---------------------+----------------+-------------+-------------+
|    Lorem ipsum dolo |    Vivamus laoreet  |    Lorem ipsum |        test |        test |
|    r sit amet, cons |    vestibulum preti |                |             |             |
|    ectetur adipisci |    um. Nulla et orn |                |             |             |
|    ng elit. Vivamus |    are elit. Cum so |                |             |             |
|     laoreet vestibu |    ciis natoque pen |                |             |             |
|    lum pretium. Nul |    atibus et magnis |                |             |             |
|    la et ornare eli |                     |                |             |             |
|    t. Cum sociis na |                     |                |             |             |
|    toque penatibus  |                     |                |             |             |
|           et magnis |                     |                |             |             |
+---------------------+---------------------+----------------+-------------+-------------+
|         test string |       test string 2 |           test |         row |        bndr |
+---------------------+---------------------+----------------+-------------+-------------+
```

A couple libraries that apparently solve that and other issues with tabular data:

https://github.com/bndr/gotabulate
https://github.com/olekukonko/tablewriter

**Comment by andronat** [comment]
The problem is that we don't want to split the lines to multiple rows as this will make parsing from other scripts (e.g. through pipes) more difficult.

**Comment by fabianofranz** [comment]
@andronat It does makes sense to me, and it's one of the possible paths to choose. But I agree with @bgrant0607 when he says that "piping into command-line tools is a different use case than read by human". For scripting, with or without piping, the solution offered is `--output` and `--template`. The default output format being discussed here should be targeted at screen reading by humans, where we could think about line splitting, paging (yikes), abbreviated data with footnotes for full data (e.g. `kubernetes.io/cluster-service=tr...[1]`) and so on.

**Comment by andronat** [comment]
I like the idea of tables and completely separating users and scripts. What the others say though?

**Comment by smarterclayton** [comment]
As Brian noted that separation was definitely intentional - "-o" should be our vehicle for delivering porcelain and user focused views.

**Comment by bgrant0607** [comment]
I'm not a fan of the multi-row column format with explicit borders, though:
https://github.com/GoogleCloudPlatform/kubernetes/pull/9032#issuecomment-106978927

I suppose I wouldn't strongly object to another output format that used that, but I wouldn't make it the default.

**Comment by thoraxe** [comment]
I just noticed that the current columns aren't even honored:

```
[root@ose3-master beta4]# osc get pod | awk {'print $1"\t"$2'} | column -t
POD             IP
router-1-cutck  10.1.0.4
router          registry.access.redhat.com/openshift3_beta/ose-haproxy-router:v0.5.2.2
```

In the 2nd row, "router" is not a pod id and the image is not an IP.

I'm not sure if this is an artifact of the fact that there is no data in the 1st "position" in the 2nd row... 

Either way, it even makes awk hard to use.

**Comment by bgrant0607** [comment]
@thoraxe Yes, it's because the 2nd row has no data in the first column. 

Take a look at #9032 for the first iteration on the new format.

**Comment by andronat** [comment]
#9032 is merged, I think that when #9490 is also merged we can close this issue.

**Comment by satnam6502** [comment]
This is now fixed and can be closed.

**Comment by a-robinson** [comment]
For what it's worth, kubectl get pods calls come out to exactly 81 columns for me now. It hurts me to see it so close to 80 columns but just over :(
