### ISSUE TITLE
Master upgrade test harness

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#8081]
Forked from #3135. 

For testing master upgrades, we will need a test harness that:

1. Launches a cluster at some known version (e.g. latest release)
1. Runs some amount of work on the cluster
  * Running e2es would be ok, but e2e tests tend to try and clean up after themselves and therefore a test that is better suited would be one that keeps running during the upgrade
1. Upgrade the master to a new version (e.g. latest release running in jenkins)
  * For GCE, we should use [cluster/gce/upgrade.sh](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/upgrade.sh) for this part (and fix it as necessary)
1. Verifies that the cluster is still in a sane state (from the previous tests)
1. Runs e2e tests against the upgraded cluster. 

/cc @zmerlynn @satnam6502

**Comment by satnam6502** [comment]
I volunteer a workload based on Elasticsearch.

**Comment by roberthbailey** [comment]
I forked #8082 to discuss the workload part. This one is for the harness (Jenkins?) itself. Feel free to assign #8082 to yourself.

**Comment by davidopp** [comment]
@ixdy are you available to work on this?

**Comment by quinton-hoole** [comment]
@ixdy is pretty busy right now getting e2e's to run on every PR pre-merge, so that we don't keep wasting so much time tracking down regressions.  I'd like him to stay focussed on that until it's done, hopefully mid next week.

**Comment by davidopp** [comment]
Yeah sorry I didn't update the issue, I checked with him a couple of days ago and he said the same, so I was leaving unassigned for now. I am hoping @piosz can work on this but haven't discussed with him yet.

**Comment by quinton-hoole** [comment]
@saad-ali Is also interested in working on it.  I just discussed it with him.

**Comment by quinton-hoole** [comment]
Provisionally assigning to @saad-ali

**Comment by davidopp** [comment]
@fgrzadkowski FYI

**Comment by zmerlynn** [comment]
cc @alex-mohr

**Comment by zmerlynn** [comment]
@saad-ali: What's the status here?

**Comment by saad-ali** [comment]
The `kubernetes-upgrade-gce` test is set up in Jenkins. It currently picks up `gs://kubernetes-release/release/stable.txt`, deploys it to a cluster, runs E2E to verify stability, then runs the upgrade GCE script to upgrade to latest_ci, and another E2E to verify cluster afterwards. The test is not passing yet, but it works, so we can close this bug.

**Comment by zmerlynn** [comment]
Where is it failing? If you "upgrade" instead to just `stable.txt` again, does it pass?

**Comment by saad-ali** [comment]
For v17.1 to v17.1 it fails at: "line 71: set-master-htpasswd: command not
found"
This should be fixed in v18.0

**Comment by davidopp** [comment]
@saad-ali do you think you could add what is described in this comment
https://github.com/GoogleCloudPlatform/kubernetes/issues/8082#issuecomment-107650747
namely adding "invoke kube-push and run e2e again" ?

**Comment by saad-ali** [comment]
Yep, I'll take a crack at it today.

**Comment by saad-ali** [comment]
Done. Added `kubernetes-upgrade-gce-step5-kube-push` and `kubernetes-upgrade-gce-step6-e2e` to Jenkins GCE upgrade test.

**Comment by piosz** [comment]
Thanks a lot @saad-ali !

**Comment by davidopp** [comment]
+1, thanks!

**Comment by davidopp** [comment]
@roberthbailey I think we can close this. If you agree, please close it.

**Comment by alex-mohr** [comment]
Thanks for the work here!

My understanding from @saad-ali's comment at https://github.com/GoogleCloudPlatform/kubernetes/issues/8081#issuecomment-106613111 that of Robby's initial comment, the tests now do 1., 3., and 5., but not 2. or 4.?

If the e2es clean up after themselves and we're testing upgrading an empty cluster, are we vulnerable to upgrades causing existing pods/services/etc to become broken in some way?  Or restarted all pods?

**Comment by davidopp** [comment]
Agh, sorry, I wasn't paying attention. I can see from @piosz 's description in #8082 that we run e2e before and after upgrade, but not during. IIUC you're suggesting we should be running some test during the upgrade. Unfortunately we never got around to doing #8081 (and @piosz is out until a week and a half from now), so we don't have a lot of options. I think there are two choices
(i) Run e2e during upgrade in addition to before and after
(ii) Write a new correctness test (maybe @satnam6502 can do it?) that we would start right before the upgrade and would run during the entirety of the upgrade. 

Would (i) be sufficient?

BTW I didn't understand step 4: "Verifies that the cluster is still in a sane state (from the previous tests)" -- what does "sane state" mean?

**Comment by satnam6502** [comment]
Certainly happy to jump on this on Monday when I return assuming @thockin is OK with it. I think I asked this question on another thread, but don't we also want to check that the upgrade actually occurred? Otherwise the "NOP" operation would satisfy the test? This seems to suggest that we want something running that spans the lifetime of the two clusters and applies a probe to check for the dy/dx.

**Comment by alex-mohr** [comment]
The issue with e2es is that they start from an empty cluster state and return it to an empty cluster state.  I think making sure they pass before and after is necessary, but it'd be even better to test more things.

What are the invariants we want to ensure through an upgrade process?  Something like:
- components are actually running the new versions, as @satnam6502 described.
- pods/services/whatevers created before the upgrade still exist and are running afterwards?
- others?

If so, that would mean step 2 creates a bunch of pods/services/whatevers, ensures they're in a sane state (accessible via network, running, ...?), and step 4 then verifies they're still accessible, running, etc.  Step 4 probably also verifies components are the new version.  And maybe also that e.g. pods didn't get restarted or evicted or deleted?

Sorry for the super-high-level vagueness.  I think I'm proposing that someone think about what's needed to ensure a good upgrade experience, maybe document it if the existing issues don't capture that, and then start implementing paths to achieve that good experience along with the tests that will verify it holds true across future versions?

**Comment by davidopp** [comment]
SGTM. Thanks @satnam6502 for taking over this issue. For reference, @piosz 's plan was to take his load test and just add a final step where you create a service and then use it to test connectivity to all of the pods. The load test is having problems, though (and it's probably better not to conflate load testing and correctness testing right now), so it would probably be better if you were to just do something simple from scratch (it could still have the same basic idea, I guess -- e.g. create a replication controller and a service, verify you can connect to the pods through the service).

**Comment by davidopp** [comment]
@mikedanese offered to work on this and @satnam6502 was OK with that (and it seems an especially good idea since @mikedanese  just did the etcd-killing e2e test), so reassigning to Mike. Thanks, Mike!

**Comment by mbforbes** [comment]
Hmm, I don't think this should have been closed. I'm adding my comment from #9517 below.

**Comment by mbforbes** [comment]
The following could come as follow-up PRs / work, but are necessary to close #8081:

0. Validate that the upgrade actually happened. We want to ensure that the new software is really running, otherwise--as @satnam6502 pointed out in #8081--a no-op would satisfy the "upgrade".
0. Have the webserver util create a replication controller rather than just a pod. At a minimum, we want to validate the core k8s resources, and I think pod/rc/svc are the minimum. We'd have to make sure the services test still works, and we'd probably want to pull this code out of services and into util.
0. Do a bit more validation. I think we want to check, e.g., more than just the name of the service. Think of it this way: if you were running a cluster with a bunch of resources, what are all of the properties of your resources that you'd expect to hold after an upgrade? I think we need a bit deeper introspection.
0. Make the script (`hack/upgrade-e2e-test.sh`) only run stable e2es when it runs e2es before and after the upgrade. We also don't want to run the 'restart' e2e test as that does another upgrade. This will hopefully be solved soon by having the necessary ginkgo test arg strings checked into github (cc @ixdy), so we can just `curl` that and use it in the script.
0. Set up a Jenkins job to basically run what `hack/upgrade-e2e-test.sh` does. We'll have to see how this is best done given the current Jenkins script. The answer might be to have multiple "step" jobs for Jenkins that trigger each other.

The above, in my mind, will close out #8081. The following would be extra credit (after the above are fixed):

0. Validate more kubernetes resources (secretes, volumes, persistent volumes, ...?) can be created before an upgrade, (possibly) work during an upgrade, and (definitely) are correct after an upgrade.

Let's make the above change to this PR and then we can divy up the rest. (I'll also extend this to do it for nodes.)

**Comment by davidopp** [comment]
@mbforbes Do you have an ETA on the remaining work for this issue?

**Comment by mbforbes** [comment]
I updated the checklist; I can get a PR for the last item above out today.
