### ISSUE TITLE
Master upgrade cluster test

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#8082]
Forked from #3135.

Step 2 of #8081 is to "Run some amount of work on the cluster". We need a test driver that exercises the cluster before (and possibly during and after) an upgrade. 

#3139 may be sufficient and @satnam6502 had some ideas of how to stress out a cluster as well.

**Comment by davidopp** [comment]
@piosz do you think your workload generator would be suitable for this?

**Comment by piosz** [comment]
I think so. Once I'll finish load test I'll try to extract load generating part from it.

**Comment by davidopp** [comment]
Great. Assigning this issue to you.

(Satnam, feel free to also contribute your workload generator to this.)

**Comment by satnam6502** [comment]
If @piosz is on it then I shall save my energy for other things.

**Comment by davidopp** [comment]
This is basically a test for #6427

**Comment by davidopp** [comment]
@piosz did you have a chance to look into this yet?

**Comment by piosz** [comment]
So actually I implemented first version of load generator and I'm working on make it stable in kubernetes-e2e-gce-scalability Jenkins job. Since this is just a basic version of load generator and it doesn't verify that the stuff is working I want to first improve it and then apply to this test. However I may start with this test, and then use it as scalability test depending which test has higher priority.

**Comment by davidopp** [comment]
@piosz Can you give an update on your progress?

**Comment by piosz** [comment]
As for now cluster upgrade is tested in the following way ([details here](http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GCE/)):
1. create cluster
2. run e2e
3. upgrade
4. run e2e
Once #9063 will be merged we want to add the following steps:
5. kube-push
6. run e2e

I implemented first version of load generator (as load e2e test) and wanted to improve it and possibly make stable if it isn't. Unfortunately we haven't stabilized scalability suite on Jenkins yet, so I haven't got a chance to do it. Hopefully it will be done soon.

According to this issue we can of course replace steps 2, 4 (and 6) by load generator or just enable load e2e test. However the mentioned Upgrade Test GCE job hasn't passed yet, so I think the priority is to make it green.

cc @saad-ali who created Upgrade Test job on Jenkins

**Comment by piosz** [comment]
As for now the cluster after upgrade is tested by running e2e test (especially load generator I implemented runs as for now as e2e test). I don't think there would be a value in changing this approach, so we can mark this issue as completed.

Any objections? @davidopp @roberthbailey @satnam6502

**Comment by satnam6502** [comment]
That seems reasonable. Some of the e2e tests need a lot of things to be working in order to pass (e.g. the end to end cluster level logging test) although I am not sure if we can tell if the cluster was updated? Surely we need one test which can compare the "before and after" which can't run as a single isolated e2e invocation?

**Comment by piosz** [comment]
Since there is no objections I'm closing the issue.
