### ISSUE TITLE
Revert #7567 after it's been in a few versions (July or August 2015)

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#8192]
#7567 adds the ability to migrate etcd keys to a new prefix. This is fine, but it'll be tricky to use once apiserver is HA. We should either document the proper steps (shut down all apiservers, run a single apiserver with the right command to do the migration, shut down that apiserver, start all apiservers again), or (my preference) remove it. IMO it should not have gone in at all; you should use a specific tool to do the migration after shutting down all apiservers. There's no need to build that into apiserver, and in fact, it's dangerous if used incorrectly.

**Comment by jedsmith** [comment]
There's also a bug in the migration code -- since the flag for "old" etcd-prefix [defaults to a value](https://github.com/GoogleCloudPlatform/kubernetes/blob/59876df736c41093363f4c198aeec05e29c9c902/cmd/kube-apiserver/app/server.go#L121), [the migration code always runs](https://github.com/GoogleCloudPlatform/kubernetes/blob/59876df736c41093363f4c198aeec05e29c9c902/cmd/kube-apiserver/app/server.go#L312) when you specify an `etcd-prefix`. apiserver then crashes immediately on a clean setup without `/registry`:

    $ docker run --net=host -v /etc/kubernetes:/etc/kubernetes \
        -v /usr/share/ca-certificates:/etc/ssl/certs -v /var/run/kubernetes:/var/run/kubernetes \
        --name api0 quay.io/kelseyhightower/kube-apiserver:0.19.0 \
        --etcd-servers=http://127.0.0.1:2379 --insecure-bind-address=10.0.1.6 \
        --insecure-port=10000 --logtostderr=true --service-cluster-ip-range=10.200.0.0/24 \
        --v=2 --etcd-prefix=/clusters/10000
    I0619 05:52:57.151224       1 plugins.go:69] No cloud provider specified.
    I0619 05:52:57.152515       1 etcd_helper.go:621] Couldn't get the existing etcd root node.
    F0619 05:52:57.152575       1 server.go:314] Migration of old etcd keys failed: 100: Key not found (/registry) [2]

    $ etcdctl ls
    $

The workaround is to pass an empty `--old-etcd-prefix=`.

cc @kbeecher

**Comment by lavalamp** [comment]
Now that this is going to be removed, a note to those who want to use this migration functionality:

Shutdown all apiservers. Make an etcd backup. Use etdctl.
