### ISSUE TITLE
Does kubernetes support auto-scaling of containers/pods according to cpu utilization?

### ISSUE THREAD

**Issue by 289801922** [GoogleCloudPlatform/kubernetes#8242]
Does kubernetes support auto-scaling of containers/pods according to cpu utilization?
If yes, can you show me the reference?
Thanks.

**Comment by rjnagal** [comment]
This is still under work.

**Comment by rektide** [comment]
This was also mentioned in #2922, [https://github.com/GoogleCloudPlatform/kubernetes/issues/2922#issuecomment-67069629](here) and [https://github.com/GoogleCloudPlatform/kubernetes/issues/2922#issuecomment-67100187](here). That issue was also closed. I'd love to have an issue to track. This and load-balancing are what I think of as bread-and-butter for most webapp deployment scenarios.

**Comment by matschaffer** [comment]
@rektide incase you haven't come across it yet, seems like https://github.com/kubernetes/kubernetes/blob/master/docs/design/horizontal-pod-autoscaler.md has some info on the plans around pod autoscaling
