### ISSUE TITLE
Generate https certs with  Virtual IP of APIServer (for RW ports)

### ISSUE THREAD

**Issue by ArtfulCoder** [GoogleCloudPlatform/kubernetes#8371]
Please refert to #8314 for full context.

We need to reserve virtual IPs for APIServer and have them on the apiserver server-side certs so that clients can successfully validate the certs when they access apiserver using the virtual ip

@thockin @vishh @roberthbailey @cjcullen

**Comment by roberthbailey** [comment]
I'm not sure we need to put the virtual IP on the certs. Can we just use the kubernetes service name instead?

Also, it isn't needed for the RO port because a) it's going away soon and b) it's http rather than https.

**Comment by thockin** [comment]
Have a chicken-egg thing.  If we cert on the name, DNS has to be up.  But
we can't get DNS up unless we can talk to the API, which requires cert.

We can either break this (as I understand) by putting the service IP in the
cert or by putting the service IP into every container's /etc/hosts

**Comment by roberthbailey** [comment]
We don't need skydns to be up to cert on the name of the master vm (because that uses dns outside of our cluster, e.g. project dns in GCE). And we already cert on the IP of the master, so skydns can use that as well. This IP can be a VIP that is balanced across multiple apiservers for HA. Or the (external) dns name of the master can be balanced across apiservers for HA.

**Comment by thockin** [comment]
I admit I don't know enough about how certs are validated, so I'll
probably say something dumb...



On Sat, May 16, 2015 at 6:47 PM, Robert Bailey <notifications@github.com> wrote:
>
> We don't need skydns to be up to cert on the name of the master vm (because that uses dns outside of our
> cluster, e.g. project dns in GCE).

Doesn't this force DNS to talk to the master VM's IP, rather than the
service IP?  The point of having master Services is to get rid of
knowledge of the master VM.

> And we already cert on the IP of the master, so skydns can use that as well.

The public IP or the internal IP?  But again, this is the VM.  The
master should not be coupled to a machine.  Frankly, the apiserver
should be a pod controlled by a replication controller if we can do
it.

> This IP can be a VIP that is balanced across multiple apiservers for HA.

That's a Service, which is what was proposed, wasn't it?

> Or the (external) dns name of the master can be balanced across apiservers for HA.

Yeah, we could make DNS go through the external IP.  That's a hell of
a kludge...

**Comment by ArtfulCoder** [comment]
I had listed similar reasons to Tim's at https://github.com/GoogleCloudPlatform/kubernetes/issues/8314#issuecomment-102643859

The Virtual IP :
1. load balances when have more than one APIServer
2. does not need an external load balancer
3. does not need an external dns server
4. Would work across multiple cloud providers since we have no dependencies.
4. Does not preclude the possibility of accessing APIServer using a dns-name or external-ip.

**Comment by roberthbailey** [comment]
> The point of having master Services is to get rid of knowledge of the master VM.

This is true _except_ for skydns, which provides the knowledge of how to reach the master to the rest of the cluster. Other than skydns, all other pods should be using the service name (not IP) to reach the master. 

> The master should not be coupled to a machine.

What is your thinking about how the kubelet and kube-proxy should find the master? I'm proposing that skydns use the same mechanism as those two binaries, and that they should evolve in concert. When we go HA, we will need to solve this problem for kubelet and kube-proxy and then that should provide a clear path forward for skydns as well. 

> That's a Service, which is what was proposed, wasn't it?

No. I mean a VIP in the sense of using a cloud L3 load balancer. 

> The proposal is to add a virtual ip on the cert along with the existing name (kubernetes-master) and the external ip of the master.

I'm leery of putting a non-routable IP address on the cert (e.g. 10.0.0.2). I think we should put the internal service name (rather than IP) on the cert instead.

**Comment by thockin** [comment]
On Sat, May 16, 2015 at 11:18 PM, Robert Bailey
<notifications@github.com> wrote:
>
> The point of having master Services is to get rid of knowledge of the master VM.
>
> This is true except for skydns, which provides the knowledge of how to reach the master to the rest of the cluster. Other than skydns, all other pods should be using the service name (not IP) to reach the master.
>
> The master should not be coupled to a machine.
>
> What is your thinking about how the kubelet and kube-proxy should find the master? I'm proposing that skydns use the same mechanism as those two binaries, and that they should evolve in concert. When we go HA, we will need to solve this problem for kubelet and kube-proxy and then that should provide a clear path forward for skydns as well.

That's a fair point, but with a notable difference - DNS is a plain
old pod, not a special "every machine" pod.  It is salted, but only to
get config params in, not quite the same depth as kubelet or
kube-proxy.

Do we have an answer for kubelet and kube-proxy yet?  Are we sure that
the IP the master VIP gets will be stable enough to cert on? or else
use the external IP, which I guess has to be stable enough? I'm having
a hard time convincing myself...

**Comment by erictune** [comment]
For the specific case of DNS, kube-proxy, and kubelet, we control the TLS client.
So, there is no need to restrict ourselves to just IPs or hostnames.  
It could be any URI we chose which uniquely identifies this kubernetes cluster.

**Comment by erictune** [comment]
This could be a UUID as an URN: `urn:uuid:xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`.

**Comment by roberthbailey** [comment]
This issue is superseded by #8480.
