### ISSUE TITLE
NoSuchBucket on aws getting started

### ISSUE THREAD

**Issue by matschaffer** [GoogleCloudPlatform/kubernetes#8395]
I ran into this when trying out k8s on AWS via kube-up:

```sh
Creating kubernetes-staging-4e8025693080b690b0bb0a08b3fc1d98
make_bucket: s3://kubernetes-staging-4e8025693080b690b0bb0a08b3fc1d98/
+++ Staging server tars to S3 Storage: kubernetes-staging-4e8025693080b690b0bb0a08b3fc1d98/devel
upload failed: server/kubernetes-server-linux-amd64.tar.gz to s3://kubernetes-staging-4e8025693080b690b0bb0a08b3fc1d98/devel/kubernetes-server-linux-amd64.tar.gz
A client error (NoSuchBucket) occurred when calling the UploadPart operation: The specified bucket does not exist
```

I suspect it's mainly that the newly created bucket takes some time to be usable. A retry worked fine.

Figured I'd at least open this to mention it and see if enough others are hitting it to make it worth building in a check loop for bucket creation.

**Comment by justinsb** [comment]
I've never seen it personally, but what you suggest as the cause (a delay in bucket creation) does sounds plausible.

If you're motivated to fix it, that's great.  I would propose simply putting the entire upload in a retry (two or three times maybe, with a short sleep in between), because that way we also catch failures to upload due to e.g. connection loss (although I'm not sure if the aws cli tool retries those errors for us).

There are lots of examples in that same script of our (very particular) bash style, so I would recommend copying-and-pasting one of those.

**Comment by matschaffer** [comment]
Found https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/aws/util.sh#L312, is that the sort of bash style you'd recommend? Thanks!

**Comment by justinsb** [comment]
Yes, that's a good example to borrow from.
