### ISSUE TITLE
Adding & removing nodes from existing cluster (creating new instances)

### ISSUE THREAD

**Issue by madis** [GoogleCloudPlatform/kubernetes#8406]
Is there a way for adding and removing nodes from existing cluster (not just the node objects in master but actual instances too)? How do the authors see it happening or how is it done currently?

If there is no existing solution, I'm thinking of implementing this functionality either by

1. Two additional scripts like *cluster/kube-spawn-node.sh* and *cluster/kube-destroy-node.sh*. The logic would be similar to how *kube-up* creates nodes. I used spawn & destroy to avoid confusion with create/delete, hopefully signifying that actual machines are being created.
2. One one script like *kube-resize-cluster* which would take number of nodes as an argument and would spawn or destroy nodes based on that.

Do you feel there is a need for these kind of scripts? What approach would be better?

Regarding terminology, I've seen node and minion both being used. Do they mean the same or is *node* meant to replace *minion*?

**Comment by vmarmol** [comment]
There is currently no automated way to do this. The provisioning is left to the user and the addition to the cluster can be done with an API call. AFAIK there was some work to automate some of the provisioning. @alex-mohr @davidopp or @ddysher may know more.

**Comment by davidopp** [comment]
Sorry for the delay in responding. IIUC, part of what you are talking about is #6087, but you always want to tell the cloud provider to create/destroy the new nodes (e.g. create/destroy VM instances if running on VMs)? This latter thing is indeed not implement yet, but will be implemented as part of horizontal auto-scaling. We've had some initial work on this and we expect the work to continue after 1.0 (see #5492).

Since we're in a code freeze right now, this isn't a good time to work on it, but once you see activity again on #5492 please feel free to chime in and contribute.

Regarding terminology, yes, "node" and "minion" mean exactly the same thing. "minion" was the term we originally used; we've incrementally moved the code and documentation over to "node" but still have a few references to "minion" (please feel free to send PRs if you see "minion" anywhere).

Please re-open this issue if it does not address your question/comments. Thanks for your interest!
