### ISSUE TITLE
Clarify strange kubernetes behaviour (bugs or features)

### ISSUE THREAD

**Issue by pythonpowerd** [GoogleCloudPlatform/kubernetes#8661]
Hi, in order to find most suitable way(for us) to zero-downtime cluster updates i do some research of kubernetes behavior and found it very strange, so we need to know what things are bugs and what are features, what may changes in future and what not.
All for Kubernetes v0.15.

I have two nodes, and start pod on node1 then i delete node via REST delete /nodes/node1 but didn't stop any services like kubelet, docker, kube-proxy.

Results:
1) Pod still running, more than a hour... works fine, and even restarted by kubelet if it fails. No evicting process happens on this node(bug or feature?).
2) Pod has status "running" even if i stop kubelet and docker on this node.
3) After restarting pod on node (simulated fail via docker stop\kill) new containerID is updated on Master, updated pod ip. Service for this pod update his endpoints and emits events. But why? Node is even not a member of a cluster...
4) If i delete pod via kubectl on Master it will be deleted on removed node too.
5) If add this node to cluster again - pods will works fine and wouldn't be deleted during kubelet resync process.
Same behavior even for replicated pods.

What we like in this behavior is:
1) No evicting after 4 min. This gives us more time to update node. No pods will be stopped during update process.
2) We can add this node to cluster again and all pods will continue to work.

Best way for us is to control evicting behavior. May be there any way to do this? For example temporary disable it for update process and then enable at the and.
Maybe some thing like this?
```bash
kubectl update nodes $NODENAME --patch='{"apiVersion": "v1beta3", "spec": {"unschedulable": true, "evicting_policy": "off or 0min or 2hour"}}
```

**Comment by davidopp** [comment]
Hi. Some of the issues you mentioned are discussed in #7351 (although some of the codepaths were changed in #6949). 

If you pass --register-node flag to Kubelet (defaults to true), then Kubelet will create the Node object representing itself at startup, and will keep re-creating it even if you delete it via the API server; the code in Kuebelet is here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/233ce46b83aeb30b07b52ddaddf70f7ef4148ec1/pkg/kubelet/kubelet.go#L776

So if you want to get rid of a Node and --register-node==true, then you have two choices:
1) if you are running on a cloud provider, then delete the VM; this will of course kill the kubelet so it will stop re-registering, and it will also trigger this code
https://github.com/GoogleCloudPlatform/kubernetes/blob/8b498aee4ae9a8442ee6adb49608196aa5499be4/pkg/cloudprovider/nodecontroller/nodecontroller.go#L401
which will delete the Node object for you .
2) if you are running on bare metal, then shut down the machine (or do something else that kills the kubelet), and then manually delete the Node object through the API server

If --register-node==false, then the automatic registration code is not triggered. In that case you need to create and delete the Node object yourself through the API server, and the system will not try to do anything on your behalf.

Your other question was about evicting pods from nodes. If Kubelet is unreachable from master for more than 5 minutes (due to network partition, or kubelet is dead, or whatever), then it will delete the pods in the API server (which will also cause them to be deleted on the node if it comes back up). You can control this interval using the --pod-eviction-timeout; as I mentioned, it defaults to 5 minutes. You can set it longer to give you time to upgrade the Kubelet without any of the pods being killed.

BTW if you are interested in node upgrade, you might want to follow along in issue #6079.

**Comment by erictune** [comment]
Much of this is covered in docs/node.md and docs/cluster_management.md
