### ISSUE TITLE
Infra pod status on kubectl get pods is confusing and probably not necessary

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#8685]
I couldn't find an issue specifically describing this, so I'm assuming it's a bug:

```
$ kubectl get pods 
POD                        IP             CONTAINER(S)   IMAGE(S)                               HOST                  LABELS         STATUS    CREATED      MESSAGE
nettest-controller-3a11u   172.17.0.103                                                         127.0.0.1/127.0.0.1   name=nettest   Running   47 seconds   
                                          webserver      gcr.io/google_containers/nettest:1.4                                        Running   22 seconds   
nettest-controller-5453i   172.17.0.110                                                         127.0.0.1/127.0.0.1   name=nettest   Running   47 seconds   
                                          webserver      gcr.io/google_containers/nettest:1.4                                        Running   20 seconds   
```

The infra container being unidentified is confusing - and the only thing that's unique to it is the creation time relative to the first pod (which could be represented in one field).  For single container pods I'd really like to be a short list, not a long one.

**Comment by yujuhong** [comment]
I don't see the status of the infra container in your output.... For each controller, there are two lines:
- The first line is the pod-level information:  `127.0.0.1/127.0.0.1   name=nettest   Running   47 seconds `
- Starting from the second line, every line correspond to a container:  ` webserver      gcr.io/google_containers/nettest:1.4                                        Running   22 seconds`

In this case, each pod shows one container named `webserver` in the second line.
We formatted the output this way so that container statuses can reuse the columns (`STATUS`, `CREATED`, 'MESSAGE`) from the pod-level status. Alternatively, we'd need to add more columns dedicated for the containers. I agree it'd be nice to have a single line representation of a pod with only one pod though.

**Comment by smarterclayton** [comment]
Yeah, in this case there is only one bit of infra that is truly unique - the infra pod's start time, which I just don't think is very relevant to 90% of users.  I'd prefer to make that be something you have to use describe for if it reduces our number of lines by a factor of two.

**Comment by bgrant0607** [comment]
Related: #7843

**Comment by dchen1107** [comment]
We hide infra container completely from kubectl. In your example, it is a better kubectl output.

**Comment by derekwaynecarr** [comment]
I think its clearer if container status and pod status do not piggy back on the same column.

**Comment by derekwaynecarr** [comment]
I guess CREATED is the same issue.  I can see having too many columns is a problem, and maybe width is the main confusion for me when I use it since there is wrapping.

**Comment by bgrant0607** [comment]
We should merge this discussion w/  #7843

**Comment by yujuhong** [comment]
> Yeah, in this case there is only one bit of infra that is truly unique - the infra pod's start time, which I just don't think is very relevant to 90% of users.

@smarterclayton, I am not sure if you meant the infra container (which we don't expose at all) or the user container (`webserver`) in your example.


> I guess CREATED is the same issue. I can see having too many columns is a problem, and maybe width is the main confusion for me when I use it since there is wrapping.

@derekwaynecarr, yes, there are pros and cons about sharing columns, and width is definitely a problem. We can continue the discussion in #7843 :)


> We should merge this discussion w/ #7843

Agreed. Closing this issue. Feel free to reopen if I misunderstood the issue.
