### ISSUE TITLE
Should we expose a reason for LoadBalancer creation failure?

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#8760]
If a LoadBalancer cannot be created (e.g. quota limit hit), there is currently no way to know why other than reviewing the logs (?).  We could put an status message / object into LoadBalancerStatus.

**Comment by pmorie** [comment]
We could make an event for this too

**Comment by lavalamp** [comment]
+1 for event

**Comment by thockin** [comment]
I think that is reasonable, but we need to be careful how we define it.
Event also sounds good.

**Comment by bgrant0607** [comment]
I'm in favor of status as well as an event. The pattern I recommend is an array of conditions, similar to NodeCondition, where each contains at least a Status, Reason, and Message.

**Comment by a-robinson** [comment]
+1 for an event. I'd argue this is important enough for usability that we should get it into v1.

**Comment by bgrant0607** [comment]
How often does this failure mode occur?

**Comment by a-robinson** [comment]
I unfortunately don't have stats, but it can happen for a handful of reasons. I think these are the most likely:

* Cloud provider unavailability/errors
* Ran out of quota from the cloud provider
* The cluster is using a cloud provider that doesn't support external load balancers

I expect the third one is most common by far. We could perhaps move that into the API object validation rather than writing events to handle that particularly case, but using events would solve all the cases together.
