### ISSUE TITLE
Shell auto completion support

### ISSUE THREAD

**Issue by noonien** [GoogleCloudPlatform/kubernetes#8773]
Since sometimes kubernetes commands can get quite big, having zsh/bash auto completion would be quite a time saver.

I understand might be the lowest priority for the project right now, but it would be a great feature to have.

**Comment by mikedanese** [comment]
Bash completion is generated for kubectl command. You can drop https://github.com/GoogleCloudPlatform/kubernetes/blob/master/contrib/completions/bash/kubectl into your /etc/bash_completion.d. Not sure if this is documented anywhere though.

**Comment by mikedanese** [comment]
Please reopen if you have questions.

**Comment by dserodio** [comment]
What about zsh completion, should I file another enhancement request?

**Comment by mikedanese** [comment]
completions are generated by https://github.com/spf13/cobra. once they have it, we get it for free.Maybe file it there

**Comment by wernight** [comment]
There is a feature request on Cobra, https://github.com/spf13/cobra/issues/107, but not yet resolved.

**Comment by mikedanese** [comment]
Cobra already supports bash completion

**Comment by wernight** [comment]
I'm talking about ZSH.

**Comment by olalonde** [comment]
Is  zsh completion available yet?

**Comment by michaelfavia** [comment]
@olalonde: Yes zsh completion is currently shoehorned in kubectl via `kubectl completion zsh` this issue is currently addressing the fact that it is a design goal of the upstream project "cobra" to automate the creation of this script. It is currently being managed by a thin compatibility layer in the kubectl source that is more brittle and difficult to maintain.

If you wan tot add zsh shell completion to your shell you can (among other options):
`source <(kubectl completion zsh)`
