### ISSUE TITLE
Use local gce metadata server in kubelet

### ISSUE THREAD

**Issue by simon3z** [GoogleCloudPlatform/kubernetes#8911]
Kubelet / gce provider should access the local metadata server to get the Instance ID of a node.

Reference: https://github.com/GoogleCloudPlatform/kubernetes/pull/7775#discussion_r31180032

 		// TODO(roberthbailey): Can we do this without having credentials to talk
 		// to the cloud provider?
		externalID, err := instances.ExternalID(kl.hostname)
		if err != nil {
			return nil, fmt.Errorf("failed to get external ID from cloud provider: %v", err)
		}
		node.Spec.ExternalID = externalID
		// TODO: We can't assume that the node has credentials to talk to the
		// cloudprovider from arbitrary nodes. At most, we should talk to a
		// local metadata server here.
		instanceID, err := instances.InstanceID(node.Name)

/cc @bgrant0607 @roberthbailey

**Comment by roberthbailey** [comment]
@quinton-hoole When https://github.com/GoogleCloudPlatform/kubernetes/pull/7775 goes in we'll be hitting the GCE API quite a bit more... so this should get fixed asap.

**Comment by simon3z** [comment]
@roberthbailey @bgrant0607 how come kubelet should access the cloud provider? Can't we just have `nodecontroller` to fill in the missing information? (And keep only `nodecontroller` the one accessing the cloud provider which seem safer).

**Comment by roberthbailey** [comment]
The kubelet should be able to gather information from the local metadata server about itself (provider ID, internal and external IP, etc) which doesn't require any special permissions or making calls to the cloud provider's API. 

Since this process is different for each cloud provider, it uses the cloud provider abstraction in our code. Unfortunately there isn't an obvious distinction in that abstraction between calls that actually hit the cloud provider API and calls that should only be implemented in terms of gathering data locally from a metadata server.

**Comment by roberthbailey** [comment]
I had thought that `InstanceID(instance string)` would be hitting the GCE API but instead it is just computing the instance id with the passed in name. This is a non-issue.
