### ISSUE TITLE
kube-down.sh does not cleanup aws keypair for kubernetes

### ISSUE THREAD

**Issue by hurtz** [GoogleCloudPlatform/kubernetes#8932]
When creating a Kubernetes cluster in any AWS region a new keypair is created named kubernetes. When calling kube-down.sh, this keypair is not removed, making the next kube-up.sh in the same region fail when looking for the salt-master. Once the key is manually removed the cluster can be created successfully.

**Comment by justinsb** [comment]
This should only fail if you use another machine or otherwise switch the contents of ~/.ssh/kube_aws_rsa.

But you're right, this is an issue, and we have other issues related to this also.

I'll figure out a better way (I also want to support multiple clusters in a single AZ/region, and those could overlap and even have different keys - maybe).

**Comment by justinsb** [comment]
I just proposed #9294.  We include the public key fingerprint in the name, so that the tool won't get confused by different keys.

We don't delete keypairs, so theoretically they leak, but I don't think this is a huge problem.

**Comment by justinsb** [comment]
#9294 has merged.  I'm going to close this, as I think/hope that is a good solution.  If not, please feel free to reopen though.
