### ISSUE TITLE
Garbage collect container log file symlinks

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#8945]
A user who was hit by a crash-looping DNS pod (see #8144) says that he's "seeing 7,891 log files in /var/log/containers for kube-dns-*". We should be cleaning these up at some point.

@satnam6502

**Comment by satnam6502** [comment]
We have log rotation set up for Docker container logs (set up by @brendandburns I think). If we have a crash loop then the log rotation frequency we have right now is not going to save anyone. I am not sure that changing the log rotation frequency to catch crash loops is the right thing to do. If this pod is ill then surely nothing else (much) is working in the cluster and this is the least of your problems?

**Comment by satnam6502** [comment]
Also, are the symlinks the issue, or the actual log files?

**Comment by rjnagal** [comment]
@satnam6502 parking in your bucket while we decide what needs to be done here for v1.

**Comment by a-robinson** [comment]
The issue is to ensure we have *something* making sure we don't allow a resource to grow unbounded over time, so that nodes can run indefinitely without running out of disk. The logs themselves being garbage collected is great. Is there anything that ever garbage collects the symlinks?

It's possible that there is something already and it just hadn't cleaned up this user's symlinks yet, which would be great, but if not, we should seriously consider adding something.

**Comment by satnam6502** [comment]
I view the symlinks as a temporary terrible hack until we can get the required metadata in a more disciplined manner.

**Comment by justinsb** [comment]
I'd also like to get the metadata into the logs, which is I think what these symlinks are about.  I can see two options: we can either have the log collector connect to the API, or we can have kubelet write the information (the pod info) to a JSON file under /var/lib/containers/ (and GC it!)

Any thoughts on which way is better?  And if the latter, what are the chances of getting this into 1.0?

**Comment by justinsb** [comment]
e.g. I'm thinking we should write a data file like this (totally untested, just "here's what I mean"): https://github.com/GoogleCloudPlatform/kubernetes/commit/e6d8ac6d2e867d0a5eaa3af433d4beccade86b45

**Comment by satnam6502** [comment]
@jimmidyson is our man I think for doing this properly.

**Comment by a-robinson** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/8632 is in the works, although perhaps less elegant than your example

**Comment by justinsb** [comment]
That PR doesn't look it includes labels though, although maybe I can abuse naming & namespacing to meet my current requirements.

BTW, found this little trick to delete those broken links:
```find -L /var/log/containers -type l -delete```

The trick is explained here: http://www.trilithium.com/johan/2011/09/delete-broken-symlinks/

**Comment by jimmidyson** [comment]
The fluentd plugin in #8632 can add metadata retrieved from api server, but there's still an unanswered question on service accounts for static pods required to authenticate to api server.

I really like the metadata file being local on the node. How would you deal with label updates to running pods? With the fluentd plugin we set up a watch to be notified of pod label changes to update metadata. With the file approach could set up file watches I guess.

But that's out of scope of this issue & should probably be discussed in a separate issue. The crux of this issue is that symlinks should be garbage collected at the same time as the docker container. Should be a quick easy fix to make.

**Comment by satnam6502** [comment]
The reason I did not add code to delete the symlinks as soon as the container is deleted is that we need to allow so time for the collector to grab the last few dying breath log lines before the symlink is deleted. For this I thought we could just spawn a goroutine with a delay (5 minutes?) after which the deletion occurs. Right now that is not done so if the symlink is deleted as soon as the container is deleted then we will loose log lines.

**Comment by jimmidyson** [comment]
With docker when the container is deleted isn't the log file deleted too? So the symlink will be a dead link... no need to keep it after container is deleted.

**Comment by satnam6502** [comment]
The log file lingers.

**Comment by jimmidyson** [comment]
@satnam6502 Are you perhaps confusing stopping a container (`docker stop` / `docker.StopContainer`)  with deleting a container (`docker rm` / `docker.RemoveContainer`)? AFAIK the latter deletes the whole container from the file system, including the log file & this is what happens in container GC - see https://github.com/GoogleCloudPlatform/kubernetes/blob/4a6ab7fd3698c5cc7172c5bd63efab320d1f2d17/pkg/kubelet/container_gc.go#L178.

IMO we have to clean up symlinks when the container is deleted by container GC else we're leaving dead symlinks as the OP stated.

**Comment by satnam6502** [comment]
What I notice is that after a container for a Kubernetes pod is not running anymore and has been restarted (i.e. another container is running for that image) the log files for the old ones are still around ( and thankfully subject to log rotation). Perhaps I am wrong? I will check.

**Comment by satnam6502** [comment]
But yes, we need to delete the symlinks of course -- just in a way that does not loose log lines.

**Comment by jimmidyson** [comment]
Right so there's the difference between a pod being deleted & a docker container being deleted. When a pod is deleted the underlying docker container is not deleted so the docker log file remains until the docker container is actually deleted.

The docker container is deleted only through container garbage collection & that only happens when certain thresholds are met (e.g. 100 dead containers). When the docker container is deleted the log file is also deleted at this point.

So we need to add the symlink cleanup to the docker container deletion which is done in container GC, not pod lifecycle.

**Comment by satnam6502** [comment]
Thanks for clearing that up (quite literally).
