### ISSUE TITLE
Help needed to update the examples in getting-started-guides/mesos.md

### ISSUE THREAD

**Issue by caesarxuchao** [GoogleCloudPlatform/kubernetes#8957]
Hi @ConnorDoyle @jdef  @guenter @nak3, 

We are updating docs to v1beta3. v1beta1 and v1beta2 will be abandoned soon. For the examples in getting-started-guides, we tend to use hyperlinks to point to examples instead of letting them have their own individual examples (see #5799). 

However, in the mesos guide, the examples contain mesos specific setup and knowledge, so I can't simply remove the texts and point to kubernetes/examples/guestbook, which is updated to v1beta3. My suggestion is that we update the guestbook example in kubernetes-mesos, and use a hyperlink in mesos getting-started-guide to replace the example texts. Could you help to make the changes? Thanks.

**Comment by caesarxuchao** [comment]
cc @nikhiljindal @krousey @bgrant0607

**Comment by bgrant0607** [comment]
We're going to delete v1beta1 and v1beta2 in O(days). See PR #8917.

**Comment by bgrant0607** [comment]
cc @davidopp

**Comment by jdef** [comment]
we've initiated an effort to upstream some components into k8s. as part of
that effort, we're upgrading the guestbook examples for k8s-mesos:

https://github.com/mesosphere/kubernetes-mesos/tree/upstream_k8sm

the getting started guide for mesos will likely have to change in order to
align with the move upstream.

tracking this issue here:
https://github.com/mesosphere/kubernetes-mesos/issues/295

**Comment by jdef** [comment]
xref https://github.com/GoogleCloudPlatform/kubernetes/pull/8882

**Comment by bgrant0607** [comment]
Ref #8087

**Comment by bgrant0607** [comment]
cc @krousey

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/295

**Comment by bgrant0607** [comment]
This needs to be moved to the v1 API.

**Comment by jdef** [comment]
Agreed. We have changes in review right now, should be merged soon.
