### ISSUE TITLE
Provide versioned documentation

### ISSUE THREAD

**Issue by kprobst** [GoogleCloudPlatform/kubernetes#8969]
We should provide versioned documentation, so that customers who use a specific version (like 1.0) will have access to 1.0-specific documentation, rather than only to documentation at head.

One suggestion is to provide shortlinks to versioned docs such as:
docs.k8s.io/v0.17/README.md

**Comment by bgrant0607** [comment]
That's what github tags are for. :-)

**Comment by roberthbailey** [comment]
I thought we were planning to snapshot v1.0 documentation onto kubernetes.io and leave github documentation floating at HEAD. Folks who are using a stable version of kubernetes shouldn't need to browse Github to learn how to use it. Github should be primarily targeted at developers.

**Comment by bgrant0607** [comment]
Ok, fair enough, but we're terrible about keeping the docs in sync with the code, so docs snapshotted when we do a release are unlikely to actually match the release functionality, unless we change our policy for accepting PRs.

**Comment by bgrant0607** [comment]
We also need to make the docs worth looking at.

**Comment by RichieEscarez** [comment]
Im working on moving all non-Kubernetes Contributor content (all docs not targeted at developers) into [Kubernetes.io](http://kubernetes.io/). Kubernetes.io should reflect HEAD and not be frozen (snapshotted) so we can continue to resolve doc bugs, fill doc gaps, and add new content. 

Its too much overhead to try and document every version (ie. 0.17) and would be a maintenance nightmare and a publishing challenge especially since (as bgrant0607 mentioned), the docs are always behind (so a single doc update would increase/be mulitplied by the number of versions we maintain). 

I will work on getting a clear answer about how we will document for version changes once we move  all the "user" content into Kubernetes.io. *Note: the published content at kubernetes.io does not have the tags options but you could continue to view anything that gets tagged from the "[gh-pages](https://github.com/GoogleCloudPlatform/kubernetes/tree/gh-pages)" branch in GitHub (but you lose the "worth looking at" formatting)).*

**Comment by roberthbailey** [comment]
> We will need to hold off on publishing changes in HEAD that are not released (so doc changes and binaries go out at the same time).

I think this is a recipe for disaster. Documentation at head should match code at head, not code at the latest stable release. Otherwise developers will have no idea of the current state of the project and we will have a huge backlog of documentation PRs that get merged at the same time we cut a release.

Why can't we sync documentation on kubernetes.io to the latest stable release branch? If we find a documentation bug, we can create a PR to fix it in the release branch (and at head it if applies there as well).

**Comment by RichieEscarez** [comment]
The way the "GitHub Pages" feature works is that whats in HEAD of the gh-pages branch gets published to Kubernetes.io. Ill look into what options we have here? Maybe we create and maintain a new "gh-pages-HEAD" branch so that branch acts as doc HEAD and aligns (in sync) with developments HEAD (therefore doc HEAD content is not automatically published and we can control when to push "gh-pages-HEAD" into "gh-pages" for publishing to k8s.io)?

**Comment by brendandburns** [comment]
This is addressed with the PR here:

https://github.com/GoogleCloudPlatform/kubernetes/pull/9305

Which will clone the docs.

And yes, @bgrant0607 there is a chance that they will be out of date anyway, but they definitely won't be any _worse_ than what is at head.

@RichieEscarez we should also work to scriptify the migration of docs from vanilla github into the gh-pages branch.  We should be a little bit more careful and principled about how we do that, since those docs will be "official".

**Comment by brendandburns** [comment]
Additionally I added Documentation and Examples links to the release pages for 0.18.1 and 0.17.1, we should continue to do that going forward.

**Comment by goltermann** [comment]
Fixed with merge of the Add Links to 0.19.0
