### ISSUE TITLE
Add a link to a public k8s presentation to our main README.md or one of the other docs pages

### ISSUE THREAD

**Issue by davidopp** [GoogleCloudPlatform/kubernetes#9205]
I recently gave a public talk on k8s and got some feedback that the presentation was useful for understanding the system at a high level (this came from someone who had already poked around in our Github site). I think we should put a link to a presentation on our main README.md or one of the other documentation pages.

In theory we could post a video of someone giving a presentation, or a presentation with detailed Notes section on each slide to flesh it out, but for now I think just a bare presentation is probably good enough.

**Comment by bgrant0607** [comment]
That's a good start, but I think we should incorporate similar diagrams directly into our docs.
@RichieEscarez @mansoorj

**Comment by davidopp** [comment]
I think we want both, not either/or. Presentation is a very different format than documentation/howto/getting started guide/etc. 

I will clean up the most recent presentation I gave (remove backup slides and any speaker notes) and send out a PR to add a link to our github page.

**Comment by RichieEscarez** [comment]
Today we have this wiki page with other presentations and videos: https://github.com/GoogleCloudPlatform/kubernetes/wiki/Media

I am also working this into the restructuring of the site (for our near future move out of GitHub.com and into Kubernetes.io) so that we will have a dedicated page for this type of material (and its clearly visible from the site navigation tree). 

I think in general (and agree with @bgrant0607), that we(I) need to incorporate what makes the presentation "useful" into our Overview/Conceptual information (once moved to Kubernetes.io) and then we can supplement the overview/conceptual info with links to presentations, videos, etc.

**Comment by juliaferraioli** [comment]
Presentations generally have a very different utility and audience than documentation. Short videos and the like may be useful in line with the documentation, but in general users want a centralized location to view media such as presentations à la what @RichieEscarez mentioned.

Keep in mind that if you put a presentation in the documentation itself, you need to commit to keeping it updated with current terminology, links, etc... because it is now part of the documentation. Whereas if you put it in a separate location, it's more accepted to be a bit more ephemeral.

**Comment by RichieEscarez** [comment]
@davidopp Ive created a "Media" page (still in review, see #12501) that can be used as a repository for links to useful videos, presentations, and other documents

**Comment by davidopp** [comment]
I'll just close this issue, though I still wonder if we should have some kind of slideshow right on the kubernetes.io page to give people a high level overview of the reasons they should want to use Kubernetes and define the basic abstractions. (In other words, basically the talk we've been using publicly, maybe a little condensed.) But Julia makes a good point about having to keep it very up to date if it's on the main page. Also, in general it doesn't seem like there was much interest in this idea.
