### ISSUE TITLE
Emulate 'createExternalLoadBalancer' support with default 'publicIPs' list

### ISSUE THREAD

**Issue by matt-deboer** [GoogleCloudPlatform/kubernetes#9320]
question/possible-enhancement:
Currently in the docs (in various places), I read that if your cloud provider doesn't support 'createExternalLoadBalancer', you have to modify your Service definitions to contain a list of 'publicIPs'.
I'm in the process of testing k8s in various deployment scenarios, and it's a little annoying to have to change my service definitions (or template them and token-replace) for each cluster environment.
Is there any way I could provide a default list of "publicIPs" for my cluster as a fall-back for lack of 'createExternalLoadBalancer'-support?

**Comment by thockin-cc** [comment]
Good news, I hope. PublicIPs is deprecated, in part because it only sort of
limps along as you experienced.

Instead, set your Services with spec.type = "NodePort". This will allocate
a port (not your Service's port, so no conflicts) that is exposed on every
node. You can then set up your own LB to target that port on one or more
nodes. Or you can use DNS-RR with SRV.

Tim
