### ISSUE TITLE
Don't show cluster addons by default

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#9356]
We've discussed using labels or even namespaces so that cluster addons don't show up in kubectl output by default. Users appear confused by this when they get pods, rcs, services.

Addons are labeled, so this filtering should be possible.

**Comment by davidopp** [comment]
But users are also confused when the node has less available resources than the machine's capacity. I think hiding this stuff may be more confusing than not.

**Comment by bgrant0607** [comment]
The problem is most severe when working through an example:
* create one service and RC and see half a dozen of each
* create 3 pods and see a dozen

Perhaps describe node should indicate what's running on it -- at least number of pods and amount of resources reserved. Probably would need to add that to node status since users won't be able to get all the pods when authz is enabled.

**Comment by davidopp** [comment]
I really like the idea of "describe node" showing all the pods running on it, and their limits/requests/whatever. As you know, we have this in Borg, and it's definitely the most useful debugging page we have. I think that would make it more reasonable to hide the cluster addon pods. 

But as a secondary issue, are you implying that when we have authz, you won't be able to see pods from other namespaces when you use kubectl and the API directly? If so, I really hope that behavior is optional (configed by administrator). I think most organizations will want to prevent users/groups from mutating cluster state belonging to other users/groups, but seeing the cluster state is a different matter. Allowing users to see all the details of what other users are running is tremendously helpful for self-service problem debugging (i.e. I don't think saying just admins can see everything is sufficient). Just aggregating and displaying the limit/request of pods-not-belonging-to-you isn't sufficient either IMO (though it's better than nothing) because users still may want to see everything to better understand resource interference effects from other pods on the same machine, etc.

**Comment by erictune** [comment]
The two authorization policies that make the most sense to me are:
 - typical users can read node objects.  - Borg model.
 - typical users cannot read node objects.  - GCE model.
Brian seems to be implying some middle ground which I hadn't considered.

In either model, it makes sense to me to put the addons in a different namespace than is used by a typical user.  This has nothing to do with authorization, and just has to do with ensuring that I don't have a name collision with objects I don't care about.

Hiding them with labels seems bad because you don't see them but you can still have a name collision.  Unlikely, but it feels like the wrong solution.

**Comment by bgrant0607** [comment]
I prefer putting the addons in a different namespace. The main reason they aren't now is lack of convergence of previous rounds of discussion.

**Comment by bgrant0607** [comment]
One of the previous discussions (though I think main discussion was offline): https://github.com/GoogleCloudPlatform/kubernetes/pull/4417#discussion_r24699831

**Comment by bgrant0607** [comment]
cc @piosz

**Comment by erictune** [comment]
cc @thockin

**Comment by davidopp** [comment]
I'm not really objecting to putting them in a single namespace, I'm just saying that the Borg experience suggests that it's absolutely crucial that the user be able to see everything that's running on the machine, and the associated resource request/usage. So I like Brian's suggestion of putting this in "describe node" (and, if we really must have some super-secretive mode, which honestly I don't see the value of, then we could do as Brian suggested and just aggregate the request/usage information of all of the pods that don't belong to the user, into one opaque bucket--but this should not be the default way the system works).

**Comment by dchen1107** [comment]
"kubectl describe nodes" already display which pods on it, but lack of namespace and resource related information.

**Comment by dchen1107** [comment]
But I don't think it is easy to retrieve resource usage related information for pods today. node team did export such information long time back, but removed due to API refactory later. Also  please note that there is no Pod level resource request at our API yet.

**Comment by bgrant0607** [comment]
@davidopp They don't all need to go into a single namespace, just not in the default namespace.

**Comment by bgrant0607** [comment]
@dchen1107 At the moment, we don't need actual resource usage. We only need resource limits, since that's the only info used in scheduling.

**Comment by derekwaynecarr** [comment]
@davidopp - the user can list namespaces, so if I understand this correctly, it's not that the user will not be able to find the pods, they just have to get namespaces, and then get pods in that namespace.

Is there a proposed name of the namespace that holds add-ons?

**Comment by dchen1107** [comment]
@bgrant0607 I agreed that we don't need resource usage now. But for resource limit, it is only at container level, no pod level. Are we going to show all containers too when describe node?

**Comment by davidopp** [comment]
@erictune pointed out that the "describe nodes" model where it only shows your own containers, and nothing about other containers (even aggregate request or usage), is important for people who use k8s to run a hosting provider. So I could see an admin wanting to configure any of the three options we've discussed here (Borg model, GCE model, GCE model but showing you only aggregate stats about stuff that doesn't belong to you). @bgrant0607 pointed out that the right way to define "your own" in this context is "your namespace and all other namespaces you have access to" (and needs to specifically include the namespace that we put the addons into, if we put addons in a separate namespace. which I now realize means that each other's addons would need to be in a separate namespace, as opposed to putting all addons in one namespace.)

We also discussed the main question, of whether the right way to avoid showing them by default is to put them in a separate namespace or just use labels and then by default don't show stuff with those labels. The former seems more principled and seems to be what people are leaning towards, but I think we need to think through the implications for the features that are namespace-based, like admission control, quota, LimitRange, billing (I assume we'll have that eventually), etc. None of the stuff the user sets up for their own pods (with respect to these features) would apply by default to the cluster addons if we put the cluster addons in a separate namespace. This might be a good or bad thing.

@dchen1107 I think it would be good to show all containers in "describe node" (for the same reasons it's useful that we show in-alloc tasks in Borg machine debug output, not just allocs).

**Comment by dchen1107** [comment]
Please don't put all containers related information when describe a node. I believe very soon we are going to get people complaining about describe nodes useless like what we had for kubectl get pod. I spent a lot of time on arguing with ppl that you can use describe pod to get detail information about a pod, please don't make get pod too verbose, but failed. Now we reset everything back to the original state. I don't want to get into the same situation again with describe node. 

But I do feel there are several missing pieces for the user to figure out what's going on with the node. #9356 is filed to include namespace for each pod running on a node, so that the user can easily get / describe that pod for more information. #9435 is filed to check namespace specific quota and other resources belong to the same namespace. 

There is no pod-level resource limit at API level, but we could have it by summing up all container's limits.

So here is the complete proposal:

kubectl describe node id will include 
1) all information from NodeStatus, which includes resource capacity, system info like daemon versions, creation timestamp, NodeCondition, etc. 
2) pods and corresponding namespace, and pod-level resource request / limit
3) node level events

kubectl describe pod id will include 
1) all information from PodStatus: Condition, Phase, namespace, etc. 
2) all user-defined container (ruled out network container) including per container's resource request / limit
3) pod and container level events.

With the fix, I am ok to put addson into a separate namespace then. :-)

**Comment by davidopp** [comment]
@dchen1107 mentioned the more verbose output suggestion I made is related to #3500 and could be handled by a separate command as suggested there.

**Comment by davidopp** [comment]
sorry I meant the verbose output suggestion Brian made :-) (but I agree with it)

**Comment by davidopp** [comment]
@fgrzadkowski @gmarek @marekbiskup

**Comment by piosz** [comment]
Is there any decision made? I'm happy to fix it once the decision is made.

**Comment by satnam6502** [comment]
Where are we with this issue? I suggest:
* It's too late to move the add-ons to a different namespace before 1.0
* We keep the add-ons visible as is the case now when someone does `get pods`.
* The more concise output makes this less troublesome.
* Consequently I propose that we close this issue and re-think add-ons etc. post 1.0

Agreed?

**Comment by dchen1107** [comment]
Agreed with @satnam6502, and my suggestion is do nothing for 1.0 since we already have a concise output for kubectl get pods.

**Comment by davidopp** [comment]
+1

**Comment by thockin** [comment]
Last time (if I recall) we decided that defsault was fine for addons, and
that users should start their kubernetes experience with "here's how you
create a namespace".  Why don't we just update examples?

**Comment by davidopp** [comment]
I remember that was discussed as a possibility, but I didn't realize it had been firmly decided (and I guess at least some others didn't remember it either).

I guess my concern would be whether this would be considered unnecessary complexity that would negatively affect the kick-the-tires experience.

**Comment by dchen1107** [comment]
@thockin I am not sure we decided on that. If we ended to do that, I want create a default LimitRange object for each namespace by default. We had tons of issues caused by overcommit nodes nowadays, and there is no way to protect the nodes without reasonable admission control. LimitRange is the minimum thing we can do for now.

+1 on @davidopp said about the complexity too.

**Comment by davidopp** [comment]
I think #5547 is an alternative to LimitRange if we just care about limiting number of pods per node. (Actually using the feature is blocked on #8802 because there was some disagreement as to how to best set different flag value in test vs. production, but we could easily get that submitted and use the feature if it was considered important for 1.0.) We had put testing it on the back burner since we thought LimitRange was sufficient for 1.0.

**Comment by dchen1107** [comment]
I don't treat #5547 as an alternative to LimitRanger since there is no easy way to configure it based on node side. 

For our internal system, I treated max_tasks_on_node as the control knob for capping daemons' management cost. Based on that we could roughly estimate the time / resource the agent needs to manage the workload on a machine at the worst case. So that we can do a careful resource provisioning and proper resource management. Unfortunately 1.0 we don't have much resource management thus, we run into tons of issues for overcommit nodes.

**Comment by satnam6502** [comment]
+1 to what Tim says.

**Comment by bgrant0607** [comment]
The whole point of the default namespace is to reduce friction for kick-the-tires users, demos, etc. We shouldn't even have a default namespace if we were going to require users to always create their own namespaces.

**Comment by bgrant0607** [comment]
More and more people keep complaining about this, and I think it's justified. The default namespace should be reserved for kick-the-tires users.

Openshift uses namespace `openshift-infra` (https://github.com/GoogleCloudPlatform/kubernetes/pull/9975#issuecomment-113191817) for a similar purpose. I think we should use simply `kubernetes` as the namespace for addons, not unlike our label prefix `kubernetes.io`. Thoughts @derekwaynecarr or @smarterclayton?

@thockin said that it may be too late to move the Kubernetes service (any opinions @roberthbailey?), but I'm ok with leaving that in default, if necessary.

**Comment by satnam6502** [comment]
I assume you mean both the static/mirror pods (e.g. fluentd-cloud-logging) as well as the add-on pods (elasticsearch-logging).

**Comment by smarterclayton** [comment]
> On Jun 19, 2015, at 5:35 PM, Brian Grant <notifications@github.com> wrote:
> 
> More and more people keep complaining about this, and I think it's justified. The default namespace should be reserved for kick-the-tires users.
> 
> Openshift uses namespace openshift-infra (#9975 (comment)) for a similar purpose. I think we should use simply kubernetes as the namespace for addons, not unlike our label prefix kubernetes.io. Thoughts @derekwaynecarr or @smarterclayton?
> 
No objection - this has come up on our end as well.  We have our registry and router in the default namespace but we want to move it out.

**Comment by roberthbailey** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/10107 assumes that the kubernetes service (to reach the master) is in the default namespace.

**Comment by satnam6502** [comment]
I am happy to make and test this change (for GCE) on Monday (swamped with on-call today).

**Comment by smarterclayton** [comment]
If we want fix this... I think we should fix it before 1.0.  Because it will be near impossible to fix later.  

----- Original Message -----

**Comment by derekwaynecarr** [comment]
No objection.  Whatever we settle on needs to be identified as immortal in the related PR that blocks deletion of the default namespace.

**Comment by davidopp** [comment]
I'm fine with it since "describe node" shows all of the pods from all namespaces. My main concern was that too much would be hidden from the user. We should document the add-on pod stuff better, though -- in some sense we are exchanging one problem (too much information) for another problem (too little information). But I do think putting them in a separate namespace is a good idea.

**Comment by dchen1107** [comment]
"describe node" just recently add namespaces associated with each pod. But still if you have 100 nodes, you are going to describe them one-by-one to find your addons pods?

**Comment by davidopp** [comment]
Maybe we can add a command-line flag to "get pods" that lets you limit the query to only a particular namespace, and also lets you say "from all namespaces" ? (Default behavior would be to only show from default namespace.)

**Comment by satnam6502** [comment]
Surely `get pods` already has a `--namespace` flag which selects the namespace?

**Comment by davidopp** [comment]
Ah yes, good point. Can you use it to say "all namespaces"

**Comment by dchen1107** [comment]
My above comment https://github.com/GoogleCloudPlatform/kubernetes/issues/9356#issuecomment-113668647 is replying @davidopp's describe node one. 

If we decided to put addons pods to a well-known and reserved namespace, I am fine with it.

**Comment by satnam6502** [comment]
No, but that would be good. Perhaps --namespaces should take a regexp

On Fri, Jun 19, 2015 at 4:20 PM, David Oppenheimer <notifications@github.com

**Comment by davidopp** [comment]
Yeah, I think that would address the concern. Then you could continue to get the current "get pods" behavior if you use the flag.

**Comment by satnam6502** [comment]
@jlowdermilk about a possible change to kubectl

**Comment by jlowdermilk** [comment]
IIRC, having a single kubectl command work across multiple namespaces was considered a security risk. @smarterclayton, is that still the case?

**Comment by bprashanth** [comment]
> IIRC, having a single kubectl command work across multiple namespaces was considered a security risk.

doesn't --all-namespaces already do this?

**Comment by davidopp** [comment]
I don't think that flag exists. I tried it and got
```
Error: unknown command "--all-namespaces"
```

BTW what is the current state of our IAM? If we don't currently restrict the namespaces in which a user can mutate objects, then I don't see the harm in letting them see the objects in all namespaces. I can see that down the road we would want something more secure, but for now it seems overly restrictive.

**Comment by bprashanth** [comment]
it's hidden away, I use it fairly regularly because our e2es setup a custom ns
```
$ k get pods --help 2>&1 | grep all
// List all pods in ps output format.
// List all replication controllers and services together in ps output format.
      --all-namespaces=false: If present, list the requested object(s) across all namespaces. Namespace in current context is ignored even if specified with --namespace.
```

**Comment by davidopp** [comment]
Is that new? I ran your comment and didn't see it.

```
$ kubectl get pods --help 2>&1 | grep all
// List all pods in ps output format.
// List all replication controllers and services together in ps output format.

$ kubectl version
Client Version: version.Info{Major:"0", Minor:"17", GitVersion:"v0.17.0", GitCommit:"82f8bdac06ddfacf493a9ed0fedc85f5ea62ebd5", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"18+", GitVersion:"v0.18.2-590-gb68e08f55f5ae5", GitCommit:"b68e08f55f5ae566c4ea3905d0993a8735d6d34f", GitTreeState:"clean"}
```

**Comment by davidopp** [comment]
I see it was added here
https://github.com/GoogleCloudPlatform/kubernetes/commit/8ce64ec69e560379d888f7b58483e4b22bb7e462

so never mind.

**Comment by bgrant0607** [comment]
All these cross-namespaces issues exist when the addons are in default, also, so that shouldn't block moving the addons.

@satnam6502 Yes, mirror pods shouldn't be in the default namespace, either.

**Comment by smarterclayton** [comment]
Mirror pods in an infra namespace helps control admission decisions as well.

**Comment by smarterclayton** [comment]
It's more that it needs to be explicit - you have to tell us when you want to operate in a different context.  We finally have a concrete need for identifying a source and destination namespace in Openshift - we store templates in shared public namespaces, and apply them to private personal namespaces. 

The destination should probably always default to your configured namespace so as not to potentially reveal private info (a password, a generated secret, your social security number), but you want to enable referencing a source in another namespace.

**Comment by bgrant0607** [comment]
We have a similar policy internally (--borg-user for Googlers).

**Comment by smarterclayton** [comment]
If we move the Kubernetes service to a Kubernetes namespace we may want to rename it to something like "api" or "master" and shorten the other service names "dns".  Would require changes to the kubelet for env vars though.

**Comment by thockin** [comment]
Yeah, I am very afraid that there are numerous things that assume "default"
is special and we will just miss some.

**Comment by smarterclayton** [comment]
e2e test that randomly deleted the default namespace during the runs should do it :)

**Comment by thockin** [comment]
Nah, a bunch of stuff will work well enough at startup and then not fail or
fail in unrelated ways.

**Comment by davidopp** [comment]
This issue is marked 1.0 but seems to be languishing. Is there a decision on whether we're going to put system objects in a separate namespace? I believe the main arguments are
pro: if we don't do it now, it will be hard to do it later
con: this is a somewhat large change to do so close to 1.0
?

**Comment by satnam6502** [comment]
Once a decision is made I am ready to jump on it and get it done. Note to self: make sure whatever namespace we choose, it can't be deleted (just like default).

**Comment by bprashanth** [comment]
That's confused me in the past and I just never remembered to bring it up. So I can delete the default ns, it will delete the rcs and pods, but the ns stays active? I've already lost the rcs, so what's the point (or has this behavior changed recently)?

**Comment by satnam6502** [comment]
Not sure if I have a vote, but I like having the system containers in the default namespace and how they show up when you do `kubectl get pods` -- I always type `ps aux`.

**Comment by bgrant0607** [comment]
Dupe of #4231 (will check whether there's anything relevant there before closing it).

Yes, we should put system objects in a separate namespace.

It's no longer possible to delete the default namespace.

**Comment by davidopp** [comment]
> It's no longer possible to delete the default namespace.

Sorry, I didn't understand the connection between this comment and the rest of your comment.

**Comment by bgrant0607** [comment]
I was responding to https://github.com/GoogleCloudPlatform/kubernetes/issues/9356#issuecomment-114652706

**Comment by bgrant0607** [comment]
Decision: We're moving addons and mirror pods, but not the kubernetes service.

@satnam6502 and @brendandburns can work out who's actually going to do it

**Comment by bgrant0607** [comment]
For posterity, additional previous discussion: #3293

**Comment by satnam6502** [comment]
What name shall we use for the new namespace? `kubernetes` ?

**Comment by bgrant0607** [comment]
Yes, `kubernetes`. 

Mirror pods should take their namespace from their config files on Kubelet, and Kubelet should reject the config if the namespace is missing. We should update our static pods to put them into the `kubernetes` namespace. @yujuhong

**Comment by yujuhong** [comment]
> Mirror pods should take their namespace from their config files on Kubele

We already do that, but would use the default namespace if it's not specified.

> Kubelet should reject the config if the namespace is missing.

Are we enforcing namespaces for all config files? What's wrong with using the "default" (or any other default) namespace if user doesn't specify one? Isn't it the same as the regular pods created through the apiserver?

**Comment by thockin** [comment]
Yeah, we could just audit all our own file-based configs to specify
namespace.

**Comment by satnam6502** [comment]
Brendan is already only it so I have re-assigned.

**Comment by smarterclayton** [comment]
@derekwaynecarr @deads2k our admission controllers and kubelet acl should change to reflect this in our next major - we should only grant pod create to kubelet clients in the Kubernetes namespace

**Comment by bgrant0607** [comment]
@yujuhong Ok, fair enough, we could default to `default`. If that's what we do now, that's fine.

**Comment by alex-mohr** [comment]
#10487 is the current PR, with discussion as to whether we're going to try to get this into v1 or whether we should push it to later.

**Comment by zmerlynn** [comment]
Re-requesting triage on this. We were unable to get PR #10487 merged, and unless it gets merged maybe early tomorrow (Sunday) morning, there's not really enough time to shake out whether it needs to be rolled back for a Monday release cut.

**Comment by goltermann** [comment]
@zmerlynn Triaged today - quorum was to push this in before today's release, and get test cycles in this week.

**Comment by zmerlynn** [comment]
This can't go in right before a release is cut. It needs 2-3 good Jenkins cycles before we can cut a release.

**Comment by zmerlynn** [comment]
(Or, y'know, at least one - and maybe a sidelong glance at scalability.)

**Comment by zmerlynn** [comment]
But let's get some leads on here to LGTM up this PR.

**Comment by thockin** [comment]
Discussed this morning - I think we're OK to go - @brendandburns @bgrant0607

**Comment by zmerlynn** [comment]
If someone gives it another review, I'll happily warn the oncall.

**Comment by roberthbailey** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/10817 is still outstanding to finish this off.

**Comment by bgrant0607** [comment]
Rats. Missed the UI redirect:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/ui/installsupport.go#L28

**Comment by satnam6502** [comment]
Argh! Sorry about that.
