### ISSUE TITLE
Provide only one command for starting a cluster, or clearly state the difference between the two command options. 

### ISSUE THREAD

**Issue by evasnee** [GoogleCloudPlatform/kubernetes#9417]
We give two commands for starting a cluster, but why? 

![image](https://cloud.githubusercontent.com/assets/11644912/8042535/bb904bd6-0dd4-11e5-9767-b76791cd13d9.png)

Help doc: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/gce.md

Hackathon participants weren't completely clear on what the difference was between these two options.

**Comment by amygdala** [comment]
They might have both been provided since people might not necessarily have both installed on their laptops (e.g. on osx I think you have to specifically install wget).  Otherwise they should act the same.
(A somewhat separate comment -- I think vote for this page to also show how you'd start up a cluster via gcloud).

**Comment by goltermann** [comment]
They're not both installed by default on all OSes - we might need to revert this change.

**Comment by amygdala** [comment]
In a recent PR I modified the GCE getting started info so that both are now referenced again, with some clarifying text. (sorry, missed referencing this bug).  Closing this.
