### ISSUE TITLE
Nodes Network should survive network partition. (Failed 4 times in the last 20 runs. Stability: 80 %)

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#9487]
Master tracking bug: #9312

**Comment by marekbiskup** [comment]
The scenario of the test is the following:
 1. create a service
 1. create an RC with as many pods as the number of nodes
 1. wait for pods created, running and responding
 1. take the first node and get the pod from it
 1. ...

It is assumed that the first node has a pod - that's because kubernetes is supposed to distribute pods for which there is a service evenly among nodes. So we expect that each node has one pod.
This turns out to be false. (in 80% cases the first node doesn't have a pod.

**Comment by quinton-hoole** [comment]
Thanks @marekbiskup .  cc: @lavalamp @davidopp Is it a valid assumption that pods should be evenly spread across nodes?  I assume not?

If even spreading is a valid assumption, then there's a bug in the system.  If not, then we need to fix this test.

**Comment by quinton-hoole** [comment]
To clarify the above, it's perfectly sensible to me that k8s should in an ideal world spread pods that constitute a service across as many nodes as possible.  But I doubt whether our scheduler has such logic yet?

**Comment by lavalamp** [comment]
Our spreading is only a probabilistic guarantee. So this is incorrect test behavior.

**Comment by lavalamp** [comment]
We do actually have spreading logic.

To determine if this is a scheduler bug, you'd have to know the state of the system more exactly. Spreading is balanced with resource usage, for example-- if something big was a little slow leaving the node, it could cause it to not get a pod. Or if it was briefly unavailable.

**Comment by quinton-hoole** [comment]
OK, I'd suggest that we change the test then, to not assume that pods are perfectly evenly spread across nodes.

**Comment by marekbiskup** [comment]
@lavalamp , is there a way to run the scheduler with debug logs?
I'm interested about the scores for nodes.
(even if it won't help me in this issue, it's a nice exercise)

I suppose the test fails because CPU utilization has a significant impact on scheduling pods - more that having a service. That's why all pods are scheduled on the same node.

I'm going to remove the requirement that there is one pod per node (I'll still create a service though - just to make pods spread more evenly). I'll simply remove from the network one node that has a pod (without assuming that the first one has). I believe the scenario will still test everything we need ( @jszczepkowski please correct me if I'm wrong).

The PR should be ready today.

By the way, a side effect of this test is that in a 2-node cluster, all add-ons will end up on one node, occupying 0.9 cores - this setup will stay for further tests, so it's good to be aware of it. I'll write this comment in the test code as well.

**Comment by marekbiskup** [comment]
#9671 is ready for review. Possible second round will be needed.
No changes in production code have been made (tests only).

**Comment by lavalamp** [comment]
> is there a way to run the scheduler with debug logs?

I think if you set v=10 you'll see the log messages with that info in them.

**Comment by jszczepkowski** [comment]
> I'm going to remove the requirement that there is one pod per node (I'll still create a service though - just to make pods spread more evenly). I'll simply remove from the network one node that has a pod (without assuming that the first one has).

This scenario is OK.

**Comment by marekbiskup** [comment]
@lavalamp , sorry for such simple questions, but how do I set v=10?

**Comment by brendandburns** [comment]
@marekbiskup you need to edit ```/etc/kubernetes/manifests/kube-scheduler.manifest``` and change ```--v=2``` to ```--v=10``` in the command line args.

The kubelet should then restart the container (validate with ```docker ps```) if it doesn't, ```sudo /etc/init.d/kubelet restart``` should fix it.

**Comment by marekbiskup** [comment]
Status: waiting for review of #9671
