### ISSUE TITLE
Communication between Kubernetes client and server broke unexpectedly

### ISSUE THREAD

**Issue by Kielan** [GoogleCloudPlatform/kubernetes#9558]
I believe this happened unexpectedly but I may have changed AWS regions though I don't think I did.

After a few minutes away I kielan$ kubectl get pods

after some delay 

Unable to connect to the server: dial tcp 52.26.140.56:443: i/o timeout

Even kubectl version returns the client kubernetes version and after some delay the same error as above 

I restart my system after some poking around and now if I run kubectl version get the client version but the following response in the server section:

Couldn't read version from server: Get https://52.26.140.56/version: x509: cannot validate certificate for 52.26.140.56 because it doesn't contain any IP SANs

My analysis is that I need to point to a different IP so the kubectl is trying to retrieve https://52.74.189.120, where I know kubernetes is chilling on the cloud and I believe exposed.

My trouble is figuring out what the kubectl command is to do this assuming I am on the right path.

Feel free to ask any questions and I will do my best to give you the correct answers.

Update: 

Further looking into this looks like I need to configure kubernetes in .kube/kubernetes. 

I now get the dial tcp 52.74.189.120:443: i/o timeout error again after changing the value of server and restarting my system.

**Comment by justinsb** [comment]
@Kielan - not sure I fully understand, but I have hit similar things if I shut down one k8s cluster, and then spin up another, but I still have a configuration pointing at the old server.  So, in your case, you shut down the cluster on 52.26.140.56, and now someone else has that IP.  And you have a working cluster on 52.74.189.120, although even changing the configuration doesn't quite work.

The first thing to check is that if you SSH in to the master (`ssh -i ~/.ssh/kube_aws_rsa ubuntu@52.74.189.120`) that you can then run `kubectl get nodes` and other kubectl commands.  This will confirm that the problem is a problem on your client machine, and not a problem on your cluster.

Then, posting the output of `kubectl version` would be helpful!

**Comment by Kielan** [comment]
I found that I had removed a  VPC rule I had reset on AWS. I could ssh into the machine but all other ports I was trying to access were closed.

**Comment by voyalab** [comment]
+1 @justinsb I faced the similar issue. If load balancer is creating another cluster. then how to update my API server endpoint ?
