### ISSUE TITLE
issues in documentation of images.md

### ISSUE THREAD

**Issue by vincentcr** [GoogleCloudPlatform/kubernetes#9740]
- the link to secrets is a 404
- the imagePullSecrets instructions don't work as written:
 - the json is invalid
 - if run with `"apiVersion": "v1"`, i get the error:
`` Error: the server could not find the requested resource``
 - if run with `"apiVersion": "v1beta3"`, i get the error:

`` Error: Secret "myregistrykey" is invalid: data[.dockercfg]: invalid value '.dockercfg': must have at most 253 characters and match regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*``

**Comment by erictune** [comment]
#10316 will fix the broken link and invalid json.

The `Error: the server could not find the requested resource` is due to your server not having a recent enough version to support api version v1.  That error message could definitely be cleared.  Filed #10318 to improve that error message

I think the `Error: Secret "myregistrykey" is invalid ...` is due to your server not having this commit # in it:
https://github.com/GoogleCloudPlatform/kubernetes/commit/c27999da07b26187c225fb6647008624bc1bf2c9

**Comment by erictune** [comment]
Thanks for the report, it was useful.
