### ISSUE TITLE
Clarify label prefix guidance

### ISSUE THREAD

**Issue by marekbiskup** [GoogleCloudPlatform/kubernetes#9932]
I just found in 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/labels.md

that:

Valid label keys have two segments: an optional prefix and name, separated by a slash (/). (...)
If the prefix is omitted, the label key is presumed to be private to the user. System components which use labels **must specify a prefix**. The kubernetes.io/ prefix is reserved for kubernetes core components.

I found that cluster addons specify "k8s-app" and "version" label with no prefix:
```
    k8s-app: heapster
    version: v2
    kubernetes.io/cluster-service: "true"
```

I wonder if we should rename it to:
```
    kubernetes.io/k8s-app: heapster
    kubernetes.io/version: v2
    kubernetes.io/cluster-service: "true"
```

or rather update the doc about labels.

**Comment by saad-ali** [comment]
Does #9901 address this?

**Comment by dchen1107** [comment]
#9901 only fixed heapster service labels, there are other services. I can work on it now.

**Comment by dchen1107** [comment]
I were wrong, #9901 fix the last one.

**Comment by bgrant0607** [comment]
The guidance should specify that system components attaching labels to user objects must be prefixed. 

In the case of cluster addons, we're the "user".

The real problem is that the cluster addons are in the default namespace -- #9356, so our object names and labels pollute users' object names and labels.
