### ISSUE TITLE
kubectl expose on GCE does not fill in 

### ISSUE THREAD

**Issue by kenmoore** [GoogleCloudPlatform/kubernetes#9960]
(from following the nginx example here https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/simple-nginx.md)
 
Upon running kubectl expose, no load balancer is associated with the service -- the output of the command lacks an IP address and the status.loadBalancer property of the my-nginx service is emtpy HOWEVER  the corresponding forwarding rule and target pool had been created in the project successfully.

Related discussion in the google-containers forum:
https://groups.google.com/forum/#!topic/google-containers/WCPbR_5rdfA

**Comment by a-robinson** [comment]
I talked to Ken offline, and it's due to version skew between his kubectl and the kubernetes versions. Unfortunately there were breaking API changes to services between 0.17 and 0.18. Having one of them at 0.17.x and the other at 0.18.y will prevent you from seeing your load balancers' public IPs. His particular case is kubectl at 0.18.1 and kubernetes at 0.17.1, but both directions are broken.

There's nothing we can do here other than ask users to grab an older kubectl binary or upgrade/replace their cluster to a newer version.
